LCTT/TranslateProject

sources/tech/20140805 How to Install Cinnamon Desktop on Ubuntu.md
[translating by dianbanjiu] How to Install Cinnamon Desktop on Ubuntu
=> dianbanjiu translating

sources/tech/20180917 4 scanning tools for the Linux desktop.md
=> Update 20180917 4 scanning tools for the Linux desktop.md

sources/tech/20180925 9 Easiest Ways To Find Out Process ID (PID) In Linux.md
【moria(knuth.fan at gmail.com)翻译中】
9 Easiest Ways To Find Out Process ID (PID) In Linux
=> moria translating

translated/tech/20180910 How To List An Available Package Groups In Linux.md
翻译完成 20180910 How To List An Available Package Groups In Linux
=> 翻译完成 20180910 How To List An Available Package Groups In Linux

sources/tech/20180831 Publishing Markdown to HTML with MDwiki.md
=> Update 20180831 Publishing Markdown to HTML with MDwiki.md

sources/tech/20170810 How we built our first full-stack JavaScript web app in three weeks.md
article: The user’s home dashboard in our app, AlignHow we built our first full-stack JavaScript web app in three weeks
=> pick article

translated/tech/20180709 How To Configure SSH Key-based Authentication In Linux.md
@wxy @LuuMing 已完成校对，请看一下，有问题请直接在该行留言。
@lujun9972 原文网页生成 Markdown 格式时 `sk@192.168.225.22` 被替换为 `[email protected]` 了，不知道是否有问题，有时间也请关注。
=> PRF: #10302 完成校对 20180709 How To Configure SSH Key-based Authentication In Linux.md

sources/talk/20180123 Moving to Linux from dated Windows machines.md
【翻译中】Moving to Linux from dated Windows machines
=> 【翻译中】Moving to Linux from dated Windows machines

published/20170926 Managing users on Linux systems.md
@wxy @dianbanjiu 这篇我重新校对了一下，大家可以看看。
=> PRF: #10487 # 10594 完成校对 20170926 Managing users on Linux systems.md

sources/tech/20180913 Lab 1- PC Bootstrap and GCC Calling Conventions.md
=> 选题: Lab 1: PC Bootstrap and GCC Calling Conventions

sources/tech/20180907 6.828 lab tools guide.md
=> 选题: 6.828 lab tools guide

sources/tech/20180927 Lab 2- Memory Management.md
=> 选题: Lab 2: Memory Management

sources/tech/20181004 Lab 3- User Environments.md
=> 选题: Lab 3: User Environments

sources/tech/20161014 Compiling Lisp to JavaScript From Scratch in 350 LOC.md
20161014 Compiling Lisp to JavaScript From Scratch in 350 LOC
=> Pick an article

sources/tech/20180928 Using Grails with jQuery and DataTables.md
translating by jrg,20181014
老大，我现在每天上网很不方便，所以一下子申请了三篇翻译。因为我看到Hacktoberfest上写着要前50000名PRs才有T-shirt，现在已经有将近20000名PRs了，为保险起见，先申请翻译3篇（每篇选题时间都隔了几天，因此问题应该不大），这个月完成翻译即可。请老大通融，因工作原因上网多有不便！谅解！
=> Update 20180928 Using Grails with jQuery and DataTables.md

sources/tech/20181004 PyTorch 1.0 Preview Release- Facebook-s newest Open Source AI.md
I want to translate this essay.
=> 20181004 PyTorch 1.0 Preview Release- Facebook-s newest Open Source AI.md

sources/tech/20180827 A sysadmin-s guide to containers.md
翻译申领: A sysadmin's guide to containers.
=> translating by belitex: A sysadmin-s guide to containers

sources/tech/20181016 Lab 5- File system, Spawn and Shell.md
=> 选题: Lab 5: File system, Spawn and Shell

sources/tech/20181016 Lab 4- Preemptive Multitasking.md
=> 选题: Lab 4: Preemptive Multitasking

sources/tech/20181016 Lab 6- Network Driver.md
=> 选题: Lab 6: Network Driver

sources/tech/20181012 Command line quick tips- Reading files different ways.md
=> Update 20181012 Command line quick tips- Reading files different ways.md

sources/tech/20180924 Why Linux users should try Rust.md
=> Update 20180924 Why Linux users should try Rust.md

sources/tech/20181008 Play Windows games on Fedora with Steam Play and Proton.md
=> translated over

translated/tech/20181003 Tips for listing files with ls at the Linux command line.md
@wxy @geekpi 已校对完成，请检查，有问题请直接在 review 时提出。
=> PRF: #10709 完成校对 20181003 Tips for listing files with ls at the Linux command line.md

sources/tech/20180901 Flameshot - A Simple, Yet Powerful Feature-rich Screenshot Tool.md
申请翻译该篇。
我本想提出翻译申请，在网页操作时，它建议开一个新分支，我以为是在 我 fork 的仓库里面开分支，
我就开了一个分支，结果是 LCTT 和我 fork 的仓库都开了个分支。
这个 PR 好像准许后，就可以去掉这个分支，如果不行，请麻烦处理一下。
非常抱歉！！
=> Update 20180901 Flameshot - A Simple, Yet Powerful Feature-rich Screenshot Tool.md

sources/tech/20180827 Top 10 Raspberry Pi blogs to follow.md
申请翻译：Top 10 Raspberry Pi blogs to follow
=> Update 20180827 Top 10 Raspberry Pi blogs to follow.md

sources/tech/20181011 Exploring the Linux kernel- The secrets of Kconfig-kbuild.md
[translating by leemeans]Exploring the Linux kernel: The secrets of Kconfig/kbuild
=> [translating by leemeans]Exploring the Linux kernel: The secrets of Kconfig/kbuild

sources/tech/20171005 10 Games You Can Play on Linux with Wine.md
it is reverted, but I am still translating
=> reapply for the article

sources/tech/20180903 A Cross-platform High-quality GIF Encoder.md
=> Update 20180903 A Cross-platform High-quality GIF Encoder.md

sources/tech/20180905 How To Run MS-DOS Games And Programs In Linux.md
=> Update 20180905 How To Run MS-DOS Games And Programs In Linux.md

sources/tech/20181004 4 Must-Have Tools for Monitoring Linux.md
=> Update 20181004 4 Must-Have Tools for Monitoring Linux.md

sources/tech/20180523 How to dual-boot Linux and Windows.md
=> Update 20180523 How to dual-boot Linux and Windows.md

sources/tech/20180801 5 of the Best Linux Games to Play in 2018.md
[translating by seriouszyx]5 of the Best Linux Games to Play in 2018
=> [translating by seriouszyx]5 of the Best Linux Games to Play in 2018

sources/tech/20181105 Revisiting the Unix philosophy in 2018.md
[Translating] 20181105 Revisiting the Unix philosophy in 2018
=> [Translating] 20181105 Revisiting the Unix philosophy in 2018

sources/talk/20180127 Write Dumb Code.md
=> write dumb code

sources/tech/20180412 A new approach to security instrumentation.md
=> Translating by hopefully2333

sources/tech/20181106 How to partition and format a drive on Linux.md
[Translating] How to partition and format a drive on Linux
=> [Translating] How to partition and format a drive on Linux

sources/tech/20181115 How to install a device driver on Linux.md
[Translating] How to install a device driver on Linux
=> [Translating] How to install a device driver on Linux

sources/tech/20181120 How To Change GDM Login Screen Background In Ubuntu.md
=> How To Change GDM Login Screen Background In Ubuntu

sources/tech/20171108 Continuous infrastructure- The other CI.md
[Translating] 20171108 Continuous infrastructure- The other CI
=> [Translating] 20171108 Continuous infrastructure- The other CI

sources/talk/20181121 10 ways to give thanks to open source and free software maintainers.md
=> 选题: 10 ways to give thanks to open source and free software maintainers

sources/tech/20181122 Getting started with Jenkins X.md
=> 选题: Getting started with Jenkins X

sources/talk/20181121 A Closer Look at Voice-Assisted Speakers.md
=> 选题: A Closer Look at Voice-Assisted Speakers

sources/tech/20181121 Coupled commands with control operators in Bash.md
[Translating] 20181121 Coupled commands with control operators in Bash
=> [Translating] 20181121 Coupled commands with control operators in Bash

sources/talk/20171007 The Most Important Database You-ve Never Heard of.md
=> Update 20171007 The Most Important Database You-ve Never Heard of.md

published/20181120 How To Change GDM Login Screen Background In Ubuntu.md, translated/tech/20181120 How To Change GDM Login Screen Background In Ubuntu.md
@guevaraya 恭喜你完成了第一篇翻译！
本文首发地址： https://linux.cn/article-10289-1.html
您的 LCTT 专页地址： https://linux.cn/lctt/guevaraya
请注册领取您的 LCCN ： https://lctt.linux.cn/
=> PRF&PUB:20181120 How To Change GDM Login Screen Background In Ubuntu

sources/tech/20180226 -Getting to Done- on the Linux command line.md
=> Translating by Guevaraya

sources/tech/20181025 How to write your favorite R functions in Python.md
=>  yongshouzhang translating

sources/tech/20181011 Exploring the Linux kernel- The secrets of Kconfig-kbuild.md
[Translating] Exploring the Linux kernel- The secrets of Kconfig-kbuild
=> [Translating] Exploring the Linux kernel- The secrets of Kconfig-kbuild

sources/tech/20180420 How To Remove Password From A PDF File in Linux.md
=> Update 20180420 How To Remove Password From A PDF File in Linux.md

sources/tech/20181112 A Free, Secure And Cross-platform Password Manager.md
[seriouszyx translating] A Free, Secure And Cross-platform Password Manager
=> [seriouszyx translating] A Free, Secure And Cross-platform Password Manager

sources/tech/20181129 4 open source Markdown editors.md
[translating by lxfminions] 4 open source Markdown editors
=> lxfminions translating

translated/tech/20180814 HTTP request routing and validation with gorilla-mux.md
翻译不够准确，一些词不知道怎么翻译合适，比如 cliche pairs  。对GO 语言不太熟悉，校对费心了
=>  yongshouzhang translated

sources/talk/20181127 What the open source community means to me.md
[Translating by seriouszyx]What the open source community means to me.md
=> seriouszyx translating

translated/tech/20181204 Have a cow at the Linux command line.md
=> Translate heguangzhi 20181206

translated/tech/20180814 HTTP request routing and validation with gorilla-mux.md
=> PRF:20180814 HTTP request routing and validation with gorilla mux

sources/talk/20180826 How to Install and Use FreeDOS on VirtualBox.md
申请翻译  20180826 How to Install and Use FreeDOS on VirtualBox.md
=> 申请翻译  20180826 How to Install and Use FreeDOS on VirtualBox.md

sources/tech/20171012 7 Best eBook Readers for Linux.md
zjon is translating
20171012 7 Best eBook Readers for Linux
=> zjon is translating | 20171012 7 Best eBook Readers for Linux.md

sources/tech/20181213 What is PPA- Everything You Need to Know About PPA in Linux.md
=> 申请翻译-20181213 What is PPA- Everything You Need to Know About PPA in Linux.md

published/20181206 Take a break at the Linux command line with Nyan Cat.md, translated/tech/20181206 Take a break at the Linux command line with Nyan Cat.md
@zhs852 https://linux.cn/article-10398-1.html
=> PRF&PUB:20181206 Take a break at the Linux command line with Nyan Cat

sources/talk/20180625 8 reasons to use the Xfce Linux desktop environment.md
申请翻译 20180625 8 reasons to use the Xfce Linux desktop environment.md
=> 申请翻译 20180625 8 reasons to use the Xfce Linux desktop environment.md

sources/talk/20180809 Two Years With Emacs as a CEO (and now CTO).md
=> 选题: Two Years With Emacs as a CEO (and now CTO)

sources/talk/20180731 How to be the lazy sysadmin.md
zgj1024 认领文章 20180731 How to be the lazy sysadmin
=> zgj1024 talk/20180731 How to be the lazy sysadmin

sources/tech/20120202 Computer Laboratory - Raspberry Pi- Lesson 2 OK02.md
=> 选题: Computer Laboratory – Raspberry Pi: Lesson 2 OK02

sources/tech/20120204 Computer Laboratory - Raspberry Pi- Lesson 4 OK04.md
=> 选题: Computer Laboratory – Raspberry Pi: Lesson 4 OK04

sources/tech/20091104 Linux-Unix App For Prevention Of RSI (Repetitive Strain Injury).md
=> Linux/Unix App For Prevention Of RSI (Repetitive Strain Injury)

sources/talk/20181009 GCC- Optimizing Linux, the Internet, and Everything.md
=> 取消翻译 GCC:Optimizing Linux,the Internet,and Everything

sources/tech/20190107 Testing isn-t everything.md
sources/tech/20190107 Testing isn-t everything.md
=> 选题: 20190107 Testing isn't everything

sources/tech/20190114 Get started with Wekan, an open source kanban board.md
sources/tech/20190114 Get started with Wekan, an open source kanban board.md
=> 选题: 20190114 Get started with Wekan, an open source kanban board

sources/talk/20190115 The Art of Unix Programming, reformatted.md
sources/talk/20190115 The Art of Unix Programming, reformatted.md
=> 选题: 20190115 The Art of Unix Programming, reformatted

sources/tech/20190115 Linux Tools- The Meaning of Dot.md
sources/tech/20190115 Linux Tools- The Meaning of Dot.md
=> 选题: 20190115 Linux Tools: The Meaning of Dot

sources/talk/20190114 Remote Working Survival Guide.md
sources/talk/20190114 Remote Working Survival Guide.md
=> 选题: 20190114 Remote Working Survival Guide

translated/talk/20171119 The Ruby Story.md
=> PRF:20171119 The Ruby Story.md

sources/tech/20150616 Computer Laboratory - Raspberry Pi- Lesson 10 Input01.md
sources/tech/20150616 Computer Laboratory - Raspberry Pi- Lesson 10 Input01.md
=> 选题: 20150616 Computer Laboratory – Raspberry Pi: Lesson 10 Input01

sources/tech/20150616 Computer Laboratory - Raspberry Pi- Lesson 11 Input02.md
sources/tech/20150616 Computer Laboratory - Raspberry Pi- Lesson 11 Input02.md
=> 选题: 20150616 Computer Laboratory – Raspberry Pi: Lesson 11 Input02

sources/talk/20180809 Two Years With Emacs as a CEO (and now CTO).md
20180809 Two Years With Emacs as a CEO (and now CTO).md's translation is under progress, will come out by **this weekend**. Hopefully to publish by the **Chinese New Year's Festival**. @wxy 
BRs
Liu Yuqi
=> translating by oneforalone

sources/tech/20190114 Turn a Raspberry Pi 3B- into a PriTunl VPN.md
=> [翻译中]by jrg

sources/tech/20190118 Top 5 Linux Server Distributions.md
sources/tech/20190118 Top 5 Linux Server Distributions.md
=> 选题: 20190118 Top 5 Linux Server Distributions

sources/talk/20190121 Booting Linux faster.md
sources/talk/20190121 Booting Linux faster.md
=> 选题: 20190121 Booting Linux faster

sources/tech/20190121 Akira- The Linux Design Tool We-ve Always Wanted.md
sources/tech/20190121 Akira- The Linux Design Tool We-ve Always Wanted.md
=> 选题: 20190121 Akira: The Linux Design Tool We’ve Always Wanted?

sources/tech/20150717 The History of Hello World.md
sources/tech/20150717 The History of Hello World.md
=> 选题: 20150717 The History of Hello World

sources/tech/20190118 Get started with WTF, a dashboard for the terminal.md
sources/tech/20190118 Get started with WTF, a dashboard for the terminal.md
=> 选题: 20190118 Get started with WTF, a dashboard for the terminal

published/20190118 Get started with WTF, a dashboard for the terminal.md
@wxy https://linux.cn/article-10484-1.html
=> PUB:20190118 Get started with WTF, a dashboard for the terminal.md

sources/tech/20190121 Get started with TaskBoard, a lightweight kanban board.md
sources/tech/20190121 Get started with TaskBoard, a lightweight kanban board.md
=> 选题: 20190121 Get started with TaskBoard, a lightweight kanban board

sources/tech/20190123 Mind map yourself using FreeMind and Fedora.md
sources/tech/20190123 Mind map yourself using FreeMind and Fedora.md
=> 选题: 20190123 Mind map yourself using FreeMind and Fedora

sources/talk/20190123 Book Review- Fundamentals of Linux.md
sources/talk/20190123 Book Review- Fundamentals of Linux.md
=> 选题: 20190123 Book Review: Fundamentals of Linux

sources/tech/20190124 ODrive (Open Drive) - Google Drive GUI Client For Linux.md
sources/tech/20190124 ODrive (Open Drive) - Google Drive GUI Client For Linux.md
=> 选题: 20190124 ODrive (Open Drive) – Google Drive GUI Client For Linux

sources/tech/20190125 Top 5 Linux Distributions for Development in 2019.md
sources/tech/20190125 Top 5 Linux Distributions for Development in 2019.md
=> 选题: 20190125 Top 5 Linux Distributions for Development in 2019

sources/tech/20190126 Get started with Tint2, an open source taskbar for Linux.md
sources/tech/20190126 Get started with Tint2, an open source taskbar for Linux.md
=> 选题: 20190126 Get started with Tint2, an open source taskbar for Linux

sources/tech/20190123 GStreamer WebRTC- A flexible solution to web-based media.md
sources/tech/20190123 GStreamer WebRTC- A flexible solution to web-based media.md
=> 选题: 20190123 GStreamer WebRTC: A flexible solution to web-based media

sources/tech/20190128 3 simple and useful GNOME Shell extensions.md
sources/tech/20190128 3 simple and useful GNOME Shell extensions.md
=> 选题: 20190128 3 simple and useful GNOME Shell extensions

sources/tech/20180128 Get started with Org mode without Emacs.md
sources/tech/20180128 Get started with Org mode without Emacs.md
=> 选题: 20180128 Get started with Org mode without Emacs

sources/tech/20180129 Tips and tricks for using CUPS for printing with Linux.md
sources/tech/20180129 Tips and tricks for using CUPS for printing with Linux.md
=> 选题: 20180129 Tips and tricks for using CUPS for printing with Linux

sources/tech/20190128 fdisk - Easy Way To Manage Disk Partitions In Linux.md
sources/tech/20190128 fdisk - Easy Way To Manage Disk Partitions In Linux.md
=> 选题: 20190128 fdisk – Easy Way To Manage Disk Partitions In Linux

sources/tech/20190128 Top Hex Editors for Linux.md
sources/tech/20190128 Top Hex Editors for Linux.md
=> 选题: 20190128 Top Hex Editors for Linux

sources/tech/20190124 What does DevOps mean to you.md
sources/tech/20190124 What does DevOps mean to you.md
=> 选题: 20190124 What does DevOps mean to you?

sources/tech/20190118 Secure Email Service Tutanota Has a Desktop App Now.md
sources/tech/20190118 Secure Email Service Tutanota Has a Desktop App Now.md
=> 选题: 20190118 Secure Email Service Tutanota Has a Desktop App Now

sources/tech/20190130 Get started with Budgie Desktop, a Linux environment.md
sources/tech/20190130 Get started with Budgie Desktop, a Linux environment.md
=> 选题: 20190130 Get started with Budgie Desktop, a Linux environment

sources/tech/20190116 The Evil-Twin Framework- A tool for improving WiFi security.md
sources/tech/20190116 The Evil-Twin Framework- A tool for improving WiFi security.md
=> 选题: 20190116 The Evil-Twin Framework: A tool for improving WiFi security

sources/tech/20190104 Midori- A Lightweight Open Source Web Browser.md
sources/tech/20190104 Midori- A Lightweight Open Source Web Browser.md
=> 选题: 20190104 Midori: A Lightweight Open Source Web Browser

sources/tech/20190104 Take to the virtual skies with FlightGear.md
sources/tech/20190104 Take to the virtual skies with FlightGear.md
=> 选题: 20190104 Take to the virtual skies with FlightGear

sources/tech/20190116 Best Audio Editors For Linux.md
sources/tech/20190116 Best Audio Editors For Linux.md
=> 选题: 20190116 Best Audio Editors For Linux

sources/tech/20190103 How to use Magit to manage Git projects.md
sources/tech/20190103 How to use Magit to manage Git projects.md
=> 选题: 20190103 How to use Magit to manage Git projects

sources/tech/20181224 Go on an adventure in your Linux terminal.md
sources/tech/20181224 Go on an adventure in your Linux terminal.md
=> 选题: 20181224 Go on an adventure in your Linux terminal

sources/tech/20171215 Top 5 Linux Music Players.md
Applying for translating a passage
=> Applying for translating a passage

sources/tech/20190208 7 steps for hunting down Python code bugs.md
sources/tech/20190208 7 steps for hunting down Python code bugs.md
=> 选题: 20190208 7 steps for hunting down Python code bugs

sources/talk/20190206 What blockchain and open source communities have in common.md
sources/talk/20190206 What blockchain and open source communities have in common.md
=> 选题: 20190206 What blockchain and open source communities have in common

sources/talk/20190208 Which programming languages should you learn.md
sources/talk/20190208 Which programming languages should you learn.md
=> 选题: 20190208 Which programming languages should you learn?

sources/talk/20190131 OOP Before OOP with Simula.md
sources/talk/20190131 OOP Before OOP with Simula.md
=> 选题: 20190131 OOP Before OOP with Simula

sources/tech/20190129 A small notebook for a system administrator.md
sources/tech/20190129 A small notebook for a system administrator.md
=> 选题: 20190129 A small notebook for a system administrator

sources/tech/20190205 Installing Kali Linux on VirtualBox- Quickest - Safest Way.md
sources/tech/20190205 Installing Kali Linux on VirtualBox- Quickest - Safest Way.md
=> 选题: 20190205 Installing Kali Linux on VirtualBox: Quickest & Safest Way

sources/tech/20190205 DNS and Root Certificates.md
sources/tech/20190205 DNS and Root Certificates.md
=> 选题: 20190205 DNS and Root Certificates

sources/tech/20190205 Install Apache, MySQL, PHP (LAMP) Stack On Ubuntu 18.04 LTS.md
sources/tech/20190205 Install Apache, MySQL, PHP (LAMP) Stack On Ubuntu 18.04 LTS.md
=> 选题: 20190205 Install Apache, MySQL, PHP (LAMP) Stack On Ubuntu 18.04 LTS

sources/tech/20190204 Top 5 open source network monitoring tools.md
sources/tech/20190204 Top 5 open source network monitoring tools.md
=> 选题: 20190204 Top 5 open source network monitoring tools

sources/tech/20190201 Top 5 Linux Distributions for New Users.md
sources/tech/20190201 Top 5 Linux Distributions for New Users.md
=> 选题: 20190201 Top 5 Linux Distributions for New Users

sources/tech/20190206 4 cool new projects to try in COPR for February 2019.md
sources/tech/20190206 4 cool new projects to try in COPR for February 2019.md
=> 选题: 20190206 4 cool new projects to try in COPR for February 2019

sources/talk/20190204 Config management is dead- Long live Config Management Camp.md
sources/talk/20190204 Config management is dead- Long live Config Management Camp.md
=> 选题: 20190204 Config management is dead: Long live Config Management Camp

sources/tech/20190205 CFS- Completely fair process scheduling in Linux.md
sources/tech/20190205 CFS- Completely fair process scheduling in Linux.md
=> 选题: 20190205 CFS: Completely fair process scheduling in Linux

sources/tech/20190131 Will quantum computing break security.md
sources/tech/20190131 Will quantum computing break security.md
=> 选题: 20190131 Will quantum computing break security?

sources/talk/20190206 4 steps to becoming an awesome agile developer.md
sources/talk/20190206 4 steps to becoming an awesome agile developer.md
=> 选题: 20190206 4 steps to becoming an awesome agile developer

sources/tech/20190206 Getting started with Vim visual mode.md
sources/tech/20190206 Getting started with Vim visual mode.md
=> 选题: 20190206 Getting started with Vim visual mode

sources/talk/20190205 7 predictions for artificial intelligence in 2019.md
sources/talk/20190205 7 predictions for artificial intelligence in 2019.md
=> 选题: 20190205 7 predictions for artificial intelligence in 2019

sources/tech/20190206 And, Ampersand, and - in Linux.md
sources/tech/20190206 And, Ampersand, and - in Linux.md
=> 选题: 20190206 And, Ampersand, and & in Linux

sources/tech/20190207 10 Methods To Create A File In Linux.md
sources/tech/20190207 10 Methods To Create A File In Linux.md
=> 选题: 20190207 10 Methods To Create A File In Linux

sources/tech/20190208 3 Ways to Install Deb Files on Ubuntu Linux.md
sources/tech/20190208 3 Ways to Install Deb Files on Ubuntu Linux.md
=> 选题: 20190208 3 Ways to Install Deb Files on Ubuntu Linux

sources/tech/20190208 How To Install And Use PuTTY On Linux.md
sources/tech/20190208 How To Install And Use PuTTY On Linux.md
=> 选题: 20190208 How To Install And Use PuTTY On Linux

sources/tech/20190204 7 Best VPN Services For 2019.md
sources/tech/20190204 7 Best VPN Services For 2019.md
=> 选题: 20190204 7 Best VPN Services For 2019

sources/tech/20190211 How To Remove-Delete The Empty Lines In A File In Linux.md
sources/tech/20190211 How To Remove-Delete The Empty Lines In A File In Linux.md
=> 选题: 20190211 How To Remove/Delete The Empty Lines In A File In Linux

sources/talk/20190211 Introducing kids to computational thinking with Python.md
sources/talk/20190211 Introducing kids to computational thinking with Python.md
=> 选题: 20190211 Introducing kids to computational thinking with Python

sources/tech/20190205 5 Streaming Audio Players for Linux.md
sources/tech/20190205 5 Streaming Audio Players for Linux.md
=> 选题: 20190205 5 Streaming Audio Players for Linux

sources/tech/20190211 How does rootless Podman work.md
sources/tech/20190211 How does rootless Podman work.md
=> 选题: 20190211 How does rootless Podman work?

sources/tech/20190212 Ampersands and File Descriptors in Bash.md
sources/tech/20190212 Ampersands and File Descriptors in Bash.md
=> 选题: 20190212 Ampersands and File Descriptors in Bash

sources/tech/20190213 How to use Linux Cockpit to manage system performance.md
sources/tech/20190213 How to use Linux Cockpit to manage system performance.md
=> 选题: 20190213 How to use Linux Cockpit to manage system performance

sources/tech/20190214 Drinking coffee with AWK.md
sources/tech/20190214 Drinking coffee with AWK.md
=> 选题: 20190214 Drinking coffee with AWK

sources/talk/20190214 Top 5 podcasts for Linux news and tips.md
sources/talk/20190214 Top 5 podcasts for Linux news and tips.md
=> 选题: 20190214 Top 5 podcasts for Linux news and tips

sources/tech/20190215 4 Methods To Change The HostName In Linux.md
sources/tech/20190215 4 Methods To Change The HostName In Linux.md
=> 选题: 20190215 4 Methods To Change The HostName In Linux

sources/tech/20190217 Install Android 8.1 Oreo on Linux To Run Apps - Games.md
sources/tech/20190217 Install Android 8.1 Oreo on Linux To Run Apps - Games.md
=> 选题: 20190217 Install Android 8.1 Oreo on Linux To Run Apps & Games

sources/tech/20190213 How To Install, Configure And Use Fish Shell In Linux.md
sources/tech/20190213 How To Install, Configure And Use Fish Shell In Linux.md
=> 选题: 20190213 How To Install, Configure And Use Fish Shell In Linux?

sources/tech/20190213 How to build a WiFi picture frame with a Raspberry Pi.md
sources/tech/20190213 How to build a WiFi picture frame with a Raspberry Pi.md
=> 选题: 20190213 How to build a WiFi picture frame with a Raspberry Pi

sources/tech/20190216 FinalCrypt - An Open Source File Encryption Application.md
sources/tech/20190216 FinalCrypt - An Open Source File Encryption Application.md
=> 选题: 20190216 FinalCrypt – An Open Source File Encryption Application

sources/tech/20190216 How To Grant And Remove Sudo Privileges To Users On Ubuntu.md
sources/tech/20190216 How To Grant And Remove Sudo Privileges To Users On Ubuntu.md
=> 选题: 20190216 How To Grant And Remove Sudo Privileges To Users On Ubuntu

sources/tech/20190215 Make websites more readable with a shell script.md
sources/tech/20190215 Make websites more readable with a shell script.md
=> 选题: 20190215 Make websites more readable with a shell script

sources/tech/20190214 Run Particular Commands Without Sudo Password In Linux.md
sources/tech/20190214 Run Particular Commands Without Sudo Password In Linux.md
=> 选题: 20190214 Run Particular Commands Without Sudo Password In Linux

sources/tech/20190217 How to Change User Password in Ubuntu -Beginner-s Tutorial.md
sources/tech/20190217 How to Change User Password in Ubuntu -Beginner-s Tutorial.md
=> 选题: 20190217 How to Change User Password in Ubuntu [Beginner’s Tutorial]

sources/tech/20190218 SPEED TEST- x86 vs. ARM for Web Crawling in Python.md
sources/tech/20190218 SPEED TEST- x86 vs. ARM for Web Crawling in Python.md
=> 选题: 20190218 SPEED TEST: x86 vs. ARM for Web Crawling in Python

sources/tech/20190219 Logical - in Bash.md
sources/tech/20190219 Logical - in Bash.md
=> 选题: 20190219 Logical & in Bash

sources/tech/20180926 HTTP- Brief History of HTTP.md
sources/tech/20180926 HTTP- Brief History of HTTP.md
=> 选题: 20180926 HTTP: Brief History of HTTP

sources/tech/20190219 3 tools for viewing files at the command line.md
sources/tech/20190219 3 tools for viewing files at the command line.md
=> 选题: 20190219 3 tools for viewing files at the command line

sources/talk/20120911 Doug Bolden, Dunnet (IF).md
sources/talk/20120911 Doug Bolden, Dunnet (IF).md
=> 选题: 20120911 Doug Bolden, Dunnet (IF)

sources/tech/20190131 19 days of productivity in 2019- The fails.md
sources/tech/20190131 19 days of productivity in 2019- The fails.md
=> 选题: 20190131 19 days of productivity in 2019: The fails

published/20181123 Three SSH GUI Tools for Linux.md, translated/tech/20181123 Three SSH GUI Tools for Linux.md
@wxy https://linux.cn/article-10559-1.html
=> PRF&PUB:20181123 Three SSH GUI Tools for Linux

sources/tech/20190223 Regex groups and numerals.md
sources/tech/20190223 Regex groups and numerals.md
=> 选题: 20190223 Regex groups and numerals

sources/tech/20190220 Automation evolution.md
sources/tech/20190220 Automation evolution.md
=> 选题: 20190220 Automation evolution

sources/tech/20190109 Configure Anaconda on Emacs - iD.md
sources/tech/20190109 Configure Anaconda on Emacs - iD.md
=> 选题: 20190109 Configure Anaconda on Emacs – iD

translated/tech/20160922 Annoying Experiences Every Linux Gamer Never Wanted.md
=> PRF:20160922 Annoying Experiences Every Linux Gamer Never Wanted.md

sources/talk/20160921 lawyer The MIT License, Line by Line.md
sources/talk/20160921 lawyer The MIT License, Line by Line.md
=> 选题: 20160921 lawyer The MIT License, Line by Line

sources/tech/20180507 Modularity in Fedora 28 Server Edition.md
sources/tech/20180507 Modularity in Fedora 28 Server Edition.md
=> 选题: 20180507 Modularity in Fedora 28 Server Edition

sources/tech/20190212 Top 10 Best Linux Media Server Software.md
sources/tech/20190212 Top 10 Best Linux Media Server Software.md
=> 选题: 20190212 Top 10 Best Linux Media Server Software

sources/tech/20190218 How To Restore Sudo Privileges To A User.md
sources/tech/20190218 How To Restore Sudo Privileges To A User.md
=> 选题: 20190218 How To Restore Sudo Privileges To A User

sources/tech/20190218 Emoji-Log- A new way to write Git commit messages.md
sources/tech/20190218 Emoji-Log- A new way to write Git commit messages.md
=> 选题: 20190218 Emoji-Log: A new way to write Git commit messages

sources/tech/20170721 Firefox and org-protocol URL Capture.md
sources/tech/20170721 Firefox and org-protocol URL Capture.md
=> 选题: 20170721 Firefox and org-protocol URL Capture

sources/tech/20190222 Q4OS Linux Revives Your Old Laptop with Windows- Looks.md
sources/tech/20190222 Q4OS Linux Revives Your Old Laptop with Windows- Looks.md
=> 选题: 20190222 Q4OS Linux Revives Your Old Laptop with Windows’ Looks

sources/tech/20170519 zsh shell inside Emacs on Windows.md
sources/tech/20170519 zsh shell inside Emacs on Windows.md
=> 选题: 20170519 zsh shell inside Emacs on Windows

sources/tech/20170223 Use Emacs to create OAuth 2.0 UML sequence diagrams.md
sources/tech/20170223 Use Emacs to create OAuth 2.0 UML sequence diagrams.md
=> 选题: 20170223 Use Emacs to create OAuth 2.0 UML sequence diagrams

sources/tech/20190221 Testing Bash with BATS.md
sources/tech/20190221 Testing Bash with BATS.md
=> 选题: 20190221 Testing Bash with BATS

sources/tech/20190219 4 secrets management tools for Git encryption.md
sources/tech/20190219 4 secrets management tools for Git encryption.md
=> 选题: 20190219 4 secrets management tools for Git encryption

sources/talk/20190220 Do Linux distributions still matter with containers.md
sources/talk/20190220 Do Linux distributions still matter with containers.md
=> 选题: 20190220 Do Linux distributions still matter with containers?

sources/talk/20190219 How Linux testing has changed and what matters today.md
sources/talk/20190219 How Linux testing has changed and what matters today.md
=> 选题: 20190219 How Linux testing has changed and what matters today

sources/tech/20190218 Get started and organized with TiddlyWiki.md
sources/tech/20190218 Get started and organized with TiddlyWiki.md
=> 选题: 20190218 Get started and organized with TiddlyWiki

published/20190212 Two graphical tools for manipulating PDFs on the Linux desktop.md
@geekpi https://linux.cn/article-10584-1.html
=> PRF&PUB:20190212 Two graphical tools for manipulating PDFs on the Linux desktop.md

sources/talk/20190211 Introducing kids to computational thinking with Python.md
申请翻译 20190211 Introducing kids to computational thinking with Python.md
=> 申请翻译 20190211 Introducing kids to computational thinking with Python.md

sources/tech/20190301 Which Raspberry Pi should you choose.md
sources/tech/20190301 Which Raspberry Pi should you choose.md
=> 选题: 20190301 Which Raspberry Pi should you choose?

sources/talk/20190228 Why CLAs aren-t good for open source.md
sources/talk/20190228 Why CLAs aren-t good for open source.md
=> 选题: 20190228 Why CLAs aren't good for open source

sources/tech/20190228 3 open source behavior-driven development tools.md
sources/tech/20190228 3 open source behavior-driven development tools.md
=> 选题: 20190228 3 open source behavior-driven development tools

sources/tech/20190228 Connecting a VoIP phone directly to an Asterisk server.md
sources/tech/20190228 Connecting a VoIP phone directly to an Asterisk server.md
=> 选题: 20190228 Connecting a VoIP phone directly to an Asterisk server

sources/tech/20190301 Guide to Install VMware Tools on Linux.md
sources/tech/20190301 Guide to Install VMware Tools on Linux.md
=> 选题: 20190301 Guide to Install VMware Tools on Linux

sources/talk/20190301 What-s happening in the OpenStack community.md
sources/talk/20190301 What-s happening in the OpenStack community.md
=> 选题: 20190301 What's happening in the OpenStack community?

sources/tech/20190228 MiyoLinux- A Lightweight Distro with an Old-School Approach.md
sources/tech/20190228 MiyoLinux- A Lightweight Distro with an Old-School Approach.md
=> 选题: 20190228 MiyoLinux: A Lightweight Distro with an Old-School Approach

sources/tech/20190304 How to Install MongoDB on Ubuntu.md
sources/tech/20190304 How to Install MongoDB on Ubuntu.md
=> 选题: 20190304 How to Install MongoDB on Ubuntu

sources/tech/20190302 How to buy a Raspberry Pi.md
sources/tech/20190302 How to buy a Raspberry Pi.md
=> 选题: 20190302 How to buy a Raspberry Pi

sources/tech/20190303 Manage Your Mirrors with ArchLinux Mirrorlist Manager.md
sources/tech/20190303 Manage Your Mirrors with ArchLinux Mirrorlist Manager.md
=> 选题: 20190303 Manage Your Mirrors with ArchLinux Mirrorlist Manager

sources/tech/20190301 How to use sudo access in winSCP.md
sources/tech/20190301 How to use sudo access in winSCP.md
=> 选题: 20190301 How to use sudo access in winSCP

sources/tech/20190304 What you need to know about Ansible modules.md
sources/tech/20190304 What you need to know about Ansible modules.md
=> 选题: 20190304 What you need to know about Ansible modules

sources/tech/20190305 5 ways to teach kids to program with Raspberry Pi.md
sources/tech/20190305 5 ways to teach kids to program with Raspberry Pi.md
=> 选题: 20190305 5 ways to teach kids to program with Raspberry Pi

sources/tech/20190304 Learn Linux with the Raspberry Pi.md
sources/tech/20190304 Learn Linux with the Raspberry Pi.md
=> 选题: 20190304 Learn Linux with the Raspberry Pi

sources/talk/20190228 IRC vs IRL- How to run a good IRC meeting.md
sources/talk/20190228 IRC vs IRL- How to run a good IRC meeting.md
=> 选题: 20190228 IRC vs IRL: How to run a good IRC meeting

sources/tech/20190205 5 Linux GUI Cloud Backup Tools.md
sources/tech/20190205 5 Linux GUI Cloud Backup Tools.md
=> 选题: 20190205 5 Linux GUI Cloud Backup Tools

sources/talk/20190225 Teaching scientists how to share code.md
sources/talk/20190225 Teaching scientists how to share code.md
=> 选题: 20190225 Teaching scientists how to share code

sources/tech/20190225 Netboot a Fedora Live CD.md
sources/tech/20190225 Netboot a Fedora Live CD.md
=> 选题: 20190225 Netboot a Fedora Live CD

sources/tech/20190225 How to Install VirtualBox on Ubuntu -Beginner-s Tutorial.md
sources/tech/20190225 How to Install VirtualBox on Ubuntu -Beginner-s Tutorial.md
=> 选题: 20190225 How to Install VirtualBox on Ubuntu [Beginner’s Tutorial]

sources/talk/20190222 Developer happiness- What you need to know.md
sources/talk/20190222 Developer happiness- What you need to know.md
=> 选题: 20190222 Developer happiness: What you need to know

sources/tech/20190226 How To SSH Into A Particular Directory On Linux.md
sources/tech/20190226 How To SSH Into A Particular Directory On Linux.md
=> 选题: 20190226 How To SSH Into A Particular Directory On Linux

sources/talk/20190226 Reducing security risks with centralized logging.md
sources/talk/20190226 Reducing security risks with centralized logging.md
=> 选题: 20190226 Reducing security risks with centralized logging

sources/tech/20190227 How to Display Weather Information in Ubuntu 18.04.md
sources/tech/20190227 How to Display Weather Information in Ubuntu 18.04.md
=> 选题: 20190227 How to Display Weather Information in Ubuntu 18.04

sources/talk/20190228 A Brief History of FOSS Practices.md
sources/talk/20190228 A Brief History of FOSS Practices.md
=> 选题: 20190228 A Brief History of FOSS Practices

sources/tech/20190226 All about -Curly Braces- in Bash.md
sources/tech/20190226 All about -Curly Braces- in Bash.md
=> 选题: 20190226 All about {Curly Braces} in Bash

sources/talk/20190227 Let your engineers choose the license- A guide.md
sources/talk/20190227 Let your engineers choose the license- A guide.md
=> 选题: 20190227 Let your engineers choose the license: A guide

sources/tech/20190227 How To Find Available Network Interfaces On Linux.md
sources/tech/20190227 How To Find Available Network Interfaces On Linux.md
=> 选题: 20190227 How To Find Available Network Interfaces On Linux

sources/talk/20181205 5 reasons to give Linux for the holidays.md
申请翻译“20181205 5 reasons to give Linux for the holidays”
=> translating by mokshal

sources/tech/20180518 What-s a hero without a villain- How to add one to your Python game.md
Reverts LCTT/TranslateProject#12694
忘记移动到 translated 目录了。请先移动，
=> Revert "Translated by cycoe"

sources/tech/20190218 Emoji-Log- A new way to write Git commit messages.md
=> Translating by MjSeven

sources/tech/20180220 JSON vs XML vs TOML vs CSON vs YAML.md
tech/20180220 JSON vs XML vs TOML vs CSON vs YAML.md
=> GraveAccent reserved 20180220JSON vs XML vs TOML vs CSON vs YAML.md

sources/tech/20190306 Getting started with the Geany text editor.md
sources/tech/20190306 Getting started with the Geany text editor.md
=> 选题: 20190306 Getting started with the Geany text editor

sources/tech/20181218 Using Pygame to move your game character around.md
sources/tech/20181218 Using Pygame to move your game character around.md
=> 选题: 20181218 Using Pygame to move your game character around

sources/tech/20171214 Build a game framework with Python using the module Pygame.md
sources/tech/20171214 Build a game framework with Python using the module Pygame.md
=> 选题: 20171214 Build a game framework with Python using the module Pygame

sources/tech/20171215 How to add a player to your Python game.md
sources/tech/20171215 How to add a player to your Python game.md
=> 选题: 20171215 How to add a player to your Python game

sources/tech/20190116 Get started with Cypht, an open source email client.md
sources/tech/20190116 Get started with Cypht, an open source email client.md
=> 选题: 20190116 Get started with Cypht, an open source email client

sources/tech/20190312 Do advanced math with Mathematica on the Raspberry Pi.md
sources/tech/20190312 Do advanced math with Mathematica on the Raspberry Pi.md
=> 选题: 20190312 Do advanced math with Mathematica on the Raspberry Pi

sources/tech/20180725 Put platforms in a Python game with Pygame.md
sources/tech/20180725 Put platforms in a Python game with Pygame.md
=> 选题: 20180725 Put platforms in a Python game with Pygame

sources/tech/20190309 How To Fix -Network Protocol Error- On Mozilla Firefox.md
sources/tech/20190309 How To Fix -Network Protocol Error- On Mozilla Firefox.md
=> 选题: 20190309 How To Fix “Network Protocol Error” On Mozilla Firefox

sources/tech/20190311 7 resources for learning to use your Raspberry Pi.md
sources/tech/20190311 7 resources for learning to use your Raspberry Pi.md
=> 选题: 20190311 7 resources for learning to use your Raspberry Pi

sources/tech/20190718 3 Emacs modes for taking notes.md
sources/tech/20190718 3 Emacs modes for taking notes.md
=> 选题: 20190718 3 Emacs modes for taking notes

sources/tech/20160301 How To Set Password Policies In Linux.md
sources/tech/20160301 How To Set Password Policies In Linux.md
=> 选题: 20160301 How To Set Password Policies In Linux

sources/talk/20190312 When the web grew up- A browser story.md
sources/talk/20190312 When the web grew up- A browser story.md
=> 选题: 20190312 When the web grew up: A browser story

sources/tech/20190307 How to Restart a Network in Ubuntu -Beginner-s Tip.md
sources/tech/20190307 How to Restart a Network in Ubuntu -Beginner-s Tip.md
=> 选题: 20190307 How to Restart a Network in Ubuntu [Beginner’s Tip]

sources/tech/20190307 13 open source backup solutions.md
sources/tech/20190307 13 open source backup solutions.md
=> 选题: 20190307 13 open source backup solutions

sources/talk/20190307 Small Scale Scrum vs. Large Scale Scrum.md
sources/talk/20190307 Small Scale Scrum vs. Large Scale Scrum.md
=> 选题: 20190307 Small Scale Scrum vs. Large Scale Scrum

sources/talk/20190311 Discuss everything Fedora.md
sources/talk/20190311 Discuss everything Fedora.md
=> 选题: 20190311 Discuss everything Fedora

sources/tech/20190306 Get cooking with GNOME Recipes on Fedora.md
sources/tech/20190306 Get cooking with GNOME Recipes on Fedora.md
=> 选题: 20190306 Get cooking with GNOME Recipes on Fedora

sources/talk/20190306 How to pack an IT travel kit.md
sources/talk/20190306 How to pack an IT travel kit.md
=> 选题: 20190306 How to pack an IT travel kit

sources/tech/20190311 Blockchain 2.0- Redefining Financial Services -Part 3.md
sources/tech/20190311 Blockchain 2.0- Redefining Financial Services -Part 3.md
=> 选题: 20190311 Blockchain 2.0: Redefining Financial Services [Part 3]

sources/tech/20190303 How to boot up a new Raspberry Pi.md
sources/tech/20190303 How to boot up a new Raspberry Pi.md
=> 选题: 20190303 How to boot up a new Raspberry Pi

sources/tech/20190307 How to keep your Raspberry Pi updated.md
sources/tech/20190307 How to keep your Raspberry Pi updated.md
=> 选题: 20190307 How to keep your Raspberry Pi updated

sources/tech/20190308 How to use your Raspberry Pi for entertainment.md
sources/tech/20190308 How to use your Raspberry Pi for entertainment.md
=> 选题: 20190308 How to use your Raspberry Pi for entertainment

sources/tech/20190309 Emulators and Native Linux games on the Raspberry Pi.md
sources/tech/20190309 Emulators and Native Linux games on the Raspberry Pi.md
=> 选题: 20190309 Emulators and Native Linux games on the Raspberry Pi

sources/tech/20180330 Asynchronous rsync with Emacs, dired and tramp..md
sources/tech/20180330 Asynchronous rsync with Emacs, dired and tramp..md
=> 选题: 20180330 Asynchronous rsync with Emacs, dired and tramp.

sources/tech/20180826 Be productive with Org-mode.md
sources/tech/20180826 Be productive with Org-mode.md
=> 选题: 20180826 Be productive with Org-mode

sources/tech/20190312 BackBox Linux for Penetration Testing.md
sources/tech/20190312 BackBox Linux for Penetration Testing.md
=> 选题: 20190312 BackBox Linux for Penetration Testing

sources/tech/20190313 Game Review- Steel Rats is an Enjoyable Bike-Combat Game.md
sources/tech/20190313 Game Review- Steel Rats is an Enjoyable Bike-Combat Game.md
=> 选题: 20190313 Game Review: Steel Rats is an Enjoyable Bike-Combat Game

sources/tech/20171119 Advanced Techniques for Reducing Emacs Startup Time.md
sources/tech/20171119 Advanced Techniques for Reducing Emacs Startup Time.md
=> 选题: 20171119 Advanced Techniques for Reducing Emacs Startup Time

sources/talk/20190313 Why is no one signing their emails.md
sources/talk/20190313 Why is no one signing their emails.md
=> 选题: 20190313 Why is no one signing their emails?

sources/talk/20190314 A Look Back at the History of Firefox.md
sources/talk/20190314 A Look Back at the History of Firefox.md
=> 选题: 20190314 A Look Back at the History of Firefox

sources/tech/20180329 Python ChatOps libraries- Opsdroid and Errbot.md
=> Apply for Translatting

sources/tech/20180629 100 Best Ubuntu Apps.md
I want to translate this article. Thanks a lot.
=> Translating by DavidMax2006

sources/tech/20180919 Host your own cloud with Raspberry Pi NAS.md
sources/tech/20180919 Host your own cloud with Raspberry Pi NAS.md
=> 选题: 20180919 Host your own cloud with Raspberry Pi NAS

sources/tech/20190314 14 days of celebrating the Raspberry Pi.md
sources/tech/20190314 14 days of celebrating the Raspberry Pi.md
=> 选题: 20190314 14 days of celebrating the Raspberry Pi

sources/tech/20190316 Program the real world using Rust on Raspberry Pi.md
sources/tech/20190316 Program the real world using Rust on Raspberry Pi.md
=> 选题: 20190316 Program the real world using Rust on Raspberry Pi

sources/tech/20190315 How to create portable documents with CBZ and DjVu.md
sources/tech/20190315 How to create portable documents with CBZ and DjVu.md
=> 选题: 20190315 How to create portable documents with CBZ and DjVu

sources/tech/20190318 Install MEAN.JS Stack In Ubuntu 18.04 LTS.md
sources/tech/20190318 Install MEAN.JS Stack In Ubuntu 18.04 LTS.md
=> 选题: 20190318 Install MEAN.JS Stack In Ubuntu 18.04 LTS

sources/tech/20190315 How To Parse And Pretty Print JSON With Linux Commandline Tools.md
=> add translator

sources/tech/20190319 How To Set Up a Firewall with GUFW on Linux.md
sources/tech/20190319 How To Set Up a Firewall with GUFW on Linux.md
=> 选题: 20190319 How To Set Up a Firewall with GUFW on Linux

sources/tech/20190319 Blockchain 2.0- Blockchain In Real Estate -Part 4.md
sources/tech/20190319 Blockchain 2.0- Blockchain In Real Estate -Part 4.md
=> 选题: 20190319 Blockchain 2.0: Blockchain In Real Estate [Part 4]

sources/tech/20190301 Emacs for (even more of) the win.md
sources/tech/20190301 Emacs for (even more of) the win.md
=> 选题: 20190301 Emacs for (even more of) the win

sources/tech/20190319 Five Commands To Use Calculator In Linux Command Line.md
sources/tech/20190319 Five Commands To Use Calculator In Linux Command Line.md
=> 选题: 20190319 Five Commands To Use Calculator In Linux Command Line?

sources/tech/20190319 How to set up a homelab from hardware to firewall.md
sources/tech/20190319 How to set up a homelab from hardware to firewall.md
=> 选题: 20190319 How to set up a homelab from hardware to firewall

translated/tech/20180330 Asynchronous rsync with Emacs, dired and tramp..md
=> PRF:20180330 Asynchronous rsync with Emacs, dired and tramp 

published/20180330 Asynchronous rsync with Emacs, dired and tramp..md
@lujun9972 https://linux.cn/article-10639-1.html
=> PRF&PUB:20180330 Asynchronous rsync with Emacs, dired and tramp 

sources/tech/20190318 How to host your own webfonts.md
sources/tech/20190318 How to host your own webfonts.md
=> 选题: 20190318 How to host your own webfonts

sources/tech/20190318 10 Python image manipulation tools.md
sources/tech/20190318 10 Python image manipulation tools.md
=> 选题: 20190318 10 Python image manipulation tools

sources/tech/20190318 Solus 4 ‘Fortitude- Released with Significant Improvements.md
sources/tech/20190318 Solus 4 ‘Fortitude- Released with Significant Improvements.md
=> 选题: 20190318 Solus 4 ‘Fortitude’ Released with Significant Improvements

sources/tech/20190320 Choosing an open messenger client- Alternatives to WhatsApp.md
sources/tech/20190320 Choosing an open messenger client- Alternatives to WhatsApp.md
=> 选题: 20190320 Choosing an open messenger client: Alternatives to WhatsApp

sources/talk/20190319 6 steps to stop ethical debt in AI product development.md
sources/talk/20190319 6 steps to stop ethical debt in AI product development.md
=> 选题: 20190319 6 steps to stop ethical debt in AI product development

sources/tech/20190320 Move your dotfiles to version control.md
sources/tech/20190320 Move your dotfiles to version control.md
=> 选题: 20190320 Move your dotfiles to version control

sources/tech/20190320 Nuvola- Desktop Music Player for Streaming Services.md
sources/tech/20190320 Nuvola- Desktop Music Player for Streaming Services.md
=> 选题: 20190320 Nuvola: Desktop Music Player for Streaming Services

sources/tech/20190321 How To Setup Linux Media Server Using Jellyfin.md
sources/tech/20190321 How To Setup Linux Media Server Using Jellyfin.md
=> 选题: 20190321 How To Setup Linux Media Server Using Jellyfin

sources/tech/20190320 4 cool terminal multiplexers.md
sources/tech/20190320 4 cool terminal multiplexers.md
=> 选题: 20190320 4 cool terminal multiplexers

sources/tech/20190321 How to add new disk in Linux.md
sources/tech/20190321 How to add new disk in Linux.md
=> 选题: 20190321 How to add new disk in Linux

sources/talk/20190322 How to save time with TiDB.md
sources/talk/20190322 How to save time with TiDB.md
=> 选题: 20190322 How to save time with TiDB

sources/talk/20190323 How to transition into a Developer Relations career.md
sources/talk/20190323 How to transition into a Developer Relations career.md
=> 选题: 20190323 How to transition into a Developer Relations career

sources/tech/20190322 How to Install OpenLDAP on Ubuntu Server 18.04.md
sources/tech/20190322 How to Install OpenLDAP on Ubuntu Server 18.04.md
=> 选题: 20190322 How to Install OpenLDAP on Ubuntu Server 18.04

sources/tech/20190322 12 open source tools for natural language processing.md
sources/tech/20190322 12 open source tools for natural language processing.md
=> 选题: 20190322 12 open source tools for natural language processing

sources/tech/20190322 Easy means easy to debug.md
sources/tech/20190322 Easy means easy to debug.md
=> 选题: 20190322 Easy means easy to debug

sources/tech/20180205 Rancher - Container Management Application.md
=> translating by arrowfeng

sources/talk/20190329 9 open source tools for building a fault-tolerant system.md
sources/talk/20190329 9 open source tools for building a fault-tolerant system.md
=> 选题: 20190329 9 open source tools for building a fault-tolerant system

sources/tech/20190327 Setting kernel command line arguments with Fedora 30.md
sources/tech/20190327 Setting kernel command line arguments with Fedora 30.md
=> 选题: 20190327 Setting kernel command line arguments with Fedora 30

sources/tech/20190317 How To Configure sudo Access In Linux.md
sources/tech/20190317 How To Configure sudo Access In Linux.md
=> 选题: 20190317 How To Configure sudo Access In Linux?

sources/tech/20190327 How to make a Raspberry Pi gamepad.md
sources/tech/20190327 How to make a Raspberry Pi gamepad.md
=> 选题: 20190327 How to make a Raspberry Pi gamepad

sources/tech/20190326 Using Square Brackets in Bash- Part 1.md
sources/tech/20190326 Using Square Brackets in Bash- Part 1.md
=> 选题: 20190326 Using Square Brackets in Bash: Part 1

sources/tech/20190326 How to use NetBSD on a Raspberry Pi.md
sources/tech/20190326 How to use NetBSD on a Raspberry Pi.md
=> 选题: 20190326 How to use NetBSD on a Raspberry Pi

sources/tech/20190325 Reducing sysadmin toil with Kubernetes controllers.md
sources/tech/20190325 Reducing sysadmin toil with Kubernetes controllers.md
=> 选题: 20190325 Reducing sysadmin toil with Kubernetes controllers

sources/tech/20190321 4 ways to jumpstart productivity at work.md
sources/tech/20190321 4 ways to jumpstart productivity at work.md
=> 选题: 20190321 4 ways to jumpstart productivity at work

sources/tech/20190322 Printing from the Linux command line.md
sources/tech/20190322 Printing from the Linux command line.md
=> 选题: 20190322 Printing from the Linux command line

sources/tech/20190320 Getting started with Jaeger to build an Istio service mesh.md
sources/tech/20190320 Getting started with Jaeger to build an Istio service mesh.md
=> 选题: 20190320 Getting started with Jaeger to build an Istio service mesh

sources/tech/20190325 Getting started with Vim- The basics.md
sources/tech/20190325 Getting started with Vim- The basics.md
=> 选题: 20190325 Getting started with Vim: The basics

sources/tech/20190325 Backup on Fedora Silverblue with Borg.md
sources/tech/20190325 Backup on Fedora Silverblue with Borg.md
=> 选题: 20190325 Backup on Fedora Silverblue with Borg

sources/tech/20190402 How to Install and Configure Plex on Ubuntu Linux.md
sources/tech/20190402 How to Install and Configure Plex on Ubuntu Linux.md
=> 选题: 20190402 How to Install and Configure Plex on Ubuntu Linux

sources/tech/20171226 The shell scripting trap.md
sources/tech/20171226 The shell scripting trap.md
=> 选题: 20171226 The shell scripting trap

sources/talk/20190320 Managing changes in open source projects.md
sources/talk/20190320 Managing changes in open source projects.md
=> 选题: 20190320 Managing changes in open source projects

sources/tech/20190321 How to use Spark SQL- A hands-on tutorial.md
sources/tech/20190321 How to use Spark SQL- A hands-on tutorial.md
=> 选题: 20190321 How to use Spark SQL: A hands-on tutorial

sources/tech/20180407 12 Best GTK Themes for Ubuntu and other Linux Distributions.md
=> translating by robsean

sources/tech/20190326 Bringing Kubernetes to the bare-metal edge.md
sources/tech/20190326 Bringing Kubernetes to the bare-metal edge.md
=> 选题: 20190326 Bringing Kubernetes to the bare-metal edge

sources/talk/20190327 Why DevOps is the most important tech strategy today.md
sources/talk/20190327 Why DevOps is the most important tech strategy today.md
=> 选题: 20190327 Why DevOps is the most important tech strategy today

sources/tech/20190403 5 useful open source log analysis tools.md
sources/tech/20190403 5 useful open source log analysis tools.md
=> 选题: 20190403 5 useful open source log analysis tools

sources/tech/20190402 Manage your daily schedule with Git.md
sources/tech/20190402 Manage your daily schedule with Git.md
=> 选题: 20190402 Manage your daily schedule with Git

sources/talk/20190402 Making computer science curricula as adaptable as our code.md
sources/talk/20190402 Making computer science curricula as adaptable as our code.md
=> 选题: 20190402 Making computer science curricula as adaptable as our code

sources/tech/20190401 Build and host a website with Git.md
sources/tech/20190401 Build and host a website with Git.md
=> 选题: 20190401 Build and host a website with Git

sources/tech/20190402 Automate password resets with PWM.md
sources/tech/20190402 Automate password resets with PWM.md
=> 选题: 20190402 Automate password resets with PWM

sources/talk/20190328 Why do organizations have open secrets.md
sources/talk/20190328 Why do organizations have open secrets.md
=> 选题: 20190328 Why do organizations have open secrets?

sources/talk/20190401 How Kubeflow is evolving without ksonnet.md
sources/talk/20190401 How Kubeflow is evolving without ksonnet.md
=> 选题: 20190401 How Kubeflow is evolving without ksonnet

sources/tech/20190328 How to run PostgreSQL on Kubernetes.md
sources/tech/20190328 How to run PostgreSQL on Kubernetes.md
=> 选题: 20190328 How to run PostgreSQL on Kubernetes

sources/tech/20190403 Use Git as the backend for chat.md
sources/tech/20190403 Use Git as the backend for chat.md
=> 选题: 20190403 Use Git as the backend for chat

sources/tech/20190402 Parallel computation in Python with Dask.md
sources/tech/20190402 Parallel computation in Python with Dask.md
=> 选题: 20190402 Parallel computation in Python with Dask

sources/tech/20160301 How To Set Password Policies In Linux.md
=> how to set password policies in linux

sources/tech/20190401 How to create a filesystem on a Linux partition or logical volume.md
=> How to create a filesystem on a Linux partition or logicl volume

sources/tech/20190403 How to rebase to Fedora 30 Beta on Silverblue.md
sources/tech/20190403 How to rebase to Fedora 30 Beta on Silverblue.md
=> 选题: 20190403 How to rebase to Fedora 30 Beta on Silverblue

sources/tech/20190329 How to submit a bug report with Bugzilla.md
sources/tech/20190329 How to submit a bug report with Bugzilla.md
=> 选题: 20190329 How to submit a bug report with Bugzilla

sources/tech/20190401 3 cool text-based email clients.md
sources/tech/20190401 3 cool text-based email clients.md
=> 选题: 20190401 3 cool text-based email clients

sources/tech/20190405 Command line quick tips- Cutting content out of files.md
sources/tech/20190405 Command line quick tips- Cutting content out of files.md
=> 选题: 20190405 Command line quick tips: Cutting content out of files

sources/tech/20190404 Running LEDs in reverse could cool computers.md
sources/tech/20190404 Running LEDs in reverse could cool computers.md
=> 选题: 20190404 Running LEDs in reverse could cool computers

sources/tech/20190403 Intel unveils an epic response to AMD-s server push.md
sources/tech/20190403 Intel unveils an epic response to AMD-s server push.md
=> 选题: 20190403 Intel unveils an epic response to AMD’s server push

sources/tech/20190402 3 Essentials for Achieving Resiliency at the Edge.md
sources/tech/20190402 3 Essentials for Achieving Resiliency at the Edge.md
=> 选题: 20190402 3 Essentials for Achieving Resiliency at the Edge

sources/tech/20190402 5G- A deep dive into fast, new wireless.md
sources/tech/20190402 5G- A deep dive into fast, new wireless.md
=> 选题: 20190402 5G: A deep dive into fast, new wireless

sources/tech/20190402 Zero-trust- microsegmentation networking.md
sources/tech/20190402 Zero-trust- microsegmentation networking.md
=> 选题: 20190402 Zero-trust: microsegmentation networking

sources/tech/20190401 What is 5G- How is it better than 4G.md
sources/tech/20190401 What is 5G- How is it better than 4G.md
=> 选题: 20190401 What is 5G? How is it better than 4G?

sources/tech/20190204 Enjoy Netflix- You Should Thank FreeBSD.md
sources/tech/20190204 Enjoy Netflix- You Should Thank FreeBSD.md
=> 选题: 20190204 Enjoy Netflix? You Should Thank FreeBSD

sources/tech/20190329 How to manage your Linux environment.md
sources/tech/20190329 How to manage your Linux environment.md
=> 选题: 20190329 How to manage your Linux environment

sources/tech/20190328 Robots in Retail are Real- and so is Edge Computing.md
sources/tech/20190328 Robots in Retail are Real- and so is Edge Computing.md
=> 选题: 20190328 Robots in Retail are Real… and so is Edge Computing

sources/tech/20190328 Microsoft introduces Azure Stack for HCI.md
sources/tech/20190328 Microsoft introduces Azure Stack for HCI.md
=> 选题: 20190328 Microsoft introduces Azure Stack for HCI

sources/tech/20190326 Today-s Retailer is Turning to the Edge for CX.md
sources/tech/20190326 Today-s Retailer is Turning to the Edge for CX.md
=> 选题: 20190326 Today’s Retailer is Turning to the Edge for CX

sources/tech/20190326 An inside look at an IIoT-powered smart factory.md
sources/tech/20190326 An inside look at an IIoT-powered smart factory.md
=> 选题: 20190326 An inside look at an IIoT-powered smart factory

sources/tech/20190318 Let-s try dwm - dynamic window manager.md
sources/tech/20190318 Let-s try dwm - dynamic window manager.md
=> 选题: 20190318 Let’s try dwm — dynamic window manager

sources/tech/20190322 How to set up Fedora Silverblue as a gaming station.md
sources/tech/20190322 How to set up Fedora Silverblue as a gaming station.md
=> 选题: 20190322 How to set up Fedora Silverblue as a gaming station

sources/tech/20190325 Contribute at the Fedora Test Day for Fedora Modularity.md
sources/tech/20190325 Contribute at the Fedora Test Day for Fedora Modularity.md
=> 选题: 20190325 Contribute at the Fedora Test Day for Fedora Modularity

sources/tech/20190315 Mageia Linux Is a Modern Throwback to the Underdog Days.md
sources/tech/20190315 Mageia Linux Is a Modern Throwback to the Underdog Days.md
=> 选题: 20190315 Mageia Linux Is a Modern Throwback to the Underdog Days

sources/tech/20190405 How to Authenticate a Linux Desktop to Your OpenLDAP Server.md
sources/tech/20190405 How to Authenticate a Linux Desktop to Your OpenLDAP Server.md
=> 选题: 20190405 How to Authenticate a Linux Desktop to Your OpenLDAP Server

sources/tech/20190402 Using Square Brackets in Bash- Part 2.md
sources/tech/20190402 Using Square Brackets in Bash- Part 2.md
=> 选题: 20190402 Using Square Brackets in Bash: Part 2

sources/tech/20190321 Top 10 New Linux SBCs to Watch in 2019.md
sources/tech/20190321 Top 10 New Linux SBCs to Watch in 2019.md
=> 选题: 20190321 Top 10 New Linux SBCs to Watch in 2019

sources/tech/20190327 HPE introduces hybrid cloud consulting business.md
sources/tech/20190327 HPE introduces hybrid cloud consulting business.md
=> 选题: 20190327 HPE introduces hybrid cloud consulting business

sources/tech/20190131 VA Linux- The Linux Company That Once Ruled NASDAQ.md
sources/tech/20190131 VA Linux- The Linux Company That Once Ruled NASDAQ.md
=> 选题: 20190131 VA Linux: The Linux Company That Once Ruled NASDAQ

sources/tech/20190202 CrossCode is an Awesome 16-bit Sci-Fi RPG Game.md
sources/tech/20190202 CrossCode is an Awesome 16-bit Sci-Fi RPG Game.md
=> 选题: 20190202 CrossCode is an Awesome 16-bit Sci-Fi RPG Game

sources/tech/20190407 Fixing Ubuntu Freezing at Boot Time.md
sources/tech/20190407 Fixing Ubuntu Freezing at Boot Time.md
=> 选题: 20190407 Fixing Ubuntu Freezing at Boot Time

sources/tech/20190207 Review of Debian System Administrator-s Handbook.md
sources/tech/20190207 Review of Debian System Administrator-s Handbook.md
=> 选题: 20190207 Review of Debian System Administrator’s Handbook

sources/tech/20190405 File sharing with Git.md
sources/tech/20190405 File sharing with Git.md
=> 选题: 20190405 File sharing with Git

sources/tech/20190406 Run a server with Git.md
sources/tech/20190406 Run a server with Git.md
=> 选题: 20190406 Run a server with Git

sources/tech/20190407 Happy 14th anniversary Git- What do you love about Git.md
sources/tech/20190407 Happy 14th anniversary Git- What do you love about Git.md
=> 选题: 20190407 Happy 14th anniversary Git: What do you love about Git?

sources/tech/20190407 Manage multimedia files with Git.md
sources/tech/20190407 Manage multimedia files with Git.md
=> 选题: 20190407 Manage multimedia files with Git

sources/tech/20190409 Anbox - Easy Way To Run Android Apps On Linux.md
sources/tech/20190409 Anbox - Easy Way To Run Android Apps On Linux.md
=> 选题: 20190409 Anbox – Easy Way To Run Android Apps On Linux

sources/tech/20190409 Four Methods To Add A User To Group In Linux.md
sources/tech/20190409 Four Methods To Add A User To Group In Linux.md
=> 选题: 20190409 Four Methods To Add A User To Group In Linux

sources/tech/20190409 How To Install And Configure Chrony As NTP Client.md
sources/tech/20190409 How To Install And Configure Chrony As NTP Client.md
=> 选题: 20190409 How To Install And Configure Chrony As NTP Client?

sources/tech/20190409 How To Install And Enable Flatpak Support On Linux.md
sources/tech/20190409 How To Install And Enable Flatpak Support On Linux.md
=> 选题: 20190409 How To Install And Enable Flatpak Support On Linux?

sources/tech/20190408 Getting started with Python-s cryptography library.md
sources/tech/20190408 Getting started with Python-s cryptography library.md
=> 选题: 20190408 Getting started with Python's cryptography library

sources/tech/20190408 Bash vs. Python- Which language should you use.md
sources/tech/20190408 Bash vs. Python- Which language should you use.md
=> 选题: 20190408 Bash vs. Python: Which language should you use?

sources/tech/20190405 Streaming internet radio with RadioDroid.md
sources/tech/20190405 Streaming internet radio with RadioDroid.md
=> 选题: 20190405 Streaming internet radio with RadioDroid

sources/tech/20190405 5 open source tools for teaching young children to read.md
sources/tech/20190405 5 open source tools for teaching young children to read.md
=> 选题: 20190405 5 open source tools for teaching young children to read

sources/tech/20190404 9 features developers should know about Selenium IDE.md
sources/tech/20190404 9 features developers should know about Selenium IDE.md
=> 选题: 20190404 9 features developers should know about Selenium IDE

sources/tech/20190402 Intel-s Agilex FPGA family targets data-intensive workloads.md
sources/tech/20190402 Intel-s Agilex FPGA family targets data-intensive workloads.md
=> 选题: 20190402 Intel's Agilex FPGA family targets data-intensive workloads

sources/tech/20190325 How Open Source Is Accelerating NFV Transformation.md
sources/tech/20190325 How Open Source Is Accelerating NFV Transformation.md
=> 选题: 20190325 How Open Source Is Accelerating NFV Transformation

sources/tech/20190409 5 open source mobile apps.md
sources/tech/20190409 5 open source mobile apps.md
=> 选题: 20190409 5 open source mobile apps

sources/tech/20190409 5 Linux rookie mistakes.md
sources/tech/20190409 5 Linux rookie mistakes.md
=> 选题: 20190409 5 Linux rookie mistakes

sources/tech/20190409 What it takes to become a blockchain developer.md
sources/tech/20190409 What it takes to become a blockchain developer.md
=> 选题: 20190409 What it takes to become a blockchain developer

sources/tech/20190409 AI Ops- Let the data talk.md
sources/tech/20190409 AI Ops- Let the data talk.md
=> 选题: 20190409 AI Ops: Let the data talk

sources/tech/20190409 Working with variables on Linux.md
sources/tech/20190409 Working with variables on Linux.md
=> 选题: 20190409 Working with variables on Linux

sources/tech/20190409 Juniper opens SD-WAN service for the cloud.md
sources/tech/20190409 Juniper opens SD-WAN service for the cloud.md
=> 选题: 20190409 Juniper opens SD-WAN service for the cloud

sources/tech/20190409 Enhanced security at the edge.md
sources/tech/20190409 Enhanced security at the edge.md
=> 选题: 20190409 Enhanced security at the edge

sources/tech/20190410 How To Check The List Of Open Ports In Linux.md
sources/tech/20190410 How To Check The List Of Open Ports In Linux.md
=> 选题: 20190410 How To Check The List Of Open Ports In Linux?

sources/tech/20190313 How to contribute to the Raspberry Pi community.md
sources/tech/20190313 How to contribute to the Raspberry Pi community.md
=> 选题: 20190313 How to contribute to the Raspberry Pi community

sources/talk/20190410 Google partners with Intel, HPE and Lenovo for hybrid cloud.md
sources/talk/20190410 Google partners with Intel, HPE and Lenovo for hybrid cloud.md
=> 选题: 20190410 Google partners with Intel, HPE and Lenovo for hybrid cloud

sources/tech/20190410 How to enable serverless computing in Kubernetes.md
sources/tech/20190410 How to enable serverless computing in Kubernetes.md
=> 选题: 20190410 How to enable serverless computing in Kubernetes

sources/tech/20190410 How we built a Linux desktop app with Electron.md
sources/tech/20190410 How we built a Linux desktop app with Electron.md
=> 选题: 20190410 How we built a Linux desktop app with Electron

sources/tech/20190410 Managing Partitions with sgdisk.md
sources/tech/20190410 Managing Partitions with sgdisk.md
=> 选题: 20190410 Managing Partitions with sgdisk

translated/tech/20190410 How To Check The List Of Open Ports In Linux.md
Check The List Of Open Ports In Linux.md → ... Check The List Of Open Ports In Linux.md
=> Check The List Of Open Ports In Linux

sources/tech/20190411 Installing Ubuntu MATE on a Raspberry Pi.md
sources/tech/20190411 Installing Ubuntu MATE on a Raspberry Pi.md
=> 选题: 20190411 Installing Ubuntu MATE on a Raspberry Pi

sources/tech/20190411 How do you contribute to open source without code.md
sources/tech/20190411 How do you contribute to open source without code.md
=> 选题: 20190411 How do you contribute to open source without code?

sources/tech/20190411 Be your own certificate authority.md
sources/tech/20190411 Be your own certificate authority.md
=> 选题: 20190411 Be your own certificate authority

sources/tech/20190411 Testing Small Scale Scrum in the real world.md
sources/tech/20190411 Testing Small Scale Scrum in the real world.md
=> 选题: 20190411 Testing Small Scale Scrum in the real world

sources/tech/20190413 The Fargate Illusion.md
sources/tech/20190413 The Fargate Illusion.md
@wxy
=> 选题: 20190413 The Fargate Illusion

sources/tech/20190412 Joe Doss- How Do You Fedora.md
sources/tech/20190412 Joe Doss- How Do You Fedora.md
=> 选题: 20190412 Joe Doss: How Do You Fedora?

sources/tech/20190414 Working with Microsoft Exchange from your Linux Desktop.md
sources/tech/20190414 Working with Microsoft Exchange from your Linux Desktop.md
=> 选题: 20190414 Working with Microsoft Exchange from your Linux Desktop

sources/tech/20190413 How to Zip Files and Folders in Linux -Beginner Tip.md
sources/tech/20190413 How to Zip Files and Folders in Linux -Beginner Tip.md
=> 选题: 20190413 How to Zip Files and Folders in Linux [Beginner Tip]

sources/tech/20190412 How libraries are adopting open source.md
sources/tech/20190412 How libraries are adopting open source.md
=> 选题: 20190412 How libraries are adopting open source

sources/tech/20190412 Designing posters with Krita, Scribus, and Inkscape.md
sources/tech/20190412 Designing posters with Krita, Scribus, and Inkscape.md
=> 选题: 20190412 Designing posters with Krita, Scribus, and Inkscape

published/20190314 A Look Back at the History of Firefox.md
修正链接错误 @lujun9972 这个应该是 md 制作过程的问题，可以回头看看。
=> PRF:20190314 A Look Back at the History of Firefox

sources/tech/20190415 Kubernetes on Fedora IoT with k3s.md
sources/tech/20190415 Kubernetes on Fedora IoT with k3s.md
=> 选题: 20190415 Kubernetes on Fedora IoT with k3s

sources/tech/20190415 Troubleshooting slow WiFi on Linux.md
sources/tech/20190415 Troubleshooting slow WiFi on Linux.md
=> 选题: 20190415 Troubleshooting slow WiFi on Linux

sources/tech/20190416 Linux Foundation Training Courses Sale - Discount Coupon.md
sources/tech/20190416 Linux Foundation Training Courses Sale - Discount Coupon.md
=> 选题: 20190416 Linux Foundation Training Courses Sale & Discount Coupon

sources/tech/20190416 How to Install MySQL in Ubuntu Linux.md
sources/tech/20190416 How to Install MySQL in Ubuntu Linux.md
=> 选题: 20190416 How to Install MySQL in Ubuntu Linux

sources/tech/20190416 Building a DNS-as-a-service with OpenStack Designate.md
sources/tech/20190416 Building a DNS-as-a-service with OpenStack Designate.md
=> 选题: 20190416 Building a DNS-as-a-service with OpenStack Designate

sources/tech/20190416 Detecting malaria with deep learning.md
sources/tech/20190416 Detecting malaria with deep learning.md
=> 选题: 20190416 Detecting malaria with deep learning

sources/tech/20190416 Can schools be agile.md
sources/tech/20190416 Can schools be agile.md
=> 选题: 20190416 Can schools be agile?

sources/tech/20190415 Getting started with Mercurial for version control.md
sources/tech/20190415 Getting started with Mercurial for version control.md
=> 选题: 20190415 Getting started with Mercurial for version control

sources/tech/20190415 Inter-process communication in Linux- Shared storage.md
sources/tech/20190415 Inter-process communication in Linux- Shared storage.md
=> 选题: 20190415 Inter-process communication in Linux: Shared storage

sources/talk/20190416 What SDN is and where it-s going.md
sources/talk/20190416 What SDN is and where it-s going.md
=> 选题: 20190416 What SDN is and where it’s going

sources/tech/20190415 How to identify duplicate files on Linux.md
sources/tech/20190415 How to identify duplicate files on Linux.md
=> 选题: 20190415 How to identify duplicate files on Linux

sources/talk/20190415 Nyansa-s Voyance expands to the IoT.md
sources/talk/20190415 Nyansa-s Voyance expands to the IoT.md
=> 选题: 20190415 Nyansa’s Voyance expands to the IoT

sources/tech/20190419 4 cool new projects to try in COPR for April 2019.md
sources/tech/20190419 4 cool new projects to try in COPR for April 2019.md
=> 选题: 20190419 4 cool new projects to try in COPR for April 2019

sources/tech/20190417 Managing RAID arrays with mdadm.md
sources/tech/20190417 Managing RAID arrays with mdadm.md
=> 选题: 20190417 Managing RAID arrays with mdadm

sources/tech/20190416 Move Data to the Cloud with Azure Data Migration.md
sources/tech/20190416 Move Data to the Cloud with Azure Data Migration.md
=> 选题: 20190416 Move Data to the Cloud with Azure Data Migration

sources/tech/20190420 New Features Coming to Debian 10 Buster Release.md
sources/tech/20190420 New Features Coming to Debian 10 Buster Release.md
=> 选题: 20190420 New Features Coming to Debian 10 Buster Release

sources/tech/20190419 This is how System76 does open hardware.md
sources/tech/20190419 This is how System76 does open hardware.md
=> 选题: 20190419 This is how System76 does open hardware

sources/tech/20190418 How to organize with Calculist- Ideas, events, and more.md
sources/tech/20190418 How to organize with Calculist- Ideas, events, and more.md
=> 选题: 20190418 How to organize with Calculist: Ideas, events, and more

sources/tech/20190418 Level up command-line playgrounds with WebAssembly.md
sources/tech/20190418 Level up command-line playgrounds with WebAssembly.md
=> 选题: 20190418 Level up command-line playgrounds with WebAssembly

sources/tech/20190417 How to use Ansible to document procedures.md
sources/tech/20190417 How to use Ansible to document procedures.md
=> 选题: 20190417 How to use Ansible to document procedures

sources/talk/20190417 Clearing up confusion between edge and cloud.md
sources/talk/20190417 Clearing up confusion between edge and cloud.md
=> 选题: 20190417 Clearing up confusion between edge and cloud

sources/talk/20190417 Want to the know future of IoT- Ask the developers.md
sources/talk/20190417 Want to the know future of IoT- Ask the developers.md
=> 选题: 20190417 Want to the know future of IoT? Ask the developers!

sources/tech/20190417 Inter-process communication in Linux- Sockets and signals.md
sources/tech/20190417 Inter-process communication in Linux- Sockets and signals.md
=> 选题: 20190417 Inter-process communication in Linux: Sockets and signals

sources/tech/20190422 2 new apps for music tweakers on Fedora Workstation.md
sources/tech/20190422 2 new apps for music tweakers on Fedora Workstation.md
=> 选题: 20190422 2 new apps for music tweakers on Fedora Workstation

sources/tech/20190422 9 ways to save the planet.md
sources/tech/20190422 9 ways to save the planet.md
=> 选题: 20190422 9 ways to save the planet

sources/tech/20190422 Tracking the weather with Python and Prometheus.md
sources/tech/20190422 Tracking the weather with Python and Prometheus.md
=> 选题: 20190422 Tracking the weather with Python and Prometheus

sources/tech/20190422 4 open source apps for plant-based diets.md
sources/tech/20190422 4 open source apps for plant-based diets.md
=> 选题: 20190422 4 open source apps for plant-based diets

sources/tech/20190422 Strawberry- A Fork of Clementine Music Player.md
sources/tech/20190422 Strawberry- A Fork of Clementine Music Player.md
=> 选题: 20190422 Strawberry: A Fork of Clementine Music Player

sources/tech/20190402 Announcing the release of Fedora 30 Beta.md
This reverts commit ac33225de30eb62c96d09fef0eb91c2021ddb4a9.
=> Revert "translating"

sources/tech/20180831 Get desktop notifications from Emacs shell commands .md
sources/tech/20180831 Get desktop notifications from Emacs shell commands .md
=> 选题: 20180831 Get desktop notifications from Emacs shell commands ·

published/20180823 Getting started with Sensu monitoring.md, translated/tech/20180823 Getting started with Sensu monitoring.md
@MjSeven https://linux.cn/article-10783-1.html
=> PRF&PUB:20180823 Getting started with Sensu monitoring

sources/tech/20190503 SuiteCRM- An Open Source CRM Takes Aim At Salesforce.md
sources/tech/20190503 SuiteCRM- An Open Source CRM Takes Aim At Salesforce.md
=> 选题: 20190503 SuiteCRM: An Open Source CRM Takes Aim At Salesforce

sources/tech/20190505 Five Methods To Check Your Current Runlevel In Linux.md
sources/tech/20190505 Five Methods To Check Your Current Runlevel In Linux.md
=> 选题: 20190505 Five Methods To Check Your Current Runlevel In Linux?

sources/tech/20190503 Mirror your System Drive using Software RAID.md
sources/tech/20190503 Mirror your System Drive using Software RAID.md
=> 选题: 20190503 Mirror your System Drive using Software RAID

sources/tech/20190501 3 apps to manage personal finances in Fedora.md
sources/tech/20190501 3 apps to manage personal finances in Fedora.md
=> 选题: 20190501 3 apps to manage personal finances in Fedora

sources/tech/20190430 Upgrading Fedora 29 to Fedora 30.md
sources/tech/20190430 Upgrading Fedora 29 to Fedora 30.md
=> 选题: 20190430 Upgrading Fedora 29 to Fedora 30

sources/tech/20190505 Blockchain 2.0 - What Is Ethereum -Part 9.md
sources/tech/20190505 Blockchain 2.0 - What Is Ethereum -Part 9.md
=> 选题: 20190505 Blockchain 2.0 – What Is Ethereum [Part 9]

sources/tech/20190429 Awk utility in Fedora.md
sources/tech/20190429 Awk utility in Fedora.md
=> 选题: 20190429 Awk utility in Fedora

sources/tech/20190425 Automate backups with restic and systemd.md
sources/tech/20190425 Automate backups with restic and systemd.md
=> 选题: 20190425 Automate backups with restic and systemd

sources/tech/20190423 How to identify same-content files on Linux.md
sources/tech/20190423 How to identify same-content files on Linux.md
=> 选题: 20190423 How to identify same-content files on Linux

sources/tech/20190430 The Awesome Fedora 30 is Here- Check Out the New Features.md
sources/tech/20190430 The Awesome Fedora 30 is Here- Check Out the New Features.md
=> 选题: 20190430 The Awesome Fedora 30 is Here! Check Out the New Features

sources/tech/20190428 Installing Budgie Desktop on Ubuntu -Quick Guide.md
sources/tech/20190428 Installing Budgie Desktop on Ubuntu -Quick Guide.md
=> 选题: 20190428 Installing Budgie Desktop on Ubuntu [Quick Guide]

sources/tech/20190427 Monitoring CPU and GPU Temperatures on Linux.md
sources/tech/20190427 Monitoring CPU and GPU Temperatures on Linux.md
=> 选题: 20190427 Monitoring CPU and GPU Temperatures on Linux

sources/tech/20190426 NomadBSD, a BSD for the Road.md
sources/tech/20190426 NomadBSD, a BSD for the Road.md
=> 选题: 20190426 NomadBSD, a BSD for the Road

sources/tech/20190423 Epic Games Store is Now Available on Linux Thanks to Lutris.md
sources/tech/20190423 Epic Games Store is Now Available on Linux Thanks to Lutris.md
=> 选题: 20190423 Epic Games Store is Now Available on Linux Thanks to Lutris

sources/tech/20190504 Add methods retroactively in Python with singledispatch.md
sources/tech/20190504 Add methods retroactively in Python with singledispatch.md
=> 选题: 20190504 Add methods retroactively in Python with singledispatch

sources/tech/20190425 Debian has a New Project Leader.md
sources/tech/20190425 Debian has a New Project Leader.md
=> 选题: 20190425 Debian has a New Project Leader

sources/tech/20190504 Using the force at the Linux command line.md
sources/tech/20190504 Using the force at the Linux command line.md
=> 选题: 20190504 Using the force at the Linux command line

sources/tech/20190503 Check your spelling at the command line with Ispell.md
sources/tech/20190503 Check your spelling at the command line with Ispell.md
=> 选题: 20190503 Check your spelling at the command line with Ispell

sources/tech/20190503 API evolution the right way.md
sources/tech/20190503 API evolution the right way.md
=> 选题: 20190503 API evolution the right way

sources/tech/20190503 Say goodbye to boilerplate in Python with attrs.md
sources/tech/20190503 Say goodbye to boilerplate in Python with attrs.md
=> 选题: 20190503 Say goodbye to boilerplate in Python with attrs

sources/tech/20190502 Format Python however you like with Black.md
sources/tech/20190502 Format Python however you like with Black.md
=> 选题: 20190502 Format Python however you like with Black

sources/talk/20190501 Health care is still stitching together IoT systems.md
sources/talk/20190501 Health care is still stitching together IoT systems.md
=> 选题: 20190501 Health care is still stitching together IoT systems

sources/talk/20190430 Must-know Linux Commands.md
sources/talk/20190430 Must-know Linux Commands.md
=> 选题: 20190430 Must-know Linux Commands

sources/talk/20190429 How to shop for enterprise firewalls.md
sources/talk/20190429 How to shop for enterprise firewalls.md
=> 选题: 20190429 How to shop for enterprise firewalls

sources/talk/20190423 Edge computing is in most industries- future.md
sources/talk/20190423 Edge computing is in most industries- future.md
=> 选题: 20190423 Edge computing is in most industries’ future

sources/talk/20190424 No, drone delivery still isn-t ready for prime time.md
sources/talk/20190424 No, drone delivery still isn-t ready for prime time.md
=> 选题: 20190424 No, drone delivery still isn’t ready for prime time

sources/talk/20190424 How data storage will shift to blockchain.md
sources/talk/20190424 How data storage will shift to blockchain.md
=> 选题: 20190424 How data storage will shift to blockchain

sources/talk/20190424 Cisco- DNSpionage attack adds new tools, morphs tactics.md
sources/talk/20190424 Cisco- DNSpionage attack adds new tools, morphs tactics.md
=> 选题: 20190424 Cisco: DNSpionage attack adds new tools, morphs tactics

sources/talk/20190424 IoT roundup- VMware, Nokia beef up their IoT.md
sources/talk/20190424 IoT roundup- VMware, Nokia beef up their IoT.md
=> 选题: 20190424 IoT roundup: VMware, Nokia beef up their IoT

sources/talk/20190425 Dell EMC and Cisco renew converged infrastructure alliance.md
sources/talk/20190425 Dell EMC and Cisco renew converged infrastructure alliance.md
=> 选题: 20190425 Dell EMC and Cisco renew converged infrastructure alliance

sources/talk/20190429 Cisco goes all in on WiFi 6.md
sources/talk/20190429 Cisco goes all in on WiFi 6.md
=> 选题: 20190429 Cisco goes all in on WiFi 6

sources/talk/20190430 Measuring the edge- Finding success with edge deployments.md
sources/talk/20190430 Measuring the edge- Finding success with edge deployments.md
=> 选题: 20190430 Measuring the edge: Finding success with edge deployments

sources/tech/20190501 Looking into Linux modules.md
sources/tech/20190501 Looking into Linux modules.md
=> 选题: 20190501 Looking into Linux modules

sources/tech/20190502 The making of the Breaking the Code electronic book.md
sources/tech/20190502 The making of the Breaking the Code electronic book.md
=> 选题: 20190502 The making of the Breaking the Code electronic book

sources/tech/20190502 Crowdsourcing license compliance with ClearlyDefined.md
sources/tech/20190502 Crowdsourcing license compliance with ClearlyDefined.md
=> 选题: 20190502 Crowdsourcing license compliance with ClearlyDefined

sources/tech/20190505 How To Create SSH Alias In Linux.md
sources/tech/20190505 How To Create SSH Alias In Linux.md
=> 选题: 20190505 How To Create SSH Alias In Linux

sources/tech/20190505 Kindd - A Graphical Frontend To dd Command.md
sources/tech/20190505 Kindd - A Graphical Frontend To dd Command.md
=> 选题: 20190505 Kindd – A Graphical Frontend To dd Command

sources/tech/20190505 How To Navigate Directories Faster In Linux.md
sources/tech/20190505 How To Navigate Directories Faster In Linux.md
=> 选题: 20190505 How To Navigate Directories Faster In Linux

published/20190416 Building a DNS-as-a-service with OpenStack Designate.md, translated/tech/20190416 Building a DNS-as-a-service with OpenStack Designate.md
@wxy https://linux.cn/article-10840-1.html
=> PRF&PUB:20190416 Building a DNS as a service with OpenStack Designate

sources/tech/20190510 Check storage performance with dd.md
sources/tech/20190510 Check storage performance with dd.md
=> 选题: 20190510 Check storage performance with dd

sources/tech/20190513 How To Set Password Complexity On Linux.md
sources/tech/20190513 How To Set Password Complexity On Linux.md
=> 选题: 20190513 How To Set Password Complexity On Linux?

sources/tech/20190510 How to Use 7Zip in Ubuntu and Other Linux -Quick Tip.md
sources/tech/20190510 How to Use 7Zip in Ubuntu and Other Linux -Quick Tip.md
=> 选题: 20190510 How to Use 7Zip in Ubuntu and Other Linux [Quick Tip]

sources/tech/20190501 Write faster C extensions for Python with Cython.md
sources/tech/20190501 Write faster C extensions for Python with Cython.md
=> 选题: 20190501 Write faster C extensions for Python with Cython

sources/talk/20190510 Supermicro moves production from China.md
sources/talk/20190510 Supermicro moves production from China.md
=> 选题: 20190510 Supermicro moves production from China

sources/talk/20190509 Cisco adds AMP to SD-WAN for ISR-ASR routers.md
sources/talk/20190509 Cisco adds AMP to SD-WAN for ISR-ASR routers.md
=> 选题: 20190509 Cisco adds AMP to SD-WAN for ISR/ASR routers

sources/tech/20190508 Why startups should release their code as open source.md
sources/tech/20190508 Why startups should release their code as open source.md
=> 选题: 20190508 Why startups should release their code as open source

sources/tech/20190508 How to use advanced rsync for large Linux backups.md
sources/tech/20190508 How to use advanced rsync for large Linux backups.md
=> 选题: 20190508 How to use advanced rsync for large Linux backups

sources/tech/20190506 Use udica to build SELinux policy for containers.md
sources/tech/20190506 Use udica to build SELinux policy for containers.md
=> 选题: 20190506 Use udica to build SELinux policy for containers

sources/tech/20190506 How to Add Application Shortcuts on Ubuntu Desktop.md
sources/tech/20190506 How to Add Application Shortcuts on Ubuntu Desktop.md
=> 选题: 20190506 How to Add Application Shortcuts on Ubuntu Desktop

sources/tech/20190505 -Review- Void Linux, a Linux BSD Hybrid.md
sources/tech/20190505 -Review- Void Linux, a Linux BSD Hybrid.md
=> 选题: 20190505 [Review] Void Linux, a Linux BSD Hybrid

sources/tech/20190510 Keeping an open source project alive when people leave.md
sources/tech/20190510 Keeping an open source project alive when people leave.md
=> 选题: 20190510 Keeping an open source project alive when people leave

sources/tech/20190510 5 open source hardware products for the great outdoors.md
sources/tech/20190510 5 open source hardware products for the great outdoors.md
=> 选题: 20190510 5 open source hardware products for the great outdoors

sources/tech/20190509 5 essential values for the DevOps mindset.md
sources/tech/20190509 5 essential values for the DevOps mindset.md
=> 选题: 20190509 5 essential values for the DevOps mindset

sources/talk/20190506 Cisco boosts SD-WAN with multicloud-to-branch access system.md
sources/talk/20190506 Cisco boosts SD-WAN with multicloud-to-branch access system.md
=> 选题: 20190506 Cisco boosts SD-WAN with multicloud-to-branch access system

sources/talk/20190507 SD-WAN is Critical for IoT.md
sources/talk/20190507 SD-WAN is Critical for IoT.md
=> 选题: 20190507 SD-WAN is Critical for IoT

sources/talk/20190507 Some IT pros say they have too much data.md
sources/talk/20190507 Some IT pros say they have too much data.md
=> 选题: 20190507 Some IT pros say they have too much data

published/20190510 How to Use 7Zip in Ubuntu and Other Linux -Quick Tip.md, translated/tech/20190510 How to Use 7Zip in Ubuntu and Other Linux -Quick Tip.md
@warmfrog https://linux.cn/article-10855-1.html
=> PRF&PUB:20190510 How to Use 7Zip in Ubuntu and Other Linux  Quick Tip

sources/tech/20190510 Learn to change history with git rebase.md
sources/tech/20190510 Learn to change history with git rebase.md
=> 选题: 20190510 Learn to change history with git rebase!

sources/tech/20190510 PHP in 2019.md
sources/tech/20190510 PHP in 2019.md
@wxy 讲PHP的现状的，老大亲自来一篇？
=> 选题: 20190510 PHP in 2019

sources/tech/20190516 Building Smaller Container Images.md
sources/tech/20190516 Building Smaller Container Images.md
=> 选题: 20190516 Building Smaller Container Images

sources/tech/20190520 PiShrink - Make Raspberry Pi Images Smaller.md
sources/tech/20190520 PiShrink - Make Raspberry Pi Images Smaller.md
=> 选题: 20190520 PiShrink – Make Raspberry Pi Images Smaller

sources/tech/20190520 Getting Started With Docker.md
sources/tech/20190520 Getting Started With Docker.md
=> 选题: 20190520 Getting Started With Docker

sources/talk/20190513 HPE-s CEO lays out his technology vision.md
sources/talk/20190513 HPE-s CEO lays out his technology vision.md
=> 选题: 20190513 HPE’s CEO lays out his technology vision

sources/talk/20190513 Top auto makers rely on cloud providers for IoT.md
sources/talk/20190513 Top auto makers rely on cloud providers for IoT.md
=> 选题: 20190513 Top auto makers rely on cloud providers for IoT

sources/tech/20190513 When to be concerned about memory levels on Linux.md
sources/tech/20190513 When to be concerned about memory levels on Linux.md
=> 选题: 20190513 When to be concerned about memory levels on Linux

sources/talk/20190515 Extreme addresses networked-IoT security.md
sources/talk/20190515 Extreme addresses networked-IoT security.md
=> 选题: 20190515 Extreme addresses networked-IoT security

sources/talk/20190516 Will 5G be the first carbon-neutral network.md
sources/talk/20190516 Will 5G be the first carbon-neutral network.md
=> 选题: 20190516 Will 5G be the first carbon-neutral network?

sources/tech/20190515 How to manage access control lists with Ansible.md
sources/tech/20190515 How to manage access control lists with Ansible.md
=> 选题: 20190515 How to manage access control lists with Ansible

sources/tech/20190516 System76-s secret sauce for success.md
sources/tech/20190516 System76-s secret sauce for success.md
=> 选题: 20190516 System76's secret sauce for success

sources/tech/20190517 Using Testinfra with Ansible to verify server state.md
sources/tech/20190517 Using Testinfra with Ansible to verify server state.md
=> 选题: 20190517 Using Testinfra with Ansible to verify server state

sources/tech/20190517 Announcing Enarx for running sensitive workloads.md
sources/tech/20190517 Announcing Enarx for running sensitive workloads.md
=> 选题: 20190517 Announcing Enarx for running sensitive workloads

sources/tech/20190513 How to SSH into a Raspberry Pi -Beginner-s Tip.md
sources/tech/20190513 How to SSH into a Raspberry Pi -Beginner-s Tip.md
=> 选题: 20190513 How to SSH into a Raspberry Pi [Beginner’s Tip]

sources/tech/20190517 10 Places Where You Can Buy Linux Computers.md
sources/tech/20190517 10 Places Where You Can Buy Linux Computers.md
=> 选题: 20190517 10 Places Where You Can Buy Linux Computers

sources/tech/20190513 Manage business documents with OpenAS2 on Fedora.md
sources/tech/20190513 Manage business documents with OpenAS2 on Fedora.md
=> 选题: 20190513 Manage business documents with OpenAS2 on Fedora

sources/tech/20190520 xsos - A Tool To Read SOSReport In Linux.md
sources/tech/20190520 xsos - A Tool To Read SOSReport In Linux.md
=> 选题: 20190520 xsos – A Tool To Read SOSReport In Linux

sources/talk/20180604 10 principles of resilience for women in tech.md
=> Update 20180604 10 principles of resilience for women in tech.md

sources/tech/20190527 How to write a good C main function.md
sources/tech/20190527 How to write a good C main function.md
=> 选题: 20190527 How to write a good C main function

sources/tech/20190527 Dockly - Manage Docker Containers From Terminal.md
sources/tech/20190527 Dockly - Manage Docker Containers From Terminal.md
=> 选题: 20190527 Dockly – Manage Docker Containers From Terminal

sources/tech/20190527 20- FFmpeg Commands For Beginners.md
sources/tech/20190527 20- FFmpeg Commands For Beginners.md
=> 选题: 20190527 20+ FFmpeg Commands For Beginners

sources/talk/20190521 Enterprise IoT- Companies want solutions in these 4 areas.md
sources/talk/20190521 Enterprise IoT- Companies want solutions in these 4 areas.md
=> 选题: 20190521 Enterprise IoT: Companies want solutions in these 4 areas

sources/tech/20190527 5 GNOME keyboard shortcuts to be more productive.md
sources/tech/20190527 5 GNOME keyboard shortcuts to be more productive.md
=> 选题: 20190527 5 GNOME keyboard shortcuts to be more productive

sources/tech/20190522 Securing telnet connections with stunnel.md
sources/tech/20190522 Securing telnet connections with stunnel.md
=> 选题: 20190522 Securing telnet connections with stunnel

sources/tech/20190522 Damn- Antergos Linux has been Discontinued.md
sources/tech/20190522 Damn- Antergos Linux has been Discontinued.md
=> 选题: 20190522 Damn! Antergos Linux has been Discontinued

sources/talk/20190522 French IT giant Atos enters the edge-computing business.md
sources/talk/20190522 French IT giant Atos enters the edge-computing business.md
=> 选题: 20190522 French IT giant Atos enters the edge-computing business

sources/talk/20190522 Experts- Enterprise IoT enters the mass-adoption phase.md
sources/talk/20190522 Experts- Enterprise IoT enters the mass-adoption phase.md
=> 选题: 20190522 Experts: Enterprise IoT enters the mass-adoption phase

sources/talk/20190523 Benchmarks of forthcoming Epyc 2 processor leaked.md
sources/talk/20190523 Benchmarks of forthcoming Epyc 2 processor leaked.md
=> 选题: 20190523 Benchmarks of forthcoming Epyc 2 processor leaked

sources/talk/20190523 Study- Most enterprise IoT transactions are unencrypted.md
sources/talk/20190523 Study- Most enterprise IoT transactions are unencrypted.md
=> 选题: 20190523 Study: Most enterprise IoT transactions are unencrypted

sources/tech/20190522 Convert Markdown files to word processor docs using pandoc.md
sources/tech/20190522 Convert Markdown files to word processor docs using pandoc.md
=> 选题: 20190522 Convert Markdown files to word processor docs using pandoc

sources/tech/20190523 Testing a Go-based S2I builder image.md
sources/tech/20190523 Testing a Go-based S2I builder image.md
=> 选题: 20190523 Testing a Go-based S2I builder image

sources/tech/20190524 Dual booting Windows and Linux using UEFI.md
sources/tech/20190524 Dual booting Windows and Linux using UEFI.md
=> 选题: 20190524 Dual booting Windows and Linux using UEFI

sources/tech/20190523 Hardware bootstrapping with Ansible.md
sources/tech/20190523 Hardware bootstrapping with Ansible.md
=> 选题: 20190523 Hardware bootstrapping with Ansible

sources/tech/20190523 Run your blog on GitHub Pages with Python.md
sources/tech/20190523 Run your blog on GitHub Pages with Python.md
=> 选题: 20190523 Run your blog on GitHub Pages with Python

sources/tech/20190527 4 open source mobile apps for Nextcloud.md
sources/tech/20190527 4 open source mobile apps for Nextcloud.md
=> 选题: 20190527 4 open source mobile apps for Nextcloud

sources/tech/20190520 Zettlr - Markdown Editor for Writers and Researchers.md
sources/tech/20190520 Zettlr - Markdown Editor for Writers and Researchers.md
=> 选题: 20190520 Zettlr – Markdown Editor for Writers and Researchers

sources/tech/20190521 How to Disable IPv6 on Ubuntu Linux.md
sources/tech/20190521 How to Disable IPv6 on Ubuntu Linux.md
=> 选题: 20190521 How to Disable IPv6 on Ubuntu Linux

sources/tech/20190525 4 Ways to Run Linux Commands in Windows.md
sources/tech/20190525 4 Ways to Run Linux Commands in Windows.md
=> 选题: 20190525 4 Ways to Run Linux Commands in Windows

sources/talk/20190529 Nvidia launches edge computing platform for AI processing.md
sources/talk/20190529 Nvidia launches edge computing platform for AI processing.md
=> 选题: 20190529 Nvidia launches edge computing platform for AI processing

sources/talk/20190528 Moving to the Cloud- SD-WAN Matters.md
sources/talk/20190528 Moving to the Cloud- SD-WAN Matters.md
=> 选题: 20190528 Moving to the Cloud? SD-WAN Matters!

sources/tech/20190527 A deeper dive into Linux permissions.md
sources/tech/20190527 A deeper dive into Linux permissions.md
=> 选题: 20190527 A deeper dive into Linux permissions

sources/talk/20190528 Managed WAN and the cloud-native SD-WAN.md
sources/talk/20190528 Managed WAN and the cloud-native SD-WAN.md
=> 选题: 20190528 Managed WAN and the cloud-native SD-WAN

sources/tech/20190529 NVMe on Linux.md
sources/tech/20190529 NVMe on Linux.md
=> 选题: 20190529 NVMe on Linux

sources/talk/20190529 Satellite-based internet possible by year-end, says SpaceX.md
sources/talk/20190529 Satellite-based internet possible by year-end, says SpaceX.md
=> 选题: 20190529 Satellite-based internet possible by year-end, says SpaceX

sources/tech/20190603 How to set up virtual environments for Python on MacOS.md
sources/tech/20190603 How to set up virtual environments for Python on MacOS.md
=> 选题: 20190603 How to set up virtual environments for Python on MacOS

sources/talk/20190603 It-s time for the IoT to -optimize for trust.md
sources/talk/20190603 It-s time for the IoT to -optimize for trust.md
=> 选题: 20190603 It’s time for the IoT to 'optimize for trust'

sources/tech/20190603 How to stream music with GNOME Internet Radio.md
sources/tech/20190603 How to stream music with GNOME Internet Radio.md
=> 选题: 20190603 How to stream music with GNOME Internet Radio

sources/tech/20190531 Why translation platforms matter.md
sources/tech/20190531 Why translation platforms matter.md
=> 选题: 20190531 Why translation platforms matter

published/20190520 Getting Started With Docker.md, translated/tech/20190520 Getting Started With Docker.md
@zhang5788 恭喜你完成了第一篇翻译，本文首发地址： https://linux.cn/article-10940-1.html
你的 LCTT 专页地址： https://linux.cn/lctt/zhang5788
请注册领取 LCCN： https://lctt.linux.cn/
=> PRF&PUB:20190520 Getting Started With Docker

sources/tech/20190531 Learn Python with these awesome resources.md
sources/tech/20190531 Learn Python with these awesome resources.md
=> 选题: 20190531 Learn Python with these awesome resources

sources/tech/20190530 A short primer on assemblers, compilers, and interpreters.md
sources/tech/20190530 A short primer on assemblers, compilers, and interpreters.md
=> 选题: 20190530 A short primer on assemblers, compilers, and interpreters

sources/tech/20190530 Creating a Source-to-Image build pipeline in OKD.md
sources/tech/20190530 Creating a Source-to-Image build pipeline in OKD.md
=> 选题: 20190530 Creating a Source-to-Image build pipeline in OKD

sources/tech/20190603 How many browser tabs do you usually have open.md
sources/tech/20190603 How many browser tabs do you usually have open.md
=> 选题: 20190603 How many browser tabs do you usually have open?

sources/tech/20190604 Create a CentOS homelab in an hour.md
sources/tech/20190604 Create a CentOS homelab in an hour.md
=> 选题: 20190604 Create a CentOS homelab in an hour

sources/tech/20190604 Aging in the open- How this community changed us.md
sources/tech/20190604 Aging in the open- How this community changed us.md
=> 选题: 20190604 Aging in the open: How this community changed us

sources/tech/20190528 A Quick Look at Elvish Shell.md
sources/tech/20190528 A Quick Look at Elvish Shell.md
=> 选题: 20190528 A Quick Look at Elvish Shell

sources/tech/20190531 Unity Editor is Now Officially Available for Linux.md
sources/tech/20190531 Unity Editor is Now Officially Available for Linux.md
=> 选题: 20190531 Unity Editor is Now Officially Available for Linux

sources/tech/20190531 Use Firefox Send with ffsend in Fedora.md
sources/tech/20190531 Use Firefox Send with ffsend in Fedora.md
=> 选题: 20190531 Use Firefox Send with ffsend in Fedora

sources/tech/20190529 Packit - packaging in Fedora with minimal effort.md
sources/tech/20190529 Packit - packaging in Fedora with minimal effort.md
=> 选题: 20190529 Packit – packaging in Fedora with minimal effort

sources/tech/20190604 How To Verify NTP Setup (Sync) is Working or Not In Linux.md
sources/tech/20190604 How To Verify NTP Setup (Sync) is Working or Not In Linux.md
=> 选题: 20190604 How To Verify NTP Setup (Sync) is Working or Not In Linux?

sources/tech/20190111 Top 5 Linux Distributions for Productivity.md
=> translating by qfzy1233

translated/tech/20190423 How to identify same-content files on Linux.md
Submit Translated passage for review
=> Submit Translated passage for review

published/20190410 How we built a Linux desktop app with Electron.md
@wxy https://linux.cn/article-10957-1.html
=> PRF&PUB:20190410 How we built a Linux desktop app with Electron

sources/tech/20190610 Graviton- A Minimalist Open Source Code Editor.md
sources/tech/20190610 Graviton- A Minimalist Open Source Code Editor.md
=> 选题: 20190610 Graviton: A Minimalist Open Source Code Editor

sources/tech/20190605 Tweaking the look of Fedora Workstation with themes.md
sources/tech/20190605 Tweaking the look of Fedora Workstation with themes.md
=> 选题: 20190605 Tweaking the look of Fedora Workstation with themes

sources/tech/20190610 Try a new game on Free RPG Day.md
sources/tech/20190610 Try a new game on Free RPG Day.md
=> 选题: 20190610 Try a new game on Free RPG Day

sources/tech/20190607 4 tools to help you drive Kubernetes.md
sources/tech/20190607 4 tools to help you drive Kubernetes.md
=> 选题: 20190607 4 tools to help you drive Kubernetes

sources/tech/20190606 Why hypothesis-driven development is key to DevOps.md
sources/tech/20190606 Why hypothesis-driven development is key to DevOps.md
=> 选题: 20190606 Why hypothesis-driven development is key to DevOps

sources/tech/20190607 5 reasons to use Kubernetes.md
sources/tech/20190607 5 reasons to use Kubernetes.md
=> 选题: 20190607 5 reasons to use Kubernetes

sources/tech/20190607 An Introduction to Kubernetes Secrets and ConfigMaps.md
sources/tech/20190607 An Introduction to Kubernetes Secrets and ConfigMaps.md
=> 选题: 20190607 An Introduction to Kubernetes Secrets and ConfigMaps

sources/tech/20190606 Kubernetes basics- Learn how to drive first.md
sources/tech/20190606 Kubernetes basics- Learn how to drive first.md
=> 选题: 20190606 Kubernetes basics: Learn how to drive first

sources/tech/20190606 Examples of blameless culture outside of DevOps.md
sources/tech/20190606 Examples of blameless culture outside of DevOps.md
=> 选题: 20190606 Examples of blameless culture outside of DevOps

sources/tech/20190606 How Linux can help with your spelling.md
sources/tech/20190606 How Linux can help with your spelling.md
=> 选题: 20190606 How Linux can help with your spelling

sources/talk/20190606 Juniper- Security could help drive interest in SDN.md
sources/talk/20190606 Juniper- Security could help drive interest in SDN.md
=> 选题: 20190606 Juniper: Security could help drive interest in SDN

sources/talk/20190606 For enterprise storage, persistent memory is here to stay.md
sources/talk/20190606 For enterprise storage, persistent memory is here to stay.md
=> 选题: 20190606 For enterprise storage, persistent memory is here to stay

sources/talk/20190606 Self-learning sensor chips won-t need networks.md
sources/talk/20190606 Self-learning sensor chips won-t need networks.md
=> 选题: 20190606 Self-learning sensor chips won’t need networks

sources/talk/20190604 5G will augment Wi-Fi, not replace it.md
sources/talk/20190604 5G will augment Wi-Fi, not replace it.md
=> 选题: 20190604 5G will augment Wi-Fi, not replace it

sources/talk/20190605 Cisco will use AI-ML to boost intent-based networking.md
sources/talk/20190605 Cisco will use AI-ML to boost intent-based networking.md
=> 选题: 20190605 Cisco will use AI/ML to boost intent-based networking

sources/talk/20190604 Moving to the Cloud- SD-WAN Matters- Part 2.md
sources/talk/20190604 Moving to the Cloud- SD-WAN Matters- Part 2.md
=> 选题: 20190604 Moving to the Cloud? SD-WAN Matters! Part 2

sources/talk/20190601 HPE Synergy For Dummies.md
sources/talk/20190601 HPE Synergy For Dummies.md
=> 选题: 20190601 HPE Synergy For Dummies

sources/tech/20190610 Welcoming Blockchain 3.0.md
sources/tech/20190610 Welcoming Blockchain 3.0.md
=> 选题: 20190610 Welcoming Blockchain 3.0

sources/tech/20190610 Tmux Command Examples To Manage Multiple Terminal Sessions.md
sources/tech/20190610 Tmux Command Examples To Manage Multiple Terminal Sessions.md
=> 选题: 20190610 Tmux Command Examples To Manage Multiple Terminal Sessions

sources/tech/20190610 Expand And Unexpand Commands Tutorial With Examples.md
sources/tech/20190610 Expand And Unexpand Commands Tutorial With Examples.md
=> 选题: 20190610 Expand And Unexpand Commands Tutorial With Examples

published/20190109 GoAccess - A Real-Time Web Server Log Analyzer And Interactive Viewer.md
@wxy https://linux.cn/article-10969-1.html
=> PRF&PUB:20190109 GoAccess   A Real Time Web Server Log Analyzer And Interactive Viewer

sources/tech/20190521 I don-t know how CPUs work so I simulated one in code.md
sources/tech/20190521 I don-t know how CPUs work so I simulated one in code.md
=> 选题: 20190521 I don't know how CPUs work so I simulated one in code

sources/tech/20190610 Applications for writing Markdown.md
sources/tech/20190610 Applications for writing Markdown.md
=> 选题: 20190610 Applications for writing Markdown

sources/tech/20190610 Welcoming Blockchain 3.0.md
【申请翻译】20190610 Welcoming Blockchain 3.0
Signed-off-by: MurphyZhao <d2014zjt@163.com>
=> 【申请翻译】20190610 Welcoming Blockchain 3.0

sources/tech/20190610 Applications for writing Markdown.md
【申请翻译】20190610 Applications for writing Markdown
Signed-off-by: MurphyZhao <d2014zjt@163.com>
=> 【申请翻译】20190610 Applications for writing Markdown

sources/tech/20190617 How To Find Linux System Details Using inxi.md
sources/tech/20190617 How To Find Linux System Details Using inxi.md
=> 选题: 20190617 How To Find Linux System Details Using inxi

sources/tech/20190610 Neofetch - Display Linux system Information In Terminal.md
sources/tech/20190610 Neofetch - Display Linux system Information In Terminal.md
=> 选题: 20190610 Neofetch – Display Linux system Information In Terminal

sources/tech/20190617 How To Check Linux Package Version Before Installing It.md
sources/tech/20190617 How To Check Linux Package Version Before Installing It.md
=> 选题: 20190617 How To Check Linux Package Version Before Installing It

sources/tech/20190614 How to send email from the Linux command line.md
sources/tech/20190614 How to send email from the Linux command line.md
=> 选题: 20190614 How to send email from the Linux command line

sources/tech/20190612 The bits and bytes of PKI.md
sources/tech/20190612 The bits and bytes of PKI.md
=> 选题: 20190612 The bits and bytes of PKI

sources/tech/20190612 How to write a loop in Bash.md
sources/tech/20190612 How to write a loop in Bash.md
=> 选题: 20190612 How to write a loop in Bash

sources/tech/20190611 What is a Linux user.md
sources/tech/20190611 What is a Linux user.md
=> 选题: 20190611 What is a Linux user?

sources/talk/20190614 Report- Mirai tries to hook its tentacles into SD-WAN.md
sources/talk/20190614 Report- Mirai tries to hook its tentacles into SD-WAN.md
=> 选题: 20190614 Report: Mirai tries to hook its tentacles into SD-WAN

sources/tech/20190612 Why use GraphQL.md
sources/tech/20190612 Why use GraphQL.md
=> 选题: 20190612 Why use GraphQL?

sources/tech/20190613 Continuous integration testing for the Linux kernel.md
sources/tech/20190613 Continuous integration testing for the Linux kernel.md
=> 选题: 20190613 Continuous integration testing for the Linux kernel

sources/tech/20190614 A data-centric approach to patching systems with Ansible.md
sources/tech/20190614 A data-centric approach to patching systems with Ansible.md
=> 选题: 20190614 A data-centric approach to patching systems with Ansible

sources/tech/20190614 Learning by teaching, and speaking, in open source.md
sources/tech/20190614 Learning by teaching, and speaking, in open source.md
=> 选题: 20190614 Learning by teaching, and speaking, in open source

sources/tech/20190614 What is a Java constructor.md
sources/tech/20190614 What is a Java constructor.md
=> 选题: 20190614 What is a Java constructor?

sources/talk/20190611 6 ways to make enterprise IoT cost effective.md
sources/talk/20190611 6 ways to make enterprise IoT cost effective.md
=> 选题: 20190611 6 ways to make enterprise IoT cost effective

sources/tech/20190613 Ubuntu Kylin- The Official Chinese Version of Ubuntu.md
sources/tech/20190613 Ubuntu Kylin- The Official Chinese Version of Ubuntu.md
=> 选题: 20190613 Ubuntu Kylin: The Official Chinese Version of Ubuntu

sources/talk/20190611 Cisco launches a developer-community cert program.md
sources/talk/20190611 Cisco launches a developer-community cert program.md
=> 选题: 20190611 Cisco launches a developer-community cert program

sources/talk/20190612 IoT security vs. privacy- Which is a bigger issue.md
sources/talk/20190612 IoT security vs. privacy- Which is a bigger issue.md
=> 选题: 20190612 IoT security vs. privacy: Which is a bigger issue?

sources/talk/20190612 Dell and Cisco extend VxBlock integration with new features.md
sources/talk/20190612 Dell and Cisco extend VxBlock integration with new features.md
=> 选题: 20190612 Dell and Cisco extend VxBlock integration with new features

sources/talk/20190613 Data centers should sell spare UPS capacity to the grid.md
sources/talk/20190613 Data centers should sell spare UPS capacity to the grid.md
=> 选题: 20190613 Data centers should sell spare UPS capacity to the grid

sources/talk/20190612 When to use 5G, when to use Wi-Fi 6.md
sources/talk/20190612 When to use 5G, when to use Wi-Fi 6.md
=> 选题: 20190612 When to use 5G, when to use Wi-Fi 6

sources/talk/20190612 Cisco offers cloud-based security for SD-WAN resources.md
sources/talk/20190612 Cisco offers cloud-based security for SD-WAN resources.md
=> 选题: 20190612 Cisco offers cloud-based security for SD-WAN resources

sources/tech/20190617 KIT Scenarist is a Powerful Tool for Creating Screenplays.md
sources/tech/20190617 KIT Scenarist is a Powerful Tool for Creating Screenplays.md
=> 选题: 20190617 KIT Scenarist is a Powerful Tool for Creating Screenplays

sources/tech/20190614 Personal assistant with Mycroft and Fedora.md
sources/tech/20190614 Personal assistant with Mycroft and Fedora.md
=> 选题: 20190614 Personal assistant with Mycroft and Fedora

sources/tech/20190612 Installing alternative versions of RPMs in Fedora.md
sources/tech/20190612 Installing alternative versions of RPMs in Fedora.md
=> 选题: 20190612 Installing alternative versions of RPMs in Fedora

sources/tech/20190617 Exploring -run on Linux.md
sources/tech/20190617 Exploring -run on Linux.md
=> 选题: 20190617 Exploring /run on Linux

sources/tech/20190618 Cylon - The Arch Linux Maintenance Program For Newbies.md
sources/tech/20190618 Cylon - The Arch Linux Maintenance Program For Newbies.md
=> 选题: 20190618 Cylon – The Arch Linux Maintenance Program For Newbies

sources/talk/20190617 5 transferable higher-education skills.md
sources/talk/20190617 5 transferable higher-education skills.md
=> 选题: 20190617 5 transferable higher-education skills

sources/talk/20190617 Use ImageGlass to quickly view JPG images as a slideshow.md
sources/talk/20190617 Use ImageGlass to quickly view JPG images as a slideshow.md
=> 选题: 20190617 Use ImageGlass to quickly view JPG images as a slideshow

sources/tech/20190611 How To Find Linux System Details Using inxi.md
sources/tech/20190611 How To Find Linux System Details Using inxi.md
=> 选题: 20190611 How To Find Linux System Details Using inxi

sources/tech/20190619 11 Free and Open Source Video Editing Software.md
sources/tech/20190619 11 Free and Open Source Video Editing Software.md
=> 选题: 20190619 11 Free and Open Source Video Editing Software

sources/tech/20190619 Get the latest Ansible 2.8 in Fedora.md
sources/tech/20190619 Get the latest Ansible 2.8 in Fedora.md
=> 选题: 20190619 Get the latest Ansible 2.8 in Fedora

sources/tech/20131228 Introduction to Clojure - Modern dialect of Lisp (Part 1).md
Reverts LCTT/TranslateProject#14099
=> Revert "超期回收: sources/tech/20131228 Introduction to Clojure - Modern dialect of Lisp (Part 1).md"

sources/tech/20190604 Kubernetes is a dump truck- Here-s why.md
sources/tech/20190604 Kubernetes is a dump truck- Here-s why.md
=> 选题: 20190604 Kubernetes is a dump truck: Here's why

sources/tech/20190605 How to navigate the Kubernetes learning curve.md
sources/tech/20190605 How to navigate the Kubernetes learning curve.md
=> 选题: 20190605 How to navigate the Kubernetes learning curve

sources/tech/20190619 Getting started with OpenSSL- Cryptography basics.md
sources/tech/20190619 Getting started with OpenSSL- Cryptography basics.md
=> 选题: 20190619 Getting started with OpenSSL: Cryptography basics

sources/tech/20190618 How to use MapTool to build an interactive dungeon RPG.md
sources/tech/20190618 How to use MapTool to build an interactive dungeon RPG.md
=> 选题: 20190618 How to use MapTool to build an interactive dungeon RPG

sources/tech/20190618 A beginner-s guide to Linux permissions.md
sources/tech/20190618 A beginner-s guide to Linux permissions.md
=> 选题: 20190618 A beginner's guide to Linux permissions

sources/talk/20190331 Codecademy vs. The BBC Micro.md
sources/talk/20190331 Codecademy vs. The BBC Micro.md
=> 选题: 20190331 Codecademy vs. The BBC Micro

published/20190628 FreeDOS turns 25 years old- An origin story.md
@wxy https://linux.cn/article-11033-1.html
=> PUB:20190628 FreeDOS turns 25 years old- An origin story.md

sources/tech/20180620 How To Find The Port Number Of A Service In Linux.md
sources/tech/20180620 How To Find The Port Number Of A Service In Linux.md
=> 选题: 20180620 How To Find The Port Number Of A Service In Linux

sources/tech/20190706 Say WHAAAT- Mozilla has Been Nominated for the -Internet Villain- Award in the UK.md
Reverts LCTT/TranslateProject#14463
=> Revert "APL:20190706 Say WHAAAT  Mozilla has Been Nominated for the  Internet Villain  Award in the UK"

sources/tech/20190518 Best Linux Distributions for Beginners.md
sources/tech/20190518 Best Linux Distributions for Beginners.md
=> 选题: 20190518 Best Linux Distributions for Beginners

sources/news/20190630 Donald Trump Now Wants to Ban End-to-End Encryption.md
sources/news/20190630 Donald Trump Now Wants to Ban End-to-End Encryption.md
@wxy 这个新闻有点老，但是感觉干系重大
=> 选题: 20190630 Donald Trump Now Wants to Ban End-to-End Encryption

sources/talk/20190705 Lessons in Vendor Lock-in- Google and Huawei.md
sources/talk/20190705 Lessons in Vendor Lock-in- Google and Huawei.md
@wxy  蹭个热度
=> 选题: 20190705 Lessons in Vendor Lock-in: Google and Huawei

sources/tech/20190706 How To Delete A Repository And GPG Key In Ubuntu.md
sources/tech/20190706 How To Delete A Repository And GPG Key In Ubuntu.md
=> 选题: 20190706 How To Delete A Repository And GPG Key In Ubuntu

sources/talk/20190604 Why Emacs.md
sources/talk/20190604 Why Emacs.md
=> 选题: 20190604 Why Emacs

sources/tech/20190518 Best Linux Distributions for Beginners.md
最近突然比较忙，预计一段时间都没有时间参与翻译了，这篇文章题材不错，就释放出来留给别人吧。。
=> 取消申领翻译：20190518 Best Linux Distributions for Beginners

sources/tech/20190710 How To Find Virtualbox Version From Commandline In Linux.md
sources/tech/20190710 How To Find Virtualbox Version From Commandline In Linux.md
=> 选题: 20190710 How To Find Virtualbox Version From Commandline In Linux

published/20190630 Donald Trump Now Wants to Ban End-to-End Encryption.md
@wxy https://linux.cn/article-11092-1.html
=> PUB:20190630 Donald Trump Now Wants to Ban End to End Encryption

sources/tech/20190710 Test 200- Linux And Unix Operating Systems Online For Free.md
=> APL: 20190710 Test 200- Linux And Unix Operating Systems Online For Free

sources/tech/20190708 10 ways to get started with Linux.md
=> TSL:20190708 10 ways to get started with Linux

sources/tech/20190718 What you need to know to be a sysadmin.md
申请翻译 20190718 What you need to know to be a sysadmin.md
=> 申请翻译 20190718 What you need to know to be a sysadmin.md

published/20190306 ClusterShell - A Nifty Tool To Run Commands On Cluster Nodes In Parallel.md
@wxy https://linux.cn/article-11147-1.html
=> PUB:20190306 ClusterShell - A Nifty Tool To Run Commands On Cluster Nodes In Parallel.md

sources/talk/20170320 An Ubuntu User-s Review Of Dell XPS 13 Ubuntu Edition.md
anonymone  is translating the paper, An Ubuntu User-s Review Of Dell XPS 13 Ubuntu Edition.md
=> anonymone apply to translate this paper.

translated/talk/20190730 Is This the End of Floppy Disk in Linux- Linus Torvalds Marks Floppy Disks ‘Orphaned.md
@wxy https://linux.cn/article-11167-1.html
=> PUB:20190730 Is This the End of Floppy Disk in Linux  Linus Torvalds Marks Floppy Disks ‘Orphaned

published/20190315 How To Parse And Pretty Print JSON With Linux Commandline Tools.md
@wxy https://linux.cn/article-11198-1.html
=> PUB:20190315 How To Parse And Pretty Print JSON With Linux Commandline Tools.md

published/20190801 Bash Script to Send a Mail When a New User Account is Created in System.md, translated/tech/20190801 Bash Script to Send a Mail When a New User Account is Created in System.md
@geekpi https://linux.cn/article-11199-1.html
=> PRF&PUB:20190801 Bash Script to Send a Mail When a New User Account is Created in System

published/20181222 How to detect automatically generated emails.md
@wxy https://linux.cn/article-11200-1.html
=> PUB:20181222 How to detect automatically generated emails

published/20190715 What is POSIX- Richard Stallman explains.md
=> PRF:20190715 What is POSIX- Richard Stallman explains.md

sources/talk/20180116 Command Line Heroes- Season 1- OS Wars.md
sources/talk/20180116 Command Line Heroes- Season 1- OS Wars.md
=> 选题: 20180116 Command Line Heroes: Season 1: OS Wars

sources/talk/20180720 A brief history of text-based games and open source.md
translating by cycoe & add lacking informations
=> translating by cycoe & add lacking informations
