LCTT/TranslateProject

published/20181029 Create animated, scalable vector graphic images with MacSVG.md
@wxy https://linux.cn/article-11239-1.html
=> PUB:20181029 Create animated, scalable vector graphic images with MacSVG.md

published/20190715 Understanding software design patterns.md
=> PRF:20190715 Understanding software design patterns

published/20190811 How to measure the health of an open source community.md
@wxy https://linux.cn/article-11244-1.html
=> PUB:20190811 How to measure the health of an open source community.md

sources/talk/20180116 Command Line Heroes- Season 1- OS Wars.md, sources/talk/20180116 Command Line Heroes- Season 1- OS Wars_2.md
sources/talk/20180116 Command Line Heroes- Season 1- OS Wars_2.md
=> 选题: 20180116 Command Line Heroes: Season 1: OS Wars(part2 Rise of Linux)

published/20181030 Podman- A more secure way to run containers.md
@wxy https://linux.cn/article-11261-1.html
=> PUB:20181030 Podman- A more secure way to run containers.md

published/20190825 Happy birthday to the Linux kernel- What-s your favorite release.md
@wxy https://linux.cn/article-11271-1.html
=> PUB:20190825 Happy birthday to the Linux kernel  What s your favorite release

published/20190827 A dozen ways to learn Python.md
@wxy https://linux.cn/article-11280-1.html
=> PUB:20190827 A dozen ways to learn Python

published/20190830 11 surprising ways you use Linux every day.md
@wxy https://linux.cn/article-11289-1.html
=> PUB:20190830 11 surprising ways you use Linux every day.md

sources/talk/20190825 Top 5 IoT networking security mistakes.md
=> Update 20190825 Top 5 IoT networking security mistakes.md

sources/tech/20181113 Eldoc Goes Global.md
sources/tech/20181113 Eldoc Goes Global.md
=> 选题: 20181113 Eldoc Goes Global

sources/tech/20190524 Spell Checking Comments.md
sources/tech/20190524 Spell Checking Comments.md
=> 选题: 20190524 Spell Checking Comments

sources/tech/20190404 How writers can get work done better with Git.md
sources/tech/20190404 How writers can get work done better with Git.md
=> 选题: 20190404 How writers can get work done better with Git

published/20190906 How to change the color of your Linux terminal.md
@wxy https://linux.cn/article-11324-1.html
=> PUB:20190906 How to change the color of your Linux terminal.md

published/20190914 GNOME 3.34 Released With New Features - Performance Improvements.md
@wxy https://linux.cn/article-11345-1.html
=> PUB:20190914 GNOME 3.34 Released With New Features   Performance Improvements

sources/tech/20190916 Linux commands to display your hardware information.md
=> Update 20190916 Linux commands to display your hardware information.md

published/20190826 Introduction to the Linux chown command.md
@wxy https://linux.cn/article-11416-1.html
=> PUB:20190826 Introduction to the Linux chown command

published/20180906 What a shell dotfile can do for you.md
@wxy https://linux.cn/article-11417-1.html
=> PUB:20180906 What a shell dotfile can do for you

sources/tech/20190301 Guide to Install VMware Tools on Linux.md
=> Request for Translate

translated/tech/20191010 Viewing files and processes as trees on Linux.md
20191010-viewing-files-and-processes-as-trees-on-linux translated, remove the AD.
=> 20191010-viewing-files-and-processes-as-trees-on-linux translated, remove AD

sources/tech/20191014 Use sshuttle to build a poor man-s VPN.md
Reverts LCTT/TranslateProject#15936
=> Revert "APL:20191014 Use sshuttle to build a poor man s VPN"

published/20190905 Building CI-CD pipelines with Jenkins.md
@wxy https://linux.cn/article-11546-1.html
=> PUB:20190905 Building CI-CD pipelines with Jenkins.md

sources/tech/20191113 Getting Started With ZFS Filesystem on Ubuntu 19.10.md
=> Update 20191113 Getting Started With ZFS Filesystem on Ubuntu 19.10.md

published/20190328 Can Better Task Stealing Make Linux Faster.md
@wxy https://linux.cn/article-11607-1.html
=> PUB:20190328 Can Better Task Stealing Make Linux Faster.md

published/20191120 How to install Java on Linux.md
@wxy https://linux.cn/article-11614-1.html
=> PUB:20191120 How to install Java on Linux

published/20191124 Bauh - Manage Snaps, Flatpaks and AppImages from One Interface.md
@wxy https://linux.cn/article-11617-1.html
=> PUB:20191124 Bauh - Manage Snaps, Flatpaks and AppImages from One Interface.md

sources/talk/20191031 A Bird-s Eye View of Big Data for Enterprises.md
=> Update 20191031 A Bird-s Eye View of Big Data for Enterprises.md

sources/tech/20191118 How internet security works- TLS, SSL, and CA.md
=> 补全How internet security works: TLS, SSL, and CA

published/20191210 3 easy steps to update your apps to Python 3.md, translated/tech/20191210 3 easy steps to update your apps to Python 3.md
@HankChow https://linux.cn/article-11696-1.html
=> PRF&PUB:20191210 3 easy steps to update your apps to Python 3

published/20191230 Fixing -VLC is Unable to Open the MRL- Error -Quick Tip.md, translated/tech/20191230 Fixing -VLC is Unable to Open the MRL- Error -Quick Tip.md
@geekpi https://linux.cn/article-11748-1.html
=> PRF&PUB:20191230 Fixing  VLC is Unable to Open the MRL  Error  Quick Tip

sources/tech/20171130 Excellent Business Software Alternatives For Linux.md
=> Update 20171130 Excellent Business Software Alternatives For Linux.md

sources/tech/20191226 10 Linux command tutorials for beginners and experts.md
=> Update 20191226 10 Linux command tutorials for beginners and experts.md

sources/tech/20180416 Cgo and Python.md
=> Update 20180416 Cgo and Python.md

published/20190405 File sharing with Git.md
@wxy https://linux.cn/article-11768-1.html
=> PRF&PUB:20190405 File sharing with Git

sources/tech/20190503 Mirror your System Drive using Software RAID.md
=> lixin555 is translating

published/20200122 Setting up passwordless Linux logins using public-private keys.md, translated/tech/20200122 Setting up passwordless Linux logins using public-private keys.md
@laingke
https://linux.cn/article-11830-1.html
=> PRF&PUB:20200122 Setting up passwordless Linux logins using public private keys

sources/tech/20200129 Showing memory usage in Linux by process and user.md
File name: 20200129 Showing memory usage in Linux by process and user.md
Translator: mengxinayan
=> Translating (mengxinayan)

published/20200126 What-s your favorite Linux distribution.md
@LazyWolfLin
https://linux.cn/article-11867-1.html
=> PRF&PUB:20200126 What s your favorite Linux distribution

sources/tech/20190407 Manage multimedia files with Git.md
翻译Update 20190407 Manage multimedia files with Git.md
=> Update 20190407 Manage multimedia files with Git.md

sources/tech/20170918 Fun and Games in Emacs.md
sources/tech/20170918 Fun and Games in Emacs.md
=> 选题: 20170918 Fun and Games in Emacs

sources/tech/20190114 Some Advice for How to Make Emacs Tetris Harder.md
sources/tech/20190114 Some Advice for How to Make Emacs Tetris Harder.md
=> 选题: 20190114 Some Advice for How to Make Emacs Tetris Harder

translated/tech/20200214 Digging up IP addresses with the Linux dig command.md
翻译完成 20200214 Digging up IP addresses with the Linux dig command.md
=> hankchow translated

sources/tech/20190422 9 ways to save the planet.md
=> Update 20190422 9 ways to save the planet.md

sources/tech/20180306 Exploring free and open web fonts.md
=> Update 20180306 Exploring free and open web fonts.md

published/20200304 Drauger OS Linux Aims to Bring Console Gaming Experience on the Desktop.md, translated/tech/20200304 Drauger OS Linux Aims to Bring Console Gaming Experience on the Desktop.md
@wxy
https://linux.cn/article-11972-1.html
=> PRF&PUB:20200304 drauger os linux aims to bring console gaming experience on the desktop

published/20200305 Install and Use Wireshark on Ubuntu Linux.md, translated/tech/20200305 Install and Use Wireshark on Ubuntu Linux.md
@qianmingtian
https://linux.cn/article-11987-1.html
=> PRF&PUB:20200305 Install and Use Wireshark on Ubuntu Linux

sources/tech/20190116 Best Audio Editors For Linux.md
=> Update 20190116 Best Audio Editors For Linux.md

sources/tech/20200310 Run Kubernetes on a Raspberry Pi with k3s.md
sources/tech/20200310 Run Kubernetes on a Raspberry Pi with k3s.md
=> 选题: 20200310 Run Kubernetes on a Raspberry Pi with k3s

sources/talk/20191031 A Bird-s Eye View of Big Data for Enterprises.md
=> 超期回收: sources/talk/20191031 A Bird-s Eye View of Big Data for Enterprises.md

sources/tech/20190730 Using Python to explore Google-s Natural Language API.md
@zhangxiangping 申请翻译文章33天，因超时而撤销.
=> 超期回收: sources/tech/20190730 Using Python to explore Google-s Natural Language API.md

published/20200313 How to Change MAC Address in Linux.md, translated/tech/20200313 How to Change MAC Address in Linux.md
@geekpi
https://linux.cn/article-12008-1.html
=> PRF&PUB:20200313 how to change mac address in linux

sources/tech/20200319 4 Markdown tools for the Linux command line.md
Reverts LCTT/TranslateProject#17847
=> Revert "APL:20200319 4 Markdown tools for the Linux command line"

published/20200310 Run Kubernetes on a Raspberry Pi with k3s.md
@HankChow
https://linux.cn/article-12049-1.html
=> PRF&PUB:20200310 Run Kubernetes on a Raspberry Pi with k3s.md

sources/tech/20190702 One CI-CD pipeline per product to rule them all.md
=> 超期回收: sources/tech/20190702 One CI-CD pipeline per product to rule them all.md

sources/talk/20190429 10 moments that shaped Linux history.md
sources/talk/20190429 10 moments that shaped Linux history.md
=> 选题: 20190429 10 moments that shaped Linux history

sources/tech/20190605 What is GraphQL.md
sources/tech/20190605 What is GraphQL.md
=> 选题: 20190605 What is GraphQL?

published/20190429 10 moments that shaped Linux history.md
@wxy
https://linux.cn/article-12060-1.html
=> PUB:20190429 10 moments that shaped Linux history

published/20200401 IEEE Standards Association Launches an Open Source Collaboration Platform.md
@wxy
https://linux.cn/article-12096-1.html
=> PUB:20200401 IEEE Standards Association Launches an Open Source Collaboration Platform.md

sources/talk/20200306 How I learned about burnout the hard way.md
@Xuzhou Zheng 申请翻译文章30天，因超时而撤销.
=> 超期回收: sources/talk/20200306 How I learned about burnout the hard way.md

sources/tech/20200417 12 Linux Commands to Have Some Fun in the Terminal.md
=> Update 20200417 12 Linux Commands to Have Some Fun in the Terminal.md

sources/tech/20200415 Writing Java with Quarkus in VS Code.md
Reverts LCTT/TranslateProject#18173
=> Revert "APL:20200415 writing java with quarkus in vs code"

sources/tech/20200424 16 Things to do After Installing Ubuntu 20.04.md
Reverts LCTT/TranslateProject#18258
=> Revert "申领原文"

sources/tech/20200427 How to secure your Linux email services with SSL-TLS.md
=> Update 20200427 How to secure your Linux email services with SSL-TLS.md

sources/tech/20200428 Open source has room for everyone.md
=> Update 20200428 Open source has room for everyone.md

sources/tech/20200407 How to use pyenv to run multiple versions of Python on a Mac.md
=> 超期回收: sources/tech/20200407 How to use pyenv to run multiple versions of Python on a Mac.md

sources/tech/20200410 Get started with Bash programming.md
=> 超期回收: sources/tech/20200410 Get started with Bash programming.md

sources/tech/20200408 My Linux Story- From 8-bit enthusiast to Unix sysadmin.md
=> 超期回收: sources/tech/20200408 My Linux Story- From 8-bit enthusiast to Unix sysadmin.md

translated/tech/20190510 Learn to change history with git rebase.md
=> TSL:20190510 Learn to change history with git rebase

sources/tech/20180710 Building a Messenger App- Messages.md
=> 超期回收: sources/tech/20180710 Building a Messenger App- Messages.md

published/20200525 How to Properly Install and Setup KDE Plasma on Arch Linux.md
@wxy
https://linux.cn/article-12258-1.html
=> PUB:20200525 How to Properly Install and Setup KDE Plasma on Arch Linux

published/20200525 How to Manipulate an Ethernet Card Using the ethtool Command.md
@wxy
https://linux.cn/article-12290-1.html
=> PRF&PUB:20200525 How to Manipulate an Ethernet Card Using the ethtool Command

sources/tech/20200410 How Kubernetes saved my desktop application.md
=> 超期回收: sources/tech/20200410 How Kubernetes saved my desktop application.md

published/20200525 Linux Mint 20- Release Date, Features and Everything Important Associated With it.md
@wxy
https://linux.cn/article-12297-1.html
=> PUB:20200525 Linux Mint 20- Release Date, Features and Everything Important Associated With it.md

sources/talk/20200519 24 Linux desktops you need to try.md
sources/talk/20200519 24 Linux desktops you need to try.md
=> 选题: 20200519 24 Linux desktops you need to try

published/20200604 How to Install Nvidia Drivers on Fedora Linux.md, translated/tech/20200604 How to Install Nvidia Drivers on Fedora Linux.md
@geekpi
https://linux.cn/article-12301-1.html
=> PRF&PUB:20200604 how to install nvidia drivers on fedora linux

sources/talk/20200514 What is IoT- The internet of things explained.md
Application for translating talk article "What is IoT? The internet of things explained".
Please merge, thanks.
=> Application for translating talk article "What is IoT? The internet of things explained".

sources/talk/20200514 How IoT will rescue aviation.md
Application for translating the talk article "How IoT will rescue aviation"
=> Application for translating the talk article "How IoT will rescue aviation"

sources/tech/20200624 Customize your Raspberry Pi operating system for everyday use.md
Application for translating the tech article "Customize your Raspberry Pi operating system for everyday use."
=> Application for translating the tech article "Customize your Raspberry Pi operating system for everyday use."

sources/tech/20200627 Learn Shell Scripting for Free With These Resources -PDF, Video Courses and Interactive Websites.md
Application for translating the tech article "Learn Shell Scripting for Free With These Resources [PDF, Video Courses and Interactive Websites]"
=> Application for translating the tech article "Learn Shell Scripting for Free With These Resources [PDF, Video Courses and Interactive Websites]"

sources/tech/20200628 How to crop images in GIMP -Quick Tip.md
sources/tech/20200628 How to crop images in GIMP -Quick Tip.md
=> 选题[tech]: 20200628 How to crop images in GIMP [Quick Tip]

sources/tech/20200627 An open source browser extension to zoom in on images.md
sources/tech/20200627 An open source browser extension to zoom in on images.md
=> 选题[tech]: 20200627 An open source browser extension to zoom in on images

published/20200621 How to Make Ubuntu Look Like macOS in 5 Easy Steps.md, translated/tech/20200621 How to Make Ubuntu Look Like macOS in 5 Easy Steps.md
@robsean
https://linux.cn/article-12361-1.html
=> PRF&PUB:20200621 How to Make Ubuntu Look Like macOS in 5 Easy Steps

sources/tech/20200615 LaTeX Typesetting - Part 1 (Lists).md
sources/tech/20200615 LaTeX Typesetting - Part 1 (Lists).md
=> 选题[tech]: 20200615 LaTeX Typesetting – Part 1 (Lists)

sources/tech/20200525 How Cloud-init can be used for your Raspberry Pi homelab.md
sources/tech/20200525 How Cloud-init can be used for your Raspberry Pi homelab.md
=> 选题: 20200525 How Cloud-init can be used for your Raspberry Pi homelab

sources/tech/20200701 How to install Java on a Mac.md
Application for translating the tech article "How to install Java on a Mac"
=> Application for translating the tech article "How to install Java on a Mac"

sources/tech/20180730 50 Best Ubuntu Apps You Should Be Using Right Now.md
=> 超期回收: sources/tech/20180730 50 Best Ubuntu Apps You Should Be Using Right Now.md

sources/talk/20190222 Developer happiness- What you need to know.md
=> Update 20190222 Developer happiness- What you need to know.md

sources/tech/20200707 What you need to know about hash functions.md
Application for translating the tech article "What you need to know about hash functions"
=> Application for translating the tech article "What you need to know about hash functions"

sources/talk/20200708 How wireless networks can battle COVID-19.md
=> Update 20200708 How wireless networks can battle COVID-19.md

sources/talk/20200706 Project OWL- IoT trying to hold connectivity together in disasters.md
Application for translating the talk article "Project OWL: IoT trying to hold connectivity together in disasters"
=> Application for translating the talk article "Project OWL: IoT trying to hold connectivity together in disasters"

sources/talk/20200713 My Linux story- From Linux user to contributor.md
Application for translating the talk article "My Linux story: From Linux user to contributor"
=> Application for translating the talk article "My Linux story: From Linux user to contributor"

sources/talk/20200324 COVID-19- Weekly health check of ISPs, cloud providers and conferencing services.md
=> 超期回收: sources/talk/20200324 COVID-19- Weekly health check of ISPs, cloud providers and conferencing services.md

sources/tech/20200715 What-s the difference between DevSecOps and agile software development.md
=> translating by windgeek

sources/tech/20190213 How to build a WiFi picture frame with a Raspberry Pi.md
=> Update 20190213 How to build a WiFi picture frame with a Raspberry Pi.md

sources/tech/20200528 4 Linux distributions for gaming.md
=> translating by Sky0Master

sources/talk/20190225 Teaching scientists how to share code.md
=> Update 20190225 Teaching scientists how to share code.md

sources/tech/20200715 An example of very lightweight RESTful web services in Java.md
Application for translating the tech article "An example of very lightweight RESTful web services in Java"
=> Application for translating the tech article "An example of very lightweight RESTful web services in Java"

sources/tech/20190204 Getting started with Git- Terminology 101.md
sources/tech/20190204 Getting started with Git- Terminology 101.md
=> 选题[tech]: 20190204 Getting started with Git: Terminology 101

published/20200730 Defining cloud native, expanding the ecosystem, and more industry trends.md
@wxy
https://linux.cn/article-12473-1.html
=> PUB:20200730 Defining cloud native, expanding the ecosystem, and more industry trends

sources/tech/20190212 Top 10 Best Linux Media Server Software.md
认领 20190212 Top 10 Best Linux Media Server Software
=> Update 20190212 Top 10 Best Linux Media Server Software.md

published/20200730 10 cheat sheets for Linux sysadmins.md
@geekpi
https://linux.cn/article-12490-1.html
=> PRF&PUB:20200730 10 cheat sheets for Linux sysadmins

sources/talk/20160921 lawyer The MIT License, Line by Line.md
At my very beginning! Try my best to translate the article.
申领原文
=> Update 20160921 lawyer The MIT License, Line by Line.md

sources/tech/20200721 Manage network connections from the Linux command line with nmcli.md
=> [Translating] 20200721 Manage network connections from the Linux command line with nmcli.md

sources/talk/20200401 How enterprise networking is changing with a work-at-home workforce.md
=> 超期回收: sources/talk/20200401 How enterprise networking is changing with a work-at-home workforce.md

published/20200715 An example of very lightweight RESTful web services in Java.md, translated/tech/20200715 An example of very lightweight RESTful web services in Java.md
@wxy
https://linux.cn/article-12555-1.html
=> PRF&PUB:20200715 an example of very lightweight res tful web services in java

sources/talk/20200826 What is IPv6, and why aren-t we there yet.md
sources/talk/20200826 What is IPv6, and why aren-t we there yet.md
=> 选题[talk]: 20200826 What is IPv6, and why aren’t we there yet?

sources/talk/20200826 What is DNS and how does it work.md
sources/talk/20200826 What is DNS and how does it work.md
=> 选题[talk]: 20200826 What is DNS and how does it work?

sources/tech/20200826 Customize your GNOME desktop theme.md
sources/tech/20200826 Customize your GNOME desktop theme.md
=> 选题[tech]: 20200826 Customize your GNOME desktop theme

sources/tech/20200826 Create and run Python apps on your Android phone.md
sources/tech/20200826 Create and run Python apps on your Android phone.md
=> 选题[tech]: 20200826 Create and run Python apps on your Android phone

published/20200825 11 ways to list and sort files on Linux.md
@wxy
https://linux.cn/article-12560-1.html
=> PUB:20200825 11 ways to list and sort files on Linux

sources/tech/20200829 5 open source activities for kids to try this weekend.md
sources/tech/20200829 5 open source activities for kids to try this weekend.md
=> 选题[tech]: 20200829 5 open source activities for kids to try this weekend

published/20200826 Glances - A Versatile System Monitoring Tool for Linux Systems.md
@wxy
https://linux.cn/article-12567-1.html
=> PUB:20200826 Glances   A Versatile System Monitoring Tool for Linux Systems

published/20200728 How to create a documentation site with Docsify and GitHub Pages.md
@wxy
https://linux.cn/article-12572-1.html
=> PUB:20200728 How to create a documentation site with Docsify and GitHub Pages.md

published/20200415 Tweaking history on Linux.md
@wxy
https://linux.cn/article-12596-1.html
=> PUB:20200415 Tweaking history on Linux.md

sources/tech/20190325 Reducing sysadmin toil with Kubernetes controllers.md
=> 超期回收: sources/tech/20190325 Reducing sysadmin toil with Kubernetes controllers.md

sources/talk/20160921 lawyer The MIT License, Line by Line.md
@hongcha8385 申请翻译文章30天，因超时而撤销.
=> 超期回收: sources/talk/20160921 lawyer The MIT License, Line by Line.md

published/20200907 Linux Jargon Buster- What is a Linux Distribution- Why is it Called a ‘Distribution.md
@wxy
https://linux.cn/article-12609-1.html
=> PUB:20200907 Linux Jargon Buster- What is a Linux Distribution- Why is it Called a ‘Distribution.md

published/20200914 Linux Jargon Buster- What is a Long Term Support (LTS) Release- What is Ubuntu LTS.md
@wxy
https://linux.cn/article-12618-1.html
=> PUB:20200914 Linux Jargon Buster  What is a Long Term Support (LTS) Release  What is Ubuntu LTS

sources/talk/20191009 Why to choose Rust as your next programming language.md
Request https://github.com/LCTT/TranslateProject/blob/master/sources/talk/20191009%20Why%20to%20choose%20Rust%20as%20your%20next%20programming%20language.md
=> Translating by matrixkoo

published/20200916 Teach Python with Jupyter Notebooks.md
@wxy
https://linux.cn/article-12646-1.html
=> PUB:20200916 Teach Python with Jupyter Notebooks

sources/tech/20200923 Find security issues in Go code using gosec.md
sources/tech/20200923 Find security issues in Go code using gosec.md
=> 选题[tech]: 20200923 Find security issues in Go code using gosec

sources/tech/20200921 Installing and running Vagrant using qemu-kvm.md
sources/tech/20200921 Installing and running Vagrant using qemu-kvm.md
=> 选题[tech]: 20200921 Installing and running Vagrant using qemu-kvm

published/20200923 Meet eDEX-UI, A Sci-Fi Inspired Linux Terminal Emulator With Some Cool Features.md
@wxy
https://linux.cn/article-12655-1.html?wx
=> PUB:20200923 Meet eDEX UI, A Sci Fi Inspired Linux Terminal Emulator With Some Cool Features

published/20200907 Program hardware from the Linux command line.md
@wxy
https://linux.cn/article-12667-1.html
=> PUB:20200907 Program hardware from the Linux command line

sources/tech/20200512 Scan your Linux security with Lynis.md
sources/tech/20200512 Scan your Linux security with Lynis.md
=> 选题[tech]: 20200512 Scan your Linux security with Lynis

sources/tech/20180503 Go on very small hardware (Part 3).md
sources/tech/20180503 Go on very small hardware (Part 3).md
=> 选题[tech]: 20180503 Go on very small hardware (Part 3)

sources/talk/20191009 Why to choose Rust as your next programming language.md
=> 超期回收: sources/talk/20191009 Why to choose Rust as your next programming language.md

sources/tech/20200918 Add throwing mechanics to your Python game.md
sources/tech/20200918 Add throwing mechanics to your Python game.md
=> 选题[tech]: 20200918 Add throwing mechanics to your Python game

sources/talk/20191009 Why to choose Rust as your next programming language.md
Reverts LCTT/TranslateProject#19889
=> Revert "超期回收: sources/talk/20191009 Why to choose Rust as your next programming language.md"

translated/tech/20200928 Add sound to your Python game.md
=> PRF:20200928 Add sound to your Python game

sources/tech/20201116 Unlock encrypted disks on Linux automatically.md
sources/tech/20201116 Unlock encrypted disks on Linux automatically.md
=> 选题[tech]: 20201116 Unlock encrypted disks on Linux automatically

sources/tech/20201114 Woothee (HTTP User Agent Parser).md
sources/tech/20201114 Woothee (HTTP User Agent Parser).md
=> 选题[tech]: 20201114 Woothee (HTTP User Agent Parser)

sources/tech/20200907 A beginner-s guide to SSH for remote connection on Linux.md
This reverts commit d99abfa2237b520b0155d928cad7cd78b7f389b9.
=> Revert "update translator"

sources/tech/20201116 Podman with capabilities on Fedora.md
sources/tech/20201116 Podman with capabilities on Fedora.md
=> 选题[tech]: 20201116 Podman with capabilities on Fedora

sources/tech/20201116 Manage multiple Terraform versions with tfenv.md
sources/tech/20201116 Manage multiple Terraform versions with tfenv.md
=> 选题[tech]: 20201116 Manage multiple Terraform versions with tfenv

sources/tech/20201119 Day 9- Generating a lot of nonsense with an RNN.md
sources/tech/20201119 Day 9- Generating a lot of nonsense with an RNN.md
=> 选题[tech]: 20201119 Day 9: Generating a lot of nonsense with an RNN

sources/tech/20201118 LazPaint- A Free - Open Source Paint.NET Alternative.md
sources/tech/20201118 LazPaint- A Free - Open Source Paint.NET Alternative.md
=> 选题[tech]: 20201118 LazPaint: A Free & Open Source Paint.NET Alternative

sources/tech/20201117 How to upgrade to Terraform 0.12.md
sources/tech/20201117 How to upgrade to Terraform 0.12.md
=> 选题[tech]: 20201117 How to upgrade to Terraform 0.12

sources/tech/20201117 Getting started with btrfs for Linux.md
sources/tech/20201117 Getting started with btrfs for Linux.md
=> 选题[tech]: 20201117 Getting started with btrfs for Linux

sources/tech/20201117 My top 7 Rust commands for using Cargo.md
sources/tech/20201117 My top 7 Rust commands for using Cargo.md
=> 选题[tech]: 20201117 My top 7 Rust commands for using Cargo

sources/tech/20201116 Day 5- drawing lots of faces with sketch-rnn.md
sources/tech/20201116 Day 5- drawing lots of faces with sketch-rnn.md
=> 选题[tech]: 20201116 Day 5: drawing lots of faces with sketch-rnn

sources/tech/20201118 Secure your containers with SELinux.md
sources/tech/20201118 Secure your containers with SELinux.md
=> 选题[tech]: 20201118 Secure your containers with SELinux

sources/tech/20201118 Apply the Scientific Method to agile development.md
sources/tech/20201118 Apply the Scientific Method to agile development.md
=> 选题[tech]: 20201118 Apply the Scientific Method to agile development

sources/tech/20201119 Automate your tasks with this Ansible cheat sheet.md
sources/tech/20201119 Automate your tasks with this Ansible cheat sheet.md
=> 选题[tech]: 20201119 Automate your tasks with this Ansible cheat sheet

sources/tech/20201119 The relationship between labor and open source.md
sources/tech/20201119 The relationship between labor and open source.md
=> 选题[tech]: 20201119 The relationship between labor and open source

sources/tech/20201118 Day 8- Start with something that works.md
sources/tech/20201118 Day 8- Start with something that works.md
=> 选题[tech]: 20201118 Day 8: Start with something that works

sources/tech/20201120 How we develop success metrics for open source events.md
sources/tech/20201120 How we develop success metrics for open source events.md
=> 选题[tech]: 20201120 How we develop success metrics for open source events

sources/tech/20201120 What do open source product teams do.md
sources/tech/20201120 What do open source product teams do.md
=> 选题[tech]: 20201120 What do open source product teams do?

sources/tech/20201121 Open source brings musicians together virtually.md
sources/tech/20201121 Open source brings musicians together virtually.md
=> 选题[tech]: 20201121 Open source brings musicians together virtually

sources/tech/20201120 Day 10- Training an RNN to count to three.md
sources/tech/20201120 Day 10- Training an RNN to count to three.md
=> 选题[tech]: 20201120 Day 10: Training an RNN to count to three

sources/tech/20201123 6 predictions for JavaScript build tools.md
sources/tech/20201123 6 predictions for JavaScript build tools.md
=> 选题[tech]: 20201123 6 predictions for JavaScript build tools

sources/tech/20201123 A beginner-s guide to Kubernetes Jobs and CronJobs.md
sources/tech/20201123 A beginner-s guide to Kubernetes Jobs and CronJobs.md
=> 选题[tech]: 20201123 A beginner's guide to Kubernetes Jobs and CronJobs

sources/tech/20201110 Day 2- Rails associations - dragging divs around.md
sources/tech/20201110 Day 2- Rails associations - dragging divs around.md
=> 选题[tech]: 20201110 Day 2: Rails associations & dragging divs around

sources/tech/20201123 Day 11- learning about learning rates.md
sources/tech/20201123 Day 11- learning about learning rates.md
=> 选题[tech]: 20201123 Day 11: learning about learning rates

sources/tech/20201111 Day 3- an infinitely tall fridge.md
sources/tech/20201111 Day 3- an infinitely tall fridge.md
=> 选题[tech]: 20201111 Day 3: an infinitely tall fridge

sources/tech/20200711 scanimage- scan from the command line.md
sources/tech/20200711 scanimage- scan from the command line.md
=> 选题[tech]: 20200711 scanimage: scan from the command line!

sources/tech/20200619 A little bit of plain Javascript can do a lot.md
sources/tech/20200619 A little bit of plain Javascript can do a lot.md
=> 选题[tech]: 20200619 A little bit of plain Javascript can do a lot

sources/tech/20200617 What happens when you update your DNS.md
sources/tech/20200617 What happens when you update your DNS.md
=> 选题[tech]: 20200617 What happens when you update your DNS?

sources/tech/20200508 Metaphors in man pages.md
sources/tech/20200508 Metaphors in man pages.md
=> 选题[tech]: 20200508 Metaphors in man pages

sources/tech/20201030 How to rebase to Fedora 33 on Silverblue.md
sources/tech/20201030 How to rebase to Fedora 33 on Silverblue.md
=> 选题[tech]: 20201030 How to rebase to Fedora 33 on Silverblue

published/20200804 Use your favorite programming language to provision Infrastructure as Code.md
@wxy
https://linux.cn/article-12862-1.html
=> PUB:20200804 Use your favorite programming language to provision Infrastructure as Code

published/20201030 How to rebase to Fedora 33 on Silverblue.md
@geekpi
https://linux.cn/article-12880-1.html
=> PRF&PUB:20201030 How to rebase to Fedora 33 on Silverblue.md

published/20201109 Day 1- a confusing Rails error message.md
@wxy
https://linux.cn/article-12884-1.html
=> PUB:20201109 Day 1  a confusing Rails error message

sources/tech/20201012 Build a Kubernetes Minecraft server with Ansible-s Helm modules.md
=> 超期回收: sources/tech/20201012 Build a Kubernetes Minecraft server with Ansible-s Helm modules.md

sources/tech/20201026 7 Git tricks that changed my life.md
sources/tech/20201026 7 Git tricks that changed my life.md
=> 选题[tech]: 20201026 7 Git tricks that changed my life

published/20201130 Journal five minutes a day with Jupyter.md
@wxy
https://linux.cn/article-12887-1.html
=> PUB:20201130 Journal five minutes a day with Jupyter.md

published/20201203 Download the 2020 Linux Foundation Annual Report.md
@wxy
https://linux.cn/article-12889-1.html
=> PUB:20201203 Download the 2020 Linux Foundation Annual Report

published/20201110 Day 2- Rails associations - dragging divs around.md
@wxy
https://linux.cn/article-12890-1.html
=> PUB:20201110 Day 2- Rails associations - dragging divs around.md

sources/tech/20200421 How I use Python to map the global spread of COVID-19.md
Added info to 
20200421 How I use Python to map the global spread of COVID-19.
=> Added translator info

published/20201203 Get the most out of the Vi text editor.md
@wxy
https://linux.cn/article-12947-1.html
=> PUB:20201203 Get the most out of the Vi text editor

published/20201208 Learn Bash by writing an interactive game.md
@wxy
https://linux.cn/article-12962-1.html
=> PRF&PUB:20201208 Learn Bash by writing an interactive game

published/20201214 Set up an Ansible lab in 20 minutes.md
@wxy
https://linux.cn/article-12970-1.html
=> PRF&PUB:20201214 Set up an Ansible lab in 20 minutes

published/20201229 Bring an old MacBook back to life with Linux.md
@wxy
https://linux.cn/article-12976-1.html?wx
=> PUB:20201229 Bring an old MacBook back to life with Linux.md

published/20201226 Try GNU nano, a lightweight alternative to Vim.md
@wxy
https://linux.cn/article-12982-1.html
=> PRF&PUB:20201226 Try GNU nano, a lightweight alternative to Vim

published/20201222 Learn to use the Sed text editor.md
@wxy
https://linux.cn/article-12992-1.html
=> PUB:20201222 Learn to use the Sed text editor

published/20190204 Getting started with Git- Terminology 101.md
@wxy
https://linux.cn/article-12994-1.html
=> PUB:20190204 Getting started with Git  Terminology 101

published/20210107 8 open source software cheat sheets you-ll need in 2021.md
@wxy
https://linux.cn/article-12996-1.html
=> PUB:20210107 8 open source software cheat sheets you ll need in 2021

sources/talk/20191010 The biggest risk to uptime- Your staff.md
增加translator github ID “sthwhl”， 申领原文
=> translating by sthwhl

sources/tech/20201013 My first day using Ansible.md
=> 超期回收: sources/tech/20201013 My first day using Ansible.md

sources/tech/20191224 Top articles for learning Python in 2020.md
=> Update 20191224 Top articles for learning Python in 2020.md

sources/tech/20191227 The importance of consistency in your Python code.md
=> Update 20191227 The importance of consistency in your Python code.md

sources/tech/20190205 5 Streaming Audio Players for Linux.md
=> Update 20190205 5 Streaming Audio Players for Linux.md

sources/tech/20201015 Learn Python by creating a video game.md
=> Translating 20201015 Learn Python by creating a video game

sources/tech/20200522 A beginner-s guide to web scraping with Python.md
=> Translate 20200522 A beginner-s guide to web scraping with Python

published/20210108 Why I like the FED text editor.md, translated/tech/20210108 Why I like the FED text editor.md
@geekpi
https://linux.cn/article-13019-1.html
=> PRF&PUB:20210108 why i like the fed text editor

sources/talk/20190312 When the web grew up- A browser story.md
=> XYenChi is translating

published/20210112 3 email rules to live by in 2021.md
@wxy
https://linux.cn/article-13044-1.html
=> PUB:published/20210112 3 email rules to live by in 2021.md

sources/tech/20191228 The Zen of Python- Why timing is everything.md
sources/tech/20191228 The Zen of Python- Why timing is everything.md
=> 选题[tech]: 20191228 The Zen of Python: Why timing is everything

published/20210112 Super Productivity- A Super Cool Open Source To-Do List App with GitHub Integration.md
@wxy
https://linux.cn/article-13067-1.html
=> PUB:published/20210112 Super Productivity- A Super Cool Open Source To-Do List App with GitHub Integration.md

sources/tech/20200615 LaTeX Typesetting - Part 1 (Lists).md
=> 超期回收: sources/tech/20200615 LaTeX Typesetting - Part 1 (Lists).md

published/20191228 The Zen of Python- Why timing is everything.md
@wxy
https://linux.cn/article-13103-1.html
=> PUB:published/20191228 The Zen of Python- Why timing is everything.md

published/20190610 Tmux Command Examples To Manage Multiple Terminal Sessions.md, translated/tech/20190610 Tmux Command Examples To Manage Multiple Terminal Sessions.md
@chensanle
感谢你，完成了第一篇翻译贡献！
本文首发：https://linux.cn/article-13107-1.html
你的 LCTT 专页：https://linux.cn/lctt/chensanle
=> PRF&PUB:20190610 tmux command examples to manage multiple terminal sessions

published/20191230 Namespaces are the shamash candle of the Zen of Python.md, translated/tech/20191230 Namespaces are the shamash candle of the Zen of Python.md
@wxy
https://linux.cn/article-13123-1.html
=> PUB:20191230 namespaces are the shamash candle of the zen of python

sources/talk/20190313 Why is no one signing their emails.md
=> 超期回收: sources/talk/20190313 Why is no one signing their emails.md

sources/tech/20171025 Typeset your docs with LaTeX and TeXstudio on Fedora.md
sources/tech/20171025 Typeset your docs with LaTeX and TeXstudio on Fedora.md
=> 选题: 20171025 Typeset your docs with LaTeX and TeXstudio on Fedora

published/20201001 Navigating your Linux files with ranger.md
@wxy
https://linux.cn/article-13137-1.html
=> PUB:published/20201001 Navigating your Linux files with ranger.md

published/20210209 Viper Browser- A Lightweight Qt5-based Web Browser With A Focus on Privacy and Minimalism.md
@geekpi
https://linux.cn/article-13139-1.html
=> PUB:published/20210209 Viper Browser- A Lightweight Qt5-based Web Browser With A Focus on Privacy and Minimalism.md

published/20210215 A practical guide to JavaScript closures.md
@wxy
https://linux.cn/article-13140-1.html
=> PRF&PUB:published/20210215 A practical guide to JavaScript closures.md

sources/tech/20210222 5 benefits of choosing Linux.md
=> 申领文章 max27149

sources/tech/20210214 Why programmers love Linux packaging.md
=> Update 20210214 Why programmers love Linux packaging.md

sources/tech/20210212 4 reasons to choose Linux for art and design.md
=> translating by amor

published/20210119 Set up a Linux cloud on bare metal.md
@wxy
https://linux.cn/article-13161-1.html
=> PUB:published/20210119 Set up a Linux cloud on bare metal.md

published/20210118 KDE Customization Guide- Here are 11 Ways You Can Change the Look and Feel of Your KDE-Powered Linux Desktop.md
@wxy
https://linux.cn/article-13172-1.html
=> PUB:published/20210118 KDE Customization Guide- Here are 11 Ways You Can Change the Look and Feel of Your KDE-Powered Linux Desktop.md

published/20210204 5 Tweaks to Customize the Look of Your Linux Terminal.md
@wxy
https://linux.cn/article-13181-1.html
=> PUB:published/20210204 5 Tweaks to Customize the Look of Your Linux Terminal.md

published/20210228 How to Install the Latest Erlang on Ubuntu Linux.md
@geekpi
https://linux.cn/article-13182-1.html
=> PRF&PUB:published/20210228 How to Install the Latest Erlang on Ubuntu Linux.md

published/20210302 Meet SysMonTask- A Windows Task Manager Lookalike for Linux.md
@wxy
https://linux.cn/article-13189-1.html
=> PUB:published/20210302 Meet SysMonTask- A Windows Task Manager Lookalike for Linux.md

sources/talk/20200219 Multicloud, security integration drive massive SD-WAN adoption.md
申领原文：
talk/'20200219 Multicloud, security integration drive massive SD-WAN adoption.md'
=> 申领原文： talk/'20200219 Multicloud, security integration drive massive SD-WAN adoption.md'

published/20210304 An Introduction to WebAssembly.md, translated/tech/20210304 An Introduction to WebAssembly.md
@geekpi
https://linux.cn/article-13197-1.html
=> PRF&PUB:20210304 an introduction to web assembly

published/20210310 How to Update openSUSE Linux System.md, translated/tech/20210310 How to Update openSUSE Linux System.md
@geekpi
https://linux.cn/article-13199-1.html
=> PRF&PUB:20210310 how to update open suse linux system

published/20210304 Learn to debug code with the GNU Debugger.md
@wxy
https://linux.cn/article-13203-1.html
=> PUB:published/20210304 Learn to debug code with the GNU Debugger.md

published/20210309 Use gImageReader to Extract Text From Images and PDFs on Linux.md
@geekpi
https://linux.cn/article-13205-1.html
=> PUB:published/20210309 Use gImageReader to Extract Text From Images and PDFs on Linux.md

published/20210305 5 surprising things you can do with LibreOffice from the command line.md, translated/tech/20210305 5 surprising things you can do with LibreOffice from the command line.md
@geekpi
https://linux.cn/article-13219-1.html
=> PRF&PUB:20210305 5 surprising things you can do with libre office from the command line

published/20210319 Top 10 Terminal Emulators for Linux (With Extra Features or Amazing Looks).md
@wxy
https://linux.cn/article-13221-1.html
=> PUB:published/20210319 Top 10 Terminal Emulators for Linux (With Extra Features or Amazing Looks).md

published/20210225 4 new open source licenses.md, translated/tech/20210225 4 new open source licenses.md
@wyxplus
https://linux.cn/article-13224-1.html
=> PRF&PUB:20210225 4 new open source licenses

published/20210316 Kooha is a Nascent Screen Recorder for GNOME With Wayland Support.md
@geekpi
https://linux.cn/article-13227-1.html
=> PRF&PUB:published/20210316 Kooha is a Nascent Screen Recorder for GNOME With Wayland Support.md

sources/tech/20210309 Learn Python dictionary values with Jupyter.md
20210309 Learn Python dictionary values with Jupyter is translated by DCOLIVERSUN
=> translating by DCOLIVERSUN

published/20210315 6 things to know about using WebAssembly on Firefox.md, translated/tech/20210315 6 things to know about using WebAssembly on Firefox.md
@geekpi
https://linux.cn/article-13230-1.html
=> PRF&PUB:20210315 6 things to know about using web assembly on firefox

published/20210309 Learn Python dictionary values with Jupyter.md, translated/tech/20210309 Learn Python dictionary values with Jupyter.md
@DCOLIVERSUN
本文首发地址：https://linux.cn/article-13236-1.html
您的 LCTT 专页地址： https://linux.cn/lctt/DCOLIVERSUN
=> PRF&PUB:20210309 learn python dictionary values with jupyter

published/20210322 Why I use exa instead of ls on Linux.md, translated/tech/20210322 Why I use exa instead of ls on Linux.md
@geekpi
https://linux.cn/article-13237-1.html
=> PRF&PUB:20210322 why i use exa instead of ls on linux

published/20210319 4 cool new projects to try in Copr for March 2021.md
@geekpi
https://linux.cn/article-13243-1.html
=> PRF&PUB:published/20210319 4 cool new projects to try in Copr for March 2021.md

translated/tech/20210318 Reverse Engineering a Docker Image.md
"reverse-engineering-a-docker-image" translation is completed by DCOLIVERSUN
=> translation completed

published/20210318 Practice using the Linux grep command.md, translated/tech/20210318 Practice using the Linux grep command.md
@lxbwolf
https://linux.cn/article-13247-1.html
=> PRF&PUB:20210318 practice using the linux grep command

published/20210323 3 new Java tools to try in 2021.md, translated/tech/20210323 3 new Java tools to try in 2021.md
@geekpi
https://linux.cn/article-13249-1.html
=> PRF&PUB:20210323 3 new java tools to try in 2021

published/20210316 How to write -Hello World- in WebAssembly.md, translated/tech/20210316 How to write -Hello World- in WebAssembly.md
@geekpi
https://linux.cn/article-13250-1.html
=> PRF&PUB:20210316 how to write  hello world  in web assembly

published/20210315 Learn how file input and output works in C.md, translated/tech/20210315 Learn how file input and output works in C.md
@wyxplus
https://linux.cn/article-13252-1.html
=> PRF&PUB:20210315 learn how file input and output works in c

published/20210322 5 everyday sysadmin tasks to automate with Ansible.md
@wxy
https://linux.cn/article-13256-1.html
=> PUB:published/20210322 5 everyday sysadmin tasks to automate with Ansible.md

published/20210318 Reverse Engineering a Docker Image.md, translated/tech/20210318 Reverse Engineering a Docker Image.md
@DCOLIVERSUN
https://linux.cn/article-13258-1.html
=> PRF&PUB:20210318 reverse engineering a docker image

published/20210324 Read and write files with Bash.md, translated/tech/20210324 Read and write files with Bash.md
@geekpi
https://linux.cn/article-13259-1.html
=> PRF&PUB:20210324 read and write files with bash

published/20210330 NewsFlash- A Modern Open-Source Feed Reader With Feedly Support.md, translated/tech/20210330 NewsFlash- A Modern Open-Source Feed Reader With Feedly Support.md
@DCOLIVERSUN
https://linux.cn/article-13264-1.html
=> PRF&PUB:20210330 news flash  a modern open source feed reader with feedly support

published/20210403 What problems do people solve with strace.md
@wxy
https://linux.cn/article-13267-1.html
=> PUB:published/20210403 What problems do people solve with strace.md

published/20210404 Converting Multiple Markdown Files into HTML or Other Formats in Linux.md, translated/tech/20210404 Converting Multiple Markdown Files into HTML or Other Formats in Linux.md
@lxbwolf
https://linux.cn/article-13274-1.html
=> PRF&PUB:20210404 converting multiple markdown files into html or other formats in linux

published/20210401 Wrong Time Displayed in Windows-Linux Dual Boot Setup- Here-s How to Fix it.md, translated/tech/20210401 Wrong Time Displayed in Windows-Linux Dual Boot Setup- Here-s How to Fix it.md
@geekpi
https://linux.cn/article-13276-1.html
=> PRF&PUB:20210401 wrong time displayed in windows linux dual boot setup  here s how to fix it

published/20210329 Why I love using the IPython shell and Jupyter notebooks.md, translated/tech/20210329 Why I love using the IPython shell and Jupyter notebooks.md
@geekpi
https://linux.cn/article-13277-1.html
=> PRF&PUB:20210329 why i love using the i python shell and jupyter notebooks

published/20210331 Use this open source tool to monitor variables in Python.md, translated/tech/20210331 Use this open source tool to monitor variables in Python.md
@geekpi
https://linux.cn/article-13279-1.html
=> PRF&PUB:20210331 use this open source tool to monitor variables in python

published/20210401 Find what changed in a Git commit.md, translated/tech/20210401 Find what changed in a Git commit.md
@DCOLIVERSUN
https://linux.cn/article-13286-1.html
=> PRF&PUB:20210401 find what changed in a git commit

published/20210411 GNOME-s Very Own -GNOME OS- is Not a Linux Distro for Everyone -Review.md
@wxy
https://linux.cn/article-13287-1.html
=> PUB:published/20210411 GNOME-s Very Own -GNOME OS- is Not a Linux Distro for Everyone -Review.md

published/20210407 Show CPU Details Beautifully in Linux Terminal With CPUFetch.md, translated/tech/20210407 Show CPU Details Beautifully in Linux Terminal With CPUFetch.md
@geekpi
https://linux.cn/article-13289-1.html
=> PRF&PUB:20210407 show cpu details beautifully in linux terminal with cpu fetch

published/20210406 Teach anyone how to code with Hedy.md
@wxy
https://linux.cn/article-13290-1.html
=> PUB:published/20210406 Teach anyone how to code with Hedy.md

published/20210402 A practical guide to using the git stash command.md, translated/tech/20210402 A practical guide to using the git stash command.md
@wxy
https://linux.cn/article-13293-1.html
=> PRF&PUB:20210402 a practical guide to using the git stash command

published/20210407 What is Git cherry-picking.md, translated/tech/20210407 What is Git cherry-picking.md
@geekpi
https://linux.cn/article-13295-1.html
=> PRF&PUB:20210407 what is git cherry picking

published/20210413 Create an encrypted file vault on Linux.md
@wxy
https://linux.cn/article-13296-1.html
=> PUB:published/20210413 Create an encrypted file vault on Linux.md

published/20210410 How to Install Steam on Fedora -Beginner-s Tip.md, translated/tech/20210410 How to Install Steam on Fedora -Beginner-s Tip.md
@geekpi
https://linux.cn/article-13302-1.html
=> PRF&PUB:20210410 how to install steam on fedora  beginner s tip

published/20210412 Encrypt your files with this open source software.md, translated/tech/20210412 Encrypt your files with this open source software.md
@geekpi
https://linux.cn/article-13304-1.html
=> PRF&PUB:20210412 encrypt your files with this open source software

published/20210414 Make your data boss-friendly with this open source tool.md
@geekpi
https://linux.cn/article-13310-1.html
=> PRF&PUB:published/20210414 Make your data boss-friendly with this open source tool.md

published/20201109 Getting started with Stratis encryption.md
@wxy
https://linux.cn/article-13311-1.html
=> PRF&PUB:published/20201109 Getting started with Stratis encryption.md

published/20210308 Cast your Android device with a Raspberry Pi.md, translated/tech/20210308 Cast your Android device with a Raspberry Pi.md
@ShuyRoy
https://linux.cn/article-13314-1.html
=> PRF&PUB:20210308 cast your android device with a raspberry pi

sources/news/20210416 Metro Exodus is Finally Here on Steam for Linux.md
sources/news/20210416 Metro Exodus is Finally Here on Steam for Linux.md
=> 选题[news]: 20210416 Metro Exodus is Finally Here on Steam for Linux

published/20210419 4 steps to customizing your Mac terminal theme with open source tools.md, translated/tech/20210419 4 steps to customizing your Mac terminal theme with open source tools.md
@geekpi
https://linux.cn/article-13323-1.html
=> PRF&PUB:20210419 4 steps to customizing your mac terminal theme with open source tools

published/20210413 Create and Edit EPUB Files on Linux With Sigil.md, translated/tech/20210413 Create and Edit EPUB Files on Linux With Sigil.md
@geekpi
https://linux.cn/article-13325-1.html
=> PRF&ZPUB:20210413 create and edit epub files on linux with sigil

published/20210420 The Guided Installer in Arch is a Step in the Right Direction.md, translated/news/20210420 The Guided Installer in Arch is a Step in the Right Direction.md
@Kevin3599
https://linux.cn/article-13328-1.html
=> PRF&PUB:20210420 the guided installer in arch is a step in the right direction

published/20210421 Optimize your Python code with C.md, translated/tech/20210421 Optimize your Python code with C.md
@ShuyRoy
https://linux.cn/article-13338-1.html
=> PRF&PUB:20210421 optimize your python code with c

sources/tech/20210420 A beginner-s guide to network management.md
=> Update 20210420 A beginner-s guide to network management.md

published/20210407 Using network bound disk encryption with Stratis.md
@wxy
https://linux.cn/article-13340-1.html
=> PUB:published/20210407 Using network bound disk encryption with Stratis.md

published/20210420 Blanket- Ambient Noise App With Variety of Sounds to Stay Focused.md, translated/tech/20210420 Blanket- Ambient Noise App With Variety of Sounds to Stay Focused.md
@geekpi
https://linux.cn/article-13343-1.html
=> PRF&PUB:20210420 blanket  ambient noise app with variety of sounds to stay focused

published/20210203 Improve your productivity with this Linux automation tool.md, translated/tech/20210203 Improve your productivity with this Linux automation tool.md
@stevenzdg988
https://linux.cn/article-13347-1.html
=> PRF&PUB:20210416 play a fun math game with linux commands

published/20210423 What-s New in Ubuntu MATE 21.04.md, translated/news/20210423 What-s New in Ubuntu MATE 21.04.md
@Kevin3599
https://linux.cn/article-13349-1.html
=> PRF&PUB:20210423 what s new in ubuntu mate 21.04

published/20210420 Application observability with Apache Kafka and SigNoz.md
@geekpi
https://linux.cn/article-13352-1.html
=> PRF&PUB:published/20210420 Application observability with Apache Kafka and SigNoz.md

published/20210330 Access Python package index JSON APIs with requests.md, translated/tech/20210330 Access Python package index JSON APIs with requests.md
@MjSeven
https://linux.cn/article-13356-1.html
=> PRF&PUB:20210330 access python package index json ap is with requests

published/20210427 What-s new in Fedora Workstation 34.md
@wxy
https://linux.cn/article-13359-1.html
=> PUB:published/20210427 What-s new in Fedora Workstation 34.md

published/20210504 Keep multiple Linux distros on a USB with this open source tool.md
@wxy
https://linux.cn/article-13361-1.html
=> PUB:published/20210504 Keep multiple Linux distros on a USB with this open source tool.md

published/20210427 Fedora Linux 34 is officially here.md, translated/tech/20210427 Fedora Linux 34 is officially here.md
@geekpi
https://linux.cn/article-13365-1.html
=> PRF&PUB:20210427 fedora linux 34 is officially here

published/20210429 Encrypting and decrypting files with OpenSSL.md, translated/tech/20210429 Encrypting and decrypting files with OpenSSL.md
@MjSeven
https://linux.cn/article-13368-1.html
=> PRF&PUB:20210429 encrypting and decrypting files with open ssl

published/20210502 Fedora Vs Red Hat- Which Linux Distro Should You Use and Why.md, translated/tech/20210502 Fedora Vs Red Hat- Which Linux Distro Should You Use and Why.md
@wxy
https://linux.cn/article-13372-1.html
=> PRF&PUB:20210502 fedora vs red hat  which linux distro should you use and why

sources/talk/20210218 Not an engineer- Find out where you belong.md
=> 超期回收: sources/talk/20210218 Not an engineer- Find out where you belong.md

published/20210422 Running Linux Apps In Windows Is Now A Reality.md, translated/news/20210422 Running Linux Apps In Windows Is Now A Reality.md
@Kevin3599
翻译时请忠实原文意思，可以再细心些。
https://linux.cn/article-13376-1.html
=> PRF&PUB:20210422 running linux apps in windows is now a reality

published/20210427 An Open-Source App to Control All Your RGB Lighting Settings.md, translated/tech/20210427 An Open-Source App to Control All Your RGB Lighting Settings.md
@geekpi
https://linux.cn/article-13377-1.html
=> PRF&PUB:20210427 an open source app to control all your rgb lighting settings

published/20210503 Configure WireGuard VPNs with NetworkManager.md, translated/tech/20210503 Configure WireGuard VPNs with NetworkManager.md
@DCOLIVERSUN
https://linux.cn/article-13379-1.html
=> PRF&PUB:20210503 configure wire guard vp ns with network manager

published/20210505 Drop telnet for OpenSSL.md, translated/tech/20210505 Drop telnet for OpenSSL.md
@geekpi
https://linux.cn/article-13381-1.html
=> PRF&PUB:20210505 drop telnet for open ssl

published/20210421 Build smaller containers.md, translated/tech/20210421 Build smaller containers.md
@ShuyRoy
https://linux.cn/article-13382-1.html
=> PRF&PUB:20210421 build smaller containers

published/20210412 Scheduling tasks with cron.md, translated/tech/20210412 Scheduling tasks with cron.md
@MjSeven
https://linux.cn/article-13383-1.html
=> PRF&PUB:20210412 scheduling tasks with cron

published/20210417 How to Download Ubuntu via Torrent -Absolute Beginner-s Tip.md
@geekpi
https://linux.cn/article-13386-1.html
=> PRF&PUB:published/20210417 How to Download Ubuntu via Torrent -Absolute Beginner-s Tip.md

published/20210501 Chrome Browser Keeps Detecting Network Change in Linux- Here-s How to Fix it.md, translated/tech/20210501 Chrome Browser Keeps Detecting Network Change in Linux- Here-s How to Fix it.md
@HuengchI
本文首发地址：https://linux.cn/article-13389-1.html
您的 LCTT 专页地址：https://linux.cn/lctt/HuengchI
=> PRF&PUB:20210501 chrome browser keeps detecting network change in linux  here s how to fix it

published/20210506 Learn essential Kubernetes commands with a new cheat sheet.md, translated/tech/20210506 Learn essential Kubernetes commands with a new cheat sheet.md
@geekpi
https://linux.cn/article-13390-1.html
=> PRF&PUB:20210506 learn essential kubernetes commands with a new cheat sheet

published/20210510 Make Jenkins logs pretty.md, translated/tech/20210510 Make Jenkins logs pretty.md
@DCOLIVERSUN
https://linux.cn/article-13392-1.html
=> PRF&PUB:20210510 make jenkins logs pretty

published/20210412 Send your scans to a Linux machine over your network.md, translated/tech/20210412 Send your scans to a Linux machine over your network.md
@geekpi
https://linux.cn/article-13395-1.html
=> PRF&PUB:20210412 send your scans to a linux machine over your network

published/20210512 Using Ansible to configure Podman containers.md, translated/tech/20210512 Using Ansible to configure Podman containers.md
@DCOLIVERSUN
https://linux.cn/article-13396-1.html
=> PRF&PUB:20210512 using ansible to configure podman containers

sources/tech/20210222 A friendly guide to the syntax of C-- method pointers.md
File Name: A friendly guide to the syntax of C++ method pointers
=> Apply for translation(mengxinayan)

published/20200316 OpenStreetMap- A Community-Driven Google Maps Alternative.md
@rakino
https://linux.cn/article-13399-1.html
=> PRF&PUB:published/20200316 OpenStreetMap- A Community-Driven Google Maps Alternative.md

published/20210419 21 reasons why I think everyone should try Linux.md, translated/talk/20210419 21 reasons why I think everyone should try Linux.md
@ShuyRoy
https://linux.cn/article-13404-1.html
=> PRF&PUB:20210419 21 reasons why i think everyone should try linux

published/20210512 3 features that debuted in Python 3.0 you should use now.md, translated/tech/20210512 3 features that debuted in Python 3.0 you should use now.md
published/20210512 3 features that debuted in Python 3.0 you should use now.md
=> PRF&PUB:20210512 3 features that debuted in python 3.0 you should use now

published/20210516 How to install a Desktop Environment (GUI) on Ubuntu Server.md, translated/tech/20210516 How to install a Desktop Environment (GUI) on Ubuntu Server.md
@lxbwolf
https://linux.cn/article-13408-1.html
=> PRF&PUB:20210516 how to install a desktop environment (g UI) on ubuntu server

published/20210520 Remap your Caps Lock key on Linux.md
@wxy
https://linux.cn/article-13414-1.html
=> PUB:published/20210520 Remap your Caps Lock key on Linux.md

published/20210519 1Password for Linux Is Officially Here With Brand New Features.md
@wxy
https://linux.cn/article-13416-1.html
=> PUB:published/20210519 1Password for Linux Is Officially Here With Brand New Features.md

published/20210514 Drop Autotools for CMake.md, translated/tech/20210514 Drop Autotools for CMake.md
@amwps290
https://linux.cn/article-13419-1.html
=> PRF&PUB:20210514 drop autotools for c make.md

published/20210414 4 tips for context switching in Git.md, translated/tech/20210414 4 tips for context switching in Git.md
@Chao-zhi
https://linux.cn/article-13422-1.html
=> PRF&PUB:20210414 4 tips for context switching in git

published/20210427 Perform Linux memory forensics with this open source tool.md, translated/tech/20210427 Perform Linux memory forensics with this open source tool.md
@ShuyRoy
https://linux.cn/article-13425-1.html
=> PRF&PUB:20210427 perform linux memory forensics with this open source tool

published/20210521 Joining Fedora Linux to an enterprise domain.md, translated/tech/20210521 Joining Fedora Linux to an enterprise domain.md
@Chao-zhi
https://linux.cn/article-13426-1.html
=> PRF&PUB:20210521 joining fedora linux to an enterprise domain

published/20210420 5 ways to protect your documents with open source software.md
@wxy
https://linux.cn/article-13428-1.html
=> PUB:published/20210420 5 ways to protect your documents with open source software.md

published/20210513 3 features released in Python 3.1 you should use in 2021.md, translated/tech/20210513 3 features released in Python 3.1 you should use in 2021.md
@geekpi
https://linux.cn/article-13432-1.html
=> PRF&PUB:20210513 3 features released in python 3.1 you should use in 2021

published/20210425 Play retro video games on Linux with this open source project.md
@wxy
https://linux.cn/article-13433-1.html
=> PUB:published/20210425 Play retro video games on Linux with this open source project.md

published/20210514 3 Python 3.2 features that are still relevant today.md, translated/tech/20210514 3 Python 3.2 features that are still relevant today.md
@geekpi
https://linux.cn/article-13435-1.html
=> PRF&PUB:20210514 3 python 3.2 features that are still relevant today

published/20210527 Port operating systems to new chip architectures.md
@wxy
https://linux.cn/article-13436-1.html
=> PUB:published/20210527 Port operating systems to new chip architectures.md

published/20210515 What Python 3.3 did to improve exception handling in your code.md
@wxy
https://linux.cn/article-13439-1.html
=> PUB:published/20210515 What Python 3.3 did to improve exception handling in your code.md

published/20210429 Experiencing the -e- OS- The Open Source De-Googled Android Version.md
@wxy
https://linux.cn/article-13442-1.html
=> PUB:published/20210429 Experiencing the -e- OS- The Open Source De-Googled Android Version.md

published/20210516 Looking back at what Python 3.4 did for enum.md, translated/tech/20210516 Looking back at what Python 3.4 did for enum.md
published/20210516 Looking back at what Python 3.4 did for enum.md
=> PRF&PUB:20210516 looking back at what python 3.4 did for enum

sources/tech/20210523 3 reasons to learn Java in 2021.md
=> Update 20210523 3 reasons to learn Java in 2021.md

published/20210517 Convenient matrices and other improvements Python 3.5 brought us.md, translated/tech/20210517 Convenient matrices and other improvements Python 3.5 brought us.md
@geekpi
https://linux.cn/article-13448-1.html
=> PRF&PUB:20210517 convenient matrices and other improvements python 3.5 brought us

published/20210601 Nyxt Browser is a Keyboard-oriented Web Browser Inspired by Emacs and Vim.md
@wxy
https://linux.cn/article-13449-1.html
=> PUB:published/20210601 Nyxt Browser is a Keyboard-oriented Web Browser Inspired by Emacs and Vim.md

published/20210526 Make Command Not Found- Here-s How to Fix it.md
@geekpi
https://linux.cn/article-13451-1.html
=> PRF&PUB:published/20210526 Make Command Not Found- Here-s How to Fix it.md

published/20210518 Are you using this magic method for filesystems from Python 3.6.md
@geekpi
https://linux.cn/article-13454-1.html
=> PRF&PUB:published/20210518 Are you using this magic method for filesystems from Python 3.6.md

published/20210528 What you need to know about Quarkus in 2021.md
@geekpi
https://linux.cn/article-13456-1.html
=> PRF&PUB:published/20210528 What you need to know about Quarkus in 2021.md

published/20210519 Slice infinite generators with this Python 3.7 feature.md, translated/tech/20210519 Slice infinite generators with this Python 3.7 feature.md
@geekpi
https://linux.cn/article-13459-1.html
=> PRF&PUB:20210519 slice infinite generators with this python 3.7 feature

sources/talk/20191029 5 reasons why I love Python.md
=> translating by osu-zxf

published/20210602 Convert Images to ASCII Art in Linux Terminal With This Nifty Little Tool.md
@geekpi
https://linux.cn/article-13461-1.html
=> PRF&PUB:published/20210602 Convert Images to ASCII Art in Linux Terminal With This Nifty Little Tool.md

sources/tech/20210222 A friendly guide to the syntax of C-- method pointers.md
File Name: A friendly guide to the syntax of C++ method pointers
=> Finish translation(mengxinayan)

published/20210520 Make your API better with this positional trick from Python 3.8.md
@geekpi
https://linux.cn/article-13466-1.html
=> PRF&PUB:published/20210520 Make your API better with this positional trick from Python 3.8.md

published/20210602 openSUSE Leap 15.3 Release Finally Closes the Gap With SUSE Linux Enterprise.md, translated/news/20210602 openSUSE Leap 15.3 Release Finally Closes the Gap With SUSE Linux Enterprise.md
@Chao-zhi
https://linux.cn/article-13469-1.html
=> PRF&PUB:20210602 open suse leap 15.3 release finally closes the gap with suse linux enterprise

published/20210521 How Python 3.9 fixed decorators and improved dictionaries.md
@geekpi
https://linux.cn/article-13477-1.html
=> PRF&PUB:published/20210521 How Python 3.9 fixed decorators and improved dictionaries.md

published/20210611 RTFM- How to Read (and Understand) the Fantastic Man Pages in Linux.md
@wxy
https://linux.cn/article-13478-1.html
=> PUB:published/20210611 RTFM- How to Read (and Understand) the Fantastic Man Pages in Linux.md

published/20210603 How to Install Code Blocks IDE on Ubuntu Linux.md
@geekpi
https://linux.cn/article-13484-1.html
=> PRF&PUB:published/20210603 How to Install Code Blocks IDE on Ubuntu Linux.md

sources/talk/20200930 FCC auctions should be a long-term boost for 5G availability.md
=> littlebirdnest申请翻译

published/20210518 Manage your Raspberry Pi with Cockpit.md, translated/tech/20210518 Manage your Raspberry Pi with Cockpit.md
@ShuyRoy
https://linux.cn/article-13487-1.html
=> PRF&PUB:20210518 manage your raspberry pi with cockpit

published/20210601 Get started with FreeDOS.md, translated/tech/20210601 Get started with FreeDOS.md
@geekpi
https://linux.cn/article-13492-1.html
=> PRF&PUB:20210601 get started with free dos

published/20210608 How FreeDOS boots.md, translated/tech/20210608 How FreeDOS boots.md
@geekpi
https://linux.cn/article-13503-1.html
恭喜您，成为了 LCTT 第一位四钻成员！感谢您一直以来的支持和付出。
=> PRF&PUB:20210608 how free dos boots

published/20210526 How I monitor my greenhouse with CircuitPython and open source tools.md, translated/tech/20210526 How I monitor my greenhouse with CircuitPython and open source tools.md
@alim0x
https://linux.cn/article-13504-1.html
=> PRF&PUB:20210526 how i monitor my greenhouse with circuit python and open source tools

sources/tech/20200629 Scaling a GraphQL Website.md
=> 超期回收: sources/tech/20200629 Scaling a GraphQL Website.md

published/20210613 How Free - Open Source Software Can Save Online Privacy.md, translated/talk/20210613 How Free - Open Source Software Can Save Online Privacy.md
@zz-air
感谢你完成了第一篇贡献！确实用心了。
本文首发地址：https://linux.cn/article-13512-1.html
你的 LCTT 专页地址：https://linux.cn/lctt/zz-air
=> PRF&PUB:20210613 how free   open source software can save online privacy

published/20210623 Replace find with fd on Linux.md
@wxy
https://linux.cn/article-13516-1.html
=> PUB:published/20210623 Replace find with fd on Linux.md

published/20210619 Here-s Why Switching to Linux Makes Sense in 2021.md, translated/talk/20210619 Here-s Why Switching to Linux Makes Sense in 2021.md
@zEpoch
本文首发地址：https://linux.cn/article-13519-1.html
您的 LCTT 专页地址：https://linux.cn/lctt/zEpoch
=> PRF&PUB:20210619 here s why switching to linux makes sense in 2021

published/20210616 Migrate virtual machines to Kubernetes with this new tool.md, translated/tech/20210616 Migrate virtual machines to Kubernetes with this new tool.md
@geekpi
https://linux.cn/article-13520-1.html
=> PRF&PUB:20210616 migrate virtual machines to kubernetes with this new tool

published/20210618 Systemd Timers for Scheduling Tasks.md, translated/tech/20210618 Systemd Timers for Scheduling Tasks.md
@dcoliversun
https://linux.cn/article-13522-1.html
=> PRF&PUB:20210618 systemd timers for scheduling tasks

published/20210622 KTorrent- An Incredibly Useful BitTorrent Application by KDE.md, translated/tech/20210622 KTorrent- An Incredibly Useful BitTorrent Application by KDE.md
@geekpi
https://linux.cn/article-13530-1.html
=> PRF&PUB:20210622 k torrent  an incredibly useful bit torrent application by kde

sources/tech/20210628 Query your Linux operating system like a database.md
=> Update 20210628 Query your Linux operating system like a database.md

published/20210517 Use open source tools to set up a private VPN.md, translated/tech/20210517 Use open source tools to set up a private VPN.md
@stevenzdg988
https://linux.cn/article-13539-1.html
=> PRF&PUB:20210517 use open source tools to set up a private vpn

published/20210628 Forgot Linux Password on WSL- Here-s How to Reset it Easily.md, translated/tech/20210628 Forgot Linux Password on WSL- Here-s How to Reset it Easily.md
@geekpi
https://linux.cn/article-13545-1.html
=> PRF&PUB:20210628 forgot linux password on wsl  here s how to reset it easily

published/20210624 Copy files between Linux and FreeDOS.md
@geekpi
https://linux.cn/article-13548-1.html
=> PRF&PUB:published/20210624 Copy files between Linux and FreeDOS.md

published/20210625 Use Python to parse configuration files.md, translated/tech/20210625 Use Python to parse configuration files.md
@zEpoch
https://linux.cn/article-13551-1.html
=> PRF&PUB:20210625 use python to parse configuration files

sources/talk/20200124 Gartner- Data-center spending will inch up this year.md
=> Update 20200124 Gartner- Data-center spending will inch up this year.md

published/20210624 View statistics about your code with Tokei.md, translated/tech/20210624 View statistics about your code with Tokei.md
@zEpoch
https://linux.cn/article-13554-1.html
=> PRF&PUB:20210624 view statistics about your code with tokei

published/20210628 How to archive files on FreeDOS.md
@geekpi
https://linux.cn/article-13567-1.html
=> PRF&PUB:published/20210628 How to archive files on FreeDOS.md

sources/tech/20210621 Replace man pages with Tealdeer on Linux.md, translated/tech/20210621 Replace man pages with Tealdeer on Linux.md
=> Update 20210621 Replace man pages with Tealdeer on Linux.md

published/20210621 Replace man pages with Tealdeer on Linux.md, translated/tech/20210621 Replace man pages with Tealdeer on Linux.md
@ddl-hust
https://linux.cn/article-13570-1.html
=> PRF&PUB:20210621 replace man pages with tealdeer on linux

published/20210709 How to Install Zlib on Ubuntu Linux.md, translated/tech/20210709 How to Install Zlib on Ubuntu Linux.md
@MjSeven
https://linux.cn/article-13572-1.html
=> PRF&PUB:20210709 how to install zlib on ubuntu linux

published/20210706 Send and receive Gmail from the Linux command line.md, translated/tech/20210706 Send and receive Gmail from the Linux command line.md
@HankChow
https://linux.cn/article-13573-1.html
=> PRF&PUB:20210706 send and receive gmail from the linux command line

sources/tech/20180619 Systemd Services- Monitoring Files and Directories.md
=> Update 20180619 Systemd Services- Monitoring Files and Directories.md

sources/tech/20200528 9 open source JavaScript frameworks for front-end web development.md
(subject: (9 open source JavaScript frameworks for front-end web development))
=> subject: (9 open source JavaScript frameworks for front-end web development)

published/20210628 Query your Linux operating system like a database.md, translated/tech/20210628 Query your Linux operating system like a database.md
@YungeG
本文首发地址：https://linux.cn/article-13578-1.html
你的 LCTT 专页地址：https://linux.cn/lctt/YungeG
=> PRF&PUB:20210628 query your linux operating system like a database

published/20210705 Enter invisible passwords using this Python module.md
@geekpi
https://linux.cn/article-13579-1.html
=> PRF&PUB:published/20210705 Enter invisible passwords using this Python module.md

sources/talk/20210529 My family-s Linux story.md
=> Update 20210529 My family-s Linux story.md

published/20210706 Edit PDFs on the Linux command line.md, translated/tech/20210706 Edit PDFs on the Linux command line.md
@geekpi 
https://linux.cn/article-13581-1.html
=> PRF&PUB:20210706 edit pd fs on the linux command line

published/20210707 Generate passwords on the Linux command line.md
@geekpi
@turbokernel 感谢参与校对
https://linux.cn/article-13582-1.html
=> PRF&PUB:published/20210707 Generate passwords on the Linux command line.md

translated/tech/20210625 How to Setup Internet in CentOS, RHEL, Rocky Linux Minimal Install.md, translated/tech/20210708 Encrypt and decrypt files with a passphrase on Linux.md
=> Reviewed 20210625 How to Setup Internet in CentOS, RHEL, Rocky Linux 

published/20210708 Linux Mint 20.2 is Now Available With New Features and Tools.md, translated/news/20210708 Linux Mint 20.2 is Now Available With New Features and Tools.md
@lcf33
本文首发地址：https://linux.cn/article-13584-1.html
您的 LCTT 专页地址：https://linux.cn/lctt/lcf33
=> PRF&PUB:20210708 linux mint 20.2 is now available with new features and tools

published/20210625 How to Setup Internet in CentOS, RHEL, Rocky Linux Minimal Install.md, translated/tech/20210625 How to Setup Internet in CentOS, RHEL, Rocky Linux Minimal Install.md
@geekpi
@turbokernel
https://linux.cn/article-13585-1.html
=> PRF&PUB:20210625 how to setup internet in cent os, rhel, rocky linux minimal install

published/20210703 Can Windows 11 Influence Linux Distributions.md, translated/talk/20210703 Can Windows 11 Influence Linux Distributions.md
@zz-air
https://linux.cn/article-13588-1.html
=> PRF&PUB:20210703 can windows 11 influence linux distributions

translated/tech/20200807 An advanced guide to NLP analysis with Python and NLTK.md
amended 'An advanced guide to NLP analysis with Python and NLTK'
=> amended 'An advanced guide to NLP analysis with Python and NLTK'

published/20210712 Box64 Emulator Released for Arm64 Linux.md, translated/news/20210712 Box64 Emulator Released for Arm64 Linux.md
@zd200572
本文首发地址：https://linux.cn/article-13591-1.html
您的 LCTT 专页地址：https://linux.cn/lctt/zd200572
=> PRF&PUB:20210712 box64 emulator released for arm64 linux

published/20210708 Encrypt and decrypt files with a passphrase on Linux.md
@geekpi
@turbokernel
https://linux.cn/article-13592-1.html
=> PRF&PUB:published/20210708 Encrypt and decrypt files with a passphrase on Linux.md

sources/talk/20210308 How the ARPANET Protocols Worked.md, translated/talk/20210308 How the ARPANET Protocols Worked.md
=> translating by Lin-vy

sources/tech/20210129 Machine learning made easy with Python.md
申领原文 '20210129 Machine learning made easy with Python'
=> 申领原文 '20210129 Machine learning made easy with Python'

published/20210714 How different programming languages read and write data.md, translated/tech/20210714 How different programming languages read and write data.md
@MjSeven
https://linux.cn/article-13599-1.html
=> PRF&PUB:20210714 how different programming languages read and write data

sources/news/20210722 Ubuntu 20.10 Reached End of Life, Time to Upgrade.md
=> Update 20210722 Ubuntu 20.10 Reached End of Life, Time to Upgrade.md

published/20210616 Hash Linux- Arch Linux Preconfigured With Xmonad, Awesome, i3, and Bspwm Window Manager.md, translated/tech/20210616 Hash Linux- Arch Linux Preconfigured With Xmonad, Awesome, i3, and Bspwm Window Manager.md
@mcfd
https://linux.cn/article-13608-1.html
=> PRF&PUB:20210616 hash linux  arch linux preconfigured with xmonad, awesome, i3, and bspwm window manager

sources/tech/20210719 Linux package managers- dnf vs apt.md
=> translating by perfiffer

published/20210722 Ubuntu 20.10 Reached End of Life, Time to Upgrade.md, translated/news/20210722 Ubuntu 20.10 Reached End of Life, Time to Upgrade.md
@zd200572
https://linux.cn/article-13611-1.html
=> PRF&PUB:20210722 ubuntu 20.10 reached end of life, time to upgrade

published/20210714 Getting Started with Podman on Fedora.md
@geekpi
https://linux.cn/article-13615-1.html
=> PRF&PUB:published/20210714 Getting Started with Podman on Fedora.md

published/20210712 Converseen for Batch Processing Images on Linux.md, translated/tech/20210712 Converseen for Batch Processing Images on Linux.md
@geekpi
https://linux.cn/article-13617-1.html
=> PRF&PUB:20210712 converseen for batch processing images on linux

published/20210719 Linux package managers- dnf vs apt.md, translated/tech/20210719 Linux package managers- dnf vs apt.md
@perfiffer
本文首发地址：https://linux.cn/article-13620-1.html
您的 LCTT 专页地址：https://linux.cn/lctt/perfiffer
=> PRF&PUB:20210719 linux package managers  dnf vs apt

published/20210612 How to get KDE Plasma 5.22 in Kubuntu 21.04 Hirsute Hippo.md
@geekpi
https://linux.cn/article-13621-1.html
=> PRF&PUB:published/20210612 How to get KDE Plasma 5.22 in Kubuntu 21.04 Hirsute Hippo.md

published/20210317 Programming 101- Input and output with Java.md, translated/tech/20210317 Programming 101- Input and output with Java.md
@Piaoshi
https://linux.cn/article-13622-1.html
=> PRF&PUB:20210317 programming 101  input and output with java

published/20210716 Apps for daily needs part 1- web browsers.md
@geekpi
https://linux.cn/article-13625-1.html
=> PRF&PUB:published/20210716 Apps for daily needs part 1- web browsers.md

published/20210713 Use XMLStarlet to parse XML in your the Linux terminal.md, translated/tech/20210713 Use XMLStarlet to parse XML in your the Linux terminal.md
@zEpoch
https://linux.cn/article-13627-1.html
=> PRF&PUB:20210713 use xml starlet to parse xml in your the linux terminal

published/20210129 Machine learning made easy with Python.md
@tanloong
https://linux.cn/article-13628-1.html
=> PRF&PUB:published/20210129 Machine learning made easy with Python.md

published/20210719 Run Python applications in virtual environments.md
@geekpi
https://linux.cn/article-13631-1.html
=> PRF&PUB:published/20210719 Run Python applications in virtual environments.md

published/20210720 Run a Linux virtual machine in Podman.md, translated/tech/20210720 Run a Linux virtual machine in Podman.md
@geekpi
https://linux.cn/article-13635-1.html
=> PRF&PUB:20210720 run a linux virtual machine in podman

published/20210725 How to Install VLC on Fedora Linux.md
@geekpi
https://linux.cn/article-13637-1.html
=> PRF&PUB:published/20210725 How to Install VLC on Fedora Linux.md

published/20210720 Meet Clapper- A Sleek Looking Linux Video Player for Minimalists.md
@geekpi
@turbokernel
https://linux.cn/article-13638-1.html
=> PUB:published/20210720 Meet Clapper- A Sleek Looking Linux Video Player for Minimalists.md

published/20210625 Windows 11 Makes Your Hardware Obsolete, Use Linux Instead.md, translated/news/20210625 Windows 11 Makes Your Hardware Obsolete, Use Linux Instead.md
@zd200572
https://linux.cn/article-13640-1.html
=> PRF&PUB:20210625 windows 11 makes your hardware obsolete, use linux instead

published/20210720 Install Shutter in Fedora 34 and Above.md, translated/tech/20210720 Install Shutter in Fedora 34 and Above.md
@geekpi
https://linux.cn/article-13641-1.html
=> PRF&PUB:20210720 install shutter in fedora 34 and above

published/20210726 How to use cron on Linux.md
@perfiffer
@turbokernel
https://linux.cn/article-13644-1.html
=> PUB:published/20210726 How to use cron on Linux.md

published/20210720 How to Upgrade to Debian 11 from Debian 10.md, translated/tech/20210720 How to Upgrade to Debian 11 from Debian 10.md
@geekpi
https://linux.cn/article-13647-1.html
=> PRF&PUB:20210720 how to upgrade to debian 11 from debian 10

published/20210525 Pen testing with Linux security tools.md, translated/tech/20210525 Pen testing with Linux security tools.md
@MjSeven
https://linux.cn/article-13650-1.html
=> PRF&PUB:20210525 pen testing with linux security tools

sources/talk/20210804 Firefox Lost Almost 50 million Users- Here-s Why It is Concerning.md, translated/talk/20210804 Firefox Lost Almost 50 million Users- Here-s Why It is Concerning.md
=> 提交译文[talk]: Firefox Lost Almost 50 million Users

published/20210727 How to Change Lock and Login Screen Wallpaper in elementary OS.md
@geekpi
https://linux.cn/article-13655-1.html
=> PRF&PUB:published/20210727 How to Change Lock and Login Screen Wallpaper in elementary OS.md

published/20210727 Check used disk space on Linux with du.md
@geekpi
https://linux.cn/article-13656-1.html
=> PUB:published/20210727 Check used disk space on Linux with du.md

published/20210803 How to Install Google Chrome on Linux Mint -Beginners Tip.md
@geekpi
https://linux.cn/article-13659-1.html
=> PRF&PUB:published/20210803 How to Install Google Chrome on Linux Mint -Beginners Tip.md

published/20210801 Use the Linux terminal to see what files are on your computer.md
@piaoshi
https://linux.cn/article-13669-1.html
=> PRF&PUB:published/20210801 Use the Linux terminal to see what files are on your computer.md

published/20210811 The Wait is Over- elementary OS 6 ‘Odin- is Finally Here With Exciting Changes.md
@imgradeone
https://linux.cn/article-13670-1.html
=> PRF&PUB:published/20210811 The Wait is Over- elementary OS 6 ‘Odin- is Finally Here With Exciting Changes.md

published/20210725 Top 7 Linux Laptops You Can Buy in 2021.md
@wxy
https://linux.cn/article-13672-1.html
=> PUB:published/20210725 Top 7 Linux Laptops You Can Buy in 2021.md

published/20210730 4 cool new projects to try in Copr from July 2021.md
@geekpi
https://linux.cn/article-13673-1.html
=> PRF&PUB:published/20210730 4 cool new projects to try in Copr from July 2021.md

published/20210803 Use the Linux terminal to navigate throughout your computer.md
@piaoshi
https://linux.cn/article-13674-1.html
=> PRF&PUB:published/20210803 Use the Linux terminal to navigate throughout your computer.md

published/20210811 Top 11 New Features in elementary OS 6 Linux Release.md
@wxy
https://linux.cn/article-13678-1.html
=> PUB:published/20210811 Top 11 New Features in elementary OS 6 Linux Release.md

published/20210803 Mount Microsoft OneDrive in Linux With OneDriver GUI Tool.md
@geekpi
https://linux.cn/article-13681-1.html
=> PRF&PUB:20210803 mount microsoft one drive in linux with one driver g UI tool

published/20210814 What is SteamOS- Everything Important You Need to Know About This -Gaming Distribution.md, translated/tech/20210814 What is SteamOS- Everything Important You Need to Know About This -Gaming Distribution.md
@imgradeone
https://linux.cn/article-13688-1.html
=> PRF&PUB:20210814 what is steam os  everything important you need to know about this  gaming distribution

published/20210812 A Java developer-s guide to Quarkus.md
@geekpi
https://linux.cn/article-13690-1.html
=> PRF&PUB:published/20210812 A Java developer-s guide to Quarkus.md

published/20210807 How to Install Java on Fedora Linux.md
@geekpi
https://linux.cn/article-13694-1.html
=> PRF&PUB:published/20210807 How to Install Java on Fedora Linux.md

published/20210815 7 New Features in the Newly Released Debian 11 ‘Bullseye- Linux Distro.md
@wxy
https://linux.cn/article-13695-1.html
=> PUB:published/20210815 7 New Features in the Newly Released Debian 11 ‘Bullseye- Linux Distro.md

published/20210802 Use OpenCV on Fedora Linux - part 1.md, translated/tech/20210802 Use OpenCV on Fedora Linux - part 1.md
@geekpi
https://linux.cn/article-13698-1.html
=> PRF&PUB:20210802 use open cv on fedora linux   part 1

published/20210813 Parse command options in Java with commons-cli.md, translated/tech/20210813 Parse command options in Java with commons-cli.md
@unigeorge
https://linux.cn/article-13699-1.html
=> PRF&PUB:20210813 parse command options in java with commons cli

published/20210806 Change your Linux Desktop Wallpaper Every Hour -Here-s How.md, translated/tech/20210806 Change your Linux Desktop Wallpaper Every Hour -Here-s How.md
@geekpi
https://linux.cn/article-13701-1.html
=> PRF&PUB:20210806 change your linux desktop wallpaper every hour  here s how

published/20210804 Install OpenVPN on your Linux PC.md, translated/tech/20210804 Install OpenVPN on your Linux PC.md
@perfiffer
https://linux.cn/article-13702-1.html
=> PRF&PUB:20210804 install open vpn on your linux pc

sources/tech/20200107 5 ways to improve your Bash scripts.md
fisherue asks to translate this page on 2021/8/20
申请翻译此文
=> Update 20200107 5 ways to improve your Bash scripts.md

published/20210805 Configure your OpenVPN server on Linux.md
@geekpi
@turbokernel
https://linux.cn/article-13707-1.html
=> PUB:published/20210805 Configure your OpenVPN server on Linux.md

published/20210713 Use VS Code to develop in containers.md, translated/tech/20210713 Use VS Code to develop in containers.md
@wxy
https://linux.cn/article-13708-1.html
=> PRF&PUB:20210713 use vs code to develop in containers

published/20210822 Linux Phones- Here are Your Options.md
@wxy
https://linux.cn/article-13711-1.html
=> PUB:published/20210822 Linux Phones- Here are Your Options.md

published/20210811 Monitor your Linux system in your terminal with procps-ng.md, translated/tech/20210811 Monitor your Linux system in your terminal with procps-ng.md
@geekpi
https://linux.cn/article-13713-1.html
=> PRF&PUB:20210811 monitor your linux system in your terminal with procps ng

published/20210806 Access OpenVPN from a client computer.md, translated/tech/20210806 Access OpenVPN from a client computer.md
@perfiffer
https://linux.cn/article-13714-1.html
=> PRF&PUB:20210806 access open vpn from a client computer

sources/tech/20210827 How to Easily Install Debian Linux.md
=> Update 20210827 How to Easily Install Debian Linux.md

published/20210707 How to Know if Your System Uses MBR or GPT Partitioning -on Windows and Linux.md
@alim0x
https://linux.cn/article-13727-1.html
=> PRF&PUB:published/20210707 How to Know if Your System Uses MBR or GPT Partitioning -on Windows and Linux.md

published/20210819 Check free disk space in Linux with ncdu.md
@geekpi
https://linux.cn/article-13729-1.html
=> PRF&PUB:published/20210819 Check free disk space in Linux with ncdu.md

sources/tech/20210728 Kernel tracing with trace-cmd.md
File name: 20210728 Kernel tracing with trace-cmd.md
=> Apply translation (mengxinayan)

published/20210823 Access your iPhone on Linux with this open source tool.md, translated/tech/20210823 Access your iPhone on Linux with this open source tool.md
@geekpi
https://linux.cn/article-13737-1.html
=> PRF&PUB:20210823 access your i phone on linux with this open source tool

published/20210826 Elementary OS 6 Odin Review - Late Arrival but a Solid One.md, translated/tech/20210826 Elementary OS 6 Odin Review - Late Arrival but a Solid One.md
@imgradeone
https://linux.cn/article-13739-1.html
=> PRF&PUB:20210826 elementary os 6 odin review   late arrival but a solid one

published/20210819 Debian vs Ubuntu- What-s the Difference- Which One Should You Use.md, translated/tech/20210819 Debian vs Ubuntu- What-s the Difference- Which One Should You Use.md
@perfiffer
https://linux.cn/article-13746-1.html
=> PRF&PUB:20210819 debian vs ubuntu  what s the difference  which one should you use

published/20210821 10 Things to Do After Installing elementary OS 6 -Odin.md, translated/tech/20210821 10 Things to Do After Installing elementary OS 6 -Odin.md
@anine09
@anine09
本文首发：https://linux.cn/article-13749-1.html
您的 LCTT 专页：https://linux.cn/lctt/anine09
=> PRF&PUB:20210821 10 things to do after installing elementary os 6  odin

published/20210831 Zulip- An Interesting Open-Source Alternative to Slack.md, translated/tech/20210831 Zulip- An Interesting Open-Source Alternative to Slack.md
@geekpi
https://linux.cn/article-13750-1.html
=> PRF&PUB:20210831 zulip  an interesting open source alternative to slack

published/20210727 Analyze the Linux kernel with ftrace.md, translated/tech/20210727 Analyze the Linux kernel with ftrace.md
@mengxinayan
https://linux.cn/article-13752-1.html
=> PRF&PUB:20210727 analyze the linux kernel with ftrace

published/20210820 How to Download Audio Only Using youtube-dl.md
@geekpi
https://linux.cn/article-13753-1.html
=> PRF&PUB:published/20210820 How to Download Audio Only Using youtube-dl.md

published/20210719 Apps for daily needs part 2- office suites.md
@wxy
https://linux.cn/article-13755-1.html
=> PUB:published/20210719 Apps for daily needs part 2- office suites.md

published/20210829 Position text on your screen in Linux with ncurses.md, translated/tech/20210829 Position text on your screen in Linux with ncurses.md
@perfiffer
https://linux.cn/article-13756-1.html
=> PRF&PUB:20210829 position text on your screen in linux with ncurses

published/20210804 Apps for daily needs part 3- image editors.md
@wxy
https://linux.cn/article-13761-1.html
=> PUB:published/20210804 Apps for daily needs part 3- image editors.md

published/20210907 OpenWrt 21.02 Arrives With Linux Kernel 5.4 - WPA3 Support.md
@wxy
https://linux.cn/article-13763-1.html
=> PUB:published/20210907 OpenWrt 21.02 Arrives With Linux Kernel 5.4 - WPA3 Support.md

published/20210831 What is a container image.md, translated/tech/20210831 What is a container image.md
@geekpi
https://linux.cn/article-13766-1.html
=> PRF&PUB:20210831 what is a container image

sources/tech/20200121 13 of the best React JavaScript frameworks.md
@Frank Zhang 申请翻译文章30天，因超时而撤销.
=> 超期回收: sources/tech/20200121 13 of the best React JavaScript frameworks.md

published/20210904 How to Install Dropbox on Ubuntu Linux.md
@geekpi
https://linux.cn/article-13773-1.html
=> PRF&PUB:published/20210904 How to Install Dropbox on Ubuntu Linux.md

published/20210228 What is GNU-Linux Copypasta.md
@wxy
https://linux.cn/article-13776-1.html
=> PUB:published/20210228 What is GNU-Linux Copypasta.md

published/20210907 Run Web Applications in Linux Using Tangram Browser.md, translated/tech/20210907 Run Web Applications in Linux Using Tangram Browser.md
@anine09
https://linux.cn/article-13777-1.html
=> PRF&PUB:20210907 run web applications in linux using tangram browser

published/20210906 Resize an image from the Linux terminal.md
@geekpi
https://linux.cn/article-13779-1.html
=> PRF&PUB:published/20210906 Resize an image from the Linux terminal.md

published/20210911 Here-s Why Firefox is Seeing a Continuous Decline for Last 12 Years.md
@wxy
https://linux.cn/article-13780-1.html
=> PUB:published/20210911 Here-s Why Firefox is Seeing a Continuous Decline for Last 12 Years.md

published/20210909 Adobe Kills Brackets Code Editor - Suggests Using Visual Studio Code.md
@wxy
https://linux.cn/article-13782-1.html
=> PUB:published/20210909 Adobe Kills Brackets Code Editor - Suggests Using Visual Studio Code.md

published/20210906 Getting the Top Indicator Panel Back in GNOME.md
@imgradeone
https://linux.cn/article-13785-1.html
=> PRF&PUB:published/20210906 Getting the Top Indicator Panel Back in GNOME.md

published/20210910 Quadratic algorithms are slow (and hashmaps are fast).md, translated/tech/20210910 Quadratic algorithms are slow (and hashmaps are fast).md
@unigeorge
https://linux.cn/article-13786-1.html
=> PRF&PUB:20210910 quadratic algorithms are slow (and hashmaps are fast)

published/20210908 How to Run Java Programs in Ubuntu.md, translated/tech/20210908 How to Run Java Programs in Ubuntu.md
@geekpi
https://linux.cn/article-13790-1.html
=> PRF&PUB:20210908 how to run java programs in ubuntu

sources/tech/20210915 Raspberry Pi Zero vs Zero W- What-s the Difference.md
=> Update 20210915 Raspberry Pi Zero vs Zero W- What-s the Difference.md

published/20210902 4 Linux technologies fundamental to containers.md
@wxy
@turbokernel
https://linux.cn/article-13792-1.html
=> PUB:published/20210902 4 Linux technologies fundamental to containers.md

published/20210907 Use lspci on Linux to see your hardware.md
@unigeorge
@turbokernel
https://linux.cn/article-13793-1.html
=> PUB:published/20210907 Use lspci on Linux to see your hardware.md

published/20210908 Debug a web page error from the command line.md
@geekpi
https://linux.cn/article-13795-1.html
=> PRF&PUB:published/20210908 Debug a web page error from the command line.md

published/20210916 Kali Linux 2021.3 Brings in Kali Live VM Support, New Tools, and Other Improvements.md
@wxy
https://linux.cn/article-13798-1.html
=> PUB:20210916 kali linux 2021.3 brings in kali live vm support, new tools, and other improvements

published/20210915 Screen Recording in Linux With OBS and Wayland.md
@geekpi
https://linux.cn/article-13802-1.html
=> PRF&PUB:published/20210915 Screen Recording in Linux With OBS and Wayland.md

published/20210915 How to check for update info and changelogs with rpm-ostree db.md
@geekpi
https://linux.cn/article-13803-1.html
=> PRF&PUB:published/20210915 How to check for update info and changelogs with rpm-ostree db.md

sources/tech/20210917 Start using YAML now.md
Reverts LCTT/TranslateProject#23310
=> Revert "APL:sources/tech/20210917 Start using YAML now.md"

published/20210913 Replace smart quotes with the Linux sed command.md
@geekpi
https://linux.cn/article-13806-1.html
=> PRF&PUB:published/20210913 Replace smart quotes with the Linux sed command.md

published/20210908 Apps for daily needs part 5- video editors.md
@wxy
https://linux.cn/article-13808-1.html
=> PUB:published/20210908 Apps for daily needs part 5- video editors.md

published/20210916 Watch commands and tasks with the Linux watch command.md
@geekpi
https://linux.cn/article-13810-1.html
=> PRF&PUB:published/20210916 Watch commands and tasks with the Linux watch command.md

published/20210918 How to Install Ubuntu Desktop on Raspberry Pi 4.md
@wxy
@turbokernel
https://linux.cn/article-13817-1.html
=> PUB:published/20210918 How to Install Ubuntu Desktop on Raspberry Pi 4.md

published/20210920 Use this Linux command-line tool to learn more about your NVMe drives.md
@geekpi
@turbokernel
https://linux.cn/article-13822-1.html
=> PUB:published/20210920 Use this Linux command-line tool to learn more about your NVMe drives.md

published/20210921 Run containers on your Mac with Lima.md
@geekpi
https://linux.cn/article-13824-1.html
=> PRF&PUB:published/20210921 Run containers on your Mac with Lima.md

published/20210424 Can We Recommend Linux for Gaming in 2021.md, translated/talk/20210424 Can We Recommend Linux for Gaming in 2021.md
@perfiffer
https://linux.cn/article-13826-1.html
=> PRF&PUB:20210424 can we recommend linux for gaming in 2021

published/20210920 Use Vagrant to test your scripts on different operating systems.md, translated/tech/20210920 Use Vagrant to test your scripts on different operating systems.md
@geekpi
https://linux.cn/article-13829-1.html
=> PRF&PUB:20210920 use vagrant to test your scripts on different operating systems

published/20210905 Neither Windows, nor Linux- Shrine is ‘God-s Operating System.md, translated/tech/20210905 Neither Windows, nor Linux- Shrine is ‘God-s Operating System.md
@wxy
https://linux.cn/article-13831-1.html
=> PRF&PUB:20210905 neither windows, nor linux  shrine is ‘god s operating system

published/20210924 An open source alternative to Microsoft Exchange.md
@geekpi
https://linux.cn/article-13833-1.html
=> PRF&PUB:published/20210924 An open source alternative to Microsoft Exchange.md

published/20210929 Manage CentOS Stream with Foreman.md
@wxy
https://linux.cn/article-13837-1.html
=> PUB:published/20210929 Manage CentOS Stream with Foreman.md

published/20210930 Make YAML as easy as it looks.md
@wxy
https://linux.cn/article-13842-1.html
=> PUB:published/20210930 Make YAML as easy as it looks.md

published/20210702 Creating a PKGBUILD to Make Packages for Arch Linux.md
@wxy
https://linux.cn/article-13843-1.html
=> PUB:published/20210702 Creating a PKGBUILD to Make Packages for Arch Linux.md

published/20210721 Run GitHub Actions on Fedora CoreOS.md, translated/tech/20210721 Run GitHub Actions on Fedora CoreOS.md
@wxy
https://linux.cn/article-13846-1.html
=> PRF&PUB:20210721 run GitHub actions on fedora core os

published/20210104 Learn Fortran by writing a -guess the number- game.md
@unigeorge
https://linux.cn/article-13849-1.html
=> PRF&PUB:published/20210104 Learn Fortran by writing a -guess the number- game.md

published/20211001 The Official Raspberry Pi 4 Case Sucks- Here-s What You Can do to Reduce the Overheating.md
@wxy
https://linux.cn/article-13851-1.html
=> PUB:published/20211001 The Official Raspberry Pi 4 Case Sucks- Here-s What You Can do to Reduce the Overheating.md

published/20210728 Kernel tracing with trace-cmd.md, translated/tech/20210728 Kernel tracing with trace-cmd.md
@mengxinayan
https://linux.cn/article-13852-1.html
=> PRF&PUB:20210728 kernel tracing with trace cmd

published/20211001 8 reasons why I learned Core Java.md
@wxy
https://linux.cn/article-13855-1.html
=> PUB:published/20211001 8 reasons why I learned Core Java.md

published/20211029 Microsoft Edge Stable Build is Now Available to Download for Linux.md
@wxy
https://linux.cn/article-13935-1.html
=> PUB:published/20211029 Microsoft Edge Stable Build is Now Available to Download for Linux.md

published/20211020 How to Install Rust and Cargo on Ubuntu and Other Linux Distributions.md
@perfiffer
https://linux.cn/article-13938-1.html
=> PRF&PUB:published/20211020 How to Install Rust and Cargo on Ubuntu and Other Linux Distributions.md

published/20211029 Print a Halloween greeting with ASCII art on Linux.md
@wxy
https://linux.cn/article-13939-1.html
=> PUB:published/20211029 Print a Halloween greeting with ASCII art on Linux.md

published/20211031 How to kill a zombie process on Linux.md
@wxy
https://linux.cn/article-13941-1.html
=> PUB:published/20211031 How to kill a zombie process on Linux.md

published/20211017 Visual Studio Code or Atom- Which Code Editor Should You Use.md
@wxy
https://linux.cn/article-13944-1.html
=> PUB:published/20211017 Visual Studio Code or Atom- Which Code Editor Should You Use.md

published/20211029 A simple CSS trick for dark mode.md
@geekpi
https://linux.cn/article-13950-1.html
=> PRF&PUB:published/20211029 A simple CSS trick for dark mode.md

sources/tech/20211021 What you need to know about Kubernetes NetworkPolicy.md
sources/tech/20211021 What you need to know about Kubernetes NetworkPolicy.md
=> 选题[tech]: 20211021 What you need to know about Kubernetes NetworkPolicy

published/20211101 How I dynamically generate Jekyll config files.md
@geekpi
https://linux.cn/article-13957-1.html
=> PRF&PUB:published/20211101 How I dynamically generate Jekyll config files.md

published/20211104 After Moving From FreeBSD to Void Linux, Project Trident Finally Discontinues.md, translated/news/20211104 After Moving From FreeBSD to Void Linux, Project Trident Finally Discontinues.md
@zd200572
https://linux.cn/article-13960-1.html
=> PRF&PUB:20211104 after moving from free bsd to void linux, project trident finally discontinues

published/20211029 Only 4 MB- How to Fix USB ‘Destroyed- by Etcher and Rufus After Creating Live Linux USB.md
@geekpi
https://linux.cn/article-13961-1.html
=> PRF&PUB:published/20211029 Only 4 MB- How to Fix USB ‘Destroyed- by Etcher and Rufus After Creating Live Linux USB.md

published/20211107 What is the Release Schedule for Linux Kernel- How Long a Linux Kernel is Supported.md
@wxy
https://linux.cn/article-13963-1.html
=> PUB:published/20211107 What is the Release Schedule for Linux Kernel- How Long a Linux Kernel is Supported.md

published/20211108 openSUSE Leap vs Tumbleweed- What-s the Difference.md
@wxy
https://linux.cn/article-13966-1.html
=> PUB:published/20211108 openSUSE Leap vs Tumbleweed- What-s the Difference.md

published/20211110 exa- A Modern Replacement for the ls Command.md
@wxy
https://linux.cn/article-13972-1.html
=> PUB:published/20211110 exa- A Modern Replacement for the ls Command.md

sources/talk/20211103 4 tips to becoming a technical writer with open source contributions.md
…e contributions.md
Apply for translation
=> Apply for translation: 《4 tips to becoming a technical writer with open sourc…》

published/20211103 Turn any website into a Linux desktop app with open source tools.md
@geekpi
https://linux.cn/article-13975-1.html
=> PRF&PUB:published/20211103 Turn any website into a Linux desktop app with open source tools.md

published/20211101 Use the Linux cowsay command for a colorful holiday greeting.md
@unigeorge
https://linux.cn/article-13977-1.html
=> PRF&PUB:published/20211101 Use the Linux cowsay command for a colorful holiday greeting.md

published/20211110 Canonical Makes it Easy to Run a Linux VM on Apple M1.md
@wxy
https://linux.cn/article-13978-1.html
=> PUB:published/20211110 Canonical Makes it Easy to Run a Linux VM on Apple M1.md

published/20211111 Forza Horizon 5 on Linux- There-s a Good Chance That You Can Play it Already.md
@wxy
https://linux.cn/article-13980-1.html
=> PUB:published/20211111 Forza Horizon 5 on Linux- There-s a Good Chance That You Can Play it Already.md

published/20211104 How to update a Linux symlink.md
@geekpi
https://linux.cn/article-13981-1.html
=> PRF&PUB:published/20211104 How to update a Linux symlink.md

published/20210816 Parse command-line arguments with argparse in Python.md
@MjSeven
https://linux.cn/article-13986-1.html
=> PRF&PUB:published/20210816 Parse command-line arguments with argparse in Python.md

published/20211112 8 New Features - Improvements to Expect in GIMP 3.0 Release.md
@wxy
https://linux.cn/article-13987-1.html
=> PUB:published/20211112 8 New Features - Improvements to Expect in GIMP 3.0 Release.md

published/20211108 How I build command-line apps in JavaScript.md
@geekpi
https://linux.cn/article-13989-1.html
=> PUB:published/20211108 How I build command-line apps in JavaScript.md

published/20211111 7 Linux commands to use just for fun.md
@wxy
https://linux.cn/article-13990-1.html
=> PUB:published/20211111 7 Linux commands to use just for fun.md

published/20211109 How to package your Python code.md
@geekpi
https://linux.cn/article-13993-1.html
=> PRF&PUB:published/20211109 How to package your Python code.md

published/20210604 Set and use environment variables in FreeDOS.md, translated/tech/20210604 Set and use environment variables in FreeDOS.md
@robsean
https://linux.cn/article-13995-1.html
=> PRF&PUB:20210604 set and use environment variables in free dos

published/20211118 Raspberry Pi 3 vs 4- Which One Should You Get.md
@wxy
https://linux.cn/article-13997-1.html
=> PUB:published/20211118 Raspberry Pi 3 vs 4- Which One Should You Get.md

published/20211117 Create Windows, macOS, and Linux Virtual Machines Easily With QEMU-based Quickgui.md
@wxy
https://linux.cn/article-13998-1.html
=> PUB:published/20211117 Create Windows, macOS, and Linux Virtual Machines Easily With QEMU-based Quickgui.md

published/20211110 Transfer files between your phone and Linux with this open source tool.md
@geekpi
https://linux.cn/article-13999-1.html
=> PRF&PUB:published/20211110 Transfer files between your phone and Linux with this open source tool.md

published/20211120 vifm- A Terminal File Browser for Hardcore Vim Lovers.md
@wxy
https://linux.cn/article-14001-1.html
=> PUB:published/20211120 vifm- A Terminal File Browser for Hardcore Vim Lovers.md

published/20211113 How to Switch to Dark Mode in Fedora Linux -Beginner-s Tip.md
@geekpi
https://linux.cn/article-14002-1.html
=> PRF&PUB:published/20211113 How to Switch to Dark Mode in Fedora Linux -Beginner-s Tip.md

published/20211021 What you need to know about Kubernetes NetworkPolicy.md, translated/tech/20211021 What you need to know about Kubernetes NetworkPolicy.md
@perfiffer 恭喜升级三星~🌟🌟🌟
https://linux.cn/article-14005-1.html
=> PRF&PUB:20211021 what you need to know about kubernetes network policy

published/20211111 How to Mount Bitlocker Encrypted Windows Partition in Linux.md
@geekpi
https://linux.cn/article-14008-1.html
=> PRF&PUB:published/20211111 How to Mount Bitlocker Encrypted Windows Partition in Linux.md

published/20211123 KDE Plasma 5.24 To Add a GNOME-Style Overview and Will Prevent You From Uninstalling Plasma.md
@wxy
https://linux.cn/article-14015-1.html
=> PUB:published/20211123 KDE Plasma 5.24 To Add a GNOME-Style Overview and Will Prevent You From Uninstalling Plasma.md

published/20211124 Amazon-s Own Linux Distribution is Now Completely Based on Fedora.md
@wxy
https://linux.cn/article-14019-1.html
=> PUB:published/20211124 Amazon-s Own Linux Distribution is Now Completely Based on Fedora.md

published/20211125 Endless OS 4.0 is a Long-Term Support Version with Usability Improvements.md
@wxy
https://linux.cn/article-14024-1.html
=> PUB:published/20211125 Endless OS 4.0 is a Long-Term Support Version with Usability Improvements.md

published/20211120 How to Install Discord on Fedora Linux.md
@geekpi
https://linux.cn/article-14025-1.html
=> PRF&PUB:published/20211120 How to Install Discord on Fedora Linux.md

published/20211125 Tips for formatting when printing to console from C.md
@wxy
https://linux.cn/article-14027-1.html
=> PUB:published/20211125 Tips for formatting when printing to console from C.md

published/20211119 How to Install Brave Browser on Fedora, Red Hat - CentOS.md
@geekpi
https://linux.cn/article-14028-1.html
=> PRF&PUB:published/20211119 How to Install Brave Browser on Fedora, Red Hat - CentOS.md

published/20211129 Anyone can compile open source code in these three simple steps.md
@wxy
https://linux.cn/article-14033-1.html
=> PUB:published/20211129 Anyone can compile open source code in these three simple steps.md

published/20211124 Manage Flatpak Permissions Graphically With Flatseal.md
@geekpi
https://linux.cn/article-14034-1.html
=> PRF&PUB:published/20211124 Manage Flatpak Permissions Graphically With Flatseal.md

published/20211130 Collaborate on a file using Linux diff and patch.md
@wxy
https://linux.cn/article-14037-1.html
=> PUB:published/20211130 Collaborate on a file using Linux diff and patch.md

published/20211121 Google Chrome vs Chromium- What-s the difference.md
@wxy
https://linux.cn/article-14041-1.html
=> PUB:published/20211121 Google Chrome vs Chromium- What-s the difference.md

published/20211202 Vivaldi 5.0 Brings Two-Level Tabs to Android - Adds New Features for Desktop.md
@wxy
https://linux.cn/article-14044-1.html
=> PUB:published/20211202 Vivaldi 5.0 Brings Two-Level Tabs to Android - Adds New Features for Desktop.md

published/20211128 Install apps on Linux with Flatpak.md
@geekpi
https://linux.cn/article-14045-1.html
=> PRF&PUB:published/20211128 Install apps on Linux with Flatpak.md

published/20211114 5 De-Googled Android-based Operating Systems to Free Your Smartphone from Google and other Big Tech.md
@wxy
https://linux.cn/article-14047-1.html
=> PUB:published/20211114 5 De-Googled Android-based Operating Systems to Free Your Smartphone from Google and other Big Tech.md

published/20211129 How to Install Apache Cassandra on Ubuntu and Other Linux.md
@geekpi
https://linux.cn/article-14048-1.html
=> PRF&PUB:published/20211129 How to Install Apache Cassandra on Ubuntu and Other Linux.md

published/20210929 How to Install and Setup Flutter Development on Ubuntu and Other Linux.md
@wxy
https://linux.cn/article-14054-1.html
=> PUB:published/20210929 How to Install and Setup Flutter Development on Ubuntu and Other Linux.md

published/20211206 Upcoming CutefishOS Could Topple Deepin as the Most Beautiful Linux Distro.md
@wxy
https://linux.cn/article-14058-1.html
=> PUB:published/20211206 Upcoming CutefishOS Could Topple Deepin as the Most Beautiful Linux Distro.md

published/20211206 19 Absolute Simple Things About Linux Terminal Every Ubuntu User Should Know.md
@wxy
https://linux.cn/article-14064-1.html
=> PUB:published/20211206 19 Absolute Simple Things About Linux Terminal Every Ubuntu User Should Know.md

translated/tech/20210922 Add storage with LVM.md
=> translated by perfiffer

published/20210902 Best Web Browsers for Ubuntu and Other Linux Distributions.md
@wxy
https://linux.cn/article-14075-1.html
=> PUB:published/20210902 Best Web Browsers for Ubuntu and Other Linux Distributions.md

published/20211207 Gaphor- Open Source Graphical Modeling Tool.md
@geekpi
https://linux.cn/article-14079-1.html
=> PRF&PUB:published/20211207 Gaphor- Open Source Graphical Modeling Tool.md

published/20211215 Pop-_OS 21.10 Introduces a New Application Library, GNOME 40, and a Refresh Install Option.md
@wxy
https://linux.cn/article-14083-1.html
=> PUB:published/20211215 Pop-_OS 21.10 Introduces a New Application Library, GNOME 40, and a Refresh Install Option.md

published/20210915 A guide to web scraping in Python using Beautiful Soup.md
@MjSeven
https://linux.cn/article-14086-1.html
=> PRF&PUB:published/20210915 A guide to web scraping in Python using Beautiful Soup.md

published/20211210 Reveal your source code with Jinja2 and Git.md
@geekpi
https://linux.cn/article-14091-1.html
=> PUB:published/20211210 Reveal your source code with Jinja2 and Git.md

published/20211207 Learn more about distributed databases with ShardingSphere.md
@geekpi
https://linux.cn/article-14095-1.html
=> PRF&PUB:published/20211207 Learn more about distributed databases with ShardingSphere.md

published/20211213 My favorite Linux commands for optimizing web images.md
@geekpi
https://linux.cn/article-14096-1.html
=> PRF&PUB:published/20211213 My favorite Linux commands for optimizing web images.md

published/20210903 Print files from your Linux terminal.md
@geekpi
https://linux.cn/article-14099-1.html
=> PRF&PUB:published/20210903 Print files from your Linux terminal.md

published/20211215 Deploy Mycroft AI voice assistant on Raspberry Pi using Ansible.md, translated/tech/20211215 Deploy Mycroft AI voice assistant on Raspberry Pi using Ansible.md
@jrglinux
https://linux.cn/article-14102-1.html
=> PRF&PUB:20211215 deploy mycroft ai voice assistant on raspberry pi using ansible

published/20211220 12 Biggest Linux Stories of the Year 2021.md
@wxy
https://linux.cn/article-14103-1.html
=> PUB:published/20211220 12 Biggest Linux Stories of the Year 2021.md

published/20211221 Great News- 80- of Steam-s Top 100 Games Now Run on Linux.md
@wxy
https://linux.cn/article-14105-1.html
=> PUB:published/20211221 Great News- 80- of Steam-s Top 100 Games Now Run on Linux.md

published/20200315 Getting started with shaders- signed distance functions.md
@Starryi
https://linux.cn/article-14107-1.html
=> PRF&PUB:published/20200315 Getting started with shaders- signed distance functions.md

published/20211223 7 Best Rolling Release Linux Distributions for People Who Want the Latest and Greatest of Kernel and Software.md
@wxy
https://linux.cn/article-14112-1.html
=> PUB:published/20211223 7 Best Rolling Release Linux Distributions for People Who Want the Latest and Greatest of Kernel and Software.md

published/20211030 7 ways anyone can contribute to Open Practice Library.md
@wxy
https://linux.cn/article-14117-1.html
=> PUB:published/20211030 7 ways anyone can contribute to Open Practice Library.md

published/20211226 7 Reasons Why I Use Pop-_OS Linux Distro as My Daily Driver.md
@wxy
https://linux.cn/article-14118-1.html
=> PUB:published/20211226 7 Reasons Why I Use Pop-_OS Linux Distro as My Daily Driver.md

sources/tech/20211211 Open source digital painting with Krita.md
This reverts commit fce3dc23b7b311e7e1c8cb47ec07cdc031c19b32.
=> Revert "APL"

published/20211226 5 Things elementary OS 6 Should Improve for a Better Linux Desktop Experience.md
@wxy
https://linux.cn/article-14120-1.html
=> PUB:published/20211226 5 Things elementary OS 6 Should Improve for a Better Linux Desktop Experience.md

published/20211221 AppImage Pool is an App Store to Help You Find - Manage AppImages.md
@geekpi
https://linux.cn/article-14124-1.html
=> PRF&PUB:published/20211221 AppImage Pool is an App Store to Help You Find - Manage AppImages.md

published/20210927 Bash Shell Scripting for beginners (Part 1).md
@unigeorge
https://linux.cn/article-14131-1.html
=> PRF&PUB:published/20210927 Bash Shell Scripting for beginners (Part 1).md

published/20211230 Maui Shell is Here, Ushering in a New Era of Desktop Linux.md
@imgradeone 新年好！
https://linux.cn/article-14136-1.html
=> PRF&PUB:published/20211230 Maui Shell is Here, Ushering in a New Era of Desktop Linux.md

published/20211229 Folder or Directory- Here-s Why Folders are Called Directories in Linux.md
@wxy
https://linux.cn/article-14137-1.html
=> PUB:published/20211229 Folder or Directory- Here-s Why Folders are Called Directories in Linux.md

published/20211228 7 Linux Distros to Look Forward to in 2022.md, translated/news/20211228 7 Linux Distros to Look Forward to in 2022.md
@imgradeone
https://linux.cn/article-14143-1.html
=> PRF&PUB:20211228 7 linux distros to look forward to in 2022

published/20210901 Ubuntu Server vs Desktop- What-s the Difference.md
@wxy
https://linux.cn/article-14146-1.html
=> PUB:published/20210901 Ubuntu Server vs Desktop- What-s the Difference.md

published/20211226 9 open source alternatives to try in 2022.md
@geekpi
https://linux.cn/article-14148-1.html
=> PRF&PUB:published/20211226 9 open source alternatives to try in 2022.md

published/20220104 Deepin Desktop With Ubuntu- UbuntuDDE Remix 21.10 is Here.md
@wxy
https://linux.cn/article-14149-1.html
=> PUB:published/20220104 Deepin Desktop With Ubuntu- UbuntuDDE Remix 21.10 is Here.md

published/20220104 Pinta 2.0 is a Major Upgrade With GTK 3 Port and Improved HiDPI Support.md
@wxy
https://linux.cn/article-14150-1.html
=> PUB:published/20220104 Pinta 2.0 is a Major Upgrade With GTK 3 Port and Improved HiDPI Support.md

sources/tech/20211027 Bash Shell Scripting for beginners (Part 2).md
sources/tech/20211027 Bash Shell Scripting for beginners (Part 2).md
@unigeorge
=> 选题[tech]: 20211027 Bash Shell Scripting for beginners (Part 2)

sources/tech/20211206 Bash Shell Scripting for beginners (Part 3).md
sources/tech/20211206 Bash Shell Scripting for beginners (Part 3).md
@unigeorge
=> 选题[tech]: 20211206 Bash Shell Scripting for beginners (Part 3)

published/20220104 Intel is Gearing Up to Give a ‘Superpower- to Linux that Windows Users Don-t Have.md
@wxy
https://linux.cn/article-14153-1.html
=> PUB:published/20220104 Intel is Gearing Up to Give a ‘Superpower- to Linux that Windows Users Don-t Have.md

published/20220106 Linux Mint 20.3 -Una- Releases With Cinnamon 5.2, Theme Refresh, and a New Document Manager.md
@wxy
https://linux.cn/article-14155-1.html
=> PUB:published/20220106 Linux Mint 20.3 -Una- Releases With Cinnamon 5.2, Theme Refresh, and a New Document Manager.md

published/20210916 Crunch numbers in Python with NumPy.md
@wxy
https://linux.cn/article-14160-1.html
=> PUB:published/20210916 Crunch numbers in Python with NumPy.md

published/20211201 Edit audio on Linux with Audacity.md
@wxy
https://linux.cn/article-14163-1.html
=> PUB:published/20211201 Edit audio on Linux with Audacity.md

sources/talk/20200421 How underwater Internet of Things will work.md
=> Translating by CN-QUAN

published/20220108 5 Tiny Yet Useful Features I Would Like to See in GNOME in 2022.md
@wxy
https://linux.cn/article-14168-1.html
=> PUB:published/20220108 5 Tiny Yet Useful Features I Would Like to See in GNOME in 2022.md

published/20220112 Modern Alternatives to Some of the Classic Linux Commands.md
@wxy
https://linux.cn/article-14172-1.html
=> P:published/20220112 Modern Alternatives to Some of the Classic Linux Commands.md

published/20210715 Linux for Education- Best Distributions for Kids, Teachers - Schools.md
@wxy
https://linux.cn/article-14174-1.html
=> P:published/20210715 Linux for Education- Best Distributions for Kids, Teachers - Schools.md

published/20220113 Here are the New Features Coming to Ubuntu 22.04 LTS.md
@wxy
https://linux.cn/article-14177-1.html
=> P:published/20220113 Here are the New Features Coming to Ubuntu 22.04 LTS.md

published/20220114 I Tried System76-s New Rust-based COSMIC Desktop.md
@wxy
https://linux.cn/article-14186-1.html
=> P:published/20220114 I Tried System76-s New Rust-based COSMIC Desktop.md

published/20220111 QPrompt is a Free and Open Source Teleprompter for Video Creators.md
@geekpi
https://linux.cn/article-14187-1.html
=> RP:published/20220111 QPrompt is a Free and Open Source Teleprompter for Video Creators.md

published/20211027 Bash Shell Scripting for beginners (Part 2).md, translated/tech/20211027 Bash Shell Scripting for beginners (Part 2).md
@unigeorge
https://linux.cn/article-14198-1.html
=> RP:20211027 bash shell scripting for beginners (part 2)

published/20220111 8 surprising things I learned about Python in 2021.md
@geekpi
https://linux.cn/article-14200-1.html
=> RP:published/20220111 8 surprising things I learned about Python in 2021.md

published/20220107 Try FreeDOS in 2022.md
@geekpi
https://linux.cn/article-14204-1.html
=> RP:published/20220107 Try FreeDOS in 2022.md

published/20220124 Linux Jargon Buster- What are Upstream and Downstream.md
@wxy
https://linux.cn/article-14215-1.html
=> P:published/20220124 Linux Jargon Buster- What are Upstream and Downstream.md

published/20220112 How to build an open source metaverse.md
@wxy
https://linux.cn/article-14218-1.html
=> P:published/20220112 How to build an open source metaverse.md

published/20220123 9 Open Source Add-Ons to Improve Your Mozilla Firefox Experience.md
@wxy
https://linux.cn/article-14223-1.html
=> P:published/20220123 9 Open Source Add-Ons to Improve Your Mozilla Firefox Experience.md

published/20220122 Our favorite Linux commands to use just for fun.md
@geekpi
https://linux.cn/article-14226-1.html
=> RP:published/20220122 Our favorite Linux commands to use just for fun.md

published/20211126 10 holiday gift ideas for open source enthusiasts.md
@wxy
https://linux.cn/article-14227-1.html
=> P:published/20211126 10 holiday gift ideas for open source enthusiasts.md

published/20220126 Jrnl- Your Digital Diary in the Linux Terminal.md
@geekpi
https://linux.cn/article-14229-1.html
=> RP:published/20220126 Jrnl- Your Digital Diary in the Linux Terminal.md

published/20220125 Obsidian is a Notion Alternative for Hardcore Markdown Users for Creating Knowledge Graph of Notes.md
@wxy
https://linux.cn/article-14230-1.html
=> P:published/20220125 Obsidian is a Notion Alternative for Hardcore Markdown Users for Creating Knowledge Graph of Notes.md

published/20220125 Use Mozilla DeepSpeech to enable speech to text in your application.md
@geekpi
https://linux.cn/article-14233-1.html
=> RP:published/20220125 Use Mozilla DeepSpeech to enable speech to text in your application.md

published/20220130 I Used Linux-Based PinePhone Daily For A Year. Here-s What I Learned.md
@wxy
https://linux.cn/article-14235-1.html
=> P:published/20220130 I Used Linux-Based PinePhone Daily For A Year. Here-s What I Learned.md

published/20220112 Set up a build system with CMake and VSCodium.md, translated/tech/20220112 Set up a build system with CMake and VSCodium.md
@robsean
https://linux.cn/article-14249-1.html
=> RP:20220112 set up a build system with c make and vs codium

published/20220209 Vivaldi 5.1 Introduces Horizontal Scrollable Tabs and a New Reading List.md
@imgradeone
https://linux.cn/article-14262-1.html
=> RP:published/20220209 Vivaldi 5.1 Introduces Horizontal Scrollable Tabs and a New Reading List.md

published/20220130 Open source tools to make your Wordle results accessible.md
@geekpi
https://linux.cn/article-14268-1.html
=> RP:published/20220130 Open source tools to make your Wordle results accessible.md

published/20220207 Customize your shell prompt with Starship.md
@geekpi
https://linux.cn/article-14274-1.html
=> RP:published/20220207 Customize your shell prompt with Starship.md

published/20220212 How to Get KDE Plasma 5.24 in Kubuntu 21.10 Impish Indri.md
@geekpi
https://linux.cn/article-14279-1.html
=> RP:published/20220212 How to Get KDE Plasma 5.24 in Kubuntu 21.10 Impish Indri.md

published/20220218 Use Linux Terminal on Android Smartphones With These Apps.md
@wxy
https://linux.cn/article-14286-1.html
=> P:published/20220218 Use Linux Terminal on Android Smartphones With These Apps.md

published/20220210 Troubleshooting -Unacceptable TLS certificate- Error in Linux.md
@geekpi
https://linux.cn/article-14288-1.html
=> RP:published/20220210 Troubleshooting -Unacceptable TLS certificate- Error in Linux.md

published/20220217 How to Clean Up Snap Package Versions in Linux -Quick Tip.md
@geekpi
https://linux.cn/article-14302-1.html
=> RP:published/20220217 How to Clean Up Snap Package Versions in Linux -Quick Tip.md

published/20211206 Bash Shell Scripting for beginners (Part 3).md
=> Update 20211206 Bash Shell Scripting for beginners (Part 3).md

sources/tech/20220227 12 Simple Tools to Protect Your Privacy.md
=> Translating by aREversez

published/20220302 How to use httpx, a web client for Python.md
@geekpi
https://linux.cn/article-14353-1.html
=> RP:published/20220302 How to use httpx, a web client for Python.md

sources/tech/20210401 Use awk to calculate letter frequency.md
=> Update 20210401 Use awk to calculate letter frequency.md

sources/tech/20210408 5 commands to level-up your Git game.md
=> Translating 20210408 5 commands to level-up your Git game.md

published/20220311 Zorin OS 16.1 Brings Much Needed Stability and Improvements.md
@geekpi
https://linux.cn/article-14365-1.html
=> RP:published/20220311 Zorin OS 16.1 Brings Much Needed Stability and Improvements.md

sources/tech/20210903 How to Completely Uninstall Google Chrome From Ubuntu.md
=> Translating 20210903 How to Completely Uninstall Google Chrome From Ubuntu.md

published/20210903 How to Completely Uninstall Google Chrome From Ubuntu.md
@lkxed
https://linux.cn/article-14368-1.html
=> RP:published/20210903 How to Completely Uninstall Google Chrome From Ubuntu.md

published/20220317 Ubuntu has a ‘Weird Looking- New Logo.md
@lkxed
https://linux.cn/article-14370-1.html
=> RP:published/20220317 Ubuntu has a ‘Weird Looking- New Logo.md

published/20210908 How I migrated a WordPress website to a new host.md
@lxbwolf
https://linux.cn/article-14371-1.html
=> RP:published/20210908 How I migrated a WordPress website to a new host.md

sources/tech/20210707 Parsing config files with Java.md, translated/tech/20210707 Parsing config files with Java.md
=> Translated 20210707 Parsing config files with Java.md

published/20210401 Use awk to calculate letter frequency.md
@lkxed
https://linux.cn/article-14375-1.html
=> RP:published/20210401 Use awk to calculate letter frequency.md

sources/tech/20220125 Creating and initializing lists in Java and Groovy.md
=> Translating 20220125 Creating and initializing lists in Java and Groovy.md

published/20210606 5 handy guides to open source for teachers.md
@lkxed
https://linux.cn/article-14386-1.html
=> RP:published/20210606 5 handy guides to open source for teachers.md

sources/news/20220323 Clear Linux is the First Distro to Offer GNOME 42.md
=> Translating 20220323 Clear Linux is the First Distro to Offer GNOME 42.md

published/20220323 Xonsh Shell Combines the Best of Bash Shell and Python in Linux Terminal.md
@lkxed
https://linux.cn/article-14390-1.html
=> RP:published/20220323 Xonsh Shell Combines the Best of Bash Shell and Python in Linux Terminal.md

published/20220324 GNOME 42 is Here With Dark Mode, New Screenshot UI, and More Exciting Features.md
@lkxed
https://linux.cn/article-14392-1.html
=> RP:published/20220324 GNOME 42 is Here With Dark Mode, New Screenshot UI, and More Exciting Features.md

sources/tech/20220324 7 Reasons to Try Open Source Secure Messenger ‘Threema.md
=> Translating 20220323 7 Reasons to Try Open Source Secure Messenger ‘Threema’.md

published/20220316 Gitter- A Cross-Platform Open Source Community Platform for Developers.md
@geekpi
https://linux.cn/article-14397-1.html
=> RP:published/20220316 Gitter- A Cross-Platform Open Source Community Platform for Developers.md

published/20220323 Clear Linux is the First Distro to Offer GNOME 42.md
@lkxed
https://linux.cn/article-14400-1.html
=> RP:published/20220323 Clear Linux is the First Distro to Offer GNOME 42.md

sources/tech/20210626 How I helped my mom switch from Windows to Linux.md
This post it being translated by lkxed.
=> Translating 20210626 How I helped my mom switch from Windows to Linux.md

sources/tech/20201212 Power up your Linux terminal text editor with ed.md
=> Translating 20201212 Power up your Linux terminal text editor with ed.md

published/20210626 How I helped my mom switch from Windows to Linux.md
@lkxed
https://linux.cn/article-14407-1.html
这篇翻译很好，我几乎不需要任何改动。
=> RP:published/20210626 How I helped my mom switch from Windows to Linux.md

sources/tech/20201116 Linux Jargon Buster- What is Grub in Linux- What is it Used for.md
=> Translating 20201116 Linux Jargon Buster- What is Grub in Linux- What is it Used for.md

published/20220125 Creating and initializing lists in Java and Groovy.md
@lkxed
https://linux.cn/article-14411-1.html
=> RP:published/20220125 Creating and initializing lists in Java and Groovy.md

published/20210622 How to Make LibreOffice Look Like Microsoft Office.md, translated/tech/20210622 How to Make LibreOffice Look Like Microsoft Office.md
@robsean
https://linux.cn/article-14412-1.html
=> RP:20210622 how to make libre office look like microsoft office

published/20220330 Thunderbird 102 is Getting Several Exciting New Features- Here Are 7 of Them.md
@lkxed
https://linux.cn/article-14421-1.html
=> RP:published/20220330 Thunderbird 102 is Getting Several Exciting New Features- Here Are 7 of Them.md

published/20201116 Linux Jargon Buster- What is Grub in Linux- What is it Used for.md
@lkxed
https://linux.cn/article-14427-1.html
=> RP:published/20201116 Linux Jargon Buster- What is Grub in Linux- What is it Used for.md

sources/tech/20220401 Using Sourcegraph to Search 34,000- Fedora Repositories.md, translated/tech/20220401 Using Sourcegraph to Search 34,000- Fedora Repositories.md
This post is translated by lkxed.
=> Translated 20220401 Using Sourcegraph to Search 34,000- Fedora Repositories.md

sources/tech/20210812 A guide to the Linux terminal for beginners.md
=> Translating 20210812 A guide to the Linux terminal for beginners.md

published/20201212 Power up your Linux terminal text editor with ed.md
@lkxed
https://linux.cn/article-14431-1.html
=> RP:published/20201212 Power up your Linux terminal text editor with ed.md

sources/tech/20210812 A guide to the Linux terminal for beginners.md
This post is translated by lkxed.
=> Translated 20210812 A guide to the Linux terminal for beginners.md

published/20220401 Using Sourcegraph to Search 34,000- Fedora Repositories.md
@lkxed
https://linux.cn/article-14434-1.html
=> RP:published/20220401 Using Sourcegraph to Search 34,000- Fedora Repositories.md

published/20220329 Metadata Cleaner- Remove Your Traces From Pictures and Documents in Linux.md
@geekpi
https://linux.cn/article-14437-1.html
=> RP:published/20220329 Metadata Cleaner- Remove Your Traces From Pictures and Documents in Linux.md

published/20220405 Here-s What Devs Are Planning for GNOME 43.md
@lkxed
https://linux.cn/article-14440-1.html
=> RP:published/20220405 Here-s What Devs Are Planning for GNOME 43.md

published/20220331 Add Some Colors to Your Ubuntu Desktop With the new Accent Color Options in Ubuntu 22.04.md
@geekpi
https://linux.cn/article-14441-1.html
=> RP:published/20220331 Add Some Colors to Your Ubuntu Desktop With the new Accent Color Options in Ubuntu 22.04.md

sources/news/20220407 Linux Mint 21 Code Name Announced with New Upgrade Utility and More.md
=> Translating 20220407 Linux Mint 21 Code Name Announced with New Upgrade Utility and More.md

published/20210812 A guide to the Linux terminal for beginners.md
@lkxed
https://linux.cn/article-14445-1.html
=> RP:published/20210812 A guide to the Linux terminal for beginners.md

published/20220407 Linux Mint 21 Code Name Announced with New Upgrade Utility and More.md
@lkxed
https://linux.cn/article-14448-1.html
=> RP:published/20220407 Linux Mint 21 Code Name Announced with New Upgrade Utility and More.md

sources/tech/20220214 How I configure Vim as my default editor on Linux.md
=> Translating 20220214 How I configure Vim as my default editor on Linux.md

published/20210419 How to Deploy Seafile Server with Docker to Host Your Own File Synchronization and Sharing Solution.md
@hwlife
https://linux.cn/article-14468-1.html
=> RP:published/20210419 How to Deploy Seafile Server with Docker to Host Your Own File Synchronization and Sharing Solution.md

published/20220409 How to Activate the Dark and Light Wallpaper Variants in GNOME 42.md
@lkxed
https://linux.cn/article-14472-1.html
=> RP:published/20220409 How to Activate the Dark and Light Wallpaper Variants in GNOME 42.md

sources/tech/20220417 How I scan family photos on Linux.md
This post is collected by lkxed.
=> [自动选题][tech]: 20220417 How I scan family photos on Linux.md
