LCTT/TranslateProject

translated/news/Git 2.2.1 Released To Fix Critical Security Issue.md
=> Git 发布2.2.1版，修复严重安全问题

sources/tech/20170117 How to Install WordPress with HHVM and Nginx on CentOS 7.md
在 CentOS 7 中通过 Nginx 和 HHVM 来安装 WordPress
=> [Translating] How to Install WordPress with HHVM and Nginx on CentOS 7

sources/tech/20180119 No More Ubuntu Debian is the New Choice For Googles In-house Linux Distribution.md
20180119 No More Ubuntu Debian is the New Choice For Googles In-house Linux Distribution.md
=> Update 20180119 No More Ubuntu Debian is the New Choice For Googles In-house Linux Distribution.md

translated/tech/20180206 Programming in Color with ncurses.md
[Leemeans translated]20180206 Programming in Color with ncurses.md
=> Leemeans translated

translated/tech/20180917 Getting started with openmediavault- A home NAS solution.md
getting started with openmediavault - a home NAS solution
=> translated 

scripts/check.sh, scripts/check/analyze.sh, scripts/check/check.sh, scripts/check/collect.sh, scripts/check/common.inc.sh, scripts/check/identify.sh
* 使用 POSIX shell 来保证脚本的可移植性
* 使用未转义的文件名（文件名中切不可有换行符）
* 在无更改时返回错误退出
* 移除 news 文章分类
=> 完善规则 —— 检查文章分类以及变更一致性

sources/talk/20190223 No- Ubuntu is NOT Replacing Apt with Snap.md
sources/talk/20190223 No- Ubuntu is NOT Replacing Apt with Snap.md
=> 选题: 20190223 No! Ubuntu is NOT Replacing Apt with Snap

sources/talk/20190314 Why feedback, not metrics, is critical to DevOps.md
sources/talk/20190314 Why feedback, not metrics, is critical to DevOps.md
=> 选题: 20190314 Why feedback, not metrics, is critical to DevOps

sources/tech/20190402 Announcing the release of Fedora 30 Beta.md
sources/tech/20190402 Announcing the release of Fedora 30 Beta.md
=> 选题: 20190402 Announcing the release of Fedora 30 Beta

sources/tech/20190328 Can Better Task Stealing Make Linux Faster.md
sources/tech/20190328 Can Better Task Stealing Make Linux Faster.md
=> 选题: 20190328 Can Better Task Stealing Make Linux Faster?

sources/tech/20190415 12 Single Board Computers- Alternative to Raspberry Pi.md
sources/tech/20190415 12 Single Board Computers- Alternative to Raspberry Pi.md
=> 选题: 20190415 12 Single Board Computers: Alternative to Raspberry Pi

sources/talk/20190517 HPE to buy Cray, offer HPC as a service.md
sources/talk/20190517 HPE to buy Cray, offer HPC as a service.md
=> 选题: 20190517 HPE to buy Cray, offer HPC as a service

sources/tech/20190706 How to enable DNS-over-HTTPS (DoH) in Firefox.md
sources/tech/20190706 How to enable DNS-over-HTTPS (DoH) in Firefox.md
=> 选题: 20190706 How to enable DNS-over-HTTPS (DoH) in Firefox

published/20211102 Fedora 35 Debuts With GNOME 41 and a New KDE Variant.md
@wxy
https://linux.cn/article-13949-1.html
=> PUB:published/20211102 Fedora 35 Debuts With GNOME 41 and a New KDE Variant.md

sources/news/20220502 Ubuntu’s Unity Desktop Still Lives- Version 7.6 is Available for Testing After 6 Years.md
=> [手动选题][news]: 20220502 Ubuntu’s Unity Desktop Still Lives- Version 7.6 is Available for Testing After 6 Years.md

sources/tech/20220510 Can’t Run AppImage on Ubuntu 22.04- Here’s How to Fix it.md
=> [手动选题][tech]: 20220510 Can’t Run AppImage on Ubuntu 22.04- Here’s How to Fix it.md

published/20220510 Can’t Run AppImage on Ubuntu 22.04- Here’s How to Fix it.md
@geekpi
https://linux.cn/article-14619-1.html
=> RP:published/20220510 Can’t Run AppImage on Ubuntu 22.04- Here’s How to Fix it.md

sources/news/20220526 DeepMind-s Open Source MuJoCo Is Available On GitHub.md
=> [申领原文][news]: 20220526 DeepMind-s Open Source MuJoCo Is Available On GitHub.md

published/20220518 How To Boot Into Rescue Mode Or Emergency Mode In Ubuntu 22.04 - 20.04 - 18.04.md, translated/tech/20220518 How To Boot Into Rescue Mode Or Emergency Mode In Ubuntu 22.04 - 20.04 - 18.04.md
说明：这篇我删掉了后面的很多 RUBY 标签，过于多的 RUBY 标签会影响阅读。基本上，RUBY 标签在文章开头出第一次出现时使用即可，后面可以省略。（但对于菜单、按钮名称，我一般全程保留）
另外，我在术语上区分了引导和启动，启动更多指加电启动过程。而引导是可以不同阶段的切换，比如从救援模式进入紧急模式，其实不涉及加电启动，类似于运行级的切换。
这篇有点长而琐碎，翻译起来其实挺痛苦的，辛苦你了。
@robsean
https://linux.cn/article-14709-1.html
=> RP:20220518 how to boot into rescue mode or emergency mode in ubuntu 22.04   20.04   18.04

sources/talk/20220801 What Made Fedora Choose To Use CC0 Licensed Code As The Boot.md
=> [手动选题][talk]: 20220801 What Made Fedora Choose To Use CC0 Licensed Code As The Boot.md

sources/tech/20220806 Fixing Could not get lock -var-lib-dpkg-lock Error in Ubuntu.md
=> [手动选题][tech]: 20220806 Fixing Could not get lock -var-lib-dpkg-lock Error in Ubuntu.md

sources/tech/20220815 Handling -apt-key is deprecated. Manage keyring files in trusted.gpg.d instead- in Ubuntu Linux.md
=> [手动选题][tech]: 20220815 Handling -apt-key is deprecated. Manage keyring files in trusted.gpg.d instead- in Ubuntu Linux.md

published/20220804 Install Spotify on Manjaro and Other Arch Linux Based Distros.md
@geekpi
https://linux.cn/article-14965-1.html
=> RP:published/20220804 Install Spotify on Manjaro and Other Arch Linux Based Distros.md

sources/tech/20220901 How To Convert Arch Linux Packages To AppImage Using Arch2appimage.md
=> [手动选题][tech]: 20220901 How To Convert Arch Linux Packages To AppImage Using Arch2appimage.md

sources/news/20220902 Microsoft Decides to Drop the Linux App for Teams to Replace it as a Progressive Web App Instead.md
=> [手动选题][news]: 20220902 Microsoft Decides to Drop the Linux App for Teams to Replace it as a Progressive Web App Instead.md

sources/tech/20220919 How To Find Default Gateway IP Address In Linux And Unix From Commandline.md
=> [手动选题][tech]: 20220919 How To Find Default Gateway IP Address In Linux And Unix From Commandline.md

sources/news/20221018-⭐️-Ardour-7-0-Release-Marks-the-end-of-32-bit-builds--Adds-Clip-Launching-and-Apple-Silicon-Support.md
=> [手动选题][news]: 20221018-⭐️-Ardour-7-0-Release-Marks-the-end-of-32-bit-builds--Adds-Clip-Launching-and-Apple-Silicon-Support.md

sources/news/20221101.12 ⭐️ OpenSSL 3.0.7 Fixes Two High-CVEs with Buffer Overflow.md
=> [手动选题][news]: 20221101.12 ⭐️ OpenSSL 3.0.7 Fixes Two High-CVEs with Buffer Overflow.md

sources/tech/20221118.0 ⭐️⭐️ Fixing “Key is stored in legacy trusted.gpg keyring” Issue in Ubuntu.md
=> [手动选题][tech]: 20221118.0 ⭐️⭐️ Fixing “Key is stored in legacy trusted.gpg keyring” Issue in Ubuntu.md

sources/news/20221206.1 ⭐️ Gnoppix Linux 22.12 is out with GNOME 43, Kernel 6.0, + More.md
=> [手动选题][news]: 20221206.1 ⭐️ Gnoppix Linux 22.12 is out with GNOME 43, Kernel 6.0, + More.md

sources/news/20221213.0 ⭐️ Puppy Linux 22.12 (S15Pup) Arrives Based on Slackware 15.md
=> [手动选题][news]: 20221213.0 ⭐️ Puppy Linux 22.12 (S15Pup) Arrives Based on Slackware 15.md

sources/news/20230105.2 ⭐️ Nitrux 2.6.0 Takes Bold Steps Drops apt, Adds Flathub and Pipewire.md
=> [手动选题][news]: 20230105.2 ⭐️ Nitrux 2.6.0 Takes Bold Steps Drops apt, Adds Flathub and Pipewire.md

published/20221213.1 ⭐️⭐️⭐️ Battle of the Texts and the Unicode Savior.md, translated/tech/20221213.1 ⭐️⭐️⭐️ Battle of the Texts and the Unicode Savior.md
@yzuowei
我修改了 Unicode 的字符名的 Ruby 标签使用方式，原因如下：
- 这个大写的字符名是正式名称，所以可以直接使用
- 名称太长，RUBY 标签在排版时，尤其是在微信的手机屏幕上会换行，比较难看
这篇翻译的非常尽心，非常好，👍
https://linux.cn/article-15483-1.html
=> RP:20221213.1 ⭐️⭐️⭐️ battle of the texts and the unicode savior

published/20221118.0 ⭐️⭐️ Fixing “Key is stored in legacy trusted.gpg keyring” Issue in Ubuntu.md
@geekpi
https://linux.cn/article-15565-1.html
=> RP:published/20221118.0 ⭐️⭐️ Fixing “Key is stored in legacy trusted.gpg keyring” Issue in Ubuntu.md

sources/news/20230220.0 ⭐️⭐️ Linux Kernel 6.2 is Out with IPv6 Protective Load Balancing, Improved Rust Support.md
=> [手动选题][news]: 20230220.0 ⭐️⭐️ Linux Kernel 6.2 is Out with IPv6 Protective Load Balancing, Improved Rust Support.md

sources/news/20230501.0 ⭐️ Nitrux 2.8 Launched with Updated Kernel, KDE Plasma and WayDroid support.md
=> [手动选题][news]: 20230501.0 ⭐️ Nitrux 2.8 Launched with Updated Kernel, KDE Plasma and WayDroid support.md

sources/tech/20230310.1 ⭐️⭐️ How the GDB debugger and other tools use call frame information to determine the active function calls.md
translating
How the GDB debugger and other tools use call frame information to determine the active function calls
=> translating

published/20230605.1 ⭐️⭐️ How to Setup Dynamic NFS Provisioning in Kubernetes Cluster.md
@geekpi
https://linux.cn/article-16043-1.html
=> RP:published/20230605.1 ⭐️⭐️ How to Setup Dynamic NFS Provisioning in Kubernetes Cluster.md

sources/tech/20230728 Why is DNS still hard to learn.md
sources/tech/20230728 Why is DNS still hard to learn.md
=> 选题[tech]: 20230728 Why is DNS still hard to learn?
