LCTT/TranslateProject

sources/talk/20220415 How the C programming language has grown.md
This article is <STATUS> by lkxed.
=> [自动选题][talk]: 20220415 How the C programming language has grown.md

sources/news/20220415 Elon Musk Believes Twitter Algorithm Should Be Open-Source.md
=> [申领原文][news]: 20220415 Elon Musk Believes Twitter Algorithm Should Be Open-Source.md

published/20220412 A list of new(ish) command line tools.md
@geekpi
https://linux.cn/article-14488-1.html
=> RP:published/20220412 A list of new(ish) command line tools.md

sources/tech/20220414 A guide to JVM parameters for Java developers.md
=> [手动选题][tech]: 20220414 A guide to JVM parameters for Java developers.md

sources/tech/20220414 My favorite build options for Go.md
=> [手动选题][tech]: 20220414 My favorite build options for Go.md

sources/tech/20220416 Disable Animations in Cinnamon Desktop to Slightly Speed Up Your Linux Mint System.md
=> [申领原文][tech]: 20220416 Disable Animations in Cinnamon Desktop to Slightly Speed Up Your Linux Mint System.md

sources/talk/20220421 How to Build a Career in Open Source.md
=> [手动选题][talk]: 20220421 How to Build a Career in Open Source.md

sources/talk/20220421 How Linux rescues slow computers (and the planet).md
=> [手动选题][talk]: 20220421 How Linux rescues slow computers (and the planet).md

published/20220413 Meet Lite XL- A Lightweight, Open-Source Text Editor for Linux Users.md
@geekpi
https://linux.cn/article-14497-1.html
=> RP:published/20220413 Meet Lite XL- A Lightweight, Open-Source Text Editor for Linux Users.md

sources/tech/20220414 My favorite build options for Go.md
=> [申领原文][tech]: 20220414 My favorite build options for Go.md

published/20220416 Disable Animations in Cinnamon Desktop to Slightly Speed Up Your Linux Mint System.md
@lkxed
https://linux.cn/article-14499-1.html
=> RP:published/20220416 Disable Animations in Cinnamon Desktop to Slightly Speed Up Your Linux Mint System.md

published/20220420 AlmaLinux 9.0 Beta Is Here, Ready to Replace to RHEL 9.md
@lkxed
https://linux.cn/article-14500-1.html
=> RP:published/20220420 AlmaLinux 9.0 Beta Is Here, Ready to Replace to RHEL 9.md

sources/talk/20220415 How the C programming language has grown.md
=> [申领原文][talk]: 20220415 How the C programming language has grown.md

sources/news/20220422 Open Source Software maintainer Vandalizes Own Code In Anti-Russian Protest.md
=> [手动选题][news]: 20220422 Open Source Software maintainer Vandalizes Own Code In Anti-Russian Protest.md

sources/talk/20220422 Documentation Isn’t Just Another Aspect of Open Source Development.md
=> [手动选题][talk]: 20220422 Documentation Isn’t Just Another Aspect of Open Source Development.md

published/20220317 Top 10 Most Beautiful Linux Distributions -Featured.md, translated/tech/20220317 Top 10 Most Beautiful Linux Distributions -Featured.md
@amagicboy
https://linux.cn/article-14501-1.html
=> RP:20220317 top 10 most beautiful linux distributions  featured

sources/talk/20220421 How to Build a Career in Open Source.md
=> [申领原文][talk]: 20220421 How to Build a Career in Open Source.md

sources/talk/20190404 Why you should choose mindfulness over multitasking.md
=> [手动选题][talk]: 20190404 Why you should choose mindfulness over multitasking.md

sources/tech/20210310 Troubleshoot WiFi problems with Go and a Raspberry Pi.md
=> [手动选题][tech]: 20210310 Troubleshoot WiFi problems with Go and a Raspberry Pi.md

published/20220330 10 Lightweight Linux Distributions for your Old Hardware in 2022.md, translated/tech/20220330 10 Lightweight Linux Distributions for your Old Hardware in 2022.md
@robsean
https://linux.cn/article-14505-1.html
=> RP:20220330 10 lightweight linux distributions for your old hardware in 2022

sources/talk/20190411 How do you contribute to open source without code?.md
=> [手动选题][talk]: 20190411 How do you contribute to open source without code?.md

published/20220420 Ubuntu Studio 22.04 LTS - New Features and Release Details.md
@geekpi
https://linux.cn/article-14507-1.html
=> RP:published/20220420 Ubuntu Studio 22.04 LTS - New Features and Release Details.md

sources/tech/20210310 Troubleshoot WiFi problems with Go and a Raspberry Pi.md
=> [申领原文][tech]: 20210310 Troubleshoot WiFi problems with Go and a Raspberry Pi.md

sources/tech/20220427 Bloomberg Open Sources Memray, A Python Memory Profiler.md
=> [手动选题][tech]: 20220427 Bloomberg Open Sources Memray, A Python Memory Profiler.md

sources/news/20220427 Shortwave 3.0 is Here With UI Upgrades, Private Stations, and More Improvements.md
=> [手动选题][news]: 20220427 Shortwave 3.0 is Here With UI Upgrades, Private Stations, and More Improvements.md

sources/talk/20220427 10 Reasons to Run Linux in Virtual Machines.md
=> [手动选题][talk]: 20220427 10 Reasons to Run Linux in Virtual Machines.md

sources/talk/20220422 Documentation Isn’t Just Another Aspect of Open Source Development.md
=> [申领原文][talk]: 20220422 Documentation Isn’t Just Another Aspect of Open Source Development.md

published/20220415 3-2-1 Backup plan with Fedora ARM server.md, translated/tech/20220415 3-2-1 Backup plan with Fedora ARM server.md
@hwlife
https://linux.cn/article-14519-1.html
=> RP:20220415 3 2 1 backup plan with fedora arm server

sources/tech/20220428 Why use Apache Druid for your open source analytics database.md
=> [手动选题][tech]: 20220428 Why use Apache Druid for your open source analytics database.md

sources/tech/20220428 Following Musk’s Acquisition Of Twitter, An Open Source Alternative Is Exploding.md
=> [手动选题][tech]: 20220428 Following Musk’s Acquisition Of Twitter, An Open Source Alternative Is Exploding.md

sources/talk/20220428 Elon Musk’s Plan To Open Source The Twitter Algorithm Has Flaws.md
=> [手动选题][talk]: 20220428 Elon Musk’s Plan To Open Source The Twitter Algorithm Has Flaws.md

sources/talk/20220427 How I grew my product management career with open source.md
=> [申领原文][talk]: 20220427 How I grew my product management career with open source.md

sources/tech/20220429 Detect a Phishing URL Using Machine Learning in Python.md
=> [手动选题][tech]: 20220429 Detect a Phishing URL Using Machine Learning in Python.md

published/20210126 Automate setup and delivery for virtual machines in the cloud.md
@hwlife
https://linux.cn/article-14524-1.html
=> RP:published/20210126 Automate setup and delivery for virtual machines in the cloud.md

sources/news/20220430 Rust-based Redox OS 0.7.0 Arrives with Enhanced Hardware Support.md
=> [手动选题][news]: 20220430 Rust-based Redox OS 0.7.0 Arrives with Enhanced Hardware Support.md

sources/tech/20220430 Hands On With GNOME’s New Terminal for Linux Users.md
=> [手动选题][tech]: 20220430 Hands On With GNOME’s New Terminal for Linux Users.md

sources/news/20220430 Rust-based Redox OS 0.7.0 Arrives with Enhanced Hardware Support.md
=> [申领原文][news]: 20220430 Rust-based Redox OS 0.7.0 Arrives with Enhanced Hardware Support.md

published/20220427 Shortwave 3.0 is Here With UI Upgrades, Private Stations, and More Improvements.md
@lkxed
https://linux.cn/article-14528-1.html
=> RP:published/20220427 Shortwave 3.0 is Here With UI Upgrades, Private Stations, and More Improvements.md

sources/news/20220428 Archinstall-s New Menu System Makes it Even Easier to Install Arch Linux.md
=> [申领原文][news]: 20220428 Archinstall-s New Menu System Makes it Even Easier to Install Arch Linux.md

sources/talk/20190404 Why you should choose mindfulness over multitasking.md
=> [申领原文][talk]: 20190404 Why you should choose mindfulness over multitasking.md

sources/tech/20210428 Share files between Linux and Windows computers.md
change the translator, first try.
=> [申领原文][tech]: 20210428 Share files between Linux and Windows computers.md

published/20220425 Exciting New Features Revealed for KDE Plasma 5.25- Take a Look Here.md, translated/news/20220425 Exciting New Features Revealed for KDE Plasma 5.25- Take a Look Here.md
@PeterPan0106
感谢您完成了第一篇翻译贡献！
本文首发地址：https://linux.cn/article-14532-1.html
您的 LCTT 专页：https://linux.cn/lctt/PeterPan0106
=> RP:20220425 exciting new features revealed for kde plasma 5.25  take a look here

published/20220430 Rust-based Redox OS 0.7.0 Arrives with Enhanced Hardware Support.md
@lkxed
https://linux.cn/article-14533-1.html
=> RP:published/20220430 Rust-based Redox OS 0.7.0 Arrives with Enhanced Hardware Support.md

sources/talk/20220428 Elon Musk’s Plan To Open Source The Twitter Algorithm Has Flaws.md
=> [申领原文][talk]: 20220428 Elon Musk’s Plan To Open Source The Twitter Algorithm Has Flaws.md

sources/talk/20220427 10 Reasons to Run Linux in Virtual Machines.md
=> [申领文章]10 Reasons to Run Linux in Virtual Machines

published/20220429 Detect a Phishing URL Using Machine Learning in Python.md
@lkxed
https://linux.cn/article-14535-1.html
=> RP:published/20220429 Detect a Phishing URL Using Machine Learning in Python.md

sources/talk/20220502 How to make community recognition more inclusive.md
=> [手动选题][talk]: 20220502 How to make community recognition more inclusive.md

published/20220428 Archinstall-s New Menu System Makes it Even Easier to Install Arch Linux.md
@lkxed
https://linux.cn/article-14536-1.html
=> RP:published/20220428 Archinstall-s New Menu System Makes it Even Easier to Install Arch Linux.md

published/20210428 Share files between Linux and Windows computers.md, translated/tech/20210428 Share files between Linux and Windows computers.md
@hanszhao80
感谢您。完成了第一篇翻译贡献！
本文首发地址：https://linux.cn/article-14537-1.html
您的 LCTT 专页：https://linux.cn/lctt/hanszhao80
=> RP:20210428 share files between linux and windows computers

sources/tech/20220502 Data Profiler- An Open Source Machine Learning Technology For Data Monitoring.md
=> [手动选题][tech]: 20220502 Data Profiler- An Open Source Machine Learning Technology For Data Monitoring.md

sources/news/20220502 Microsoft Joins The Open 3D Foundation For Open Source 3D Development.md
=> [手动选题][news]: 20220502 Microsoft Joins The Open 3D Foundation For Open Source 3D Development.md

sources/tech/20220502 Tools You Can Use for the Security Audit of IoT Devices.md
=> [手动选题][tech]: 20220502 Tools You Can Use for the Security Audit of IoT Devices.md

sources/tech/20210617 Linux package management with dnf.md
apt的包管理的文章翻了一篇，发现这个在todo列表里。正好一起翻译了。
=> [申领原文][tech]:20210617 Linux package management with dnf.md

sources/talk/20220502 How to make community recognition more inclusive.md
=> [申领原文]How to make community recognition more inclusive

published/20210617 Linux package management with dnf.md, translated/tech/20210617 Linux package management with dnf.md
@hanszhao80
https://linux.cn/article-14542-1.html
=> RP:20210617 linux package management with dnf

sources/tech/20220503 Package Analysis Examines Packages In Open Source Repositories In Real Time.md
=> [手动选题][tech]: 20220503 Package Analysis Examines Packages In Open Source Repositories In Real Time.md

sources/tech/20220503 PHP MySQL WHERE Clause.md
=> [手动选题][tech]: 20220503 PHP MySQL WHERE Clause.md

sources/news/20220503 Nvidia Begins To Set The Foundation For Future Open And Parallel Coding.md
=> [手动选题][news]: 20220503 Nvidia Begins To Set The Foundation For Future Open And Parallel Coding.md

sources/tech/20220503 Automate and manage multiple devices with Remote Home Assistant.md
=> [手动选题][tech]: 20220503 Automate and manage multiple devices with Remote Home Assistant.md

sources/tech/20220503 How I use the Bacula GUI for backup and recovery.md
=> [手动选题][tech]: 20220503 How I use the Bacula GUI for backup and recovery.md

published/20220502 Microsoft Joins The Open 3D Foundation For Open Source 3D Development.md
@lkxed
https://linux.cn/article-14544-1.html
哈哈，翻车了，这就是一篇软文通稿。
=> RP:published/20220502 Microsoft Joins The Open 3D Foundation For Open Source 3D Development.md

sources/news/20220504 Firefox 100 Marks 17 Years of Development with Interesting Upgrades.md
=> [手动选题][news]: 20220504 Firefox 100 Marks 17 Years of Development with Interesting Upgrades.md

sources/news/20220504 elementary OS 7 Code Name Revealed. Here are the Details.md
=> [手动选题][news]: 20220504 elementary OS 7 Code Name Revealed. Here are the Details.md

sources/news/20220504 Microsoft’s 3D Movie Maker, First Released In 1995, Is Now Open Source.md
=> [手动选题][news]: 20220504 Microsoft’s 3D Movie Maker, First Released In 1995, Is Now Open Source.md

sources/news/20220504 ESI Group Collaborates With ENSAM, Open Sources Its “Inspector” Software.md
=> [手动选题][news]: 20220504 ESI Group Collaborates With ENSAM, Open Sources Its “Inspector” Software.md

sources/tech/20220504 How I manage my own virtual network with ZeroTier.md
=> [手动选题][tech]: 20220504 How I manage my own virtual network with ZeroTier.md

published/20220504 Microsoft’s 3D Movie Maker, First Released In 1995, Is Now Open Source.md
@lkxed
https://linux.cn/article-14549-1.html
=> RP:published/20220504 Microsoft’s 3D Movie Maker, First Released In 1995, Is Now Open Source.md

sources/tech/20220505 Boost the power of C with these open source libraries.md
=> [手动选题][tech]: 20220505 Boost the power of C with these open source libraries.md

sources/tech/20220505 Experiment with containers and pods on your own computer.md
=> [手动选题][tech]: 20220505 Experiment with containers and pods on your own computer.md

sources/tech/20220505 Xebian – A Blend of Debian and Goodness of Xfce [Review].md
=> [手动选题][tech]: 20220505 Xebian – A Blend of Debian and Goodness of Xfce [Review].md

sources/news/20220504 Firefox 100 Marks 17 Years of Development with Interesting Upgrades.md
=> [申领原文][news]: 20220504 Firefox 100 Marks 17 Years of Development with Interesting Upgrades.md

published/20210710 A new open source operating system for embedded systems.md, translated/tech/20210710 A new open source operating system for embedded systems.md
@tendertime
感谢您完成了第一篇翻译贡献！
本文首发地址：https://linux.cn/article-14552-1.html
您的 LCTT 专页：https://linux.cn/lctt/tendertime
=> RP:20210710 a new open source operating system for embedded systems

published/20220414 A guide to JVM parameters for Java developers.md, translated/tech/20220414 A guide to JVM parameters for Java developers.md
@Veryzzj
感谢您完成了第一篇翻译贡献！
本文首发地址：https://linux.cn/article-14553-1.html
您的 LCTT 专页：https://linux.cn/lctt/Veryzzj
=> RP:20220414 a guide to jvm parameters for java developers

sources/news/20220506 Ubuntu MATE’s Lead Creates a Nifty Tool to Help Install 3rd Party Deb Packages.md
=> [手动选题][news]: 20220506 Ubuntu MATE’s Lead Creates a Nifty Tool to Help Install 3rd Party Deb Packages.md

sources/tech/20220506 My favorite open source tool for using crontab.md
=> [手动选题][tech]: 20220506 My favorite open source tool for using crontab.md

published/20220504 elementary OS 7 Code Name Revealed. Here are the Details.md
@lkxed
https://linux.cn/article-14556-1.html
=> RP:published/20220504 elementary OS 7 Code Name Revealed. Here are the Details.md

sources/news/20220505 Open Source Developer Creates First-of-its-Kind Fund To Support Maintainers.md
=> [申领原文][news]: 20220505 Open Source Developer Creates First-of-its-Kind Fund To Support Maintainers.md

sources/tech/20220419 Difference Between Ubuntu 22.04 and Ubuntu 20.04 LTS.md
=> [申领原文]Difference Between Ubuntu 22.04 and Ubuntu 20.04 LTS

sources/news/20220505 Tails 5.0 Release is Based on Debian 11 With a New -Kleopatra- Tool.md
=> [申领原文][news]: 20220505 Tails 5.0 Release is Based on Debian 11 With a New -Kleopatra- Tool.md

sources/news/20220506 Ubuntu MATE’s Lead Creates a Nifty Tool to Help Install 3rd Party Deb Packages.md
=> [申领原文][news]: 20220506 Ubuntu MATE’s Lead Creates a Nifty Tool to Help Install 3rd Party Deb Packages.md

published/20220113 Learn Rust in 2022.md
@hanszhao80
https://linux.cn/article-14563-1.html
=> RP:published/20220113 Learn Rust in 2022.md

sources/talk/20220508 How open source leads the way for sustainable technology.md
=> [手动选题][talk]: 20220508 How open source leads the way for sustainable technology.md

sources/talk/20220508 How open source leads the way for sustainable technology.md
=> [申领原文]How open source leads the way for sustainable technology

sources/news/20220508 KDE Plasma 5.25- Top New Features and Release Details.md
=> [手动选题][news]: 20220508 KDE Plasma 5.25- Top New Features and Release Details.md

published/20220505 Tails 5.0 Release is Based on Debian 11 With a New -Kleopatra- Tool.md
@lkxed
https://linux.cn/article-14568-1.html
=> RP:published/20220505 Tails 5.0 Release is Based on Debian 11 With a New -Kleopatra- Tool.md

sources/talk/20220509 Cloud service providers- How to keep your options open.md
=> [手动选题][talk]: 20220509 Cloud service providers- How to keep your options open.md

sources/tech/20220430 Hands On With GNOME’s New Terminal for Linux Users.md
=> [申领原文][tech]: 20220430 Hands On With GNOME’s New Terminal for Linux Users.md

sources/talk/20200807 A Beginner-s Guide to Open Source.md
原文地址：https://ruthikegah.xyz/a-beginners-guide-to-open-source
已通过推特私信获得作者 Ruth Ikegah 的许可。
=> [手动选题][talk]: 20200807 A Beginner's Guide to Open Source

sources/talk/20200807 A Beginner-s Guide to Open Source.md
=> [申领原文][talk]: 20200807 A Beginner-s Guide to Open Source.md

sources/talk/20220510 My open source journey with C from a neurodiverse perspective.md
=> [手动选题][talk]: 20220510 My open source journey with C from a neurodiverse perspective.md

sources/tech/20220510 How to (safely) read user input with the getline function.md
=> [手动选题][tech]: 20220510 How to (safely) read user input with the getline function.md

sources/tech/20220510 HydraPaper- A Wallpaper Manager for Linux with Multi-Monitor Support.md
=> [手动选题][tech]: 20220510 HydraPaper- A Wallpaper Manager for Linux with Multi-Monitor Support.md

sources/tech/20220510 Easily Connect your iPhone with Linux as KDE Connect Arrives on the App Store.md
=> [手动选题][tech]: 20220510 Easily Connect your iPhone with Linux as KDE Connect Arrives on the App Store.md

sources/news/20220510 Fedora 35 v Fedora 36- What-s the Difference-.md
=> [手动选题][news]: 20220510 Fedora 35 v Fedora 36- What-s the Difference-.md

sources/news/20220506 Announcing Fedora Linux 36.md
=> [申领原文][news]: 20220506 Announcing Fedora Linux 36.md

published/20220505 Open Source Developer Creates First-of-its-Kind Fund To Support Maintainers.md
@lkxed
https://linux.cn/article-14575-1.html
=> RP:published/20220505 Open Source Developer Creates First-of-its-Kind Fund To Support Maintainers.md

published/20220503 Package Analysis Examines Packages In Open Source Repositories In Real Time.md
@geekpi
https://linux.cn/article-14578-1.html
=> RP:published/20220503 Package Analysis Examines Packages In Open Source Repositories In Real Time.md

sources/news/20220511 Red Hat Enterprise Linux 9 Announced as the Next-Gen Backbone of Enterprise IT.md
=> [手动选题][news]: 20220511 Red Hat Enterprise Linux 9 Announced as the Next-Gen Backbone of Enterprise IT.md

sources/news/20220511 Good News! Docker Desktop is Now Here for Linux Users.md
=> [手动选题][news]: 20220511 Good News! Docker Desktop is Now Here for Linux Users.md

sources/tech/20220511 How To Upgrade To Fedora 36 From Fedora 35 [Workstation And Server].md
=> [手动选题][tech]: 20220511 How To Upgrade To Fedora 36 From Fedora 35 [Workstation And Server].md

sources/tech/20220511 5 surprising things I do with Linux.md
=> [手动选题][tech]: 20220511 5 surprising things I do with Linux.md

sources/tech/20220511 Manage your Gmail filters from the Linux command line.md
=> [手动选题][tech]: 20220511 Manage your Gmail filters from the Linux command line.md

sources/tech/20220511 10 Things to Do After Installing Fedora 36 Workstation [With Bonus Tip].md
=> [手动选题][tech]: 20220511 10 Things to Do After Installing Fedora 36 Workstation [With Bonus Tip].md

published/20220427 Bloomberg Open Sources Memray, A Python Memory Profiler.md
@geekpi
https://linux.cn/article-14582-1.html
=> RP:published/20220427 Bloomberg Open Sources Memray, A Python Memory Profiler.md

sources/news/20220512 NVIDIA Takes a Big Step to Improve its GPU Experience on Linux.md
=> [手动选题][news]: 20220512 NVIDIA Takes a Big Step to Improve its GPU Experience on Linux.md

sources/tech/20220512 5 reasons to use sudo on Linux.md
=> [手动选题][tech]: 20220512 5 reasons to use sudo on Linux.md

sources/tech/20220512 Get started with Bareos, an open source client-server backup solution.md
=> [手动选题][tech]: 20220512 Get started with Bareos, an open source client-server backup solution.md

sources/news/20220511 Good News! Docker Desktop is Now Here for Linux Users.md
=> [申领原文][news]: 20220511 Good News! Docker Desktop is Now Here for Linux Users.md

published/20220511 Good News! Docker Desktop is Now Here for Linux Users.md
@lkxed
https://linux.cn/article-14586-1.html
=> RP:published/20220511 Good News! Docker Desktop is Now Here for Linux Users.md

sources/tech/20220513 Install Third Party Software Using Fedy In Fedora 36.md
=> [手动选题][tech]: 20220513 Install Third Party Software Using Fedy In Fedora 36.md

sources/talk/20220513 When open source meets academic publishing- Platinum open access journals.md
=> [手动选题][talk]: 20220513 When open source meets academic publishing- Platinum open access journals.md

sources/tech/20220514 Hidden Features! 25 Fun Things You Can Do With DuckDuckGo Search Engine.md
=> [手动选题][tech]: 20220514 Hidden Features! 25 Fun Things You Can Do With DuckDuckGo Search Engine.md

sources/tech/20220514 An introduction to USB Device Emulation and how to take advantage of it.md
=> [手动选题][tech]: 20220514 An introduction to USB Device Emulation and how to take advantage of it.md

sources/tech/20220514 How To Enable Minimize And Maximize Buttons In Fedora 36 Workstation.md
=> [手动选题][tech]: 20220514 How To Enable Minimize And Maximize Buttons In Fedora 36 Workstation.md

sources/tech/20220514 How To Install Multimedia Codecs In Fedora Linux.md
=> [手动选题][tech]: 20220514 How To Install Multimedia Codecs In Fedora Linux.md

sources/tech/20180529 Build a concurrent TCP server in Go.md
=> [手动选题][tech]: 20180529 Build a concurrent TCP server in Go.md

sources/tech/20180529 Build a concurrent TCP server in Go.md
=> [申领原文][tech]: 20180529 Build a concurrent TCP server in Go.md

published/20220506 My favorite open source tool for using crontab.md
@geekpi
https://linux.cn/article-14598-1.html
=> RP:published/20220506 My favorite open source tool for using crontab.md

sources/tech/20220515 Top 10 Best Linux Distributions in 2022 For Everyone.md
20210722 Top 10 Best Linux Distributions in 2022 For Everyone.md
=> 修改文件名日期 & 清理内容

sources/tech/20220516 How to Dual Boot Ubuntu 22.04 LTS and Windows 11.md
=> [手动选题][tech]: 20220516 How to Dual Boot Ubuntu 22.04 LTS and Windows 11.md

published/20200807 A Beginner-s Guide to Open Source.md
@lkxed
https://linux.cn/article-14600-1.html
=> RP:published/20200807 A Beginner-s Guide to Open Source.md

sources/news/20220516 Microsoft has another Linux distribution and it is based on Debian.md
=> [手动选题][news]: 20220516 Microsoft has another Linux distribution and it is based on Debian.md

sources/news/20220516 Fudgie- The Awesome Budgie Desktop is Coming to Fedora Linux Soon.md
=> [手动选题][news]: 20220516 Fudgie- The Awesome Budgie Desktop is Coming to Fedora Linux Soon.md

sources/tech/20220516 How to rebase to Fedora Linux 36 on Silverblue.md
=> [手动选题][tech]: 20220516 How to rebase to Fedora Linux 36 on Silverblue.md

sources/talk/20220516 5 benefits of switching from Google Analytics to Plausible.md
=> [手动选题][talk]: 20220516 5 benefits of switching from Google Analytics to Plausible.md

sources/tech/20220516 Use Composer to require Git repositories within PHP projects.md
=> [手动选题][tech]: 20220516 Use Composer to require Git repositories within PHP projects.md

sources/tech/20220516 How To Reset Root Password In Fedora 36.md
=> [手动选题][tech]: 20220516 How To Reset Root Password In Fedora 36.md

sources/tech/20220516 Structured Data Processing with Spark SQL.md
=> [手动选题][tech]: 20220516 Structured Data Processing with Spark SQL.md

published/20220505 Xebian – A Blend of Debian and Goodness of Xfce [Review].md, translated/tech/20220505 Xebian – A Blend of Debian and Goodness of Xfce [Review].md
@geekpi
https://linux.cn/article-14602-1.html
=> RP:20220505 xebian – a blend of debian and goodness of xfce review]

sources/tech/20220516 -Extension Manager- App Helps You Install and Manage GNOME Shell Extensions.md
=> [手动选题][tech]: 20220516 -Extension Manager- App Helps You Install and Manage GNOME Shell Extensions.md

sources/tech/20220517 Travel off the grid and still send emails with putmail.md
=> [手动选题][tech]: 20220517 Travel off the grid and still send emails with putmail.md

sources/news/20220517 Kali Linux 2022.2 Release Adds an Amusing New Feature for the Hackers to Scare People.md
=> [手动选题][news]: 20220517 Kali Linux 2022.2 Release Adds an Amusing New Feature for the Hackers to Scare People.md

sources/news/20220517 Adobe Illustrator Alternative Inkscape Releases Version 1.2.md
=> [手动选题][news]: 20220517 Adobe Illustrator Alternative Inkscape Releases Version 1.2.md

sources/tech/20220517 Top 10 Best GNOME Extensions in 2022.md
=> [手动选题][tech]: 20220517 Top 10 Best GNOME Extensions in 2022.md

published/20220509 PyCaret- Machine Learning Model Development Made Easy.md
@geekpi
https://linux.cn/article-14607-1.html
=> RP:20220509-PyCaret--Machine-Learning-Model-Development-Made-Easy

sources/tech/20220518 A guide to Pipy, a programmable network proxy for cloud.md
=> [手动选题][tech]: 20220518 A guide to Pipy, a programmable network proxy for cloud.md

sources/news/20220518 ONLYOFFICE 7.1 Release Adds ARM Compatibility, a New PDF Viewer, and More Features.md
=> [手动选题][news]: 20220518 ONLYOFFICE 7.1 Release Adds ARM Compatibility, a New PDF Viewer, and More Features.md

sources/tech/20220518 Install Specific Package Version With Apt Command in Ubuntu.md
=> [手动选题][tech]: 20220518 Install Specific Package Version With Apt Command in Ubuntu.md

sources/tech/20220518 How To Reset Sudo Password In Ubuntu 22.04 - 20.04 LTS.md
=> [手动选题][tech]: 20220518 How To Reset Sudo Password In Ubuntu 22.04 - 20.04 LTS.md

sources/tech/20220518 How To Boot Into Rescue Mode Or Emergency Mode In Ubuntu 22.04 - 20.04 - 18.04.md
=> [手动选题][tech]: 20220518 How To Boot Into Rescue Mode Or Emergency Mode In Ubuntu 22.04 - 20.04 - 18.04.md

published/20220516 Fudgie- The Awesome Budgie Desktop is Coming to Fedora Linux Soon.md
@lkxed
https://linux.cn/article-14610-1.html
=> RP:published/20220516 Fudgie- The Awesome Budgie Desktop is Coming to Fedora Linux Soon.md

sources/tech/20220519 Use this open source screen reader on Windows.md
=> [手动选题][tech]: 20220519 Use this open source screen reader on Windows.md

sources/tech/20220519 Top 10 Essential Ubuntu Apps For Everyone in 2022.md
=> [手动选题][tech]: 20220519 Top 10 Essential Ubuntu Apps For Everyone in 2022.md

sources/talk/20220519 Near zero marginal cost societies and the impact on why we work.md
=> [手动选题][talk]: 20220519 Near zero marginal cost societies and the impact on why we work.md

sources/tech/20220519 For the Love of Ubuntu- Here are the Mascots of All Ubuntu Releases.md
=> [手动选题][tech]: 20220519 For the Love of Ubuntu- Here are the Mascots of All Ubuntu Releases.md

published/20220517 Adobe Illustrator Alternative Inkscape Releases Version 1.2.md
@lkxed
https://linux.cn/article-14615-1.html
=> RP:published/20220517 Adobe Illustrator Alternative Inkscape Releases Version 1.2.md

published/20220510 HydraPaper- A Wallpaper Manager for Linux with Multi-Monitor Support.md
@geekpi
https://linux.cn/article-14616-1.html
=> RP:published/20220510 HydraPaper- A Wallpaper Manager for Linux with Multi-Monitor Support.md

published/20220519 How To Enable Activate Linux Watermark Notification In Linux Desktop.md
@lkxed
https://linux.cn/article-14617-1.html
=> RP:published/20220519 How To Enable Activate Linux Watermark Notification In Linux Desktop.md

sources/tech/20210305 Build a printer UI for Raspberry Pi with XML and Java.md
=> Update 20210305 Build a printer UI for Raspberry Pi with XML and Java.md

sources/tech/20220520 Add, Delete And Grant Sudo Privileges To Users In Fedora 36.md
=> [手动选题][tech]: 20220520 Add, Delete And Grant Sudo Privileges To Users In Fedora 36.md

sources/tech/20220520 How to rename a branch, delete a branch, and find the author of a branch in Git.md
=> [手动选题][tech]: 20220520 How to rename a branch, delete a branch, and find the author of a branch in Git.md

sources/tech/20220520 Ubuntu vs Manjaro- Comparing the Different Linux Experiences.md
=> [手动选题][tech]: 20220520 Ubuntu vs Manjaro- Comparing the Different Linux Experiences.md

sources/tech/20220520 How to rename a branch, delete a branch, and find the author of a branch in Git.md
=> [申领原文][tech]: 20220520 How to rename a branch, delete a branch, and find the author of a branch in Git.md

sources/tech/20210207 3 ways to play video games on Linux.md
=> Update 20210207 3 ways to play video games on Linux.md

sources/tech/20180523 Creating random, secure passwords in Go.md
=> [手动选题][tech]: 20180523 Creating random, secure passwords in Go.md

sources/tech/20180712 An introduction to Go arrays and slices.md
=> [手动选题][tech]: 20180712 An introduction to Go arrays and slices.md

sources/tech/20180625 3 ways to copy files in Go.md
=> [手动选题][tech]: 20180625 3 ways to copy files in Go.md

sources/tech/20180625 3 ways to copy files in Go.md
=> [申领原文][tech]: 20180625 3 ways to copy files in Go.md

sources/tech/20180712 An introduction to Go arrays and slices.md
=> [申领原文][tech]: 20180712 An introduction to Go arrays and slices.md

sources/tech/20220520 Customize GNOME 42 with A Polished Look.md
=> [手动选题][tech]: 20220520 Customize GNOME 42 with A Polished Look.md

published/20210305 Build a printer UI for Raspberry Pi with XML and Java.md, translated/tech/20210305 Build a printer UI for Raspberry Pi with XML and Java.md
@CoWave-Fall
本文首发地址：https://linux.cn/article-14620-1.html
您的 LCTT 专页：https://linux.cn/lctt/CoWave-Fall
=> RP:20210305 build a printer UI for raspberry pi with xml and java

published/20180523 Creating random, secure passwords in Go.md
@lkxed
https://linux.cn/article-14621-1.html
=> RP:published/20180523 Creating random, secure passwords in Go.md

sources/news/20220521 FSF Does Not Accept Debian as a Free Distribution. Here-s Why!.md
=> [手动选题][news]: 20220521 FSF Does Not Accept Debian as a Free Distribution. Here-s Why!.md

published/20180529 Build a concurrent TCP server in Go.md
@lkxed
https://linux.cn/article-14623-1.html
=> RP:published/20180529 Build a concurrent TCP server in Go.md

sources/tech/20220522 Ultramarine Linux- Ultimate Fedora Spin with Budgie, Cutefish and Pantheon.md
=> [手动选题][tech]: 20220522 Ultramarine Linux- Ultimate Fedora Spin with Budgie, Cutefish and Pantheon.md

sources/news/20220523 Linux Kernel 5.18 Released with Graphics Driver Changes and New Hardware Support.md
=> [手动选题][news]: 20220523 Linux Kernel 5.18 Released with Graphics Driver Changes and New Hardware Support.md

sources/tech/20220523 -Speek!- - An Open-Source Chat App That Uses Tor.md
=> [手动选题][tech]: 20220523 -Speek!- - An Open-Source Chat App That Uses Tor.md

published/20220501 How to Install Classic GNOME Flashback in Ubuntu 22.04 LTS.md
@geekpi @turbokernel
https://linux.cn/article-14627-1.html
=> RP:published/20220501 How to Install Classic GNOME Flashback in Ubuntu 22.04 LTS.md

sources/talk/20220523 7 pieces of Linux advice for beginners.md
=> [手动选题][talk]: 20220523 7 pieces of Linux advice for beginners.md

sources/tech/20220523 A hands-on guide to images and containers for developers.md
=> [手动选题][tech]: 20220523 A hands-on guide to images and containers for developers.md

published/20220518 ONLYOFFICE 7.1 Release Adds ARM Compatibility, a New PDF Viewer, and More Features.md
@PeterPan0106
https://linux.cn/article-14630-1.html
=> RP:published/20220518 ONLYOFFICE 7.1 Release Adds ARM Compatibility, a New PDF Viewer, and More Features.md

published/20220516 Structured Data Processing with Spark SQL.md
@geekpi
https://linux.cn/article-14631-1.html
=> RP:published/20220516 Structured Data Processing with Spark SQL.md

sources/tech/20220524 12 essential Linux commands for beginners.md
=> [手动选题][tech]: 20220524 12 essential Linux commands for beginners.md

sources/tech/20220524 Build a Quarkus reactive application using Kubernetes Secrets.md
=> [手动选题][tech]: 20220524 Build a Quarkus reactive application using Kubernetes Secrets.md

sources/tech/20220524 Collision- Linux App to Verify ISO and Other Files.md
=> [手动选题][tech]: 20220524 Collision- Linux App to Verify ISO and Other Files.md

sources/news/20220524 Woah! Broadcom Could Acquire VMware for $60 Billion.md
=> [手动选题][news]: 20220524 Woah! Broadcom Could Acquire VMware for $60 Billion.md

sources/tech/20220524 How to Install KVM on Ubuntu 22.04 -Jammy Jellyfish-.md
=> [手动选题][tech]: 20220524 How to Install KVM on Ubuntu 22.04 -Jammy Jellyfish-.md

published/20220520 How to rename a branch, delete a branch, and find the author of a branch in Git.md
@lkxed
https://linux.cn/article-14635-1.html
=> RP:published/20220520 How to rename a branch, delete a branch, and find the author of a branch in Git.md

sources/news/20220525 Open Source Initiative Releases News Blog On WordPress.md
=> [手动选题][news]: 20220525 Open Source Initiative Releases News Blog On WordPress.md

sources/tech/20220525 Package is -set to manually installed-- What does it Mean-.md
=> [手动选题][tech]: 20220525 Package is -set to manually installed-- What does it Mean-.md

sources/tech/20220524 The Basic Concepts of Shell Scripting.md
=> [手动选题][tech]: 20220524 The Basic Concepts of Shell Scripting.md

sources/tech/20220525 Machine Learning- Classification Using Python.md
=> [手动选题][tech]: 20220525 Machine Learning- Classification Using Python.md

published/20220516 How To Reset Root Password In Fedora 36.md
@geekpi @turbokernel
https://linux.cn/article-14638-1.html
=> P:published/20220516 How To Reset Root Password In Fedora 36.md

sources/tech/20220526 Document your source code with Doxygen on Linux.md
=> [手动选题][tech]: 20220526 Document your source code with Doxygen on Linux.md

sources/tech/20220526 Write C applications using Vely on Linux.md
=> [手动选题][tech]: 20220526 Write C applications using Vely on Linux.md

sources/news/20220526 Plex Desktop Player is Now Available for Linux.md
=> [手动选题][news]: 20220526 Plex Desktop Player is Now Available for Linux.md

sources/tech/20220526 Shell Scripting is Still Going Strong.md
=> [手动选题][tech]: 20220526 Shell Scripting is Still Going Strong.md

sources/tech/20220526 Garuda Linux- All-Rounder Distro Based on Arch Linux.md
=> [手动选题][tech]: 20220526 Garuda Linux- All-Rounder Distro Based on Arch Linux.md

sources/news/20220526 DeepMind-s Open Source MuJoCo Is Available On GitHub.md
=> [手动选题][news]: 20220526 DeepMind-s Open Source MuJoCo Is Available On GitHub.md

published/20220518 Google To Start Distributing A Collection Of Open Source Software libraries.md, translated/news/20220518 Google To Start Distributing A Collection Of Open Source Software libraries.md
@beamrolling
https://linux.cn/article-14641-1.html
=> 20220518 google to start distributing a collection of open source software libraries

published/20220514 How To Install Multimedia Codecs In Fedora Linux.md
@robsean
https://linux.cn/article-14642-1.html
=> RP:published/20220514 How To Install Multimedia Codecs In Fedora Linux.md

sources/news/20220527 AlmaLinux Continues the Legacy of CentOS with the Release of Version 9.md
=> [手动选题][news]: 20220527 AlmaLinux Continues the Legacy of CentOS with the Release of Version 9.md

sources/tech/20220527 Plotting Data in R- Graphs.md
=> [手动选题][tech]: 20220527 Plotting Data in R- Graphs.md

sources/news/20220527 TypeScript Based Headless CMS -Payload- Becomes Open Source.md
=> [手动选题][news]: 20220527 TypeScript Based Headless CMS -Payload- Becomes Open Source.md

sources/news/20220527 Tails Linux Users Warned Against Using the Tor Browser- Here-s why!.md
=> [手动选题][news]: 20220527 Tails Linux Users Warned Against Using the Tor Browser- Here-s why!.md

sources/tech/20220528 Top 10 GNOME Themes for Your Ubuntu Desktop.md
=> [手动选题][tech]: 20220528 Top 10 GNOME Themes for Your Ubuntu Desktop.md

published/20220527 AlmaLinux Continues the Legacy of CentOS with the Release of Version 9.md
@PeterPan0106
https://linux.cn/article-14644-1.html
=> RP:published/20220527 AlmaLinux Continues the Legacy of CentOS with the Release of Version 9.md

sources/news/20220524 Woah! Broadcom Could Acquire VMware for $60 Billion.md
=> [申领原文][news]: 20220524 Woah! Broadcom Could Acquire VMware for $60 Billion.md

sources/tech/20220528 Portmaster- A GlassWire Alternative for Linux to Monitor & Secure Network Connections.md
=> [手动选题][tech]: 20220528 Portmaster- A GlassWire Alternative for Linux to Monitor & Secure Network Connections.md

sources/tech/20220528 How I automate plant care using Raspberry Pi and open source tools.md
=> [手动选题][tech]: 20220528 How I automate plant care using Raspberry Pi and open source tools.md

published/20220523 System76 Collaborates with HP for a Powerful Linux Laptop for Developers.md
@lkxed
https://linux.cn/article-14645-1.html
=> RP:published/20220523 System76 Collaborates with HP for a Powerful Linux Laptop for Developers.md

published/20220518 How To Reset Sudo Password In Ubuntu 22.04 - 20.04 LTS.md
@robsean
https://linux.cn/article-14648-1.html
=> RP:published/20220518 How To Reset Sudo Password In Ubuntu 22.04 - 20.04 LTS.md

published/20220523 DAML- The Programming Language for Smart Contracts in a Blockchain.md
@geekpi
https://linux.cn/article-14649-1.html
=> RP:published/20220523 DAML- The Programming Language for Smart Contracts in a Blockchain.md

sources/tech/20220529 Compile GNOME Shell and Apps From Source [Beginner-s Guide].md
=> [手动选题][tech]: 20220529 Compile GNOME Shell and Apps From Source [Beginner-s Guide].md

sources/news/20220525 ProtonMail is Now Just -Proton- Offering a Privacy Ecosystem.md
=> [申领原文][news]: 20220525 ProtonMail is Now Just -Proton- Offering a Privacy Ecosystem.md

published/20220526 DeepMind-s Open Source MuJoCo Is Available On GitHub.md
@lkxed
https://linux.cn/article-14650-1.html
=> RP:published/20220526 DeepMind-s Open Source MuJoCo Is Available On GitHub.md

published/20220525 ProtonMail is Now Just -Proton- Offering a Privacy Ecosystem.md
@lkxed
https://linux.cn/article-14652-1.html
=> RP:published/20220525 ProtonMail is Now Just -Proton- Offering a Privacy Ecosystem.md

sources/tech/20220530 Using a Machine Learning Model to Make Predictions.md
=> [手动选题][tech]: 20220530 Using a Machine Learning Model to Make Predictions.md

sources/news/20220526 Plex Desktop Player is Now Available for Linux.md
=> [申领原文][news]: 20220526 Plex Desktop Player is Now Available for Linux.md

sources/news/20220527 Tails Linux Users Warned Against Using the Tor Browser- Here-s why!.md
=> [申领原文][news]: 20220527 Tails Linux Users Warned Against Using the Tor Browser- Here-s why!.md

published/20220527 Tails Linux Users Warned Against Using the Tor Browser- Here-s why!.md
@lkxed
https://linux.cn/article-14654-1.html
=> RP:published/20220527 Tails Linux Users Warned Against Using the Tor Browser- Here-s why!.md

sources/news/20220530 Surfshark VPN Now Offers a Full-fledged GUI App for Linux.md
=> [手动选题][news]: 20220530 Surfshark VPN Now Offers a Full-fledged GUI App for Linux.md

sources/tech/20220530 Dynamically linking libraries while compiling code.md
=> [手动选题][tech]: 20220530 Dynamically linking libraries while compiling code.md

sources/tech/20220530 11 Themes to Make Xfce Look Modern and Beautiful.md
=> [手动选题][tech]: 20220530 11 Themes to Make Xfce Look Modern and Beautiful.md

sources/tech/20220530 Top 10 Linux Distributions for Windows Users in 2022.md
=> [手动选题][tech]: 20220530 Top 10 Linux Distributions for Windows Users in 2022.md

sources/news/20220527 TypeScript Based Headless CMS -Payload- Becomes Open Source.md
=> [申领原文][news]: 20220527 TypeScript Based Headless CMS -Payload- Becomes Open Source.md

sources/news/20220531 Rocket.Chat is Switching to Matrix to Enable Cross-App Messaging.md
=> [手动选题][news]: 20220531 Rocket.Chat is Switching to Matrix to Enable Cross-App Messaging.md

published/20220526 Plex Desktop Player is Now Available for Linux.md
@lkxed
https://linux.cn/article-14656-1.html
=> RP:published/20220526 Plex Desktop Player is Now Available for Linux.md

published/20180625 3 ways to copy files in Go.md
@lkxed
https://linux.cn/article-14658-1.html
=> RP:published/20180625 3 ways to copy files in Go.md

sources/tech/20220531 How dynamic linking for modular libraries works on Linux.md
=> [手动选题][tech]: 20220531 How dynamic linking for modular libraries works on Linux.md

published/20220527 TypeScript Based Headless CMS -Payload- Becomes Open Source.md
@lkxed
https://linux.cn/article-14660-1.html
=> RP:published/20220527 TypeScript Based Headless CMS -Payload- Becomes Open Source.md

sources/news/20220601 Linux Lite 6.0 Ditches Firefox to Favor Google Chrome as the Default Browser.md
=> [手动选题][news]: 20220601 Linux Lite 6.0 Ditches Firefox to Favor Google Chrome as the Default Browser.md

sources/tech/20220601 A visual guide to Kubernetes networking fundamentals.md
=> [手动选题][tech]: 20220601 A visual guide to Kubernetes networking fundamentals.md

sources/tech/20220601 Linux desktops- KDE vs GNOME.md
=> [手动选题][tech]: 20220601 Linux desktops- KDE vs GNOME.md

published/20220524 How to Install KVM on Ubuntu 22.04 -Jammy Jellyfish-.md, translated/tech/20220524 How to Install KVM on Ubuntu 22.04 -Jammy Jellyfish-.md
@turbokernel
本文首发地址：https://linux.cn/article-14661-1.html
您的 LCTT 专页：https://linux.cn/lctt/turbokernel
=> RP:20220524 how to install kvm on ubuntu 22.04  jammy jellyfish 

published/20220529 Compile GNOME Shell and Apps From Source [Beginner-s Guide].md
@geekpi
https://linux.cn/article-14662-1.html
=> RP:published/20220529 Compile GNOME Shell and Apps From Source [Beginner-s Guide].md

sources/news/20220601 de-Googled -e-OS v1 Released Along with a New Brand -Murena- for Smartphone and Cloud Services.md
=> [手动选题][news]: 20220601 de-Googled -e-OS v1 Released Along with a New Brand -Murena- for Smartphone and Cloud Services.md

sources/news/20220601 Google Makes Data Centre Scale Encryption Open Source.md
=> [手动选题][news]: 20220601 Google Makes Data Centre Scale Encryption Open Source.md

sources/tech/20220601 What is Federated Learning-.md
=> [手动选题][tech]: 20220601 What is Federated Learning-.md

published/20180712 An introduction to Go arrays and slices.md
@lkxed
https://linux.cn/article-14665-1.html
=> RP:published/20180712 An introduction to Go arrays and slices.md

sources/tech/20220602 Get started with Cadence, an open source workflow engine.md
=> [手动选题][tech]: 20220602 Get started with Cadence, an open source workflow engine.md

sources/tech/20220602 The only Linux command you need to know.md
=> [手动选题][tech]: 20220602 The only Linux command you need to know.md

sources/news/20220602 Linux Mint to Maintain Timeshift Backup Tool as an XApp.md
=> [手动选题][news]: 20220602 Linux Mint to Maintain Timeshift Backup Tool as an XApp.md

sources/tech/20220602 Creating a GitHub Action from Scratch.md
=> [手动选题][tech]: 20220602 Creating a GitHub Action from Scratch.md

sources/tech/20220603 How to Install FFmpeg in Ubuntu and Other Linux.md
=> [手动选题][tech]: 20220603 How to Install FFmpeg in Ubuntu and Other Linux.md

sources/tech/20220603 Titan Linux- A Blend of Debian Stable and KDE Plasma.md
=> [手动选题][tech]: 20220603 Titan Linux- A Blend of Debian Stable and KDE Plasma.md

sources/talk/20220602 Why Do Enterprises Use and Contribute to Open Source Software.md
=> [手动选题][talk]: 20220602 Why Do Enterprises Use and Contribute to Open Source Software.md

sources/tech/20220603 Fedora Linux editions part 1- Official Editions.md
=> [手动选题][tech]: 20220603 Fedora Linux editions part 1- Official Editions.md

sources/news/20220603 Spotify Introduces an Open-Source Tool to Fix a Big Problem for Modern Musicians.md
=> [手动选题][news]: 20220603 Spotify Introduces an Open-Source Tool to Fix a Big Problem for Modern Musicians.md

sources/tech/20220603 How static linking works on Linux.md
=> [手动选题][tech]: 20220603 How static linking works on Linux.md

sources/tech/20220603 Red Hat Tests The -NVK- Nouveau Open Source Vulkan Driver.md
=> [手动选题][tech]: 20220603 Red Hat Tests The -NVK- Nouveau Open Source Vulkan Driver.md

sources/tech/20220603 Simplifying Cloud Native Development with Skaffold.md
=> [手动选题][tech]: 20220603 Simplifying Cloud Native Development with Skaffold.md

sources/tech/20220604 KDE Plasma 5.25- Top New Features and Release Details.md
=> [手动选题][tech]: 20220604 KDE Plasma 5.25- Top New Features and Release Details.md

sources/tech/20220603 Kubecost Releases Open Source Project To Rein in K8s Costs.md
=> [手动选题][tech]: 20220603 Kubecost Releases Open Source Project To Rein in K8s Costs.md

sources/talk/20220604 Attract contributors to your open source project with authenticity.md
=> [手动选题][talk]: 20220604 Attract contributors to your open source project with authenticity.md

published/20220525 Package is -set to manually installed-- What does it Mean-.md
@geekpi
https://linux.cn/article-14675-1.html
=> RP:published/20220525 Package is -set to manually installed-- What does it Mean-.md

published/20220525 Machine Learning- Classification Using Python.md
@geekpi
https://linux.cn/article-14676-1.html
=> RP:published/20220525 Machine Learning- Classification Using Python.md

sources/tech/20220606 10 Best Ubuntu Apps for Everyone in 2022 [Part 2].md
=> [手动选题][tech]: 20220606 10 Best Ubuntu Apps for Everyone in 2022 [Part 2].md

sources/news/20220605 Contribute at the Fedora Linux 37 Test Week for Kernel 5.18.md
=> [手动选题][news]: 20220605 Contribute at the Fedora Linux 37 Test Week for Kernel 5.18.md

sources/tech/20220606 6 Linux word processors you need to try.md
=> [手动选题][tech]: 20220606 6 Linux word processors you need to try.md

sources/tech/20220606 A Drupal developer-s guide to Progressive Web Apps.md
=> [手动选题][tech] 20220606 A Drupal developer-s guide to Progressive Web Apps.md

sources/tech/20220606 Amberol is a Stunning Looking Music Player for Linux That Just Plays Music and Nothing Else.md
=> [手动选题][tech]: 20220606 Amberol is a Stunning Looking Music Player for Linux That Just Plays Music and Nothing Else.md

sources/news/20220606 Cloud Storage Service Internxt Has a Photos Feature as a Google Photos Alternative.md
=> [手动选题][news]: 20220606 Cloud Storage Service Internxt Has a Photos Feature as a Google Photos Alternative.md

sources/news/20220607 Linux Kernel 5.19 RC1 Released, Concluding ARM Generic Kernel Work.md
=> [手动选题][news]: 20220607 Linux Kernel 5.19 RC1 Released, Concluding ARM Generic Kernel Work.md

sources/tech/20220607 Integrating Zeek with ELK Stack.md
=> [手动选题][tech]: 20220607 Integrating Zeek with ELK Stack.md

sources/news/20220605 Contribute at the Fedora Linux 37 Test Week for Kernel 5.18.md
=> [申领原文][news]: 20220605 Contribute at the Fedora Linux 37 Test Week for Kernel 5.18.md

sources/tech/20220607 How Garbage Collection works inside a Java Virtual Machine.md
=> [手动选题][tech]: 20220607 How Garbage Collection works inside a Java Virtual Machine.md

sources/tech/20220607 How to Boot Ubuntu 22.04 into Rescue - Emergency Mode.md
=> [手动选题][tech]: 20220607 How to Boot Ubuntu 22.04 into Rescue - Emergency Mode.md

sources/tech/20220607 How Garbage Collection works inside a Java Virtual Machine.md
=> [申领原文][tech]: 20220607 How Garbage Collection works inside a Java Virtual Machine.md

published/20210405 How different programming languages do the same thing.md
@VeryZZJ
https://linux.cn/article-14687-1.html
=> RP:published/20210405 How different programming languages do the same thing.md

sources/tech/20220608 How I gave my old laptop new life with the Linux Xfce desktop.md
=> [手动选题][tech]: 20220608 How I gave my old laptop new life with the Linux Xfce desktop.md

sources/tech/20220608 Using Ansible to automate software installation on my Mac.md
=> [手动选题][tech]: 20220608 Using Ansible to automate software installation on my Mac.md

sources/tech/20220608 Rufus for Linux- Here Are the Best Live USB Creating Tools.md
=> [手动选题][tech]: 20220608 Rufus for Linux- Here Are the Best Live USB Creating Tools.md

sources/talk/20220510 6 easy ways to make your first open source contribution with LibreOffice.md
=>  [申领原文]20220510 6 easy ways to make your first open source contribution with LibreOffice

published/20220530 Using a Machine Learning Model to Make Predictions.md
@geekpi
https://linux.cn/article-14689-1.html
=> RP:published/20220530 Using a Machine Learning Model to Make Predictions.md

sources/news/20220609 openSUSE Leap 15.4 Release Adds Leap Micro 5.2, Updated Desktop Environments, and More.md
=> [手动选题][news]: 20220609 openSUSE Leap 15.4 Release Adds Leap Micro 5.2, Updated Desktop Environments, and More.md

sources/tech/20220609 Edit PDFs on Linux with these open source tools.md
=> [手动选题][tech]: 20220609 Edit PDFs on Linux with these open source tools.md

sources/tech/20220609 A guide to container orchestration with Kubernetes.md
=> [手动选题][tech]: 20220609 A guide to container orchestration with Kubernetes.md

sources/tech/20210319 Create a countdown clock with a Raspberry Pi.md
=> Update 20210319 Create a countdown clock with a Raspberry Pi.md

published/20220607 Linux Kernel 5.19 RC1 Released, Concluding ARM Generic Kernel Work.md, translated/news/20220607 Linux Kernel 5.19 RC1 Released, Concluding ARM Generic Kernel Work.md
@Donkey-Hao
本文首发地址：https://linux.cn/article-14692-1.html
您的 LCTT 专页：https://linux.cn/lctt/Donkey-Hao
=> RP:20220607 linux kernel 5.19 rc1 released, concluding arm generic kernel work

sources/tech/20220610 Handling maps in Groovy vs Java.md
=> [手动选题][tech]: 20220610 Handling maps in Groovy vs Java.md

sources/news/20220610 To Favor Microsoft VS Code, Microsoft-s GitHub is Killing GitHub-s Atom Editor.md
=> [手动选题][news]: 20220610 To Favor Microsoft VS Code, Microsoft-s GitHub is Killing GitHub-s Atom Editor.md

sources/tech/20220610 Manage Flatpak Permission Using Flatseal.md
=> [手动选题][tech]: 20220610 Manage Flatpak Permission Using Flatseal.md

sources/tech/20220610 Run Windows Apps And Games Using WineZGUI On Linux.md
=> [手动选题][tech]: 20220610 Run Windows Apps And Games Using WineZGUI On Linux.md

published/20220514 Hidden Features! 25 Fun Things You Can Do With DuckDuckGo Search Engine.md
@TravinDreek
https://linux.cn/article-14696-1.html
=> RP:published/20220514 Hidden Features! 25 Fun Things You Can Do With DuckDuckGo Search Engine.md

sources/tech/20220611 Don-t Be Afraid of Linux Terminal. Embrace it..md
=> [手动选题][tech]: 20220611 Don-t Be Afraid of Linux Terminal. Embrace it..md

published/20220601 How to Create Local Yum-DNF Repository on RHEL 9.md
@geekpi
https://linux.cn/article-14697-1.html
=> RP:published/20220601 How to Create Local Yum-DNF Repository on RHEL 9.md

sources/news/20220607 OpenInfra Foundation Launches -directed funding- To Support Open Source Projects.md
=> [申领原文][news]: 20220607 OpenInfra Foundation Launches -directed funding- To Support Open Source Projects.md

sources/news/20220609 Cloudflare Has Something New to Replace Annoying CAPTCHAs on the Internet.md
=> [申领原文][news]: 20220609 Cloudflare Has Something New to Replace Annoying CAPTCHAs on the Internet.md

sources/tech/20210503 Learn the Lisp programming language in 2021.md
Update 20210503 Learn the Lisp programming language in 2021.md
修正代码块中的 URL 编码问题，同步作者的内容更新。
=> 清理 & 更新文章内容

sources/tech/20220612 LibreOffice 7.4- Top New Features and Release Details.md
=> [手动选题][tech]: 20220612 LibreOffice 7.4- Top New Features and Release Details.md

sources/tech/20210722 Write your first JavaScript code.md
=> [申领原文][tech]: 20210722 Write your first JavaScript code.md

sources/tech/20220613 Use Terraform to manage TrueNAS.md
=> [手动选题][tech]: 20220613 Use Terraform to manage TrueNAS.md

sources/tech/20220613 A Quick Look at Cloud Cost Management Tools.md
=> [手动选题][tech]: 20220613 A Quick Look at Cloud Cost Management Tools.md

sources/tech/20210503 Learn the Lisp programming language in 2021.md
=> [申领原文][tech]: 20210503 Learn the Lisp programming language in 2021.md

sources/tech/20210104 Docker Compose- a nice way to set up a dev environment.md
=> [申领原文][tech]: 20210104 Docker Compose- a nice way to set up a dev environment.md

sources/tech/20220614 Share your Linux terminal with tmate.md
=> [手动选题][tech]: 20220614 Share your Linux terminal with tmate.md

sources/news/20220614 Adobe Launches Open Source Toolkit To Contain Visual Misinformation.md
=> [手动选题][news]: 20220614 Adobe Launches Open Source Toolkit To Contain Visual Misinformation.md

sources/tech/20220614 Build a Smart Parking System for a Metro Station.md
=> [手动选题][tech]: 20220614 Build a Smart Parking System for a Metro Station.md

sources/news/20220614 Thunderbird, The Open Source Email Client, Is Coming To Android.md
=> [手动选题][news]: 20220614 Thunderbird, The Open Source Email Client, Is Coming To Android.md

sources/tech/20220614 Distrobox- Try Multiple Linux Distributions via the Terminal.md
=> [手动选题][tech]: 20220614 Distrobox- Try Multiple Linux Distributions via the Terminal.md

sources/news/20220614 Thunderbird, The Open Source Email Client, Is Coming To Android.md
=> [申领原文][news]: 20220614 Thunderbird, The Open Source Email Client, Is Coming To Android.md

sources/news/20220614 Adobe Launches Open Source Toolkit To Contain Visual Misinformation.md
=> [申领原文][news]: 20220614 Adobe Launches Open Source Toolkit To Contain Visual Misinformation.md

sources/tech/20220615 A beginner-s guide to cloud-native open source communities.md
=> [手动选题][tech]: 20220615 A beginner-s guide to cloud-native open source communities.md

sources/news/20220615 According to studies, Twitter Drives Open Source Projects Popularity.md
=> [手动选题][news]: 20220615 According to studies, Twitter Drives Open Source Projects Popularity.md

sources/news/20220615 Mozilla Just Made Firefox the Most Secure Web Browser for All Users.md
=> [手动选题][news]: 20220615 Mozilla Just Made Firefox the Most Secure Web Browser for All Users.md

published/20220614 Thunderbird, The Open Source Email Client, Is Coming To Android.md
@lkxed
https://linux.cn/article-14715-1.html
=> RP:published/20220614 Thunderbird, The Open Source Email Client, Is Coming To Android.md

sources/talk/20220510 6 easy ways to make your first open source contribution with LibreOffice.md
Reverts LCTT/TranslateProject#25972
=> Revert " [申领原文]20220510 6 easy ways to make your first open source contribution with LibreOffice"

published/20220603 How to Install FFmpeg in Ubuntu and Other Linux.md
@aREversez
https://linux.cn/article-14716-1.html
=> RP:published/20220603 How to Install FFmpeg in Ubuntu and Other Linux.md

sources/talk/20220615 SBOM – SB Doesn-t Stand for Silver Bullet.md
=> [手动选题][talk]: 20220615 SBOM – SB Doesn-t Stand for Silver Bullet.md

sources/news/20220614 KDE Plasma 5.25 Release is All About Color, Theme, and Other Improvements.md
=> [申领原文][news]: 20220614 KDE Plasma 5.25 Release is All About Color, Theme, and Other Improvements.md

published/20220613 Thonny is an Ideal IDE for Teaching Python Programming in Schools.md
@geekpi
https://linux.cn/article-14717-1.html
=> RP:published/20220613 Thonny is an Ideal IDE for Teaching Python Programming in Schools.md

sources/talk/20220616 Using habits to practice open organization principles.md
=> [手动选题][talk]: 20220616 Using habits to practice open organization principles.md

sources/tech/20220616 Analyze web pages with Python requests and Beautiful Soup.md
=> [手动选题][tech]: 20220616 Analyze web pages with Python requests and Beautiful Soup.md

sources/tech/20220616 Analyze web pages with Python requests and Beautiful Soup.md
=> [申领原文][tech]: 20220616 Analyze web pages with Python requests and Beautiful Soup.md

sources/news/20220615 Mozilla Just Made Firefox the Most Secure Web Browser for All Users.md
=> [申领原文][news]: 20220615 Mozilla Just Made Firefox the Most Secure Web Browser for All Users.md

sources/news/20220615 According to studies, Twitter Drives Open Source Projects Popularity.md
=> [申领原文][news]: 20220615 According to studies, Twitter Drives Open Source Projects Popularity.md

sources/talk/20220616 -It-s time to contribute to open source-.md
=> [手动选题][talk]: 20220616 -It-s time to contribute to open source-.md

sources/news/20220616 Ubuntu Core 22 is Here for IoT and Edge Devices.md
=> [手动选题][news]: 20220616 Ubuntu Core 22 is Here for IoT and Edge Devices.md

sources/news/20220616 The Travis CI Vulnerability Exposes Sensitive Open Source Project Credentials.md
=> [手动选题][news]: 20220616 The Travis CI Vulnerability Exposes Sensitive Open Source Project Credentials.md

sources/tech/20220616 Voyager Live- Ubuntu LTS Spin with Immersive Experience.md
=> [手动选题][tech]: 20220616 Voyager Live- Ubuntu LTS Spin with Immersive Experience.md

sources/news/20220616 Mattermost Extends workflow platform with 7.0 release.md
=> [手动选题][news]: 20220616 Mattermost Extends workflow platform with 7.0 release.md

sources/talk/20220510 6 easy ways to make your first open source contribution with LibreOffice.md
Reverts LCTT/TranslateProject#26066
=> Revert "Revert " [申领原文]20220510 6 easy ways to make your first open source contribution with LibreOffice""

sources/tech/20220616 9 Best Matrix Clients for Decentralized Messaging.md
=> [手动选题][tech]: 20220616 9 Best Matrix Clients for Decentralized Messaging.md

sources/news/20220616 Ubuntu Core 22 is Here for IoT and Edge Devices.md
=> [申领原文][news]: 20220616 Ubuntu Core 22 is Here for IoT and Edge Devices.md

sources/news/20220616 Mattermost Extends workflow platform with 7.0 release.md
=> [申领原文][news]: 20220616 Mattermost Extends workflow platform with 7.0 release.md

sources/news/20220617 Ubuntu Runs on a Google Nest Hub, Wait, What-.md
=> [手动选题][news]: 20220617 Ubuntu Runs on a Google Nest Hub, Wait, What-.md

sources/tech/20220617 Fedora Workstation-s State of Gaming – A Case Study of Far Cry 5 -2018-.md
=> [手动选题][tech]: 20220617 Fedora Workstation-s State of Gaming – A Case Study of Far Cry 5 -2018-.md

sources/talk/20220617 What scrum masters can learn from dancing.md
=> [手动选题][talk]: 20220617 What scrum masters can learn from dancing.md

sources/tech/20220617 Containerisation of Java Microservices.md
=> [手动选题][tech]: 20220617 Containerisation of Java Microservices.md

sources/tech/20211102 Apache Kafka- Asynchronous Messaging for Seamless Systems.md
=> [手动选题][tech]: 20211102 Apache Kafka- Asynchronous Messaging for Seamless Systems.md

sources/tech/20220617 Containerisation of Java Microservices.md
=> [申领原文][tech]: 20220617 Containerisation of Java Microservices.md

sources/tech/20211102 Apache Kafka- Asynchronous Messaging for Seamless Systems.md
=> [申领原文][tech]: 20211102 Apache Kafka- Asynchronous Messaging for Seamless Systems.md

published/20220615 Mozilla Just Made Firefox the Most Secure Web Browser for All Users.md
@lkxed
https://linux.cn/article-14723-1.html
=> RP:published/20220615 Mozilla Just Made Firefox the Most Secure Web Browser for All Users.md

published/20220616 The Travis CI Vulnerability Exposes Sensitive Open Source Project Credentials.md
@lkxed
https://linux.cn/article-14724-1.html
=> RP:published/20220616 The Travis CI Vulnerability Exposes Sensitive Open Source Project Credentials.md

sources/tech/20210107 A hands-on tutorial for using the GNU Project Debugger.md
=> 超期回收: sources/tech/20210107 A hands-on tutorial for using the GNU Project Debugger.md

sources/tech/20220618 How Wordle inspired me to create a 3D printing wiki the open source way.md
=> [手动选题][tech]: 20220618 How Wordle inspired me to create a 3D printing wiki the open source way.md

sources/tech/20220619 Rocket.Chat vs. Slack- Choosing the Perfect Team Collaboration App.md
=> [手动选题][tech]: 20220619 Rocket.Chat vs. Slack- Choosing the Perfect Team Collaboration App.md

published/20220614 Adobe Launches Open Source Toolkit To Contain Visual Misinformation.md
@lkxed
https://linux.cn/article-14729-1.html
=> RP:published/20220614 Adobe Launches Open Source Toolkit To Contain Visual Misinformation.md

published/20220616 Ubuntu Core 22 is Here for IoT and Edge Devices.md
@lkxed
https://linux.cn/article-14730-1.html
=> RP:published/20220616 Ubuntu Core 22 is Here for IoT and Edge Devices.md

published/20210319 Create a countdown clock with a Raspberry Pi.md
@Donkey-Hao
https://linux.cn/article-14731-1.html
=> RP:published/20210319 Create a countdown clock with a Raspberry Pi.md

sources/tech/20220619 Top 10 App Launchers for Ubuntu & GNOME Desktop [With Bonus List].md
=> [手动选题][tech]: 20220619 Top 10 App Launchers for Ubuntu & GNOME Desktop [With Bonus List].md

sources/tech/20220620 Compress Images in Linux Easily With Curtail GUI App.md
=> [手动选题][tech]: 20220620 Compress Images in Linux Easily With Curtail GUI App.md

published/20220610 Manage Flatpak Permission Using Flatseal.md
@geekpi
https://linux.cn/article-14736-1.html
=> RP:published/20220610 Manage Flatpak Permission Using Flatseal.md

sources/tech/20220620 How I use the attr command with my Linux filesystem.md
=> [手动选题][tech]: 20220620 How I use the attr command with my Linux filesystem.md

sources/tech/20220620 What you need to know about site reliability engineering.md
=> [手动选题][tech]: 20220620 What you need to know about site reliability engineering.md

sources/news/20220620 Microsoft To Charge For Available Open Source Software In Microsoft Store.md
=> [手动选题][news]: 20220620 Microsoft To Charge For Available Open Source Software In Microsoft Store.md

sources/tech/20220620 Are Low-Code Platforms Helpful for Professional Developers-.md
=> [手动选题][tech]: 20220620 Are Low-Code Platforms Helpful for Professional Developers-.md

sources/tech/20220620 Please – A Simple Command Line Todo Manager.md
=> [手动选题][tech]: 20220620 Please – A Simple Command Line Todo Manager.md

sources/tech/20220620 The First Commercial Unikernel With POSIX Support.md
=> [手动选题][tech]: 20220620 The First Commercial Unikernel With POSIX Support.md

published/20220616 Mattermost Extends workflow platform with 7.0 release.md
@lkxed
https://linux.cn/article-14738-1.html
要减少这种带有软文性质的选题，这个网站经常有这种选题。
=> RP:published/20220616 Mattermost Extends workflow platform with 7.0 release.md

published/20210722 Write your first JavaScript code.md
@lkxed
https://linux.cn/article-14740-1.html
=> RP:published/20210722 Write your first JavaScript code.md

sources/news/20220621 Mysterious GeckoLinux Creator Reveals a New Debian Remix Distro.md
=> [手动选题][news]: 20220621 Mysterious GeckoLinux Creator Reveals a New Debian Remix Distro.md

sources/talk/20220621 7 summer book recommendations from open source enthusiasts.md
=> [手动选题][talk]: 20220621 7 summer book recommendations from open source enthusiasts.md

sources/tech/20220621 An Introduction to Teradata.md
=> [手动选题][tech]: 20220621 An Introduction to Teradata.md

sources/news/20220621 This Open-Source Project Proves Chrome Extensions Can Track You.md
=> [手动选题][news]: 20220621 This Open-Source Project Proves Chrome Extensions Can Track You.md

sources/talk/20211203 Should Businesses Opt for Serverless Computing-.md
=> [手动选题][talk]: 20211203 Should Businesses Opt for Serverless Computing-.md

sources/talk/20211203 Should Businesses Opt for Serverless Computing-.md
=> [申领原文][talk]: 20211203 Should Businesses Opt for Serverless Computing-.md

published/20220610 Run Windows Apps And Games Using WineZGUI On Linux.md
@geekpi
https://linux.cn/article-14744-1.html
=> RP:published/20220610 Run Windows Apps And Games Using WineZGUI On Linux.md

sources/tech/20220622 Using Linux System Roles to implement Clevis and Tang for automated LUKS volume unlocking.md
=> [手动选题][tech]: 20220622 Using Linux System Roles to implement Clevis and Tang for automated LUKS volume unlocking.md

sources/tech/20220622 A site reliability engineer-s guide to change management.md
=> [手动选题][tech]: 20220622 A site reliability engineer-s guide to change management.md

sources/news/20220622 Rocket.Chat Aims to Replace Skype for Business by Collaborating with Pexip.md
=> [手动选题][news]: 20220622 Rocket.Chat Aims to Replace Skype for Business by Collaborating with Pexip.md

sources/tech/20220617 Containerisation of Java Microservices.md
Reverts LCTT/TranslateProject#26114
计划有变，暂时不打算翻译这一篇，先取消申请。
=> Revert "[申领原文][tech]: 20220617 Containerisation of Java Microservices.md"

sources/tech/20220623 Minetest, an Open Source Minecraft Alternative.md
=> [手动选题][tech]: 20220623 Minetest, an Open Source Minecraft Alternative.md

published/20210104 Docker Compose- a nice way to set up a dev environment.md
@lkxed @turbokernel
https://linux.cn/article-14747-1.html
=> P:published/20210104 Docker Compose- a nice way to set up a dev environment.md

published/20220620 Compress Images in Linux Easily With Curtail GUI App.md
@geekpi
https://linux.cn/article-14748-1.html
=> RP:published/20220620 Compress Images in Linux Easily With Curtail GUI App.md

sources/talk/20220623 Applying smart thinking to open organization principles.md
=> [手动选题][talk]: 20220623 Applying smart thinking to open organization principles.md

sources/news/20220620 Microsoft To Charge For Available Open Source Software In Microsoft Store.md
=> [申领原文][news]: 20220620 Microsoft To Charge For Available Open Source Software In Microsoft Store.md

published/20210503 Learn the Lisp programming language in 2021.md
@lkxed
https://linux.cn/article-14751-1.html
=> RP:published/20210503 Learn the Lisp programming language in 2021.md

sources/news/20220621 Mysterious GeckoLinux Creator Reveals a New Debian Remix Distro.md
=> [申领原文][news]: 20220621 Mysterious GeckoLinux Creator Reveals a New Debian Remix Distro.md

sources/tech/20220623 How to Boot into an Older Kernel By Default in Ubuntu and Other Linux.md
=> [手动选题][tech]: 20220623 How to Boot into an Older Kernel By Default in Ubuntu and Other Linux.md

sources/talk/20220624 Create a more diverse and equitable open source project with open standards.md
=> [手动选题][talk]: 20220624 Create a more diverse and equitable open source project with open standards.md

sources/tech/20220624 How I sketchnote with open source tools.md
=> [手动选题][tech]: 20220624 How I sketchnote with open source tools.md

sources/news/20220624 Linus Torvalds Expects to See Rust Support in the Kernel Soon.md
=> [手动选题][news]: 20220624 Linus Torvalds Expects to See Rust Support in the Kernel Soon.md

published/20220620 Manjaro 21.3.0 -Ruah- Release Adds Latest Calmares 3.2, GNOME 42, and More Upgrades.md
@lkxed
https://linux.cn/article-14754-1.html
=> RP:published/20220620 Manjaro 21.3.0 -Ruah- Release Adds Latest Calmares 3.2, GNOME 42, and More Upgrades.md

sources/tech/20220625 Linux Distros That Turn Your PC into Retro Gaming Console.md
=> [手动选题][tech]: 20220625 Linux Distros That Turn Your PC into Retro Gaming Console.md

sources/tech/20220626 Manjaro Linux Review- Detailed deep-dive with Performance, Hardware Support + More.md
=> [手动选题][tech]: 20220626 Manjaro Linux Review- Detailed deep-dive with Performance, Hardware Support + More.md

published/20220621 Mysterious GeckoLinux Creator Reveals a New Debian Remix Distro.md
@lkxed
https://linux.cn/article-14758-1.html
=> RP:published/20220621 Mysterious GeckoLinux Creator Reveals a New Debian Remix Distro.md

sources/tech/20220625 Download YouTube Videos with VLC -Because, Why Not--.md
=> [手动选题][tech]: 20220625 Download YouTube Videos with VLC -Because, Why Not--.md

published/20220609 Edit PDFs on Linux with these open source tools.md
@geekpi
https://linux.cn/article-14761-1.html
=> RP:published/20220609 Edit PDFs on Linux with these open source tools.md

sources/tech/20220626 An open source project that opens the internet for all.md
=> [手动选题][tech]: 20220626 An open source project that opens the internet for all.md

sources/tech/20220626 Linux Mint- The Beginner-Friendly Linux Operating System for Everyone.md
=> [手动选题][tech]: 20220626 Linux Mint- The Beginner-Friendly Linux Operating System for Everyone.md

published/20220624 Linus Torvalds Expects to See Rust Support in the Kernel Soon.md
@lkxed
https://linux.cn/article-14763-1.html
=> RP:published/20220624 Linus Torvalds Expects to See Rust Support in the Kernel Soon.md

sources/news/20220627 KaOS 2022.06 Release Adds KDE Plasma 5.25 and Sets LibreOffice as the Default.md
=> [手动选题][news]: 20220627 KaOS 2022.06 Release Adds KDE Plasma 5.25 and Sets LibreOffice as the Default.md

sources/talk/20220627 Accessibility in Fedora Workstation.md
=> [手动选题][talk]: 20220627 Accessibility in Fedora Workstation.md

published/20220621 The Final Version Of 7-Zip 22.00 Is Now Available.md
=> R:published/20220621 The Final Version Of 7-Zip 22.00 Is Now Available.md

sources/news/20220627 Red Hat Hires a Blind Software Engineer to Improve Accessibility on Linux Desktop.md
=> [手动选题][news]: 20220627 Red Hat Hires a Blind Software Engineer to Improve Accessibility on Linux Desktop.md

sources/tech/20220627 How to Install Docker And Docker Compose In Ubuntu 22.04 LTS.md
=> [手动选题][tech]: 20220627 How to Install Docker And Docker Compose In Ubuntu 22.04 LTS.md

sources/tech/20220627 Open Programmable Infrastructure- 1+1=3.md
=> [手动选题][tech]: 20220627 Open Programmable Infrastructure- 1+1=3.md

sources/tech/20220627 Kuro- An Unofficial Microsoft To-Do Desktop Client for Linux.md
=> [手动选题][tech]: 20220627 Kuro- An Unofficial Microsoft To-Do Desktop Client for Linux.md

published/20220616 Analyze web pages with Python requests and Beautiful Soup.md
@lkxed
https://linux.cn/article-14769-1.html
=> RP:published/20220616 Analyze web pages with Python requests and Beautiful Soup.md

sources/tech/20220627 Linux Lite 6 Review- Well Designed -bridging-distro- for Windows Users.md
=> [手动选题][tech]: 20220627 Linux Lite 6 Review- Well Designed -bridging-distro- for Windows Users.md

sources/tech/20220628 Linux su vs sudo- what-s the difference-.md
=> [手动选题][tech]: 20220628 Linux su vs sudo- what-s the difference-.md

sources/tech/20220628 Why organizations need site reliability engineers.md
=> [手动选题][tech]: 20220628 Why organizations need site reliability engineers.md

sources/news/20220628 EndeavourOS Artemis is the First ISO with ARM Installation Support.md
=> [手动选题][news]: 20220628 EndeavourOS Artemis is the First ISO with ARM Installation Support.md

sources/tech/20220628 ripgrep-all Command in Linux- One grep to Rule Them All.md
=> [手动选题][tech]: 20220628 ripgrep-all Command in Linux- One grep to Rule Them All.md

sources/news/20220628 Firefox 102 Release Lets You Disable Download Panel and Improves Picture-in-Picture Mode.md
=> [手动选题][news]: 20220628 Firefox 102 Release Lets You Disable Download Panel and Improves Picture-in-Picture Mode.md

sources/tech/20220628 Notes on running containers with bubblewrap.md
=> [手动选题][tech]: 20220628 Notes on running containers with bubblewrap.md

published/20220623 Minetest, an Open Source Minecraft Alternative.md
@geekpi
https://linux.cn/article-14774-1.html
=> RP:published/20220623 Minetest, an Open Source Minecraft Alternative.md

sources/news/20220629 Thunderbird 102 Releases with Matrix Support and New Address Book.md
=> [手动选题][news]: 20220629 Thunderbird 102 Releases with Matrix Support and New Address Book.md

sources/news/20220629 Vim 9.0 is Here With a New Script Language Promising Performance Boost.md
=> [手动选题][news]: 20220629 Vim 9.0 is Here With a New Script Language Promising Performance Boost.md

sources/tech/20220629 DIY Embroidery with Inkscape and Ink-Stitch.md
=> [手动选题][tech]: 20220629 DIY Embroidery with Inkscape and Ink-Stitch.md

sources/tech/20220629 Finding Your Router-s IP Address -Default Gateway- in Ubuntu and Other Linux.md
=> [手动选题][tech]: 20220629 Finding Your Router-s IP Address -Default Gateway- in Ubuntu and Other Linux.md

sources/tech/20220629 ABCs of FreeDOS- 26 commands I use all the time.md
=> [手动选题][tech]: 20220629 ABCs of FreeDOS- 26 commands I use all the time.md

published/20210809 How to Enable Minimize, Maximize Window Buttons in elementary OS.md
@geekpi
https://linux.cn/article-14778-1.html
=> RP:published/20210809 How to Enable Minimize, Maximize Window Buttons in elementary OS.md

published/20220622 Manage your Rust toolchain using rustup.md
@geekpi @turbokernel
https://linux.cn/article-14779-1.html
=> RP:published/20220622 Manage your Rust toolchain using rustup.md

sources/news/20220630 6 New Changes Coming to Nautilus File Manager in GNOME 43.md
=> [手动选题][news]: 20220630 6 New Changes Coming to Nautilus File Manager in GNOME 43.md

sources/tech/20220630 Package a new Python module in 4 steps.md
=> [手动选题][tech]: 20220630 Package a new Python module in 4 steps.md

sources/tech/20220630 The Top Trends Changing The Data Center Industry.md
=> [手动选题][tech]: 20220630 The Top Trends Changing The Data Center Industry.md

published/20220627 Make a temporary file on Linux with Bash.md
@geekpi
https://linux.cn/article-14783-1.html
=> RP:published/20220627 Make a temporary file on Linux with Bash.md

sources/news/20220701 Pine64 Is Now Working On A Powerful RISC-V Single Board Computer.md
=> [手动选题][news]: 20220701 Pine64 Is Now Working On A Powerful RISC-V Single Board Computer.md

sources/tech/20220701 Why I switched from Apple Music to Jellyfin and Raspberry Pi.md
=> [手动选题][tech]: 20220701 Why I switched from Apple Music to Jellyfin and Raspberry Pi.md

sources/tech/20220701 Deprecated Linux Commands You Should Not Use Anymore -And Their Alternatives-.md
=> [手动选题][tech]: 20220701 Deprecated Linux Commands You Should Not Use Anymore -And Their Alternatives-.md

sources/news/20220701 An Open Source Organisation Has Left GitHub And Encourages You To Do The Same.md
=> [手动选题][news]: 20220701 An Open Source Organisation Has Left GitHub And Encourages You To Do The Same.md

sources/tech/20220701 How To Create Multiboot USB Drives With Ventoy In Linux.md
=> [手动选题][tech]: 20220701 How To Create Multiboot USB Drives With Ventoy In Linux.md

published/20210627 How to Convert File Formats With Pandoc in Linux -Quick Guide.md
@lkxed
https://linux.cn/article-14785-1.html
=> RP:published/20210627 How to Convert File Formats With Pandoc in Linux -Quick Guide.md

published/20210511 What is the OSI model.md
@hanszhao80
https://linux.cn/article-14786-1.html
=> RP:published/20210511 What is the OSI model.md

sources/tech/20220702 13 Interesting Distributions Based on Debian Linux.md
=> [手动选题][tech]: 20220702 13 Interesting Distributions Based on Debian Linux.md

published/20220625 Download YouTube Videos with VLC -Because, Why Not--.md
@geekpi
https://linux.cn/article-14788-1.html
=> RP:published/20220625 Download YouTube Videos with VLC -Because, Why Not--.md

sources/tech/20220703 10 Necessary Ubuntu Apps For Everyone [Part 3].md
=> [手动选题][tech]: 20220703 10 Necessary Ubuntu Apps For Everyone [Part 3].md

published/20210101 Djinn- A Code Generator and Templating Language Inspired by Jinja2.md
@hanszhao80
https://linux.cn/article-14792-1.html
=> RP:published/20210101 Djinn- A Code Generator and Templating Language Inspired by Jinja2.md

sources/news/20220704 Darktable 4.0.0 is Here with a Revamped UI and Improved Color Saturation.md
=> [手动选题][news]: 20220704 Darktable 4.0.0 is Here with a Revamped UI and Improved Color Saturation.md

sources/tech/20220704 massCode- A Free and Open-Source Code Snippet Manager.md
=> [手动选题][tech]: 20220704 massCode- A Free and Open-Source Code Snippet Manager.md

sources/tech/20220704 Manage your files in your Linux terminal with ranger.md
=> [手动选题][tech]: 20220704 Manage your files in your Linux terminal with ranger.md

sources/tech/20220704 New Features in the Upcoming Linux Mint 21 Release.md
=> [手动选题][tech]: 20220704 New Features in the Upcoming Linux Mint 21 Release.md

sources/tech/20220705 WebP Image- How to Create, Convert to JPEG, PNG & View in Ubuntu and Other Linux.md
=> [手动选题][tech]: 20220705 WebP Image- How to Create, Convert to JPEG, PNG & View in Ubuntu and Other Linux.md

sources/tech/20220705 Hamming Codes- The Error-Correcting Codes.md
=> [手动选题][tech]: 20220705 Hamming Codes- The Error-Correcting Codes.md

sources/tech/20220705 Why I love Tig for visualizing my Git workflows.md
=> [手动选题][tech]: 20220705 Why I love Tig for visualizing my Git workflows.md

published/20220630 With Extensions, GNOME Web is Slowly Becoming an Attractive Option on Desktop Linux.md
@lkxed
https://linux.cn/article-14797-1.html
=> RP:published/20220630 With Extensions, GNOME Web is Slowly Becoming an Attractive Option on Desktop Linux.md

sources/talk/20220705 GitHub Copilot Is Only Effective Because It Steals Open Source Code.md
=> [手动选题][talk]: 20220705 GitHub Copilot Is Only Effective Because It Steals Open Source Code.md

sources/tech/20220706 3 steps to create an awesome UX in a CLI application.md
=> [手动选题][tech]: 20220706 3 steps to create an awesome UX in a CLI application.md

sources/tech/20220706 10 Tools to Generate and Have Fun With ASCII Art in Linux Terminal.md
=> [手动选题][tech]: 20220706 10 Tools to Generate and Have Fun With ASCII Art in Linux Terminal.md

sources/tech/20220707 10 Great KDE Apps for Everyone [Part 2].md
=> [手动选题][tech]: 20220707 10 Great KDE Apps for Everyone [Part 2].md

sources/news/20220707 Raspberry Pi 4 Support is Coming to Fedora Linux.md
=> [手动选题][news]: 20220707 Raspberry Pi 4 Support is Coming to Fedora Linux.md

sources/news/20220707 Meta Open Sources AI Translation Tool That Works Across 200 Languages.md
=> [手动选题][news]: 20220707 Meta Open Sources AI Translation Tool That Works Across 200 Languages.md

sources/tech/20220707 Recommender Systems- An Overview of the Mathematics.md
=> [手动选题][tech]: 20220707 Recommender Systems- An Overview of the Mathematics.md

sources/tech/20220707 Use secret keyboard keys on Linux.md
=> [手动选题][tech]: 20220707 Use secret keyboard keys on Linux.md

sources/news/20220707 Google Summer of Code + Zephyr RTOS.md
=> [手动选题][news]: 20220707 Google Summer of Code + Zephyr RTOS.md

sources/tech/20220708 Data Visualisation in R- Graphs.md
=> [手动选题][tech]: 20220708 Data Visualisation in R- Graphs.md

sources/news/20220708 Do You Miss Firefox Send- Internxt Send is Ready as a Replacement.md
=> [手动选题][news]: 20220708 Do You Miss Firefox Send- Internxt Send is Ready as a Replacement.md

sources/news/20220708 Meta-s AI Model That Helps Overcome Language Barrier Is Now Open-Source.md
=> [手动选题][news]: 20220708 Meta-s AI Model That Helps Overcome Language Barrier Is Now Open-Source.md

sources/tech/20220708 Umbrel- Unique Linux Distro for Self Hosting Open Source Software for Your Homelab.md
=> [手动选题][tech]: 20220708 Umbrel- Unique Linux Distro for Self Hosting Open Source Software for Your Homelab.md

sources/talk/20220708 Meet Free Software Foundation Executive Director Zoë Kooyman.md
=> [手动选题][talk]: 20220708 Meet Free Software Foundation Executive Director Zoë Kooyman.md

sources/tech/20220708 Reptyr – Move A Running Process From One Terminal To Another Without Closing It.md
=> [手动选题][tech]: 20220708 Reptyr – Move A Running Process From One Terminal To Another Without Closing It.md

published/20220705 Why I love Tig for visualizing my Git workflows.md
@geekpi
https://linux.cn/article-14809-1.html
=> RP:published/20220705 Why I love Tig for visualizing my Git workflows.md

sources/tech/20220709 How to Use Microsoft Office on Linux.md
=> [手动选题][tech]: 20220709 How to Use Microsoft Office on Linux.md

sources/news/20220708 Meta-s AI Model That Helps Overcome Language Barrier Is Now Open-Source.md
Just want to cliam this news.
News Title: Meta’s AI Model That Helps Overcome Language Barrier Is Now Open-Source
=> Fenglyu will translate the news ‘Meta’s open surece AI Model’

sources/tech/20220709 DAT Linux- Perfect Distro for Data Science Based on Ubuntu LTS.md
=> [手动选题][tech]: 20220709 DAT Linux- Perfect Distro for Data Science Based on Ubuntu LTS.md

published/20220708 Meta-s AI Model That Helps Overcome Language Barrier Is Now Open-Source.md, translated/news/20220708 Meta-s AI Model That Helps Overcome Language Barrier Is Now Open-Source.md
@fenglyulin
本文首发地址：https://linux.cn/article-14812-1.html
您的 LCTT 专页：https://linux.cn/lctt/fenglyulin
=> RP:20220708 meta s ai model that helps overcome language barrier is now open source

sources/tech/20220710 How to Install yay AUR Helper in Arch Linux [Beginner-s Guide].md
=> [手动选题][tech]: 20220710 How to Install yay AUR Helper in Arch Linux [Beginner-s Guide].md

sources/news/20220707 Google Summer of Code + Zephyr RTOS.md
=> [申领原文][news]: 20220707 Google Summer of Code + Zephyr RTOS.md

sources/news/20220711 Microsoft Postpones A Contentious Ban On Paid for Open Source And WebKit.md
=> [手动选题][news]: 20220711 Microsoft Postpones A Contentious Ban On Paid for Open Source And WebKit.md

sources/tech/20220711 Manual Renewal of SSL Certificates- A Simple Guide.md
=> [手动选题][tech]: 20220711 Manual Renewal of SSL Certificates- A Simple Guide.md

sources/tech/20220711 Run Linux, macOS, Windows Virtual Machines With Quickemu.md
=> [手动选题][tech]: 20220711 Run Linux, macOS, Windows Virtual Machines With Quickemu.md

sources/talk/20220711 Why Agile coaches need internal cooperation.md
=> [手动选题][talk]: 20220711 Why Agile coaches need internal cooperation.md

published/20220707 Google Summer of Code + Zephyr RTOS.md
@lkxed
https://linux.cn/article-14818-1.html
=> RP:published/20220707 Google Summer of Code + Zephyr RTOS.md

sources/news/20220708 Do You Miss Firefox Send- Internxt Send is Ready as a Replacement.md
=> [申领原文][news]: 20220708 Do You Miss Firefox Send- Internxt Send is Ready as a Replacement.md

published/20220603 How static linking works on Linux.md
@robsean
@turbokernel
https://linux.cn/article-14819-1.html
=> RP:published/20220603 How static linking works on Linux.md

sources/tech/20220712 List Upgradable Packages With apt Command in Ubuntu.md
=> [手动选题][tech]: 20220712 List Upgradable Packages With apt Command in Ubuntu.md

sources/news/20220712 eBook Manager Calibre 6.0 is Here With Full-Text Search and Other Improvements.md
=> [手动选题][news]: 20220712 eBook Manager Calibre 6.0 is Here With Full-Text Search and Other Improvements.md

sources/tech/20220712 7 kinds of garbage collection for Java.md
=> [手动选题][tech]: 20220712 7 kinds of garbage collection for Java.md

sources/tech/20220712 OpenWrt, an open source alternative to firmware for home routers.md
=> [手动选题][tech]: 20220712 OpenWrt, an open source alternative to firmware for home routers.md

published/20220708 Do You Miss Firefox Send- Internxt Send is Ready as a Replacement.md
@lkxed
恭喜，达成 100 篇里程碑！
https://linux.cn/article-14822-1.html
=> RP:published/20220708 Do You Miss Firefox Send- Internxt Send is Ready as a Replacement.md

published/20220707 Check disk usage in Linux.md
@MjSeven
https://linux.cn/article-14823-1.html
=> RP:published/20220707 Check disk usage in Linux.md

sources/tech/20220713 How I create music playlists on Linux.md
=> [手动选题][tech]: 20220713 How I create music playlists on Linux.md

sources/tech/20220713 A guide to productivity management in open source projects.md
=> [手动选题][tech]: 20220713 A guide to productivity management in open source projects.md

published/20220704 massCode- A Free and Open-Source Code Snippet Manager.md
@geekpi
https://linux.cn/article-14827-1.html
=> RP:published/20220704 massCode- A Free and Open-Source Code Snippet Manager.md

sources/tech/20220714 Top 10 Linux Distros for Beginners in 2022 [Compared].md
=> [手动选题][tech]: 20220714 Top 10 Linux Distros for Beginners in 2022 [Compared].md

sources/tech/20220714 5 ways to learn C programming on Linux.md
=> [手动选题][tech]: 20220714 5 ways to learn C programming on Linux.md

sources/tech/20220714 Fixing -Command -python- not found- Error in Ubuntu Linux.md
=> [手动选题][tech]: 20220714 Fixing -Command -python- not found- Error in Ubuntu Linux.md

sources/tech/20220715 The Ultimate Guide to Epic Games Store on Linux.md
=> [手动选题][tech]: 20220715 The Ultimate Guide to Epic Games Store on Linux.md

published/20220527 Plotting Data in R- Graphs.md, translated/tech/20220527 Plotting Data in R- Graphs.md
@tanloong
https://linux.cn/article-14830-1.html
=> RP:20220527 plotting data in r  graphs

sources/tech/20210120 Highlighted Text Not Visible in gedit in Dark Mode- Here-s What You Can Do.md
trans 20210120 Highlighted Text Not Visible in gedit in Dark Mode- Here-s What You Can Do
=> trans-fix-gedit

sources/tech/20220715 Microservices Collaboration with Containerised Kafka.md
=> [手动选题][tech]: 20220715 Microservices Collaboration with Containerised Kafka.md

published/20210120 Highlighted Text Not Visible in gedit in Dark Mode- Here-s What You Can Do.md
@void-mori
https://linux.cn/article-14833-1.html
=> RP:published/20210120 Highlighted Text Not Visible in gedit in Dark Mode- Here-s What You Can Do.md

published/20211104 Beginner-s Guide to Installing Arch Linux on VirtualBox.md
@hanszhao80
https://linux.cn/article-14834-1.html
=> RP:published/20211104 Beginner-s Guide to Installing Arch Linux on VirtualBox.md

sources/tech/20220716 Top 10 Linux Distributions for KDE Plasma [Compared].md
=> [手动选题][tech]: 20220716 Top 10 Linux Distributions for KDE Plasma [Compared].md

sources/tech/20220716 Guide- How to Share A Folder Between Ubuntu-Linux and Windows.md
=> [手动选题][tech]: 20220716 Guide- How to Share A Folder Between Ubuntu-Linux and Windows.md

sources/tech/20220716 Top Nitrux Applications -Maui- Everyone Should Try.md
=> [手动选题][tech]: 20220716 Top Nitrux Applications -Maui- Everyone Should Try.md

sources/tech/20220716 13 Ways to Tweak Nautilus File Manager in Linux to Get More Out of it.md
=> [手动选题][tech]: 20220716 13 Ways to Tweak Nautilus File Manager in Linux to Get More Out of it.md

sources/tech/20220716 Listen to music on Linux with Rhythmbox.md
=> [手动选题][tech]: 20220716 Listen to music on Linux with Rhythmbox.md

sources/tech/20220716 How to Install Deepin Desktop in Arch Linux [Complete Guide].md
=> [手动选题][tech]: 20220716 How to Install Deepin Desktop in Arch Linux [Complete Guide].md

sources/tech/20220716 Ubuntu Studio 22.04 LTS – New Features and Release Details.md
=> [手动选题][tech]: 20220716 Ubuntu Studio 22.04 LTS – New Features and Release Details.md

sources/tech/20220716 4 Ways to Fix the Laptop Brightness Problem In Ubuntu.md
=> [手动选题][tech]: 20220716 4 Ways to Fix the Laptop Brightness Problem In Ubuntu.md

sources/tech/20220716 How to Clean Up Snap Versions to Free Up Disk Space.md
=> [手动选题][tech]: 20220716 How to Clean Up Snap Versions to Free Up Disk Space.md

sources/tech/20220716 Does an Ethernet splitter slow down speed-.md
=> [手动选题][tech]: 20220716 Does an Ethernet splitter slow down speed-.md

published/20220704 Manage your files in your Linux terminal with ranger.md
@geekpi
https://linux.cn/article-14835-1.html
=> RP:published/20220704 Manage your files in your Linux terminal with ranger.md

sources/tech/20220718 How I configure a DHCP server on my personal network.md
=> [手动选题][tech]: 20220718 How I configure a DHCP server on my personal network.md

sources/tech/20220718 Create a JavaScript API in 6 minutes.md
=> [手动选题][tech]: 20220718 Create a JavaScript API in 6 minutes.md

sources/tech/20220718 Monitor your Linux firewall with nftwatch.md
=> [手动选题][tech]: 20220718 Monitor your Linux firewall with nftwatch.md

sources/tech/20220718 How to Make LibreOffice Look Like Microsoft Office.md
=> [手动选题][tech]: 20220718 How to Make LibreOffice Look Like Microsoft Office.md

sources/tech/20220718 How to Install Rocky Linux 9 Step by Step with Screenshots.md
=> [手动选题][tech]: 20220718 How to Install Rocky Linux 9 Step by Step with Screenshots.md

sources/tech/20220718 Top 10 Best Professional Video Editors in 2022.md
=> [手动选题][tech]: 20220718 Top 10 Best Professional Video Editors in 2022.md

sources/tech/20220718 5 Best and Free Desktop Email Clients for Linux and Windows.md
=> [手动选题][tech]: 20220718 5 Best and Free Desktop Email Clients for Linux and Windows.md

sources/tech/20220719 How to Install Discord on Manjaro and Other Arch Linux Derivatives.md
=> [手动选题][tech]: 20220719 How to Install Discord on Manjaro and Other Arch Linux Derivatives.md

sources/tech/20220719 Event-driven architecture explained in a coloring book.md
=> [手动选题][tech]: 20220719 Event-driven architecture explained in a coloring book.md

sources/tech/20220719 Code your first React UI app.md
=> [手动选题][tech]: 20220719 Code your first React UI app.md

sources/tech/20220719 Turn your Python script into a command-line application.md
=> [手动选题][tech]: 20220719 Turn your Python script into a command-line application.md

published/20220623 How to Boot into an Older Kernel By Default in Ubuntu and Other Linux.md
@hanszhao80
https://linux.cn/article-14843-1.html
=> RP:published/20220623 How to Boot into an Older Kernel By Default in Ubuntu and Other Linux.md

sources/tech/20220719 How to Uninstall Deb Packages in Ubuntu.md
=> [手动选题][tech]: 20220719 How to Uninstall Deb Packages in Ubuntu.md

published/20210611 How to use the FreeDOS text editor.md, translated/tech/20210611 How to use the FreeDOS text editor.md
@yjacks
感谢您，完成了第一篇翻译。
不过，这篇翻译的质量并不好。请注意改进。不要使用辅助翻译软件直接翻译后就提交上来，最起码你得润色，得自己读起来通顺。
本文首发地址：https://linux.cn/article-14847-1.html
您的 LCTT 专页：https://linux.cn/lctt/yjacks
=> RP:20210611 how to use the free dos text editor

sources/tech/20220720 Update a Single Package With apt Command in Ubuntu and Debian.md
=> [手动选题][tech]: 20220720 Update a Single Package With apt Command in Ubuntu and Debian.md

sources/news/20220720 Newly Released Cat Game -STRAY- Works Pretty Good on Linux.md
=> [手动选题][news]: 20220720 Newly Released Cat Game -STRAY- Works Pretty Good on Linux.md

sources/tech/20220720 How much JavaScript do you need to know before learning ReactJS-.md
=> [手动选题][tech]: 20220720 How much JavaScript do you need to know before learning ReactJS-.md

sources/tech/20220720 A Beginners Manual To Docker Desktop For Linux.md
=> [手动选题][tech]: 20220720 A Beginners Manual To Docker Desktop For Linux.md

published/20220716 Guide- How to Share A Folder Between Ubuntu-Linux and Windows.md
@MjSeven
https://linux.cn/article-14850-1.html
=> RP:published/20220716 Guide- How to Share A Folder Between Ubuntu-Linux and Windows.md

sources/news/20220721 Dell XPS 13 Plus -Developer Edition- Gets Certified for Ubuntu 22.04 LTS.md
=> [手动选题][news]: 20220721 Dell XPS 13 Plus -Developer Edition- Gets Certified for Ubuntu 22.04 LTS.md

sources/tech/20220721 Hands-on With openSUSE MicroOS – Adaptable Linux Platform [First Look].md
=> [手动选题][tech]: 20220721 Hands-on With openSUSE MicroOS – Adaptable Linux Platform [First Look].md

published/20210602 Establish an SSH connection between Windows and Linux.md, translated/tech/20210602 Establish an SSH connection between Windows and Linux.md
@yjacks
润色之后有了进步，看得出用心了。再给你提一个建议，中文的语序倒装句比较少用，而英文这种情况非常多。所以我们翻译时，要整理语序，使之符合中文习惯。
https://linux.cn/article-14855-1.html
=> RP:20210602 establish an ssh connection between windows and linux

published/20220719 How to Install Discord on Manjaro and Other Arch Linux Derivatives.md
@geekpi
https://linux.cn/article-14856-1.html
=> RP:published/20220719 How to Install Discord on Manjaro and Other Arch Linux Derivatives.md

published/20220718 Monitor your Linux firewall with nftwatch.md
@geekpi
https://linux.cn/article-14858-1.html
=> RP:published/20220718 Monitor your Linux firewall with nftwatch.md

published/20220712 List Upgradable Packages With apt Command in Ubuntu.md
@geekpi
https://linux.cn/article-14861-1.html
=> RP:published/20220712 List Upgradable Packages With apt Command in Ubuntu.md

published/20220716 Listen to music on Linux with Rhythmbox.md
@duoluoxiaosheng
https://linux.cn/article-14865-1.html
=> RP:published/20220716 Listen to music on Linux with Rhythmbox.md

published/20220716 Listen to music on Linux with Rhythmbox.md
=> R:published/20220716 Listen to music on Linux with Rhythmbox.md

published/20220716 How to Install Deepin Desktop in Arch Linux [Complete Guide].md, sources/tech/20220716 How to Install Deepin Desktop in Arch Linux [Complete Guide].md
@wxy
https://linux.cn/article-14867-1.html
=> ALL:20220716 how to install deepin desktop in arch linux complete guide]

sources/tech/20220722 Fixing the -Pending Update of Firefox snap- Error in Ubuntu.md
=> [手动选题][tech]: 20220722 Fixing the -Pending Update of Firefox snap- Error in Ubuntu.md

sources/tech/20220723 Top 10 Best Music Players for Linux in 2022.md
=> [手动选题][tech]: 20220723 Top 10 Best Music Players for Linux in 2022.md

sources/tech/20220727 How to Install Pamac GUI Package Manager in Arch Linux.md
=> [手动选题][tech]: 20220727 How to Install Pamac GUI Package Manager in Arch Linux.md

sources/tech/20220725 Koodo is an All-in-one Open Source eBook Reader App for Linux.md
=> [手动选题][tech]: 20220725 Koodo is an All-in-one Open Source eBook Reader App for Linux.md

sources/news/20220725 In light Of The Log4j Incident, Google Supports Calls For Better Open Source Security.md
=> [手动选题][news]: 20220725 In light Of The Log4j Incident, Google Supports Calls For Better Open Source Security.md

sources/talk/20220726 Open Source Software- Is There an Easy Path to Success-.md
=> [手动选题][talk]: 20220726 Open Source Software- Is There an Easy Path to Success-.md

sources/tech/20220727 An Introduction to Sentiment Analysis Using NLP and ML.md
=> [手动选题][tech]: 20220727 An Introduction to Sentiment Analysis Using NLP and ML.md

sources/tech/20220725 Feren OS Review- Clever KDE Distro for Easy Migration from Windows.md
=> [手动选题][tech]: 20220725 Feren OS Review- Clever KDE Distro for Easy Migration from Windows.md

sources/talk/20220724 Wayland Core Protocol is Tailored Only for GNOME and That-s Not a Good Thing [Opinion].md
=> [手动选题][talk]: 20220724 Wayland Core Protocol is Tailored Only for GNOME and That-s Not a Good Thing [Opinion].md

sources/news/20220726 Debian May Consider Including Non-Free Firmware in Official Releases.md
=> [手动选题][news]: 20220726 Debian May Consider Including Non-Free Firmware in Official Releases.md

sources/news/20220727 Pop!_OS 22.04 Linux Distro is Finally Adding Raspberry Pi 4 Support.md
=> [手动选题][news]: 20220727 Pop!_OS 22.04 Linux Distro is Finally Adding Raspberry Pi 4 Support.md

sources/tech/20220723 Nala – A Feature-rich Commandline Frontend For APT Package Manager.md
=> [手动选题][tech]: 20220723 Nala – A Feature-rich Commandline Frontend For APT Package Manager.md

sources/tech/20220726 How To Change GRUB Theme In Linux.md
=> [手动选题][tech]: 20220726 How To Change GRUB Theme In Linux.md

sources/tech/20220727 How To Automatically Update Running Docker Containers Using Watchtower.md
=> [手动选题][tech]: 20220727 How To Automatically Update Running Docker Containers Using Watchtower.md

sources/tech/20220722 Create conditional pipelines with CEL.md
=> [手动选题][tech]: 20220722 Create conditional pipelines with CEL.md

sources/talk/20220723 Why Design Thinking is a box office hit for open source teams.md
=> [手动选题][talk]: 20220723 Why Design Thinking is a box office hit for open source teams.md

sources/tech/20220725 How to use LibreOffice Writer templates.md
=> [手动选题][tech]: 20220725 How to use LibreOffice Writer templates.md

sources/tech/20220726 Shrink PDFs with this Linux tool.md
=> [手动选题][tech]: 20220726 Shrink PDFs with this Linux tool.md

sources/tech/20220726 How I use Bash to automate tasks on Linux.md
=> [手动选题][tech]: 20220726 How I use Bash to automate tasks on Linux.md

sources/talk/20220727 My honest review of the HP Dev One.md
=> [手动选题][talk]: 20220727 My honest review of the HP Dev One.md

sources/tech/20220727 How I manage files from the Linux command line.md
=> [手动选题][tech]: 20220727 How I manage files from the Linux command line.md

sources/tech/20220728 LibreOffice vs OpenOffice- All You Need to Know-.md
=> [手动选题][tech]: 20220728 LibreOffice vs OpenOffice- All You Need to Know-.md

sources/tech/20220728 Use this nifty Unix tool to process text on Linux.md
=> [手动选题][tech]: 20220728 Use this nifty Unix tool to process text on Linux.md

published/20220720 How much JavaScript do you need to know before learning ReactJS-.md
@geekpi
https://linux.cn/article-14874-1.html
=> RP:published/20220720 How much JavaScript do you need to know before learning ReactJS-.md

sources/tech/20220728 How To Build Custom Docker Image Using Dockerfile.md
=> [手动选题][tech]: 20220728 How To Build Custom Docker Image Using Dockerfile.md

sources/tech/20220728 Top 10 32-Bit Linux Distributions in 2022 [Compared].md
=> [手动选题][tech]: 20220728 Top 10 32-Bit Linux Distributions in 2022 [Compared].md

sources/tech/20220729 7 Docks to Customize Your Linux Desktop.md
=> [手动选题][tech]: 20220729 7 Docks to Customize Your Linux Desktop.md

sources/tech/20220728 A Few Tools that Help Machines to Learn.md
=> [手动选题][tech]: 20220728 A Few Tools that Help Machines to Learn.md

sources/tech/20220729 Fix bugs in Bash scripts by printing a stack trace.md
=> [手动选题][tech]: 20220729 Fix bugs in Bash scripts by printing a stack trace.md

published/20220714 Fixing -Command -python- not found- Error in Ubuntu Linux.md
@geekpi
https://linux.cn/article-14878-1.html
=> RP:published/20220714 Fixing -Command -python- not found- Error in Ubuntu Linux.md

sources/tech/20220730 Top 10 Kdenlive Features for Faster Video Editing [Beginner-s Guide].md
=> [手动选题][tech]: 20220730 Top 10 Kdenlive Features for Faster Video Editing [Beginner-s Guide].md

sources/tech/20220730 SpiralLinux- The New Distro Making Debian Easier for Beginners.md
=> [手动选题][tech]: 20220730 SpiralLinux- The New Distro Making Debian Easier for Beginners.md

sources/tech/20220730 How to Install Latest Vim 9.0 on Ubuntu Based Linux Distributions.md
=> [手动选题][tech]: 20220730 How to Install Latest Vim 9.0 on Ubuntu Based Linux Distributions.md

sources/news/20220731 The Much Awaited Linux Mint 21 is Released and Available to Download.md
=> [手动选题][news]: 20220731 The Much Awaited Linux Mint 21 is Released and Available to Download.md

sources/tech/20220731 Top 10 Features of Linux Mint 21 -Vanessa-.md
=> [手动选题][tech]: 20220731 Top 10 Features of Linux Mint 21 -Vanessa-.md

published/20220719 How to Uninstall Deb Packages in Ubuntu.md
@geekpi
https://linux.cn/article-14885-1.html
=> RP:20220719 how to uninstall deb packages in ubuntu

sources/tech/20220801 AI, ML and DL- What-s the Difference-.md
=> [手动选题][tech]: 20220801 AI, ML and DL- What-s the Difference-.md

sources/tech/20220801 Padloc- An Intuitive Open-Source Password Manager.md
=> [手动选题][tech]: 20220801 Padloc- An Intuitive Open-Source Password Manager.md

sources/news/20220801 Linus Torvalds Uses Apple MacBook Hardware to Release Linux Kernel 5.19.md
=> [手动选题][news]: 20220801 Linus Torvalds Uses Apple MacBook Hardware to Release Linux Kernel 5.19.md

sources/tech/20220802 Pandas- The Popular Python Library for Data Analysis and Data Science.md
=> [手动选题][tech]: 20220802 Pandas- The Popular Python Library for Data Analysis and Data Science.md

sources/tech/20220802 How I use the Linux sed command to automate file edits.md
=> [手动选题][tech]: 20220802 How I use the Linux sed command to automate file edits.md

sources/tech/20220803 A sysadmin-s guide to network interface configuration files.md
=> [手动选题][tech]: 20220803 A sysadmin-s guide to network interface configuration files.md

sources/tech/20220803 Play Crossword Puzzle Games on Linux Desktop With this Brand New GNOME App.md
=> [手动选题][tech]: 20220803 Play Crossword Puzzle Games on Linux Desktop With this Brand New GNOME App.md

sources/news/20220803 Linux Kernel 6.0 is Likely the Next Version Upgrade With Initial Rust Code.md
=> [手动选题][news]: 20220803 Linux Kernel 6.0 is Likely the Next Version Upgrade With Initial Rust Code.md

published/20220720 Update a Single Package With apt Command in Ubuntu and Debian.md
@geekpi
https://linux.cn/article-14895-1.html
=> RP:published/20220720 Update a Single Package With apt Command in Ubuntu and Debian.md

published/20220730 How to Install Latest Vim 9.0 on Ubuntu Based Linux Distributions.md
@geekpi
https://linux.cn/article-14899-1.html
=> RP:published/20220730 How to Install Latest Vim 9.0 on Ubuntu Based Linux Distributions.md

sources/tech/20220804 How to Install Linux Mint 21 Xfce Edition Step-by-Step.md
=> [手动选题][tech]: 20220804 How to Install Linux Mint 21 Xfce Edition Step-by-Step.md

sources/tech/20220805 Delete the local reference to a remote branch in Git.md
=> [手动选题][tech]: 20220805 Delete the local reference to a remote branch in Git.md

sources/tech/20220804 3 ways to take screenshots on Linux.md
=> [手动选题][tech]: 20220804 3 ways to take screenshots on Linux.md

sources/tech/20220804 Lengthen the life of your hardware with Linux.md
=> [手动选题][tech]: 20220804 Lengthen the life of your hardware with Linux.md

sources/tech/20220806 Old-school technical writing with groff.md
=> [手动选题][tech]: 20220806 Old-school technical writing with groff.md

published/20220725 Koodo is an All-in-one Open Source eBook Reader App for Linux.md
@geekpi
https://linux.cn/article-14902-1.html
=> RP:published/20220725 Koodo is an All-in-one Open Source eBook Reader App for Linux.md

sources/tech/20220805 Delete the local reference to a remote branch in Git.md
=> Translating.

sources/tech/20220807 Why we chose the Clojure programming language for Penpot.md
=> [手动选题][tech]: 20220807 Why we chose the Clojure programming language for Penpot.md

sources/tech/20220807 How to Upgrade to Linux Mint 21 [Step by Step Tutorial].md
=> [手动选题][tech]: 20220807 How to Upgrade to Linux Mint 21 [Step by Step Tutorial].md

published/20220722 Fixing the -Pending Update of Firefox snap- Error in Ubuntu.md
@geekpi
https://linux.cn/article-14908-1.html
=> RP:published/20220722 Fixing the -Pending Update of Firefox snap- Error in Ubuntu.md

published/20220718 How to Install Rocky Linux 9 Step by Step with Screenshots.md, translated/tech/20220718 How to Install Rocky Linux 9 Step by Step with Screenshots.md
@robsean
https://linux.cn/article-14909-1.html
=> RP:20220718 how to install rocky linux 9 step by step with screenshots

sources/tech/20220807 List Files and Directories in Style Using lsd and exa.md
=> [手动选题][tech]: 20220807 List Files and Directories in Style Using lsd and exa.md

sources/tech/20220808 Sunamu- Display Lyrics for Currently Playing Music on the Desktop in Linux.md
=> [手动选题][tech]: 20220808 Sunamu- Display Lyrics for Currently Playing Music on the Desktop in Linux.md

sources/talk/20220808 How open organizations can harness energy disruptions.md
=> [手动选题][talk]: 20220808 How open organizations can harness energy disruptions.md

sources/tech/20220808 Fix file permission errors on Linux.md
This post is collected by lkxed.
=> [手动选题][tech]: 20220808 Fix file permission errors on Linux.md

sources/news/20220809 Github Takes Action To Prevent Supply Chain Attacks On Open Source.md
=> [手动选题][news]: 20220809 Github Takes Action To Prevent Supply Chain Attacks On Open Source.md

sources/tech/20220809 7 Best Distributions Based on Fedora Linux.md
=> [手动选题][tech]: 20220809 7 Best Distributions Based on Fedora Linux.md

published/20220805 Delete the local reference to a remote branch in Git.md
@Yufei-Yan
https://linux.cn/article-14919-1.html
=> RP:published/20220805 Delete the local reference to a remote branch in Git.md

sources/news/20220810 Cutefish OS Development Restarts with A Revised Vision.md
=> [手动选题][news]: 20220810 Cutefish OS Development Restarts with A Revised Vision.md

sources/tech/20220810 Using Machine Learning to Identify Reefs in the Ocean.md
=> [手动选题][tech]: 20220810 Using Machine Learning to Identify Reefs in the Ocean.md

sources/talk/20220811 What is the Difference Between macOS and Linux-.md
=> [手动选题][talk]: 20220811 What is the Difference Between macOS and Linux-.md

sources/tech/20220810 How to Record Streaming Audio in Ubuntu and other Linux Distributions.md
=> [手动选题][tech]: 20220810 How to Record Streaming Audio in Ubuntu and other Linux Distributions.md

sources/tech/20220810 Create beautiful PDFs in LaTeX.md
=> [手动选题][tech]: 20220810 Create beautiful PDFs in LaTeX.md

sources/tech/20220810 Our favorite Linux replacements for antiquated open source tools.md
=> [手动选题][tech]: 20220810 Our favorite Linux replacements for antiquated open source tools.md

sources/tech/20220811 A gentle introduction to HTML.md
=> [手动选题][tech]: 20220811 A gentle introduction to HTML.md

sources/news/20220811 Heroic Games Launcher 2.4.0 Released With Epic Overlay, GOG Cloud Save Support, and Anti-cheat Runtime.md
=> [手动选题][news]: 20220811 Heroic Games Launcher 2.4.0 Released With Epic Overlay, GOG Cloud Save Support, and Anti-cheat Runtime.md

sources/tech/20220812 5 Tools to Protect Your Email Address From Websites and Newsletters.md
=> [手动选题][tech]: 20220812 5 Tools to Protect Your Email Address From Websites and Newsletters.md

sources/tech/20220812 How I get students excited about math with Python and Raspberry Pi.md
=> [手动选题][tech]: 20220812 How I get students excited about math with Python and Raspberry Pi.md

sources/tech/20220812 Writing project documentation in HTML.md
=> [手动选题][tech]: 20220812 Writing project documentation in HTML.md

published/20220807 List Files and Directories in Style Using lsd and exa.md
@geekpi
https://linux.cn/article-14923-1.html
=> RP:published/20220807 List Files and Directories in Style Using lsd and exa.md

sources/tech/20220809 Top 10 Great Ubuntu Apps for Everyone [Part 4].md
=> [手动选题][tech]: 20220809 Top 10 Great Ubuntu Apps for Everyone [Part 4].md

sources/tech/20220809 A guide to JVM interpretation and compilation.md
=> [手动选题][tech]: 20220809 A guide to JVM interpretation and compilation.md

published/20220725 How to use LibreOffice Writer templates.md
@geekpi
https://linux.cn/article-14925-1.html
=> RP:published/20220725 How to use LibreOffice Writer templates.md

published/20220727 How To Automatically Update Running Docker Containers Using Watchtower.md
@Donkey-Hao
https://linux.cn/article-14926-1.html
=> RP:published/20220727 How To Automatically Update Running Docker Containers Using Watchtower.md

published/20220727 How I manage files from the Linux command line.md
@Donkey-Hao
https://linux.cn/article-14930-1.html
=> RP:published/20220727 How I manage files from the Linux command line.md

sources/tech/20220814 How to Record Audio in Linux With Audacity -and Reduce Noise-.md
=> [手动选题][tech]: 20220814 How to Record Audio in Linux With Audacity -and Reduce Noise-.md

sources/tech/20220814 How to Monitor Log Files in Real Time in Linux [Desktop and Server].md
=> [手动选题][tech]: 20220814 How to Monitor Log Files in Real Time in Linux [Desktop and Server].md

sources/tech/20220814 New GNOME Text Editor – Everything You Need to Know.md
=> [手动选题][tech]: 20220814 New GNOME Text Editor – Everything You Need to Know.md

sources/tech/20220814 Create Your Own Custom Light and Dark Wallpaper for GNOME.md
=> [手动选题][tech]: 20220814 Create Your Own Custom Light and Dark Wallpaper for GNOME.md

sources/tech/20220814 Best 5 Alternatives to Microsoft Office [Compared].md
=> [手动选题][tech]: 20220814 Best 5 Alternatives to Microsoft Office [Compared].md

sources/tech/20220815 Try Asciidoc instead of Markdown.md
=> [手动选题][tech]: 20220815 Try Asciidoc instead of Markdown.md

sources/tech/20220815 How ODT files are structured.md
=> [手动选题][tech]: 20220815 How ODT files are structured.md

published/20210910 MAKE MORE with Inkscape - Ink-Stitch.md
@aREversez
https://linux.cn/article-14935-1.html
=> RP:20210910 make more with inkscape   ink stitch.md

published/20210910 MAKE MORE with Inkscape - Ink-Stitch.md
=> R:published/20210910 MAKE MORE with Inkscape - Ink-Stitch.md

sources/talk/20220816 My practical advice for new programmers.md
=> [手动选题][talk]: 20220816 My practical advice for new programmers.md

sources/tech/20220816 A look inside an EPUB file.md
=> [手动选题][tech]: 20220816 A look inside an EPUB file.md

sources/tech/20220816 Marktext is an Excellent Editor Even for Those Who Don-t Know Markdown.md
=> [手动选题][tech]: 20220816 Marktext is an Excellent Editor Even for Those Who Don-t Know Markdown.md

sources/tech/20220816 Check Disk Space Using Agedu In Linux.md
=> [手动选题][tech]: 20220816 Check Disk Space Using Agedu In Linux.md

sources/news/20220816 Linux Kernel 6.0 RC1 is out with Run-Time Kernel Verification.md
=> [手动选题][news]: 20220816 Linux Kernel 6.0 RC1 is out with Run-Time Kernel Verification.md
