LCTT/TranslateProject

- sources/talk/20220816 The Effect of Nvidia-s Open Source Drivers On Linux Gamers.md
> [手动选题][talk]: 20220816 The Effect of Nvidia-s Open Source Drivers On Linux Gamers.md

- sources/talk/20220816 My practical advice for new programmers.md
> [申领原文][talk]: 20220816 My practical advice for new programmers.md

- published/20220802 How I use the Linux sed command to automate file edits.md
@perfiffer
https://linux.cn/article-14938-1.html
> RP:published/20220802 How I use the Linux sed command to automate file edits.md

- published/20220808 Sunamu- Display Lyrics for Currently Playing Music on the Desktop in Linux.md
@geekpi
https://linux.cn/article-14939-1.html
> RP:published/20220808 Sunamu- Display Lyrics for Currently Playing Music on the Desktop in Linux.md

- sources/news/20220817 Deepin 23 is Introducing a New Package Format and Repository, Sounds Interesting!.md
> [手动选题][news]: 20220817 Deepin 23 is Introducing a New Package Format and Repository, Sounds Interesting!.md

- sources/tech/20220817 How to Setup HAProxy SSL Termination on Ubuntu 22.04.md
> [手动选题][tech]: 20220817 How to Setup HAProxy SSL Termination on Ubuntu 22.04.md

- sources/tech/20220817 GNOME 43- Top New Features and Release Wiki.md
> [手动选题][tech]: 20220817 GNOME 43- Top New Features and Release Wiki.md

- published/20210921 3 ways to test your API with Python.md
@Yufei-Yan
https://linux.cn/article-14944-1.html
> RP:published/20210921 3 ways to test your API with Python.md

- sources/news/20220818 LibreOffice 7.4- Top New Features and Release Details.md
This post is collected by lkxed.
> [手动选题][news]: 20220818 LibreOffice 7.4- Top New Features and Release Details.md

- sources/tech/20220819 sssnake – A Super Addictive Snake Game for Linux Terminal.md
> [手动选题][tech]: 20220819 sssnake – A Super Addictive Snake Game for Linux Terminal.md

- sources/tech/20220818 The Functions in the R Stats Package.md
> [手动选题][tech]: 20220818 The Functions in the R Stats Package.md

- sources/news/20220818 A Bug In Open Source Makes Millions Of Websites Vulnerable To Attack.md
> [手动选题][news]: 20220818 A Bug In Open Source Makes Millions Of Websites Vulnerable To Attack.md

- sources/news/20220818 Google Surpasses Microsoft In Terms Of Open Source Contributors, Says A Study.md
> [手动选题][news]: 20220818 Google Surpasses Microsoft In Terms Of Open Source Contributors, Says A Study.md

- sources/tech/20220819 5 Ways To Prevent Open Source Licensing Violations.md
> [手动选题][tech]: 20220819 5 Ways To Prevent Open Source Licensing Violations.md

- sources/talk/20220818 Open source runs on non-code contributions.md
> [手动选题][talk]: 20220818 Open source runs on non-code contributions.md

- sources/tech/20220819 5 note-taking apps for Linux.md
> [手动选题][tech]: 20220819 5 note-taking apps for Linux.md

- published/20220814 How to Monitor Log Files in Real Time in Linux [Desktop and Server].md
@geekpi
https://linux.cn/article-14947-1.html
> RP:published/20220814 How to Monitor Log Files in Real Time in Linux [Desktop and Server].md

- sources/tech/20220818 Convert Docker Run Commands Into Docker-Compose Files.md
> [手动选题][tech]: 20220818 Convert Docker Run Commands Into Docker-Compose Files.md

- published/20220809 Github Takes Action To Prevent Supply Chain Attacks On Open Source.md
- translated/news/20220809 Github Takes Action To Prevent Supply Chain Attacks On Open Source.md
@lzx916
本文首发地址：https://linux.cn/article-14949-1.html
您的 LCTT 专页：https://linux.cn/lctt/lzx916
> RP:20220809 GitHub takes action to prevent supply chain attacks on open source

- sources/news/20220819 Krita 5.1 Focuses on Improved Usability, Handy Changes to Tools, and Much More!.md
> [手动选题][news]: 20220819 Krita 5.1 Focuses on Improved Usability, Handy Changes to Tools, and Much More!.md

- sources/news/20220819 LibreOffice 7.4 is Here With WebP Support and Powerful Enhancements for MS Office Interoperability.md
> [手动选题][news]: 20220819 LibreOffice 7.4 is Here With WebP Support and Powerful Enhancements for MS Office Interoperability.md

- sources/tech/20220820 What-s your favorite screenshot tool on Linux-.md
> [手动选题][tech]: 20220820 What-s your favorite screenshot tool on Linux-.md

- sources/tech/20220820 Linux Mint 21 Review- The Best Distro Just Got a Little Better.md
> [手动选题][tech]: 20220820 Linux Mint 21 Review- The Best Distro Just Got a Little Better.md

- sources/news/20220820 There is Life After the Death of x86.md
> [手动选题][news]: 20220820 There is Life After the Death of x86.md

- sources/tech/20220819 How to Create and Switch Workspaces in Linux Mint.md
> [手动选题][tech]: 20220819 How to Create and Switch Workspaces in Linux Mint.md

- published/20220809 7 Best Distributions Based on Fedora Linux.md
@geekpi
https://linux.cn/article-14951-1.html
> RP:published/20220809 7 Best Distributions Based on Fedora Linux.md

- published/20220816 My practical advice for new programmers.md
@lkxed
https://linux.cn/article-14952-1.html
> RP:published/20220816 My practical advice for new programmers.md

- sources/tech/20220821 risiOS- A Friendly Fedora Spin with Distinctive Features.md
> [手动选题][tech]: 20220821 risiOS- A Friendly Fedora Spin with Distinctive Features.md

- sources/news/20220822 Celluloid Video Player Gets GTK 4 UI Refresh.md
> [手动选题][news]: 20220822 Celluloid Video Player Gets GTK 4 UI Refresh.md

- sources/news/20220822 Kooha Screen Recorder Gets Enhanced Functionalities With Version 2.1 Release.md
> [手动选题][news]: 20220822 Kooha Screen Recorder Gets Enhanced Functionalities With Version 2.1 Release.md

- sources/tech/20220822 3 NES Emulators to Play Old NES Games on Linux.md
> [手动选题][tech]: 20220822 3 NES Emulators to Play Old NES Games on Linux.md

- sources/tech/20220822 How to List USB Devices Connected to Your Linux System.md
> [手动选题][tech]: 20220822 How to List USB Devices Connected to Your Linux System.md

- published/20220814 Create Your Own Custom Light and Dark Wallpaper for GNOME.md
@geekpi
https://linux.cn/article-14960-1.html
> RP:published/20220814 Create Your Own Custom Light and Dark Wallpaper for GNOME.md

- sources/news/20220823 An Open Source Mod-Based Method Of Universal Windows Customization, Windhawk.md
> [手动选题][news]: 20220823 An Open Source Mod-Based Method Of Universal Windows Customization, Windhawk.md

- sources/news/20220824 Webmin 2.0 Is Now Available For Open Source Web-Based Server Administration.md
> [手动选题][news]: 20220824 Webmin 2.0 Is Now Available For Open Source Web-Based Server Administration.md

- sources/news/20220823 Fedora 37- Top New Features and Release Wiki.md
> [手动选题][news]: 20220823 Fedora 37- Top New Features and Release Wiki.md

- sources/news/20220824 Linux-First AI Image Upscaler Upscayl Released its First Version.md
> [手动选题][news]: 20220824 Linux-First AI Image Upscaler Upscayl Released its First Version.md

- sources/news/20220824 It-s Massive! InfinityBook Pro 14 is a Lightweight Linux Laptop With a HUGE 99Wh Battery Offering.md
> [手动选题][news]: 20220824 It-s Massive! InfinityBook Pro 14 is a Lightweight Linux Laptop With a HUGE 99Wh Battery Offering.md

- sources/news/20220824 The 80-Year Computer Scientist Who Termed -Unix- Adds Unicode Support to AWK Code.md
> [手动选题][news]: 20220824 The 80-Year Computer Scientist Who Termed -Unix- Adds Unicode Support to AWK Code.md

- sources/tech/20220823 How I migrated to NetworkManager keyfiles for configuration.md
> [手动选题][tech]: 20220823 How I migrated to NetworkManager keyfiles for configuration.md

- sources/tech/20220824 Your guide to DistSQL-s cluster governance capability.md
> [手动选题][tech]: 20220824 Your guide to DistSQL-s cluster governance capability.md

- sources/tech/20220824 Blackbox is an Aesthetically Pleasing Terminal for Minimalists Linux Users.md
> [手动选题][tech]: 20220824 Blackbox is an Aesthetically Pleasing Terminal for Minimalists Linux Users.md

- sources/tech/20220824 Become A Pro Flatpak User By Learning These Commands.md
> [手动选题][tech]: 20220824 Become A Pro Flatpak User By Learning These Commands.md

- sources/tech/20220825 How to Get KDE Plasma 5.25 in Kubuntu 22.04 Jammy Jellyfish.md
> [手动选题][tech]: 20220825 How to Get KDE Plasma 5.25 in Kubuntu 22.04 Jammy Jellyfish.md

- sources/tech/20220825 Building a Stateless Firewall Using Netfilter in Linux.md
> [手动选题][tech]: 20220825 Building a Stateless Firewall Using Netfilter in Linux.md

- sources/talk/20220825 -I wish the industry would not follow this ever increasing hype cycle for new stuff-.md
> [手动选题][talk]: 20220825 -I wish the industry would not follow this ever increasing hype cycle for new stuff-.md

- sources/news/20220825 NGINX Pledges To Update, Improve, And Expand Its Open Source Ecosystem.md
> [手动选题][news]: 20220825 NGINX Pledges To Update, Improve, And Expand Its Open Source Ecosystem.md

- sources/talk/20220825 Linux Mint Release Cycle- What You Need to Know.md
> [手动选题][talk]: 20220825 Linux Mint Release Cycle- What You Need to Know.md

- sources/tech/20220825 15 Ways to Tweak Nemo File Manager in Linux to Get More Out of it.md
> [手动选题][tech]: 20220825 15 Ways to Tweak Nemo File Manager in Linux to Get More Out of it.md

- sources/tech/20220825 Using eBPF for network observability in the cloud.md
> [手动选题][tech]: 20220825 Using eBPF for network observability in the cloud.md

- sources/talk/20220825 Happy birthday, Linux! Here are 6 Linux origin stories.md
> [手动选题][talk]: 20220825 Happy birthday, Linux! Here are 6 Linux origin stories.md

- published/20220816 A look inside an EPUB file.md
@geekpi
https://linux.cn/article-14967-1.html
> RP:published/20220816 A look inside an EPUB file.md

- sources/news/20220826 Want to Help Improve GNOME- This New Tool Gives You the Chance!.md
> [手动选题][news]: 20220826 Want to Help Improve GNOME- This New Tool Gives You the Chance!.md

- sources/news/20220826 Lutris 0.5.11 Adds Open Source Macintosh Emulators and Amazon Games Integration.md
> [手动选题][news]: 20220826 Lutris 0.5.11 Adds Open Source Macintosh Emulators and Amazon Games Integration.md

- sources/talk/20220826 Why Companies Need to Set Up an Open Source Program Office.md
> [手动选题][talk]: 20220826 Why Companies Need to Set Up an Open Source Program Office.md

- sources/news/20220826 Wii U Emulator Cemu Going Open Source Is Significant For Emulation, Here-s Why.md
> [手动选题][news]: 20220826 Wii U Emulator Cemu Going Open Source Is Significant For Emulation, Here-s Why.md

- sources/tech/20220826 Microservices Deployment Architecture with Kubernetes Clusters.md
> [手动选题][tech]: 20220826 Microservices Deployment Architecture with Kubernetes Clusters.md

- sources/tech/20220826 Bash Scripting – Select Loop Explained With Examples.md
> [手动选题][tech]: 20220826 Bash Scripting – Select Loop Explained With Examples.md

- sources/talk/20220826 My open source journey from user to contributor to CTO.md
> [手动选题][talk]: 20220826 My open source journey from user to contributor to CTO.md

- sources/tech/20220826 How I analyze my music directory with Groovy.md
> [手动选题][tech]: 20220826 How I analyze my music directory with Groovy.md

- published/20220818 Convert Docker Run Commands Into Docker-Compose Files.md
@geekpi
https://linux.cn/article-14970-1.html
> RP:published/20220818 Convert Docker Run Commands Into Docker-Compose Files.md

- sources/tech/20220827 My favorite open source library for analyzing music files.md
> [手动选题][tech]: 20220827 My favorite open source library for analyzing music files.md

- published/20220822 3 NES Emulators to Play Old NES Games on Linux.md
@geekpi
https://linux.cn/article-14974-1.html
> RP:published/20220822 3 NES Emulators to Play Old NES Games on Linux.md

- published/20220807 How to Upgrade to Linux Mint 21 [Step by Step Tutorial].md
@robsean
https://linux.cn/article-14975-1.html
> RP:published/20220807 How to Upgrade to Linux Mint 21 [Step by Step Tutorial].md

- sources/tech/20220828 How I use Groovy to analyze album art in my music directory.md
> [手动选题][tech]: 20220828 How I use Groovy to analyze album art in my music directory.md

- sources/tech/20220828 7 Minimalist Linux Distributions Featuring Openbox.md
> [手动选题][tech]: 20220828 7 Minimalist Linux Distributions Featuring Openbox.md

- published/20220822 How to List USB Devices Connected to Your Linux System.md
@geekpi
https://linux.cn/article-14981-1.html
> RP:published/20220822 How to List USB Devices Connected to Your Linux System.md

- sources/tech/20220829 How To Manage Docker Containers Using Portainer In Linux.md
> [手动选题][tech]: 20220829 How To Manage Docker Containers Using Portainer In Linux.md

- sources/tech/20220830 Why We Need Time Series Databases for  Site Reliability Engineering.md
> [手动选题][tech]: 20220830 Why We Need Time Series Databases for  Site Reliability Engineering.md

- sources/news/20220830 Google Reveals Vulnerability Reward Program Specifically For Open Source Software.md
> [手动选题][news]: 20220830 Google Reveals Vulnerability Reward Program Specifically For Open Source Software.md

- sources/tech/20220830 Crystal Linux- Emerging Arch Linux Spin for GNOME Fans.md
> [手动选题][tech]: 20220830 Crystal Linux- Emerging Arch Linux Spin for GNOME Fans.md

- sources/tech/20220830 7 Best Open Source Library Management Software.md
> [手动选题][tech]: 20220830 7 Best Open Source Library Management Software.md

- sources/news/20220829 Debian Finally Starts a General Resolution to Consider a Non-Free Firmware Image.md
> [手动选题][news]: 20220829 Debian Finally Starts a General Resolution to Consider a Non-Free Firmware Image.md

- sources/news/20220830 Live Debugger Tool for Apps, Sidekick, is Now Open Source.md
> [手动选题][news]: 20220830 Live Debugger Tool for Apps, Sidekick, is Now Open Source.md

- sources/tech/20220829 Clean up unwanted files in your music directory using Groovy.md
> [手动选题][tech]: 20220829 Clean up unwanted files in your music directory using Groovy.md

- sources/tech/20220829 How to Setup EKS Cluster along with NLB on AWS.md
> [手动选题][tech]: 20220829 How to Setup EKS Cluster along with NLB on AWS.md

- sources/tech/20211203 Introduce the different Fedora Linux editions.md
> [手动选题][tech]: 20211203 Introduce the different Fedora Linux editions.md

- sources/tech/20220830 Some ways to get better at debugging.md
> [手动选题][tech]: 20220830 Some ways to get better at debugging.md

- published/20220816 Marktext is an Excellent Editor Even for Those Who Don-t Know Markdown.md
- translated/tech/20220816 Marktext is an Excellent Editor Even for Those Who Don-t Know Markdown.md
@chth0lly
本文首发地址：https://linux.cn/article-14986-1.html
您的 LCTT 专页：https://linux.cn/lctt/chth0lly
> RP:20220816 marktext is an excellent editor even for those who don t know markdown

- sources/tech/20220831 How we track the community health of our open source project.md
> [手动选题][tech]: 20220831 How we track the community health of our open source project.md

- sources/tech/20220831 Don-t Suspend Ubuntu When Laptop Lid is Closed.md
> [手动选题][tech]: 20220831 Don-t Suspend Ubuntu When Laptop Lid is Closed.md

- sources/tech/20220831 21 Basic Linux Networking Commands You Should Know.md
> [手动选题][tech]: 20220831 21 Basic Linux Networking Commands You Should Know.md

- published/20220819 5 note-taking apps for Linux.md
@geekpi
https://linux.cn/article-14990-1.html
> RP:published/20220819 5 note-taking apps for Linux.md

- published/20220824 Blackbox is an Aesthetically Pleasing Terminal for Minimalists Linux Users.md
@geekpi
https://linux.cn/article-14992-1.html
> RP:published/20220824 Blackbox is an Aesthetically Pleasing Terminal for Minimalists Linux Users.md

- sources/talk/20220901 Usability and accessibility starts with open communication.md
> [手动选题][talk]: 20220901 Usability and accessibility starts with open communication.md

- sources/tech/20220901 How Tracee solves the lack of BTF information.md
> [手动选题][tech]: 20220901 How Tracee solves the lack of BTF information.md

- sources/tech/20220901 Micro- Making File Editing Easier in Linux Terminal.md
> [手动选题][tech]: 20220901 Micro- Making File Editing Easier in Linux Terminal.md

- sources/tech/20220901 Are You Familiar with These Popular  Open Source Databases-.md
> [手动选题][tech]: 20220901 Are You Familiar with These Popular  Open Source Databases-.md

- sources/news/20220901 Unity Desktop Makes a Comeback With the Upcoming Ubuntu 22.10.md
> [手动选题][news]: 20220901 Unity Desktop Makes a Comeback With the Upcoming Ubuntu 22.10.md

- sources/tech/20220902 How to display the presence and absence of nth-highest group-wise values in SQL.md
> [手动选题][tech]: 20220902 How to display the presence and absence of nth-highest group-wise values in SQL.md

- sources/tech/20220902 Julia and Python- Which Language is Quicker-.md
> [手动选题][tech]: 20220902 Julia and Python- Which Language is Quicker-.md

- sources/tech/20220902 Where is DevOps Headed-.md
> [手动选题][tech]: 20220902 Where is DevOps Headed-.md

- sources/news/20220902 Evernote Alternative Notesnook is Now Open Source.md
> [手动选题][news]: 20220902 Evernote Alternative Notesnook is Now Open Source.md

- sources/news/20220903 8 Exciting New Features in the Upcoming KDE 5.26 Release.md
> [手动选题][news]: 20220903 8 Exciting New Features in the Upcoming KDE 5.26 Release.md

- sources/tech/20220903 GNOME Web 43 Looks Beautiful with Adwaita Tab View.md
> [手动选题][tech]: 20220903 GNOME Web 43 Looks Beautiful with Adwaita Tab View.md

- sources/tech/20220903 Infuse your awk scripts with Groovy.md
> [手动选题][tech]: 20220903 Infuse your awk scripts with Groovy.md

- published/20220825 How to Get KDE Plasma 5.25 in Kubuntu 22.04 Jammy Jellyfish.md
@geekpi
https://linux.cn/article-14997-1.html
> RP:20220825 how to get kde plasma 5.25 in kubuntu 22.04 jammy jellyfish

- sources/tech/20220904 How to Enable Dark Mode in Web Browser.md
> [手动选题][tech]: 20220904 How to Enable Dark Mode in Web Browser.md

- sources/tech/20220904 Create Bootable USB Using Etcher in Linux – Download and Usage Guide.md
> [手动选题][tech]: 20220904 Create Bootable USB Using Etcher in Linux – Download and Usage Guide.md

- sources/talk/20220904 Opinion- Car Design Was Better Before Computers.md
> [手动选题][talk]: 20220904 Opinion- Car Design Was Better Before Computers.md

- published/20220820 What if a Lifelong Linux User Tried Windows or macOS for the First Time-.md
- translated/talk/20220820 What if a Lifelong Linux User Tried Windows or macOS for the First Time-.md
@Kira-Pgr
感谢您完成了第一篇翻译贡献！
本文首发地址：https://linux.cn/article-15000-1.html
您的 LCTT 专页：https://linux.cn/lctt/Kira-Pgr
> RP:20220820 what if a lifelong linux user tried windows or mac os for the first time 

- sources/tech/20220905 How to Deploy Docker Swarm on Ubuntu 22.04 Step-by-Step.md
> [手动选题][tech]: 20220905 How to Deploy Docker Swarm on Ubuntu 22.04 Step-by-Step.md

- sources/tech/20220905 3 things to know about planning for OTA updates in your homelab.md
> [手动选题][tech]: 20220905 3 things to know about planning for OTA updates in your homelab.md

- sources/tech/20220905 How To Perform Arithmetic Operations In Bash.md
> [手动选题][tech]: 20220905 How To Perform Arithmetic Operations In Bash.md

- sources/tech/20220905 Manage containers on Fedora Linux with Podman Desktop.md
> [手动选题][tech]: 20220905 Manage containers on Fedora Linux with Podman Desktop.md

- published/20220520 Ubuntu vs Manjaro- Comparing the Different Linux Experiences.md
- translated/tech/20220520 Ubuntu vs Manjaro- Comparing the Different Linux Experiences.md
@Return7g
本文首发地址：https://linux.cn/article-15006-1.html
您的 LCTT 专页：https://linux.cn/lctt/Return7g
> RP:20220520 ubuntu vs manjaro  comparing the different linux experiences

- sources/talk/20220906 Unix History- A Mighty Origin Story.md
> [手动选题][talk]: 20220906 Unix History- A Mighty Origin Story.md

- sources/talk/20220906 Advantages and Disadvantages of Using Linux.md
> [手动选题][talk]: 20220906 Advantages and Disadvantages of Using Linux.md

- sources/tech/20220906 How to Analyse Sentiments Using Machine Learning.md
> [手动选题][tech]: 20220906 How to Analyse Sentiments Using Machine Learning.md

- sources/tech/20220906 A beginner-s guide to making a dark theme for a website.md
> [手动选题][tech]: 20220906 A beginner-s guide to making a dark theme for a website.md

- sources/news/20220906 Good News! Wii U Emulator Cemu 2.0 Goes Open Source With Linux Support.md
> [手动选题][news]: 20220906 Good News! Wii U Emulator Cemu 2.0 Goes Open Source With Linux Support.md

- sources/news/20220906 Lapce is a Fast, Lightweight Open-Source Code Editor in Making.md
> [手动选题][news]: 20220906 Lapce is a Fast, Lightweight Open-Source Code Editor in Making.md

- sources/news/20220907 Image Generation Model Stable Diffusion Is Now Open Source.md
> [手动选题][news]: 20220907 Image Generation Model Stable Diffusion Is Now Open Source.md

- sources/talk/20220907 Open source events- 4 goals to set and how to measure them.md
> [手动选题][talk]: 20220907 Open source events- 4 goals to set and how to measure them.md

- published/20220819 How to Create and Switch Workspaces in Linux Mint.md
@geekpi
https://linux.cn/article-15009-1.html
> RP:published/20220819 How to Create and Switch Workspaces in Linux Mint.md

- sources/talk/20220909 Open source matters in data analytics- Here-s why.md
> [手动选题][talk]: 20220909 Open source matters in data analytics- Here-s why.md

- sources/tech/20220908 How to use modern Python packaging and setuptools plugins together.md
> [手动选题][tech]: 20220908 How to use modern Python packaging and setuptools plugins together.md

- sources/tech/20220908 Komikku- A Free and Open-Source Manga Reader for Linux.md
> [手动选题][tech]: 20220908 Komikku- A Free and Open-Source Manga Reader for Linux.md

- sources/news/20220909 The New Raspberry Pi OS Update Brings in Sweet Little Improvements.md
> [手动选题][news]: 20220909 The New Raspberry Pi OS Update Brings in Sweet Little Improvements.md

- sources/news/20220909 Here-s What-s Coming to Fedora 37.md
> [手动选题][news]: 20220909 Here-s What-s Coming to Fedora 37.md

- sources/tech/20220909 Connect to WiFi Using Terminal in Arch Linux and Other Distros.md
> [手动选题][tech]: 20220909 Connect to WiFi Using Terminal in Arch Linux and Other Distros.md

- sources/tech/20220908 Connect to Ubuntu 20.04 from Windows 10 [Beginner-s Guide].md
> [手动选题][tech]: 20220908 Connect to Ubuntu 20.04 from Windows 10 [Beginner-s Guide].md

- published/20220831 Don-t Suspend Ubuntu When Laptop Lid is Closed.md
@geekpi
https://linux.cn/article-15015-1.html
> RP:published/20220831 Don-t Suspend Ubuntu When Laptop Lid is Closed.md

- sources/news/20220907 Image Generation Model Stable Diffusion Is Now Open Source.md
> [申领原文][news]: 20220907 Image Generation Model Stable Diffusion Is Now Open Source.md

- published/20220904 Create Bootable USB Using Etcher in Linux – Download and Usage Guide.md
@geekpi
https://linux.cn/article-15020-1.html
> RP:published/20220904 Create Bootable USB Using Etcher in Linux – Download and Usage Guide.md

- sources/tech/20220910 How to Install and Use virt-manager Virtual Machine Manager in Ubuntu and Other Linux.md
> [手动选题][tech]: 20220910 How to Install and Use virt-manager Virtual Machine Manager in Ubuntu and Other Linux.md

- sources/tech/20220910 Export or Save As PDF A Specific Range in LibreOffice Calc Sheets using Macro.md
> [手动选题][tech]: 20220910 Export or Save As PDF A Specific Range in LibreOffice Calc Sheets using Macro.md

- sources/tech/20220911 Installing Arch Linux Using archinstall Automated Script [Complete Guide].md
> [手动选题][tech]: 20220911 Installing Arch Linux Using archinstall Automated Script [Complete Guide].md

- sources/talk/20220910 Traditional Linux Packaging is not Suitable for Modern Applications [Opinion].md
> [手动选题][talk]: 20220910 Traditional Linux Packaging is not Suitable for Modern Applications [Opinion].md

- sources/tech/20220911 10 Destructive Linux Commands You Should Never Run.md
> [手动选题][tech]: 20220911 10 Destructive Linux Commands You Should Never Run.md

- sources/tech/20220910 5 ways to resize and optimize images for the web on Linux.md
> [手动选题][tech]: 20220910 5 ways to resize and optimize images for the web on Linux.md

- published/20220906 Unix History- A Mighty Origin Story.md
- translated/talk/20220906 Unix History- A Mighty Origin Story.md
@Donkey-Hao
https://linux.cn/article-15024-1.html
> RP:20220906 unix history  a mighty origin story

- sources/tech/20220913 How I troubleshoot swappiness and startup time on Linux.md
> [手动选题][tech]: 20220913 How I troubleshoot swappiness and startup time on Linux.md

- sources/tech/20220913 Remixing Linux for blind and visually impaired users.md
> [手动选题][tech]: 20220913 Remixing Linux for blind and visually impaired users.md

- sources/tech/20220912 Control your home automation remotely with Raspberry Pi and Traefik Hub.md
> [手动选题][tech]: 20220912 Control your home automation remotely with Raspberry Pi and Traefik Hub.md

- sources/tech/20220913 11 Interesting Firefox Add-ons to Improve Your Browsing Experience.md
> [手动选题][tech]: 20220913 11 Interesting Firefox Add-ons to Improve Your Browsing Experience.md

- sources/tech/20220913 CubyText is a Fast Cross-Platform Open-Source Knowledge Management App in Development.md
> [手动选题][tech]: 20220913 CubyText is a Fast Cross-Platform Open-Source Knowledge Management App in Development.md

- sources/news/20220912 GNU LibreJS For Firefox Stops Non-Free Non-Trivial JavaScript.md
> [手动选题][news]: 20220912 GNU LibreJS For Firefox Stops Non-Free Non-Trivial JavaScript.md

- sources/tech/20220912 Python Microservices Using Flask on Kubernetes.md
> [手动选题][tech]: 20220912 Python Microservices Using Flask on Kubernetes.md

- sources/tech/20220910 How to Install and Use virt-manager Virtual Machine Manager in Ubuntu and Other Linux.md
File: sources/tech/20220910 How to Install and Use virt-manager Virtual Machine Manager in Ubuntu and Other Linux.md
Type: Translation request.
> Translation request.

- published/20220630 Package a new Python module in 4 steps.md
@Return7g
https://linux.cn/article-15030-1.html
> RP:published/20220630 Package a new Python module in 4 steps.md

- published/20220904 How to Enable Dark Mode in Web Browser.md
@geekpi
https://linux.cn/article-15035-1.html
> RP:published/20220904 How to Enable Dark Mode in Web Browser.md

- sources/tech/20220914 How to Install FreeIPA Server on RHEL 9 Step-by-Step.md
> [手动选题][tech]: 20220914 How to Install FreeIPA Server on RHEL 9 Step-by-Step.md

- sources/tech/20220915 How I switched from Docker Desktop to Colima.md
> [手动选题][tech]: 20220915 How I switched from Docker Desktop to Colima.md

- sources/tech/20220914 3 steps to protect your home network.md
> [手动选题][tech]: 20220914 3 steps to protect your home network.md

- sources/tech/20220914 Packaging Job scripts in Kubernetes operators.md
> [手动选题][tech]: 20220914 Packaging Job scripts in Kubernetes operators.md

- sources/tech/20220915 How To Prevent Command Arguments With Sudo In Linux.md
> [手动选题][tech]: 20220915 How To Prevent Command Arguments With Sudo In Linux.md

- sources/tech/20220915 How To Run All Programs In A Directory Via Sudo In Linux.md
> [手动选题][tech]: 20220915 How To Run All Programs In A Directory Via Sudo In Linux.md

- sources/news/20220915 A Project For An Open Source 3D-Printed VR Headgear From Europe.md
> [手动选题][news]: 20220915 A Project For An Open Source 3D-Printed VR Headgear From Europe.md

- sources/tech/20220915 Monitoring and Debugging Kubernetes with Lens Desktop.md
> [手动选题][tech]: 20220915 Monitoring and Debugging Kubernetes with Lens Desktop.md

- sources/news/20220914 Google Uses Fully Homomorphic Open Source Duality-Led Encryption Library.md
> [手动选题][news]: 20220914 Google Uses Fully Homomorphic Open Source Duality-Led Encryption Library.md

- sources/news/20220914 CNCF Accepts Open Source Hexa Project As A Sandbox Project.md
> [手动选题][news]: 20220914 CNCF Accepts Open Source Hexa Project As A Sandbox Project.md

- sources/talk/20220914 Why Enterprises Should  Opt for Platform as a Service.md
> [手动选题][talk]: 20220914 Why Enterprises Should  Opt for Platform as a Service.md

- sources/tech/20220914 Platforms that Help Deploy AI and ML Applications on the Cloud.md
> [手动选题][tech]: 20220914 Platforms that Help Deploy AI and ML Applications on the Cloud.md

- sources/tech/20220915 How to Check if You are Using Wayland or Xorg-.md
> [手动选题][tech]: 20220915 How to Check if You are Using Wayland or Xorg-.md

- sources/tech/20220915 CrossOver Review- The -Premium Wine- to Run Windows Software on Linux.md
> [手动选题][tech]: 20220915 CrossOver Review- The -Premium Wine- to Run Windows Software on Linux.md

- sources/news/20220915 This Flutter-based Unofficial Software Center Might Replace Ubuntu-s Official App.md
> [手动选题][news]: 20220915 This Flutter-based Unofficial Software Center Might Replace Ubuntu-s Official App.md

- sources/news/20220915 Wow! Torvalds Modified Fedora Linux to Run on his Apple M2 Macbook.md
> [手动选题][news]: 20220915 Wow! Torvalds Modified Fedora Linux to Run on his Apple M2 Macbook.md

- sources/tech/20220915 Change the Default LibreOffice Look and Feel [Tutorial].md
> [手动选题][tech]: 20220915 Change the Default LibreOffice Look and Feel [Tutorial].md

- sources/tech/20220914 Install Linux Mint with Windows 11 Dual Boot [Complete Guide].md
> [手动选题][tech]: 20220914 Install Linux Mint with Windows 11 Dual Boot [Complete Guide].md

- sources/talk/20210816 What was your first programming language.md
> [申领原文] [申领原文] 20210816 What was your first programming language

- sources/tech/20220917 What is OpenRAN-.md
> [手动选题][tech]: 20220917 What is OpenRAN-.md

- sources/news/20220916 Penpot is a Solid Open-Source Figma Alternative to Look Out for!.md
> [手动选题][news]: 20220916 Penpot is a Solid Open-Source Figma Alternative to Look Out for!.md

- sources/tech/20220916 Using Python and NetworkManager to control the network.md
> [手动选题][tech]: 20220916 Using Python and NetworkManager to control the network.md

- sources/tech/20220916 Developing Low Latency Applications in the Cloud  with AI and ML.md
> [手动选题][tech]: 20220916 Developing Low Latency Applications in the Cloud  with AI and ML.md

- sources/tech/20220916 A Complete Guide to  Cloud Service Architectures.md
> [手动选题][tech]: 20220916 A Complete Guide to  Cloud Service Architectures.md

- sources/tech/20220916 How to Install Kubernetes Cluster on Debian 11 with Kubeadm.md
> [手动选题][tech]: 20220916 How to Install Kubernetes Cluster on Debian 11 with Kubeadm.md

- sources/tech/20220916 Fix the apt-key deprecation error in Linux.md
> [手动选题][tech]: 20220916 Fix the apt-key deprecation error in Linux.md

- sources/talk/20200426 20 Facts About Linus Torvalds, the Creator of Linux and Git.md
> [手动选题][talk]: 20200426 20 Facts About Linus Torvalds, the Creator of Linux and Git.md

- sources/news/20220916 Penpot is a Solid Open-Source Figma Alternative to Look Out for!.md
Reverts LCTT/TranslateProject#27227
> Revert "申请翻译：Update 20220916 Penpot is a Solid Open-Source Figma Alternative to Lo…"

- sources/tech/20220920 Atoms is a GUI Tool to Let You Manage Linux Chroot Environments Easily.md
> [手动选题][tech]: 20220920 Atoms is a GUI Tool to Let You Manage Linux Chroot Environments Easily.md

- sources/tech/20220920 3 ways to use the Linux inxi command.md
> [手动选题][tech]: 20220920 3 ways to use the Linux inxi command.md

- sources/talk/20220920 Security buzzwords to avoid and what to say instead.md
> [手动选题][talk]: 20220920 Security buzzwords to avoid and what to say instead.md

- sources/talk/20220919 I got my first pull request merged!.md
> [手动选题][talk]: 20220919 I got my first pull request merged!.md

- sources/tech/20220919 PyLint- The good, the bad, and the ugly.md
> [手动选题][tech]: 20220919 PyLint- The good, the bad, and the ugly.md

- sources/news/20220920 Loongson is Getting Ready for LoongArch Linux Laptops.md
> [手动选题][news]: 20220920 Loongson is Getting Ready for LoongArch Linux Laptops.md

- sources/news/20220919 AMD-s Open Source Vulkan Graphics Drivers Now Enable Ray Tracing.md
> [手动选题][news]: 20220919 AMD-s Open Source Vulkan Graphics Drivers Now Enable Ray Tracing.md

- sources/tech/20220919 How to Install Cockpit Web Console on Ubuntu 22.04.md
> [手动选题][tech]: 20220919 How to Install Cockpit Web Console on Ubuntu 22.04.md

- published/20220608 Rufus for Linux- Here Are the Best Live USB Creating Tools.md
- translated/tech/20220608 Rufus for Linux- Here Are the Best Live USB Creating Tools.md
@alfred-hong
本文首发地址：https://linux.cn/article-15052-1.html
您的 LCTT 专页：https://linux.cn/lctt/alfred-hong
> RP:20220608 rufus for linux  here are the best live usb creating tools

- sources/tech/20220921 6 Python interpreters to try in 2022.md
> [手动选题][tech]: 20220921 6 Python interpreters to try in 2022.md

- sources/tech/20220921 My favorite open source alternatives to Notion.md
> [手动选题][tech]: 20220921 My favorite open source alternatives to Notion.md

- sources/news/20220921 Wow! Rust-based Redox OS Gets an Anonymous Donation of $390,000 in Cryptocurrency.md
> [手动选题][news]: 20220921 Wow! Rust-based Redox OS Gets an Anonymous Donation of $390,000 in Cryptocurrency.md

- sources/news/20220921 LibreOffice is Available for $8.99 on Mac App Store- Here-s Why!.md
> [手动选题][news]: 20220921 LibreOffice is Available for $8.99 on Mac App Store- Here-s Why!.md

- sources/tech/20220921 How to Access Android Devices Internal Storage and SD Card in Ubuntu, Linux Mint using Media Transfer Protocol -MTP-.md
> [手动选题][tech]: 20220921 How to Access Android Devices Internal Storage and SD Card in Ubuntu, Linux Mint using Media Transfer Protocol -MTP-.md

- sources/tech/20220921 Garuda Linux- All-Rounder Distro Based on Arch Linux.md
> [手动选题][tech]: 20220921 Garuda Linux- All-Rounder Distro Based on Arch Linux.md

- sources/tech/20220914 3 steps to protect your home network.md
> [申领翻译]3 steps to protect your home network

- published/20220719 Turn your Python script into a command-line application.md
@MjSeven
https://linux.cn/article-15061-1.html
> RP:published/20220719 Turn your Python script into a command-line application.md

- sources/tech/20220923 5 Free and Open-Source Figma Alternatives.md
> [手动选题][tech]: 20220923 5 Free and Open-Source Figma Alternatives.md

- sources/tech/20220923 11 Gorgeous KDE Plasma Themes to Make Your Linux Desktop Even More Beautiful.md
> [手动选题][tech]: 20220923 11 Gorgeous KDE Plasma Themes to Make Your Linux Desktop Even More Beautiful.md

- sources/tech/20220923 How to build a dynamic distributed database with DistSQL.md
> [手动选题][tech]: 20220923 How to build a dynamic distributed database with DistSQL.md

- sources/tech/20220923 Install JDBC on Linux in 3 steps.md
> [手动选题][tech]: 20220923 Install JDBC on Linux in 3 steps.md

- sources/tech/20220922 5 Git configurations I make on Linux.md
> [手动选题][tech]: 20220922 5 Git configurations I make on Linux.md

- sources/tech/20220923 How To Enable RPM Fusion Repository In Fedora, RHEL, AlmaLinux, Rocky Linux.md
> [手动选题][tech]: 20220923 How To Enable RPM Fusion Repository In Fedora, RHEL, AlmaLinux, Rocky Linux.md

- sources/tech/20220922 Ansible Register Variable.md
> [手动选题][tech]: 20220922 Ansible Register Variable.md

- sources/news/20220923 Kubernetes To Soon Support Confidential Computing.md
> [手动选题][news]: 20220923 Kubernetes To Soon Support Confidential Computing.md

- sources/news/20220923 Lawmakers Proposes A New Bill To Protect Open Source Software.md
> [手动选题][news]: 20220923 Lawmakers Proposes A New Bill To Protect Open Source Software.md

- sources/news/20220923 Audacity 3.2 Released With VST3 Plugins and Apple Silicon Support.md
> [手动选题][news]: 20220923 Audacity 3.2 Released With VST3 Plugins and Apple Silicon Support.md

- sources/news/20220923 Systemd is Now Available in WSL.md
> [手动选题][news]: 20220923 Systemd is Now Available in WSL.md

- sources/news/20220923 A Modular Chromebook Launched by Framework and Google.md
> [手动选题][news]: 20220923 A Modular Chromebook Launched by Framework and Google.md

- sources/tech/20220922 EuroLinux Desktop is an RHEL-based Distro With Enterprise Perks.md
> [手动选题][tech]: 20220922 EuroLinux Desktop is an RHEL-based Distro With Enterprise Perks.md

- sources/tech/20220923 Customize Xfce Desktop for Modern Look and Productivity.md
> [手动选题][tech]: 20220923 Customize Xfce Desktop for Modern Look and Productivity.md

- sources/tech/20220922 How to Install and Use GNOME Boxes to Create Virtual Machines.md
> [手动选题][tech]: 20220922 How to Install and Use GNOME Boxes to Create Virtual Machines.md

- sources/tech/20220922 GNOME 43- Top New Features and Release Wiki.md
> [手动选题][tech]: 20220922 GNOME 43- Top New Features and Release Wiki.md

- sources/tech/20220922 4 Simple Steps to Clean Your Ubuntu System.md
> [手动选题][tech]: 20220922 4 Simple Steps to Clean Your Ubuntu System.md

- published/20220505 Boost the power of C with these open source libraries.md
@Donkey-Hao
https://linux.cn/article-15065-1.html
> RP:published/20220505 Boost the power of C with these open source libraries.md

- sources/news/20220923 Systemd is Now Available in WSL.md
申请翻译文章：news/20220923 Systemd is Now Available in WSL.md
> 翻译申请：20220923 Systemd is Now Available in WSL

- published/20220909 Connect to WiFi Using Terminal in Arch Linux and Other Distros.md
@geekpi
https://linux.cn/article-15067-1.html
> RP:published/20220909 Connect to WiFi Using Terminal in Arch Linux and Other Distros.md

- published/20220923 Systemd is Now Available in WSL.md
- translated/news/20220923 Systemd is Now Available in WSL.md
@vvvbbbcz
本文首发地址：https://linux.cn/article-15068-1.html
您的 LCTT 专页：https://linux.cn/lctt/vvvbbbcz
> RP:20220923 systemd is now available in wsl

- sources/tech/20220924 Drop your database for PostgreSQL.md
> [手动选题][tech]: 20220924 Drop your database for PostgreSQL.md

- sources/news/20220924 UbuntuDDE Remix 22.04 LTS Released!.md
> [手动选题][news]: 20220924 UbuntuDDE Remix 22.04 LTS Released!.md

- sources/tech/20220924 Wolfi is a Linux Un-distro- Built for Software Supply Chain Security.md
> [手动选题][tech]: 20220924 Wolfi is a Linux Un-distro- Built for Software Supply Chain Security.md

- sources/tech/20220926 How to Setup Internet in CentOS, RHEL, Rocky Linux Minimal Install.md
> [手动选题][tech]: 20220926 How to Setup Internet in CentOS, RHEL, Rocky Linux Minimal Install.md

- sources/tech/20220926 Speech Recognition to Text in Linux, Ubuntu using Google Docs.md
> [手动选题][tech]: 20220926 Speech Recognition to Text in Linux, Ubuntu using Google Docs.md

- sources/talk/20220926 The story behind Joplin, the open source note-taking app.md
> [手动选题][talk]: 20220926 The story behind Joplin, the open source note-taking app.md

- published/20220921 LibreOffice is Available for $8.99 on Mac App Store- Here-s Why!.md
- translated/news/20220921 LibreOffice is Available for $8.99 on Mac App Store- Here-s Why!.md
@cool-summer-021
本文首发地址：https://linux.cn/article-15075-1.html
您的 LCTT 专页：https://linux.cn/lctt/cool-summer-021
> RP:20220921 libre office is available for $8.99 on mac app store  here s why!

- published/20220908 Komikku- A Free and Open-Source Manga Reader for Linux.md
@geekpi
https://linux.cn/article-15078-1.html
> RP:published/20220908 Komikku- A Free and Open-Source Manga Reader for Linux.md

- sources/news/20220927 Google Unveils An Open Source C++ And Python Library, TensorStore.md
> [手动选题][news]: 20220927 Google Unveils An Open Source C++ And Python Library, TensorStore.md

- sources/news/20220927 Attacks On Open Source Software Are On The Rise.md
> [手动选题][news]: 20220927 Attacks On Open Source Software Are On The Rise.md

- sources/tech/20220927 165+ JavaScript terms you need to know.md
> [手动选题][tech]: 20220927 165+ JavaScript terms you need to know.md

- sources/tech/20220927 Get change alerts from any website with this open source tool.md
> [手动选题][tech]: 20220927 Get change alerts from any website with this open source tool.md

- sources/news/20220927 System76 Won-t Release Pop!_OS 22.10 Linux Distro- Here-s Why!.md
> [手动选题][news]: 20220927 System76 Won-t Release Pop!_OS 22.10 Linux Distro- Here-s Why!.md

- sources/news/20220927 ONLYOFFICE 7.2 Introduces Plugin Marketplace, Live Viewer, and More.md
> [手动选题][news]: 20220927 ONLYOFFICE 7.2 Introduces Plugin Marketplace, Live Viewer, and More.md

- sources/tech/20220927 How to Migrate to Fedora Linux from Ubuntu [Beginner-s Guide].md
> [手动选题][tech]: 20220927 How to Migrate to Fedora Linux from Ubuntu [Beginner-s Guide].md

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/questions.yml
- .github/ISSUE_TEMPLATE/topics.yml
I added two templates, question and topic, which can prompt users how to submit an Issue and help unify the submission format.
> Add issue topics template

- published/20220915 How I switched from Docker Desktop to Colima.md
@geekpi
https://linux.cn/article-15084-1.html
> RP:published/20220915 How I switched from Docker Desktop to Colima.md

- sources/tech/20220929 Execute Commands On Remote Linux Systems Via SSH.md
> [手动选题][tech]: 20220929 Execute Commands On Remote Linux Systems Via SSH.md

- sources/tech/20220929 How to Use Picture in Picture Mode in Brave Browser.md
> [手动选题][tech]: 20220929 How to Use Picture in Picture Mode in Brave Browser.md

- sources/tech/20220927 GUI Apps for Package Management in Arch Linux.md
> [手动选题][tech]: 20220927 GUI Apps for Package Management in Arch Linux.md

- sources/tech/20220929 How Podman packaging works on Linux.md
> [手动选题][tech]: 20220929 How Podman packaging works on Linux.md

- sources/talk/20220928 Build an open source project using this essential advice.md
> [手动选题][talk]: 20220928 Build an open source project using this essential advice.md

- sources/news/20220928 Oh No!😱Fedora is Dropping Support for Popular Video Codecs [Here-s Why!].md
> [手动选题][news]: 20220928 Oh No!😱Fedora is Dropping Support for Popular Video Codecs [Here-s Why!].md

- sources/news/20220928 Penpot, Gains Additional Users Thanks To Adobe-s Figma Purchase.md
> [手动选题][news]: 20220928 Penpot, Gains Additional Users Thanks To Adobe-s Figma Purchase.md

- published/20220920 Atoms is a GUI Tool to Let You Manage Linux Chroot Environments Easily.md
@geekpi
https://linux.cn/article-15087-1.html
> RP:published/20220920 Atoms is a GUI Tool to Let You Manage Linux Chroot Environments Easily.md

- published/20220922 4 Simple Steps to Clean Your Ubuntu System.md
@Donkey-Hao
https://linux.cn/article-15089-1.html
> RP:published/20220922 4 Simple Steps to Clean Your Ubuntu System.md

- sources/news/20220920 Loongson is Getting Ready for LoongArch Linux Laptops.md
翻译申请：`20220920 Loongson is Getting Ready for LoongArch Linux Laptops.md`
> 翻译申请：20220920 Loongson is Getting Ready for LoongArch Linux Laptops.md

- sources/news/20220920 Loongson is Getting Ready for LoongArch Linux Laptops.md
Reverts LCTT/TranslateProject#27373
> Revert "翻译申请：20220920 Loongson is Getting Ready for LoongArch Linux Laptops.md"

- sources/news/20220927 Attacks On Open Source Software Are On The Rise.md
翻译申请：`20220927 Attacks On Open Source Software Are On The Rise.md`
> 翻译申请：20220927 Attacks On Open Source Software Are On The Rise.md

- sources/tech/20220923 11 Gorgeous KDE Plasma Themes to Make Your Linux Desktop Even More Beautiful.md
申请翻译：`20220923 11 Gorgeous KDE Plasma Themes to Make Your Linux Desktop Even More Beautiful.md`
> [翻译申请][tech]: 20220923 11 Gorgeous KDE Plasma Themes to Make Your Linux Desktop Even More Beautiful.md

- sources/news/20220930 Red Hat Rolls Out OpenStack Platform 17.md
> [手动选题][news]: 20220930 Red Hat Rolls Out OpenStack Platform 17.md

- published/20220920 3 ways to use the Linux inxi command.md
@geekpi
https://linux.cn/article-15092-1.html
> RP:published/20220920 3 ways to use the Linux inxi command.md

- sources/news/20220930 Wow! You Can Now Use Ubuntu Desktop on Cloud.md
> [手动选题][news]: 20220930 Wow! You Can Now Use Ubuntu Desktop on Cloud.md

- sources/news/20220930 [Exclusive] Tuxedo Makes Ubuntu-based -TUXEDO OS- Available For All.md
> [手动选题][news]: 20220930 [Exclusive] Tuxedo Makes Ubuntu-based -TUXEDO OS- Available For All.md

- sources/tech/20220930 How to Properly Theme KDE Plasma [An in-depth Guide].md
> [手动选题][tech]: 20220930 How to Properly Theme KDE Plasma [An in-depth Guide].md

- sources/tech/20220930 How I dock my Linux laptop.md
> [手动选题][tech]: 20220930 How I dock my Linux laptop.md

- sources/news/20221001 A Native Linux GPU Driver for Apple Silicon is Almost Ready!.md
> [手动选题][news]: 20221001 A Native Linux GPU Driver for Apple Silicon is Almost Ready!.md

- sources/tech/20221001 How To Use Ansible Vault To Protect Sensitive Playbook Data.md
> [手动选题][tech]: 20221001 How To Use Ansible Vault To Protect Sensitive Playbook Data.md

- sources/tech/20220927 Better than Ubuntu- 11 Best Linux Distros for Ubuntu Lovers.md
> [手动选题][tech]: 20220927 Better than Ubuntu- 11 Best Linux Distros for Ubuntu Lovers.md

- sources/talk/20221001 What-s new with Awk-.md
> [手动选题][talk]: 20221001 What-s new with Awk-.md

- sources/tech/20221001 Transform Your Arch Installation with Stunning XMonad WM Setup.md
> [手动选题][tech]: 20221001 Transform Your Arch Installation with Stunning XMonad WM Setup.md

- published/20220923 11 Gorgeous KDE Plasma Themes to Make Your Linux Desktop Even More Beautiful.md
@vvvbbbcz
https://linux.cn/article-15102-1.html
> RP:published/20220923 11 Gorgeous KDE Plasma Themes to Make Your Linux Desktop Even More Beautiful.md

- published/20220923 Install JDBC on Linux in 3 steps.md
@geekpi
https://linux.cn/article-15103-1.html
> RP:published/20220923 Install JDBC on Linux in 3 steps.md

- published/20220915 How To Prevent Command Arguments With Sudo In Linux.md
@geekpi
https://linux.cn/article-15106-1.html
> RP:published/20220915 How To Prevent Command Arguments With Sudo In Linux.md

- sources/news/20221003 Get Ready for Ubuntu MATE Experience on Debian Linux!.md
> [手动选题][news]: 20221003 Get Ready for Ubuntu MATE Experience on Debian Linux!.md

- sources/tech/20221002 How to Enable RPM Fusion Repo in Fedora, CentOS, RHEL.md
> [手动选题][tech]: 20221002 How to Enable RPM Fusion Repo in Fedora, CentOS, RHEL.md

- sources/tech/20221002 String Processing in LibreOffice Calc Macro with Examples.md
> [手动选题][tech]: 20221002 String Processing in LibreOffice Calc Macro with Examples.md

- sources/tech/20221002 5 Great GUI Apps for Visual Disk Usage in Linux, Ubuntu [With Bonus].md
> [手动选题][tech]: 20221002 5 Great GUI Apps for Visual Disk Usage in Linux, Ubuntu [With Bonus].md

- published/20220914 CNCF Accepts Open Source Hexa Project As A Sandbox Project.md
- translated/news/20220914 CNCF Accepts Open Source Hexa Project As A Sandbox Project.md
@littlebirdnest
请对比我的校对，改进你的翻译质量。
https://linux.cn/article-15109-1.html
> RP:20220914 cncf accepts open source hexa project as a sandbox project

- published/20220930 [Exclusive] Tuxedo Makes Ubuntu-based -TUXEDO OS- Available For All.md
- translated/news/20220930 [Exclusive] Tuxedo Makes Ubuntu-based -TUXEDO OS- Available For All.md
@Cubik65536
感谢您，完成了第一篇翻译贡献
本文首发地址：https://linux.cn/article-15110-1.html
您的 LCTT 专页：https://linux.cn/lctt/Cubik65536
> RP:20220930 exclusive] tuxedo makes ubuntu based  tuxedo os  available for all

- sources/tech/20221003 CPU-X an Alternative to CPU-Z for Linux.md
> [手动选题][tech]: 20221003 CPU-X an Alternative to CPU-Z for Linux.md

- sources/tech/20221004 Learn the OSI model in 5 minutes.md
> [手动选题][tech]: 20221004 Learn the OSI model in 5 minutes.md

- sources/tech/20221004 5 new improvements in Apache ShardingSphere.md
> [手动选题][tech]: 20221004 5 new improvements in Apache ShardingSphere.md

- sources/tech/20221004 How to Install and Configure IceWM in Arch Linux.md
> [手动选题][tech]: 20221004 How to Install and Configure IceWM in Arch Linux.md

- sources/tech/20221004 5 Best Python IDE-s- and Code Editor-s-.md
> [手动选题][tech]: 20221004 5 Best Python IDE-s- and Code Editor-s-.md

- sources/tech/20221004 How to Enable, Disable Keyboard, Mouse and Touch Devices via Terminal.md
> [手动选题][tech]: 20221004 How to Enable, Disable Keyboard, Mouse and Touch Devices via Terminal.md

- sources/tech/20221004 Ubuntu 22.10- Top New Features and Release Wiki.md
> [手动选题][tech]: 20221004 Ubuntu 22.10- Top New Features and Release Wiki.md

- sources/talk/20221004 Security Issues With Open Source In Today-s World.md
> [手动选题][talk]: 20221004 Security Issues With Open Source In Today-s World.md

- sources/tech/20221004 Using R for Building an Interactive Web App.md
> [手动选题][tech]: 20221004 Using R for Building an Interactive Web App.md

- sources/news/20221003 World-s First Open Source Wi-Fi 7 Access Points Are Now Available.md
> [手动选题][news]: 20221003 World-s First Open Source Wi-Fi 7 Access Points Are Now Available.md

- published/20221001 A Native Linux GPU Driver for Apple Silicon is Almost Ready!.md
- translated/news/20221001 A Native Linux GPU Driver for Apple Silicon is Almost Ready!.md
@KevinZonda
本文首发地址：https://linux.cn/article-15114-1.html
您的 LCTT 专页：https://linux.cn/lctt/KevinZonda
> RP:20221001 a native linux gpu driver for apple silicon is almost ready!

- sources/tech/20221007 Tar Command in Linux with Practical Examples.md
> [手动选题][tech]: 20221007 Tar Command in Linux with Practical Examples.md

- sources/tech/20221006 Dynamically update TLS certificates in a Golang server without downtime.md
> [手动选题][tech]: 20221006 Dynamically update TLS certificates in a Golang server without downtime.md

- sources/news/20221006 Google AI Unveils A New Open Source Library for Array Storage.md
> [手动选题][news]: 20221006 Google AI Unveils A New Open Source Library for Array Storage.md

- sources/tech/20221006 Implementing JWT Using the Flask Framework.md
> [手动选题][tech]: 20221006 Implementing JWT Using the Flask Framework.md

- sources/tech/20221006 Pros and Cons of Using Btrfs Filesystem in Linux.md
> [手动选题][tech]: 20221006 Pros and Cons of Using Btrfs Filesystem in Linux.md

- sources/tech/20221006 Upgrade Various Kinds of Packages in Linux at Once With Topgrade.md
> [手动选题][tech]: 20221006 Upgrade Various Kinds of Packages in Linux at Once With Topgrade.md

- sources/news/20221006 A New Open Source Vulkan Driver for NVIDIA Graphics is Ready to Test!.md
> [手动选题][news]: 20221006 A New Open Source Vulkan Driver for NVIDIA Graphics is Ready to Test!.md

- sources/news/20221006 Ubuntu Pro Now Gives You 10 Years of Security Updates for Free.md
> [手动选题][news]: 20221006 Ubuntu Pro Now Gives You 10 Years of Security Updates for Free.md

- sources/tech/20221007 Essential DNF Commands for Linux Users [With Examples].md
> [手动选题][tech]: 20221007 Essential DNF Commands for Linux Users [With Examples].md

- sources/tech/20221007 What is KDE Connect- How Do You Use It- [Beginner-s Guide].md
> [手动选题][tech]: 20221007 What is KDE Connect- How Do You Use It- [Beginner-s Guide].md

- sources/tech/20221006 EuroLinux Desktop Review- A Worthy Alternative to Ubuntu LTS-.md
> [手动选题][tech]: 20221006 EuroLinux Desktop Review- A Worthy Alternative to Ubuntu LTS-.md

- published/20220927 System76 Won-t Release Pop!_OS 22.10 Linux Distro- Here-s Why!.md
- translated/news/20220927 System76 Won-t Release Pop!_OS 22.10 Linux Distro- Here-s Why!.md
@Cubik65536
https://linux.cn/article-15116-1.html
> RP:20220927 system76 won t release pop! os 22.10 linux distro  here s why!

- sources/news/20221006 Ubuntu Pro Now Gives You 10 Years of Security Updates for Free.md
> [Translate Request][news] 20221006 Ubuntu Pro Now Gives You 10 Years of Security Update for Free

- sources/tech/20221008 How to Create LVM Partition Step-by-Step in Linux.md
> [手动选题][tech]: 20221008 How to Create LVM Partition Step-by-Step in Linux.md

- sources/tech/20221009 5 Great Subtitle Editors in Linux Systems.md
> [手动选题][tech]: 20221009 5 Great Subtitle Editors in Linux Systems.md

- sources/tech/20221009 Best Whiteboard Applications for Linux Systems.md
> [手动选题][tech]: 20221009 Best Whiteboard Applications for Linux Systems.md

- sources/tech/20221008 Make KDE Control Centre Look Like macOS with this Widget.md
> [手动选题][tech]: 20221008 Make KDE Control Centre Look Like macOS with this Widget.md

- sources/tech/20221008 How to Use Raspberry Pi via VNC.md
> [手动选题][tech]: 20221008 How to Use Raspberry Pi via VNC.md

- published/20221006 A New Open Source Vulkan Driver for NVIDIA Graphics is Ready to Test!.md
@Cubik65536
https://linux.cn/article-15124-1.html
> RP:published/20221006 A New Open Source Vulkan Driver for NVIDIA Graphics is Ready to Test!.md

- sources/tech/20221011 Groovy vs Java- Connecting a PostgreSQL database with JDBC.md
> [手动选题][tech]: 20221011 Groovy vs Java- Connecting a PostgreSQL database with JDBC.md

- sources/news/20221011 VirtualBox 7.0 Releases With Secure Boot and Full VM Encryption Support.md
> [手动选题][news]: 20221011 VirtualBox 7.0 Releases With Secure Boot and Full VM Encryption Support.md

- sources/tech/20221010 How to Update Google Chrome on Ubuntu Linux.md
> [手动选题][tech]: 20221010 How to Update Google Chrome on Ubuntu Linux.md

- sources/tech/20221010 Xubuntu 22.10- Top New Features.md
> [手动选题][tech]: 20221010 Xubuntu 22.10- Top New Features.md

- published/20220924 Drop your database for PostgreSQL.md
- translated/tech/20220924 Drop your database for PostgreSQL.md
@chai001125
感谢您完成了第一篇翻译贡献！
本文首发地址：https://linux.cn/article-15132-1.html
您的 LCTT 专页：https://linux.cn/lctt/chai001125
> RP:20220924 drop your database for postgre sql

- published/20220919 PyLint- The good, the bad, and the ugly.md
@MjSeven
https://linux.cn/article-15144-1.html
> RP:published/20220919 PyLint- The good, the bad, and the ugly.md

- sources/tech/20221012 Kubuntu 22.10 Kinetic Kudu- Top New Features.md
> [手动选题][tech]: 20221012 Kubuntu 22.10 Kinetic Kudu- Top New Features.md

- sources/tech/20221013 Enjoy the Classic Snake Game in Your Linux Terminal.md
> [手动选题][tech]: 20221013 Enjoy the Classic Snake Game in Your Linux Terminal.md

- sources/tech/20221013 Ubuntu Budgie 22.10 Kinetic Kudu- Top New Features.md
> [手动选题][tech]: 20221013 Ubuntu Budgie 22.10 Kinetic Kudu- Top New Features.md

- sources/tech/20221013 Learn Bash base64 Encode and Decode With Examples.md
> [手动选题][tech]: 20221013 Learn Bash base64 Encode and Decode With Examples.md

- sources/tech/20221015 How to Enable and Access USB Drive in VirtualBox.md
> [手动选题][tech]: 20221015 How to Enable and Access USB Drive in VirtualBox.md

- sources/tech/20221013 How To Monitor User Activity In Linux.md
> [手动选题][tech]: 20221013 How To Monitor User Activity In Linux.md

- sources/tech/20221014 How To Restrict Access To Linux Servers Using TCP Wrappers.md
> [手动选题][tech]: 20221014 How To Restrict Access To Linux Servers Using TCP Wrappers.md

- sources/tech/20221012 How to Set Static IP Address on Ubuntu Server 22.04.md
> [手动选题][tech]: 20221012 How to Set Static IP Address on Ubuntu Server 22.04.md

- sources/news/20221014 First Look at LURE! Bringing AUR to All Linux Distros.md
> [手动选题][news]: 20221014 First Look at LURE! Bringing AUR to All Linux Distros.md

- sources/news/20221013 Blender 3.4 to Enable Native Wayland Support for Linux.md
> [手动选题][news]: 20221013 Blender 3.4 to Enable Native Wayland Support for Linux.md

- sources/news/20221014 Notion-like Markdown Note-Taking App -Obsidian- is Out of Beta.md
> [手动选题][news]: 20221014 Notion-like Markdown Note-Taking App -Obsidian- is Out of Beta.md

- sources/tech/20221013 Asynchronous programming in Rust.md
> [手动选题][tech]: 20221013 Asynchronous programming in Rust.md

- sources/tech/20221013 What you need to know about compiling code.md
> [手动选题][tech]: 20221013 What you need to know about compiling code.md

- sources/tech/20221014 Can Kubernetes help solve automation challenges-.md
> [手动选题][tech]: 20221014 Can Kubernetes help solve automation challenges-.md

- sources/tech/20221014 Install Gedit on Ubuntu 22.10 and Make it Default Text Editor.md
> [手动选题][tech]: 20221014 Install Gedit on Ubuntu 22.10 and Make it Default Text Editor.md

- sources/tech/20221014 13 Independent Linux Distros That are Built From Scratch.md
> [手动选题][tech]: 20221014 13 Independent Linux Distros That are Built From Scratch.md

- sources/tech/20221010 14 Best Open Source WYSIWYG HTML Editors.md
> [手动选题][tech]: 20221010 14 Best Open Source WYSIWYG HTML Editors.md

- sources/tech/20221014 Celebrating KDE-s 26th Birthday With Some Inspiring Facts From Its Glorious Past!.md
> [手动选题][tech]: 20221014 Celebrating KDE-s 26th Birthday With Some Inspiring Facts From Its Glorious Past!.md

- published/20221002 How to Enable RPM Fusion Repo in Fedora, CentOS, RHEL.md
@geekpi
https://linux.cn/article-15145-1.html
> RP:published/20221002 How to Enable RPM Fusion Repo in Fedora, CentOS, RHEL.md

- published/20220927 GUI Apps for Package Management in Arch Linux.md
@geekpi
https://linux.cn/article-15149-1.html
> RP:published/20220927 GUI Apps for Package Management in Arch Linux.md

- published/20221008 How to Create LVM Partition Step-by-Step in Linux.md
@geekpi
https://linux.cn/article-15152-1.html
> RP:published/20221008 How to Create LVM Partition Step-by-Step in Linux.md

- published/20220912 Python Microservices Using Flask on Kubernetes.md
@MjSeven
https://linux.cn/article-15154-1.html
> RP:published/20220912 Python Microservices Using Flask on Kubernetes.md

- published/20221010 Xubuntu 22.10- Top New Features.md
@geekpi
https://linux.cn/article-15155-1.html
> RP:published/20221010 Xubuntu 22.10- Top New Features.md

- published/20220919 How To Find Default Gateway IP Address In Linux And Unix From Commandline.md
@MjSeven
https://linux.cn/article-15158-1.html
> RP:published/20220919 How To Find Default Gateway IP Address In Linux And Unix From Commandline.md

- published/20221011 How to Enable Snap Support in Arch Linux.md
@geekpi
https://linux.cn/article-15160-1.html
> RP:published/20221011 How to Enable Snap Support in Arch Linux.md

- published/20221010 How to Update Google Chrome on Ubuntu Linux.md
@geekpi
https://linux.cn/article-15163-1.html
> RP:published/20221010 How to Update Google Chrome on Ubuntu Linux.md

- sources/news/20221017-⭐️-Ubuntu-but-rolling-but-also-stable-That-s-what-Rhino-Linux-aims-to-be.md
> [手动选题][news]: 20221017-⭐️-Ubuntu-but-rolling-but-also-stable-That-s-what-Rhino-Linux-aims-to-be.md

- sources/tech/20221021-⭐️-How-to-Install-AWS-CLI-on-Linux-Step-by-Step.md
> [手动选题][tech]: 20221021-⭐️-How-to-Install-AWS-CLI-on-Linux-Step-by-Step.md

- sources/tech/20221015-⭐️⭐️-How-to-Get-Started-with-Shell-Scripting-in-Linux.md
> [手动选题][tech]: 20221015-⭐️⭐️-How-to-Get-Started-with-Shell-Scripting-in-Linux.md

- sources/tech/20221020-⭐️-4-open-source-editors-I-use-for-my-writing.md
> [手动选题][tech]: 20221020-⭐️-4-open-source-editors-I-use-for-my-writing.md

- sources/talk/20221019-⭐️⭐️-Our-open-source-startup-journey.md
> [手动选题][talk]: 20221019-⭐️⭐️-Our-open-source-startup-journey.md

- sources/talk/20221018-⭐️⭐️⭐️-Exploring-innovative-Open-Organization-charts.md
> [手动选题][talk]: 20221018-⭐️⭐️⭐️-Exploring-innovative-Open-Organization-charts.md

- sources/tech/20221017-⭐️⭐️⭐️-Open-source-DevOps-tools-in-a-platform-future.md
> [手动选题][tech]: 20221017-⭐️⭐️⭐️-Open-source-DevOps-tools-in-a-platform-future.md

- sources/tech/20221017-⭐️⭐️⭐️-Why-you-should-consider-Rexx-for-scripting.md
> [手动选题][tech]: 20221017-⭐️⭐️⭐️-Why-you-should-consider-Rexx-for-scripting.md

- sources/talk/20221016-⭐️⭐️-What’s-new-in-GNOME-43-.md
> [手动选题][talk]: 20221016-⭐️⭐️-What’s-new-in-GNOME-43-.md

- sources/tech/20221018-⭐️-Setup-Docker-And-Docker-Compose-With-DockSTARTer.md
> [手动选题][tech]: 20221018-⭐️-Setup-Docker-And-Docker-Compose-With-DockSTARTer.md

- sources/tech/20221022.0 ⭐️⭐️ How to use journalctl to View and Analyze Systemd Logs [With Examples].md
> [手动选题][tech]: 20221022.0 ⭐️⭐️ How to use journalctl to View and Analyze Systemd Logs [With Examples].md

- published/20221017.3 ⭐️⭐️⭐️ Open source DevOps tools in a platform future.md
@lxbwolf
https://linux.cn/article-15170-1.html
> RP:published/20221017.3 ⭐️⭐️⭐️ Open source DevOps tools in a platform future.md

- published/20210530 Complete Guide to Configuring SSH in Ubuntu.md
@Donkey-Hao
https://linux.cn/article-15175-1.html
> RP:published/20210530 Complete Guide to Configuring SSH in Ubuntu.md

- published/20210604 Optimize Java serverless functions in Kubernetes.md
@cool-summer-021
https://linux.cn/article-15178-1.html
> RP:published/20210604 Optimize Java serverless functions in Kubernetes.md

- published/20221012 How to Set Static IP Address on Ubuntu Server 22.04.md
@geekpi
https://linux.cn/article-15181-1.html
> RP:20221012 how to set static ip address on ubuntu server 22.04

- published/20221021.2 ⭐️⭐️  10 Things to Do After Installing Ubuntu 22.10 [With Bonus Tip].md
@chai001125
https://linux.cn/article-15185-1.html
> RP:published/20221021.2 ⭐️⭐️  10 Things to Do After Installing Ubuntu 22.10 [With Bonus Tip].md

- published/20221013 Enjoy the Classic Snake Game in Your Linux Terminal.md
@geekpi
https://linux.cn/article-15186-1.html
> RP:published/20221013 Enjoy the Classic Snake Game in Your Linux Terminal.md

- sources/tech/20221024.0 ⭐️⭐️ Give your Terminal a Retro Look Using this Neat Application.md
> [手动选题][tech]: 20221024.0 ⭐️⭐️ Give your Terminal a Retro Look Using this Neat Application.md

- sources/news/20221028.5 ⭐️ Zorin OS 16.2 Released, It's All About Useful Refinements.md
> [手动选题][news]: 20221028.5 ⭐️ Zorin OS 16.2 Released, It's All About Useful Refinements.md

- sources/news/20221028.4 ⭐️ Oh No! Fedora 37 Release Gets Delayed.md
> [手动选题][news]: 20221028.4 ⭐️ Oh No! Fedora 37 Release Gets Delayed.md

- sources/news/20221028.3 ⭐️ A New Web Browser For P2P Internet Experience With Secure Messaging and Bitcoin Lightning Network.md
> [手动选题][news]: 20221028.3 ⭐️ A New Web Browser For P2P Internet Experience With Secure Messaging and Bitcoin Lightning Network.md

- sources/news/20221027.13 ⭐️ Canonical's Adding a Neat Ability to the Steam Snap App for Gamers.md
> [手动选题][news]: 20221027.13 ⭐️ Canonical's Adding a Neat Ability to the Steam Snap App for Gamers.md

- sources/news/20221026.5 ⭐️ Vanilla OS More Than Just Vanilla GNOME With Ubuntu.md
> [手动选题][news]: 20221026.5 ⭐️ Vanilla OS More Than Just Vanilla GNOME With Ubuntu.md

- sources/tech/20221025.3 ⭐️ How to Change Login Screen Background in Ubuntu.md
> [手动选题][tech]: 20221025.3 ⭐️ How to Change Login Screen Background in Ubuntu.md

- sources/tech/20221025.2 ⭐️⭐️ Fedora 37 Top New Features and Release Wiki.md
> [手动选题][tech]: 20221025.2 ⭐️⭐️ Fedora 37 Top New Features and Release Wiki.md

- sources/tech/20221026.4 ⭐️ How to Install Python 3.11 in Ubuntu and Other Related Linux.md
> [手动选题][tech]: 20221026.4 ⭐️ How to Install Python 3.11 in Ubuntu and Other Related Linux.md

- sources/tech/20221026.3 ⭐️⭐️ Ubuntu Unity 22.10 Review A Promising “Official” Start.md
> [手动选题][tech]: 20221026.3 ⭐️⭐️ Ubuntu Unity 22.10 Review A Promising “Official” Start.md

- sources/tech/20221027.12 ⭐️ Customize GNOME 42 with A Polished Look.md
> [手动选题][tech]: 20221027.12 ⭐️ Customize GNOME 42 with A Polished Look.md

- sources/tech/20221027.10 ⭐️⭐️ Customize GNOME 40 Desktop to Look Like macOS [Guide].md
> [手动选题][tech]: 20221027.10 ⭐️⭐️ Customize GNOME 40 Desktop to Look Like macOS [Guide].md

- sources/tech/20221027.9 ⭐️ Customize GNOME Desktop in Ubuntu with this Colorful Looks.md
> [手动选题][tech]: 20221027.9 ⭐️ Customize GNOME Desktop in Ubuntu with this Colorful Looks.md

- sources/tech/20221027.2 ⭐️ Customize GNOME in Ubuntu 20.04 with this Productive Look.md
> [手动选题][tech]: 20221027.2 ⭐️ Customize GNOME in Ubuntu 20.04 with this Productive Look.md

- sources/tech/20221027.7 ⭐️⭐️ Mabox Linux – Beautiful Arch Linux with Openbox [Review].md
> [手动选题][tech]: 20221027.7 ⭐️⭐️ Mabox Linux – Beautiful Arch Linux with Openbox [Review].md

- sources/tech/20221027.6 ⭐️⭐️ Top 10 Linux Distributions for Programmers in 2022 [Featured].md
> [手动选题][tech]: 20221027.6 ⭐️⭐️ Top 10 Linux Distributions for Programmers in 2022 [Featured].md

- sources/tech/20221027.5 ⭐️⭐️ Top 10 Most Beautiful Linux Distributions [Featured].md
> [手动选题][tech]: 20221027.5 ⭐️⭐️ Top 10 Most Beautiful Linux Distributions [Featured].md

- sources/tech/20221027.4 ⭐️⭐️ 10 Lightweight Linux Distributions for your Old Hardware in 2022.md
> [手动选题][tech]: 20221027.4 ⭐️⭐️ 10 Lightweight Linux Distributions for your Old Hardware in 2022.md

- sources/tech/20221026.2 ⭐️ How To Monitor File Changes Using fswatch In Linux.md
> [手动选题][tech]: 20221026.2 ⭐️ How To Monitor File Changes Using fswatch In Linux.md

- sources/tech/20221025.0 ⭐️⭐️ Transfer files and folders from Windows to Linux with PSCP.md
> [手动选题][tech]: 20221025.0 ⭐️⭐️ Transfer files and folders from Windows to Linux with PSCP.md

- sources/tech/20221026.1 ⭐️⭐️ Tips for using the Linux test command.md
> [手动选题][tech]: 20221026.1 ⭐️⭐️ Tips for using the Linux test command.md

- sources/tech/20221026.0 ⭐️⭐️⭐️ Doing 64-bit math on a 16-bit system.md
> [手动选题][tech]: 20221026.0 ⭐️⭐️⭐️ Doing 64-bit math on a 16-bit system.md

- sources/tech/20221027.1 ⭐️⭐️ Trick Lua into becoming an object-oriented language.md
> [手动选题][tech]: 20221027.1 ⭐️⭐️ Trick Lua into becoming an object-oriented language.md

- sources/talk/20221028.1 ⭐️⭐️ Write documentation like you develop code.md
> [手动选题][talk]: 20221028.1 ⭐️⭐️ Write documentation like you develop code.md

- sources/tech/20221029.1 ⭐️⭐️ Set up a Matrix to Discord bot.md
> [手动选题][tech]: 20221029.1 ⭐️⭐️ Set up a Matrix to Discord bot.md

- sources/tech/20221027.0 ⭐️ How to Upgrade Python Packages with Pip.md
> [手动选题][tech]: 20221027.0 ⭐️ How to Upgrade Python Packages with Pip.md

- sources/tech/20221029.0 ⭐️⭐️ 7 Best Open Source Web-based Email Clients.md
> [手动选题][tech]: 20221029.0 ⭐️⭐️ 7 Best Open Source Web-based Email Clients.md

- sources/tech/20221028.0 ⭐️ How to Install PostgreSQL 15 on Ubuntu 22.04 Step-by-Step.md
> [手动选题][tech]: 20221028.0 ⭐️ How to Install PostgreSQL 15 on Ubuntu 22.04 Step-by-Step.md

- sources/tech/20221024.2 ⭐️ How to Clean Up Flatpak Apps to Clear Disk Space.md
> [手动选题][tech]: 20221024.2 ⭐️ How to Clean Up Flatpak Apps to Clear Disk Space.md

- sources/tech/20221024.1 ⭐️ How to Check CPU and HDD Temperature in Ubuntu and Other Linux.md
> [手动选题][tech]: 20221024.1 ⭐️ How to Check CPU and HDD Temperature in Ubuntu and Other Linux.md

- published/20221014 Install Gedit on Ubuntu 22.10 and Make it Default Text Editor.md
@geekpi
https://linux.cn/article-15194-1.html
> RP:published/20221014 Install Gedit on Ubuntu 22.10 and Make it Default Text Editor.md

- sources/tech/20221030.2 ⭐️⭐️ Install WoeUSB on Ubuntu to Create a Bootable Windows USB.md
> [手动选题][tech]: 20221030.2 ⭐️⭐️ Install WoeUSB on Ubuntu to Create a Bootable Windows USB.md

- sources/tech/20221030.1 ⭐️⭐️ 3 Best Free Photoshop Alternatives for Ubuntu and other Linux.md
> [手动选题][tech]: 20221030.1 ⭐️⭐️ 3 Best Free Photoshop Alternatives for Ubuntu and other Linux.md

- sources/tech/20221030.0 ⭐️ How to Enable Dark Mode in Web Browser.md
> [手动选题][tech]: 20221030.0 ⭐️ How to Enable Dark Mode in Web Browser.md

- sources/talk/20221031.0 ⭐️⭐️⭐️ 20 technology horror stories about learning the hard way.md
> [手动选题][talk]: 20221031.0 ⭐️⭐️⭐️ 20 technology horror stories about learning the hard way.md

- sources/news/20221031.4 ⭐️ Portmaster 1.0 Release Marks it as a Solid Open-Source Application Firewall for Privacy-Focused Users.md
> [手动选题][news]: 20221031.4 ⭐️ Portmaster 1.0 Release Marks it as a Solid Open-Source Application Firewall for Privacy-Focused Users.md

- sources/tech/20221031.3 ⭐️⭐️ 5 Best Mastodon Clients for Ubuntu and Other Linux.md
> [手动选题][tech]: 20221031.3 ⭐️⭐️ 5 Best Mastodon Clients for Ubuntu and Other Linux.md

- sources/tech/20221031.2 ⭐️ How to View AVIF Images in Ubuntu and Other Linux Distributions.md
> [手动选题][tech]: 20221031.2 ⭐️ How to View AVIF Images in Ubuntu and Other Linux Distributions.md

- sources/tech/20221031.1 ⭐️⭐️⭐️ 10 universal steps for open source code review.md
> [手动选题][tech]: 20221031.1 ⭐️⭐️⭐️ 10 universal steps for open source code review.md

- sources/tech/20221101.11 ⭐️⭐️ How to Install Flatpak Apps in Ubuntu and Other Linux.md
> [手动选题][tech]: 20221101.11 ⭐️⭐️ How to Install Flatpak Apps in Ubuntu and Other Linux.md

- sources/tech/20221101.10 ⭐️⭐️ Best Remote Desktop Clients for Ubuntu and Other Linux [2022].md
> [手动选题][tech]: 20221101.10 ⭐️⭐️ Best Remote Desktop Clients for Ubuntu and Other Linux [2022].md

- sources/tech/20221101.8 ⭐️⭐️ Feren OS Review Clever KDE Distro for Easy Migration from Windows.md
> [手动选题][tech]: 20221101.8 ⭐️⭐️ Feren OS Review Clever KDE Distro for Easy Migration from Windows.md

- sources/tech/20221101.7 ⭐️ Move Virtual Machine Image to Another Host Using GNOME Boxes.md
> [手动选题][tech]: 20221101.7 ⭐️ Move Virtual Machine Image to Another Host Using GNOME Boxes.md

- sources/tech/20221101.6 ⭐️⭐️ How to Install and Use GNOME Boxes to Create Virtual Machines.md
> [手动选题][tech]: 20221101.6 ⭐️⭐️ How to Install and Use GNOME Boxes to Create Virtual Machines.md

- sources/news/20221101.4 ⭐️⭐️ Kate Editor is Getting Four New Awesome Features.md
> [手动选题][news]: 20221101.4 ⭐️⭐️ Kate Editor is Getting Four New Awesome Features.md

- sources/news/20221101.3 ⭐️ The Android Open Source Project Is Now RISC-V Compatible.md
> [手动选题][news]: 20221101.3 ⭐️ The Android Open Source Project Is Now RISC-V Compatible.md

- sources/tech/20221101.2 ⭐️ Uninstall Snap Packages from Ubuntu and Other Linux Distros.md
> [手动选题][tech]: 20221101.2 ⭐️ Uninstall Snap Packages from Ubuntu and Other Linux Distros.md

- sources/tech/20221101.1 ⭐️⭐️ Transfer files and folders from Windows to Linux with WinSCP.md
> [手动选题][tech]: 20221101.1 ⭐️⭐️ Transfer files and folders from Windows to Linux with WinSCP.md

- published/20221019.1 ⭐️ How to Install Viber in Ubuntu and Other Linux.md
@geekpi
https://linux.cn/article-15205-1.html
> RP:published/20221019.1 ⭐️ How to Install Viber in Ubuntu and Other Linux.md

- sources/news/20221102.1 ⭐️ Linux Mint's Update Manager Now Supports Flatpak.md
> [手动选题][news]: 20221102.1 ⭐️ Linux Mint's Update Manager Now Supports Flatpak.md

- sources/tech/20221103.0 ⭐️⭐️⭐️ How To Securely Transfer Files With SCP In Linux.md
- sources/tech/20221103.6 ⭐️⭐️⭐️ How To Securely Transfer Files With SCP In Linux.md
> [手动选题][tech]: 20221103.6 ⭐️⭐️⭐️ How To Securely Transfer Files With SCP In Linux.md

- sources/news/20221103.5 ⭐️ Grafana Phlare is a New Scalable Open-Source Database to Enhance Observability.md
> [手动选题][news]: 20221103.5 ⭐️ Grafana Phlare is a New Scalable Open-Source Database to Enhance Observability.md

- sources/tech/20221103.4 ⭐️ How to Install and Use Snap Packages in Ubuntu.md
> [手动选题][tech]: 20221103.4 ⭐️ How to Install and Use Snap Packages in Ubuntu.md

- sources/tech/20221103.2 ⭐️⭐️ How to Trim a Video in VLC Player [If You Really Want to].md
> [手动选题][tech]: 20221103.2 ⭐️⭐️ How to Trim a Video in VLC Player [If You Really Want to].md

- sources/tech/20221103.0 ⭐️⭐️ Is Lua worth learning.md
> [手动选题][tech]: 20221103.0 ⭐️⭐️ Is Lua worth learning.md

- sources/tech/20221102.4 ⭐️⭐️ Top 10 Features of Linux Mint 21 “Vanessa”.md
> [手动选题][tech]: 20221102.4 ⭐️⭐️ Top 10 Features of Linux Mint 21 “Vanessa”.md

- sources/tech/20221102.3 ⭐️⭐️ Top 10 32-Bit Linux Distributions in 2022 [Compared].md
> [手动选题][tech]: 20221102.3 ⭐️⭐️ Top 10 32-Bit Linux Distributions in 2022 [Compared].md

- sources/tech/20221102.2 ⭐️⭐️ Best 5 Alternatives to Microsoft Office [Compared].md
> [手动选题][tech]: 20221102.2 ⭐️⭐️ Best 5 Alternatives to Microsoft Office [Compared].md

- sources/tech/20210623 Parsing config files with Lua.md
> Update 20210623 Parsing config files with Lua.md

- sources/tech/20221104.7 ⭐️ How to iterate over tables in Lua.md
> [手动选题][tech]: 20221104.7 ⭐️ How to iterate over tables in Lua.md

- sources/tech/20221104.6 ⭐️⭐️ 10 Best Open Source Bots for Your Discord Server.md
> [手动选题][tech]: 20221104.6 ⭐️⭐️ 10 Best Open Source Bots for Your Discord Server.md

- sources/news/20221104.5 ⭐️ Gitpod, An Open Source Developer Platform, Obtains $25M.md
> [手动选题][news]: 20221104.5 ⭐️ Gitpod, An Open Source Developer Platform, Obtains $25M.md

- sources/tech/20221104.4 ⭐️ How to Remove Firefox Snap from Ubuntu (21.10 +).md
> [手动选题][tech]: 20221104.4 ⭐️ How to Remove Firefox Snap from Ubuntu (21.10 +).md

- sources/tech/20221104.3 ⭐️ How to Install Latest LibreOffice in Ubuntu and other Linux.md
> [手动选题][tech]: 20221104.3 ⭐️ How to Install Latest LibreOffice in Ubuntu and other Linux.md

- sources/tech/20221104.2 ⭐️ Upgrade to Latest LibreOffice in Ubuntu, Linux Mint and Windows.md
> [手动选题][tech]: 20221104.2 ⭐️ Upgrade to Latest LibreOffice in Ubuntu, Linux Mint and Windows.md

- sources/tech/20221104.1 ⭐️ How to Make LibreOffice Look Like Microsoft Office.md
> [手动选题][tech]: 20221104.1 ⭐️ How to Make LibreOffice Look Like Microsoft Office.md

- sources/tech/20221104.0 ⭐️ How to Enable ‘Dark Mode’ in LibreOffice.md
> [手动选题][tech]: 20221104.0 ⭐️ How to Enable ‘Dark Mode’ in LibreOffice.md

- published/20220524 12 essential Linux commands for beginners.md
@chai001125
https://linux.cn/article-15215-1.html
> RP:published/20220524 12 essential Linux commands for beginners.md

- published/20221020.0 ⭐️ How to Check：Xorg or Wayland Display Server.md
@geekpi
https://linux.cn/article-15216-1.html
> RP:published/20221020.0 ⭐️ How to Check：Xorg or Wayland Display Server.md

- published/20221030.2 ⭐️⭐️ Install WoeUSB on Ubuntu to Create a Bootable Windows USB.md
@robsean
https://linux.cn/article-15217-1.html
> RP:published/20221030.2 ⭐️⭐️ Install WoeUSB on Ubuntu to Create a Bootable Windows USB.md

- published/20221019.2 ⭐️  How to Clean Up Snap Versions to Free Up Disk Space.md
@geekpi
https://linux.cn/article-15219-1.html
> RP:published/20221019.2 ⭐️  How to Clean Up Snap Versions to Free Up Disk Space.md

- published/20221024.3 ⭐️ How to display commits created on a specific day with the git log command.md
@chai001125
https://linux.cn/article-15220-1.html
> RP:published/20221024.3 ⭐️ How to display commits created on a specific day with the git log command.md

- sources/tech/20221105.0 ⭐️⭐️ Fix scanned images with ImageMagick.md
> [手动选题][tech]: 20221105.0 ⭐️⭐️ Fix scanned images with ImageMagick.md

- sources/tech/20221106.0 ⭐️ Guide How to Share A Folder Between UbuntuLinux and Windows.md
> [手动选题][tech]: 20221106.0 ⭐️ Guide How to Share A Folder Between UbuntuLinux and Windows.md

- sources/tech/20221106.1 ⭐️ How to Install MATE Desktop in Arch Linux [Complete Guide].md
> [手动选题][tech]: 20221106.1 ⭐️ How to Install MATE Desktop in Arch Linux [Complete Guide].md

- sources/tech/20221105.1 ⭐️ How to Install Cinnamon Desktop in Arch Linux.md
> [手动选题][tech]: 20221105.1 ⭐️ How to Install Cinnamon Desktop in Arch Linux.md

- sources/tech/20221105.2 ⭐️ How to Install and Configure KDE Plasma Desktop in Arch Linux [Complete Guide].md
> [手动选题][tech]: 20221105.2 ⭐️ How to Install and Configure KDE Plasma Desktop in Arch Linux [Complete Guide].md

- sources/tech/20221105.3 ⭐️⭐️ How to Install GNOME Desktop in Arch Linux [Complete Guide].md
> [手动选题][tech]: 20221105.3 ⭐️⭐️ How to Install GNOME Desktop in Arch Linux [Complete Guide].md

- sources/tech/20221105.4 ⭐️⭐️ Crystal Linux Emerging Arch Linux Spin for GNOME Fans.md
> [手动选题][tech]: 20221105.4 ⭐️⭐️ Crystal Linux Emerging Arch Linux Spin for GNOME Fans.md

- published/20221024.1 ⭐️ How to Check CPU and HDD Temperature in Ubuntu and Other Linux.md
@geekpi
https://linux.cn/article-15223-1.html
> RP:published/20221024.1 ⭐️ How to Check CPU and HDD Temperature in Ubuntu and Other Linux.md

- published/20221027.0 ⭐️ How to Upgrade Python Packages with Pip.md
@chai001125
https://linux.cn/article-15224-1.html
> RP:published/20221027.0 ⭐️ How to Upgrade Python Packages with Pip.md

- sources/tech/20221107.5 ⭐️ How to Install OpenOffice in Arch Linux [Beginner’s Guide].md
> [手动选题][tech]: 20221107.5 ⭐️ How to Install OpenOffice in Arch Linux [Beginner’s Guide].md

- sources/tech/20221107.4 ⭐️ How to Boost Speaker Volume in Ubuntu and Other Linux.md
> [手动选题][tech]: 20221107.4 ⭐️ How to Boost Speaker Volume in Ubuntu and Other Linux.md

- sources/tech/20221107.3 ⭐️⭐️ How to Install Node.js on RHEL 9.md
> [手动选题][tech]: 20221107.3 ⭐️⭐️ How to Install Node.js on RHEL 9.md

- sources/tech/20221107.2 ⭐️⭐️⭐️ Build your own SaaS on Linux with Vely.md
> [手动选题][tech]: 20221107.2 ⭐️⭐️⭐️ Build your own SaaS on Linux with Vely.md

- sources/talk/20221107.1 ⭐️⭐️ What you actually need to know about open source to get started.md
> [手动选题][talk]: 20221107.1 ⭐️⭐️ What you actually need to know about open source to get started.md

- sources/tech/20221107.0 ⭐️⭐️ Ghostwriter An Excellent Open-Source Writing App.md
> [手动选题][tech]: 20221107.0 ⭐️⭐️ Ghostwriter An Excellent Open-Source Writing App.md

- sources/tech/20221108.5 ⭐️⭐️ Titan Linux A Blend of Debian Stable and KDE Plasma.md
> [手动选题][tech]: 20221108.5 ⭐️⭐️ Titan Linux A Blend of Debian Stable and KDE Plasma.md

- sources/tech/20221108.4 ⭐️⭐️ How to Delete Background in Image Using GIMP.md
> [手动选题][tech]: 20221108.4 ⭐️⭐️ How to Delete Background in Image Using GIMP.md

- sources/tech/20221108.3 ⭐️⭐️ How to Install Flatpak Apps in Ubuntu and Other Linux.md
> [手动选题][tech]: 20221108.3 ⭐️⭐️ How to Install Flatpak Apps in Ubuntu and Other Linux.md

- sources/talk/20221108.1 ⭐️⭐️ What stickers are on your laptop.md
> [手动选题][talk]: 20221108.1 ⭐️⭐️ What stickers are on your laptop.md

- sources/tech/20221108.0 ⭐️⭐️ Apt++ Nala is Like Apt in Ubuntu but Better.md
> [手动选题][tech]: 20221108.0 ⭐️⭐️ Apt++ Nala is Like Apt in Ubuntu but Better.md

- published/20220903 Infuse your awk scripts with Groovy.md
- translated/tech/20220903 Infuse your awk scripts with Groovy.md
@lxbwolf
https://linux.cn/article-15231-1.html
> RP:20220903 infuse your awk scripts with groovy

- sources/tech/20221109.7 ⭐️⭐️ Why sysadmins should choose Awesome window manager on Linux.md
> [手动选题][tech]: 20221109.7 ⭐️⭐️ Why sysadmins should choose Awesome window manager on Linux.md

- sources/tech/20221109.6 ⭐️ Using Python in VS Code and Codium.md
> [手动选题][tech]: 20221109.6 ⭐️ Using Python in VS Code and Codium.md

- sources/tech/20221109.5 ⭐️ How to Find Systemd or Any Other init System in Linux.md
> [手动选题][tech]: 20221109.5 ⭐️ How to Find Systemd or Any Other init System in Linux.md

- sources/tech/20221109.4 ⭐️⭐️ How to use journalctl to View and Analyze Systemd Logs [With Examples].md
> [手动选题][tech]: 20221109.4 ⭐️⭐️ How to use journalctl to View and Analyze Systemd Logs [With Examples].md

- sources/tech/20221109.3 ⭐️⭐️ A Guide to systemd journal Maintenance [With Examples].md
> [手动选题][tech]: 20221109.3 ⭐️⭐️ A Guide to systemd journal Maintenance [With Examples].md

- sources/news/20221109.2 ⭐️ Microsoft Teams Progressive Web App Experience is Here for Linux.md
> [手动选题][news]: 20221109.2 ⭐️ Microsoft Teams Progressive Web App Experience is Here for Linux.md

- sources/tech/20221109.1 ⭐️⭐️⭐️ 31 Linux Commands Every Ubuntu User Should Know.md
> [手动选题][tech]: 20221109.1 ⭐️⭐️⭐️ 31 Linux Commands Every Ubuntu User Should Know.md

- sources/tech/20221109.0 ⭐️⭐️ How To Install Netdata Performance Monitoring Tool In Linux.md
> [手动选题][tech]: 20221109.0 ⭐️⭐️ How To Install Netdata Performance Monitoring Tool In Linux.md

- published/20221025.0 ⭐️⭐️ Transfer files and folders from Windows to Linux with PSCP.md
@geekpi
https://linux.cn/article-15234-1.html
> RP:published/20221025.0 ⭐️⭐️ Transfer files and folders from Windows to Linux with PSCP.md

- published/20220519 For the Love of Ubuntu- Here are the Mascots of All Ubuntu Releases.md
- translated/tech/20220519 For the Love of Ubuntu- Here are the Mascots of All Ubuntu Releases.md
@chai001125
https://linux.cn/article-15240-1.html
> RP:20220519 for the love of ubuntu  here are the mascots of all ubuntu releases

- published/20221101.7 ⭐️ Move Virtual Machine Image to Another Host Using GNOME Boxes.md
@geekpi
https://linux.cn/article-15244-1.html
> RP:published/20221101.7 ⭐️ Move Virtual Machine Image to Another Host Using GNOME Boxes.md

- sources/tech/20221110.0 ⭐️ How to Fix sudo Command Not Found Error.md
> [手动选题][tech]: 20221110.0 ⭐️ How to Fix sudo Command Not Found Error.md

- sources/talk/20221112.0 ⭐️ Learn Python 7 of my favorite resources.md
> [手动选题][talk]: 20221112.0 ⭐️ Learn Python 7 of my favorite resources.md

- sources/tech/20221111.5 ⭐️⭐️ How to switch from Twitter to Mastodon.md
> [手动选题][tech]: 20221111.5 ⭐️⭐️ How to switch from Twitter to Mastodon.md

- sources/tech/20221111.4 ⭐️⭐️ Drop swap for zram on Linux.md
> [手动选题][tech]: 20221111.4 ⭐️⭐️ Drop swap for zram on Linux.md

- sources/talk/20221110.6 ⭐️⭐️ 4 key differences between Twitter and Mastodon.md
> [手动选题][talk]: 20221110.6 ⭐️⭐️ 4 key differences between Twitter and Mastodon.md

- sources/tech/20221110.5 ⭐️⭐️ Audit your sharding database algorithm.md
> [手动选题][tech]: 20221110.5 ⭐️⭐️ Audit your sharding database algorithm.md

- sources/news/20221111.3 ⭐️ Meet Tabby, A New Open-Source Cross-Platform Terminal App.md
> [手动选题][news]: 20221111.3 ⭐️ Meet Tabby, A New Open-Source Cross-Platform Terminal App.md

- sources/news/20221110.4 ⭐️ KDE Plasma 5.27 Bringing Subtle Outline on Windows.md
> [手动选题][news]: 20221110.4 ⭐️ KDE Plasma 5.27 Bringing Subtle Outline on Windows.md

- sources/tech/20221111.2 ⭐️⭐️ How to Install Elementary OS’s Pantheon Desktop in Arch Linux.md
> [手动选题][tech]: 20221111.2 ⭐️⭐️ How to Install Elementary OS’s Pantheon Desktop in Arch Linux.md

- sources/tech/20221111.1 ⭐️ How to Install FFmpeg in Ubuntu and Other Linux.md
> [手动选题][tech]: 20221111.1 ⭐️ How to Install FFmpeg in Ubuntu and Other Linux.md

- sources/tech/20221111.0 ⭐️ How to Install LibreOffice Base Database in Ubuntu and Other Linux.md
> [手动选题][tech]: 20221111.0 ⭐️ How to Install LibreOffice Base Database in Ubuntu and Other Linux.md

- sources/tech/20221110.3 ⭐️ How to Upgrade to Linux Mint 21 from Mint 20.3 [Complete Guide].md
> [手动选题][tech]: 20221110.3 ⭐️ How to Upgrade to Linux Mint 21 from Mint 20.3 [Complete Guide].md

- sources/tech/20221110.2 ⭐️ How to Install Enlightenment Desktop in Arch Linux [Complete Guide].md
> [手动选题][tech]: 20221110.2 ⭐️ How to Install Enlightenment Desktop in Arch Linux [Complete Guide].md

- sources/tech/20221110.1 ⭐️ How to Fix bash wget Command Not Found Error.md
> [手动选题][tech]: 20221110.1 ⭐️ How to Fix bash wget Command Not Found Error.md

- published/20221107.4 ⭐️ How to Boost Speaker Volume in Ubuntu and Other Linux.md
@geekpi
https://linux.cn/article-15250-1.html
> RP:published/20221107.4 ⭐️ How to Boost Speaker Volume in Ubuntu and Other Linux.md

- published/20221017.1 ⭐️ How to Update or Upgrade Ubuntu Offline without Internet.md
- translated/tech/20221017.1 ⭐️ How to Update or Upgrade Ubuntu Offline without Internet.md
@littlebirdnest
这几篇不够严谨。请参照我的校对。
翻译不但需要达意，而且需要尽量不丢失原文要素。望加油。
https://linux.cn/article-15253-1.html
> RP:20221017.1 ⭐️ how to update or upgrade ubuntu offline without internet

- published/20221109.6 ⭐️ Using Python in VS Code and Codium.md
@Cubik65536
https://linux.cn/article-15261-1.html
> RP:published/20221109.6 ⭐️ Using Python in VS Code and Codium.md

- published/20210607 Identify security properties on Linux using checksec.md
@chai001125
https://linux.cn/article-15264-1.html
> RP:published/20210607 Identify security properties on Linux using checksec.md

- published/20221021.3 ⭐️ How to Install AWS CLI on Linux Step-by-Step.md
- translated/tech/20221021.3 ⭐️ How to Install AWS CLI on Linux Step-by-Step.md
@littlebirdnest
首先非常感谢你愿意贡献的态度，但是我希望你能认真，而不是糊弄我。
这篇文章让你修改，我给你也留了言，但是你没有修改。
请参照我的校对来改进你的翻译质量。
https://linux.cn/article-15265-1.html
> RP:20221021.3 ⭐️ how to install aws cli on linux step by step

- published/20221105.0 ⭐️⭐️ Fix scanned images with ImageMagick.md
@geekpi
https://linux.cn/article-15268-1.html
> RP:published/20221105.0 ⭐️⭐️ Fix scanned images with ImageMagick.md

- published/20211020 Diagnose connectivity issues with the Linux ping command.md
@chai001125
https://linux.cn/article-15271-1.html
> RP:published/20211020 Diagnose connectivity issues with the Linux ping command.md

- published/20221110.0 ⭐️ How to Fix sudo Command Not Found Error.md
@geekpi
https://linux.cn/article-15280-1.html
> RP:published/20221110.0 ⭐️ How to Fix sudo Command Not Found Error.md

- published/20210108 The Definitive Guide to Using and Customizing the Dock in Ubuntu.md
@chai001125
https://linux.cn/article-15281-1.html
这篇翻译的很用心，就是 RUBY 标签和双引号的用法我做了一点调整。
> RP:published/20210108 The Definitive Guide to Using and Customizing the Dock in Ubuntu.md

- published/20221111.0 ⭐️ How to Install LibreOffice Base Database in Ubuntu and Other Linux.md
@geekpi
https://linux.cn/article-15283-1.html
> RP:published/20221111.0 ⭐️ How to Install LibreOffice Base Database in Ubuntu and Other Linux.md

- published/20220814 How to Record Audio in Linux With Audacity -and Reduce Noise-.md
@FYJNEVERFOLLOWS
https://linux.cn/article-15284-1.html
> RP:published/20220814 How to Record Audio in Linux With Audacity -and Reduce Noise-.md

- published/20221015.0 ⭐️ How to Enable and Access USB Drive in VirtualBox.md
@geekpi
https://linux.cn/article-15287-1.html
> RP:published/20221015.0 ⭐️ How to Enable and Access USB Drive in VirtualBox.md

- published/20221118 How to rebase to Fedora Linux 37 on Silverblue.md
@geekpi
https://linux.cn/article-15290-1.html
> RP:published/20221118 How to rebase to Fedora Linux 37 on Silverblue.md

- sources/tech/20221122.0 ⭐️ Find bugs with the git bisect command.md
> [手动选题][tech]: 20221122.0 ⭐️ Find bugs with the git bisect command.md

- sources/tech/20221123.0 ⭐️⭐️ apt remove vs apt purge What’s the Difference.md
> [手动选题][tech]: 20221123.0 ⭐️⭐️ apt remove vs apt purge What’s the Difference.md

- sources/tech/20221126.0 ⭐️⭐️ Pop OS Review Reasons why its an all-rounder Linux distro.md
> [手动选题][tech]: 20221126.0 ⭐️⭐️ Pop OS Review Reasons why its an all-rounder Linux distro.md

- sources/tech/20221121.0 ⭐️⭐️ How to Setup Python Development Environment in Ubuntu and Fedora.md
> [手动选题][tech]: 20221121.0 ⭐️⭐️ How to Setup Python Development Environment in Ubuntu and Fedora.md

- sources/tech/20221119.0 ⭐️⭐️ 7 Reasons Why Cinnamon is a Fantastic (Yet Underrated) Linux Desktop Environment.md
> [手动选题][tech]: 20221119.0 ⭐️⭐️ 7 Reasons Why Cinnamon is a Fantastic (Yet Underrated) Linux Desktop Environment.md

- sources/tech/20221117.0 ⭐️⭐️ How to Install and Use htop in Linux.md
> [手动选题][tech]: 20221117.0 ⭐️⭐️ How to Install and Use htop in Linux.md

- sources/tech/20221115.0 ⭐️ You Can Now Install Unity 7.6 Desktop on Arch Linux.md
> [手动选题][tech]: 20221115.0 ⭐️ You Can Now Install Unity 7.6 Desktop on Arch Linux.md

- published/20221111.2 ⭐️⭐️ How to Install Elementary OS’s Pantheon Desktop in Arch Linux.md
@geekpi
https://linux.cn/article-15293-1.html
> RP:published/20221111.2 ⭐️⭐️ How to Install Elementary OS’s Pantheon Desktop in Arch Linux.md

- sources/tech/20221126.1 ⭐️ How I Fixed Buzzing Noise Coming from Speakers in Linux.md
> [手动选题][tech]: 20221126.1 ⭐️ How I Fixed Buzzing Noise Coming from Speakers in Linux.md

- sources/tech/20221121.4 ⭐️⭐️ Using the Lesser Known File Tagging Feature in KDE’s Dolphin File Manager.md
> [手动选题][tech]: 20221121.4 ⭐️⭐️ Using the Lesser Known File Tagging Feature in KDE’s Dolphin File Manager.md

- sources/tech/20221123.1 ⭐️⭐️ Build an interactive timeline in React with this open source tool.md
> [手动选题][tech]: 20221123.1 ⭐️⭐️ Build an interactive timeline in React with this open source tool.md

- sources/tech/20221122.2 ⭐️⭐️⭐️ Introducing Rust calls to C library functions.md
> [手动选题][tech]: 20221122.2 ⭐️⭐️⭐️ Introducing Rust calls to C library functions.md

- published/20221101.1 ⭐️⭐️ Transfer files and folders from Windows to Linux with WinSCP.md
@robsean
https://linux.cn/article-15297-1.html
> RP:wxy:20221101.1-⭐️⭐️-Transfer-files-and-folders-from-Windows-to-Linux-with-WinSCP

- sources/tech/20221124.0 ⭐️ 5 NeoVim GUI Editors You Could Try If You are Not a Total Terminal Junkie.md
> [手动选题][tech]: 20221124.0 ⭐️ 5 NeoVim GUI Editors You Could Try If You are Not a Total Terminal Junkie.md

- sources/tech/20221126.2 ⭐️⭐️ Create a holiday light display with your Raspberry Pi and ping pong balls.md
> [手动选题][tech]: 20221126.2 ⭐️⭐️ Create a holiday light display with your Raspberry Pi and ping pong balls.md

- sources/tech/20221127.0 ⭐️ lnav Advanced Log File Viewer for Linux Desktops and Servers.md
> [手动选题][tech]: 20221127.0 ⭐️ lnav Advanced Log File Viewer for Linux Desktops and Servers.md

- sources/tech/20221124.1 ⭐️ How to Merge PDF Files in Linux.md
> [手动选题][tech]: 20221124.1 ⭐️ How to Merge PDF Files in Linux.md

- sources/news/20221125.1 ⭐️ Excellent News! Midori Browser to Integrate its Own Open Source Engine for a Strong Comeback.md
> [手动选题][news]: 20221125.1 ⭐️ Excellent News! Midori Browser to Integrate its Own Open Source Engine for a Strong Comeback.md

- sources/tech/20221125.2 ⭐️ Rnote An Open-Source Drawing App for Notes and Annotation.md
> [手动选题][tech]: 20221125.2 ⭐️ Rnote An Open-Source Drawing App for Notes and Annotation.md

- sources/tech/20221125.3 ⭐️⭐️ Leaving Twitter for Mastodon Here are the 7 Best Mastodon Instances You Can Join.md
> [手动选题][tech]: 20221125.3 ⭐️⭐️ Leaving Twitter for Mastodon Here are the 7 Best Mastodon Instances You Can Join.md

- sources/news/20221124.2 ⭐️ Alpine Linux 3.17 is out with OpenSSL 3.0 and new packages.md
> [手动选题][news]: 20221124.2 ⭐️ Alpine Linux 3.17 is out with OpenSSL 3.0 and new packages.md

- sources/tech/20221124.4 ⭐️⭐️⭐️ Write a C++ extension module for Python.md
> [手动选题][tech]: 20221124.4 ⭐️⭐️⭐️ Write a C++ extension module for Python.md

- published/20221122.1 ⭐️⭐️ macOS Alternative helloSystem (0.7.0) is moving towards stability.md
@Cubik65536
https://linux.cn/article-15300-1.html
> RP:published/20221122.1 ⭐️⭐️ macOS Alternative helloSystem (0.7.0) is moving towards stability.md

- sources/tech/20221128.1 ⭐️⭐️ 3 open source audio tools for creators.md
> [手动选题][tech]: 20221128.1 ⭐️⭐️ 3 open source audio tools for creators.md

- sources/news/20221128.2 ⭐️ Elon Musk's Twitter to Add Open-Source Signal Protocol for Encrypted DMs.md
> [手动选题][news]: 20221128.2 ⭐️ Elon Musk's Twitter to Add Open-Source Signal Protocol for Encrypted DMs.md

- published/20210805 Installing Packages From External Repositories in Ubuntu -Explained.md
@nophDog
https://linux.cn/article-15299-1.html
翻译的很好，很用心。
> RP:published/20210805 Installing Packages From External Repositories in Ubuntu -Explained.md

- published/20220916 How to Install Kubernetes Cluster on Debian 11 with Kubeadm.md
@lxbwolf
https://linux.cn/article-15302-1.html
> RP:published/20220916 How to Install Kubernetes Cluster on Debian 11 with Kubeadm.md

- published/20221105.1 ⭐️ How to Install Cinnamon Desktop in Arch Linux.md
@geekpi
https://linux.cn/article-15303-1.html
> RP:published/20221105.1 ⭐️ How to Install Cinnamon Desktop in Arch Linux.md

- sources/news/20221130.3 ⭐️⭐️ Wayland Protocols 1.31 Release Adds Fractional Scaling Support.md
> [手动选题][news]: 20221130.3 ⭐️⭐️ Wayland Protocols 1.31 Release Adds Fractional Scaling Support.md

- sources/tech/20221130.2 ⭐️⭐️⭐️ Build test scripts for your IoT platform.md
> [手动选题][tech]: 20221130.2 ⭐️⭐️⭐️ Build test scripts for your IoT platform.md

- sources/tech/20221130.1 ⭐️⭐️ Get to know Lua for loops in 4 minutes.md
> [手动选题][tech]: 20221130.1 ⭐️⭐️ Get to know Lua for loops in 4 minutes.md

- sources/tech/20221130.0 ⭐️⭐️ Terminator The Tiling Terminal Emulator for Linux Pros.md
> [手动选题][tech]: 20221130.0 ⭐️⭐️ Terminator The Tiling Terminal Emulator for Linux Pros.md

- sources/news/20221129.6 ⭐️ Heroic Games Launcher 2.5.0 Released as its Biggest Feature Update.md
> [手动选题][news]: 20221129.6 ⭐️ Heroic Games Launcher 2.5.0 Released as its Biggest Feature Update.md

- sources/tech/20221129.5 ⭐️⭐️ How to Set Up Pi-hole to Get an Ad-free Life.md
> [手动选题][tech]: 20221129.5 ⭐️⭐️ How to Set Up Pi-hole to Get an Ad-free Life.md

- sources/tech/20221129.3 ⭐️⭐️ Parse arguments with Lua.md
> [手动选题][tech]: 20221129.3 ⭐️⭐️ Parse arguments with Lua.md

- sources/news/20221129.1 ⭐️ Bodhi Linux 7.0.0 Testing Begins with New Features, Packages.md
> [手动选题][news]: 20221129.1 ⭐️ Bodhi Linux 7.0.0 Testing Begins with New Features, Packages.md

- sources/news/20221129.0 ⭐️ VLC 3.0.18 Release Brings RISC-V Support.md
> [手动选题][news]: 20221129.0 ⭐️ VLC 3.0.18 Release Brings RISC-V Support.md

- published/20221128.2 ⭐️ Elon Musk's Twitter to Add Open-Source Signal Protocol for Encrypted DMs.md
@chai001125
https://linux.cn/article-15306-1.html
> RP:published/20221128.2 ⭐️ Elon Musk's Twitter to Add Open-Source Signal Protocol for Encrypted DMs.md

- published/20221107.5 ⭐️ How to Install OpenOffice in Arch Linux [Beginner’s Guide].md
@geekpi
https://linux.cn/article-15308-1.html
> RP:published/20221107.5 ⭐️ How to Install OpenOffice in Arch Linux [Beginner’s Guide].md

- sources/tech/20221127.1 ⭐️ How to Automatically Indent Your Code in Visual Studio Code.md
> [手动选题][tech]: 20221127.1 ⭐️ How to Automatically Indent Your Code in Visual Studio Code.md

- published/20210922 Install PowerShell on Fedora Linux.md
- translated/tech/20210922 Install PowerShell on Fedora Linux.md
@cool-summer-021
https://linux.cn/article-15312-1.html
翻译的不错
> RP:20210922 install power shell on fedora linux

- published/20221117.1 ⭐️ Authenticator A Simple Open-Source App to Replace Authy on Linux.md
@geekpi
https://linux.cn/article-15313-1.html
> RP:published/20221117.1 ⭐️ Authenticator A Simple Open-Source App to Replace Authy on Linux.md

- sources/tech/20221201.1 ⭐️⭐️ 5 reasons I use the Dolphin file manager on Linux.md
> [手动选题][tech]: 20221201.1 ⭐️⭐️ 5 reasons I use the Dolphin file manager on Linux.md

- sources/news/20221201.2 ⭐️⭐️ Microsoft Office 365 Declared illegal for German Schools, Again!.md
> [手动选题][news]: 20221201.2 ⭐️⭐️ Microsoft Office 365 Declared illegal for German Schools, Again!.md

- sources/tech/20221201.3 ⭐️⭐️ Monica An Open-Source App for Personal Relationship Management.md
> [手动选题][tech]: 20221201.3 ⭐️⭐️ Monica An Open-Source App for Personal Relationship Management.md

- sources/talk/20221202.0 ⭐️⭐️ 8 ideas for measuring your open source software usage.md
> [手动选题][talk]: 20221202.0 ⭐️⭐️ 8 ideas for measuring your open source software usage.md

- sources/tech/20221202.1 ⭐️⭐️ Try this Java file manager on Linux.md
> [手动选题][tech]: 20221202.1 ⭐️⭐️ Try this Java file manager on Linux.md

- sources/news/20221202.2 ⭐️⭐️ Privacy-Preserving Ads Make a Debut on Brave Search.md
> [手动选题][news]: 20221202.2 ⭐️⭐️ Privacy-Preserving Ads Make a Debut on Brave Search.md

- sources/tech/20221201.4 ⭐️⭐️ Getting Nostalgic With the Historical Coherent Operating System.md
> [手动选题][tech]: 20221201.4 ⭐️⭐️ Getting Nostalgic With the Historical Coherent Operating System.md

- sources/tech/20221203.0 ⭐️⭐️ Feel like a Linux wizard with the Thunar file manager.md
> [手动选题][tech]: 20221203.0 ⭐️⭐️ Feel like a Linux wizard with the Thunar file manager.md

- published/20221115.0 ⭐️ You Can Now Install Unity 7.6 Desktop on Arch Linux.md
@geekpi
https://linux.cn/article-15316-1.html
> RP:published/20221115.0 ⭐️ You Can Now Install Unity 7.6 Desktop on Arch Linux.md

- sources/news/20221204.2 ⭐️⭐️ Trinity Desktop Environment R14.0.13 is now out with updates!.md
> [手动选题][news]: 20221204.2 ⭐️⭐️ Trinity Desktop Environment R14.0.13 is now out with updates!.md

- sources/news/20221204.1 ⭐️ 4MLinux 41.0 stable is now available with SDL games + More.md
> [手动选题][news]: 20221204.1 ⭐️ 4MLinux 41.0 stable is now available with SDL games + More.md

- sources/tech/20221204.0 ⭐️⭐️ Make your Linux computer feel faster with the Xfe file manager.md
> [手动选题][tech]: 20221204.0 ⭐️⭐️ Make your Linux computer feel faster with the Xfe file manager.md

- sources/tech/20221205.3 ⭐️⭐️ Why you should try the Nemo file manager on Linux.md
> [手动选题][tech]: 20221205.3 ⭐️⭐️ Why you should try the Nemo file manager on Linux.md

- sources/news/20221205.0 ⭐️⭐️ Linux Mint 21.1 beta is now available for testing.md
> [手动选题][news]: 20221205.0 ⭐️⭐️ Linux Mint 21.1 beta is now available for testing.md

- sources/news/20221205.1 ⭐️⭐️ Linen is a Google-Searchable Open-Source Alternative to Slack and Discord.md
> [手动选题][news]: 20221205.1 ⭐️⭐️ Linen is a Google-Searchable Open-Source Alternative to Slack and Discord.md

- published/20221129.3 ⭐️⭐️ Parse arguments with Lua.md
@geekpi
https://linux.cn/article-15321-1.html
> RP:published/20221129.3 ⭐️⭐️ Parse arguments with Lua.md

- sources/tech/20221205.4 ⭐️⭐️ True Lightweight Notepad for Ubuntu and Other Linux.md
> [手动选题][tech]: 20221205.4 ⭐️⭐️ True Lightweight Notepad for Ubuntu and Other Linux.md

- sources/tech/20221206.6 ⭐️⭐️ LibreOffice vs FreeOffice Comparing Popular Free Office Suites.md
> [手动选题][tech]: 20221206.6 ⭐️⭐️ LibreOffice vs FreeOffice Comparing Popular Free Office Suites.md

- sources/tech/20221206.5 ⭐️ How the Linux Worker file manager can work for you.md
> [手动选题][tech]: 20221206.5 ⭐️ How the Linux Worker file manager can work for you.md

- sources/tech/20221206.4 ⭐️⭐️⭐️ A 10-minute guide to the Linux ABI.md
> [手动选题][tech]: 20221206.4 ⭐️⭐️⭐️ A 10-minute guide to the Linux ABI.md

- sources/tech/20221206.3 ⭐️⭐️ A data scientist's guide to open source community analysis.md
> [手动选题][tech]: 20221206.3 ⭐️⭐️ A data scientist's guide to open source community analysis.md

- sources/talk/20221206.2 ⭐️⭐️ 'Don't be Afraid to Contribute' Mirko Brombin Talks about Vanilla OS and Other Future Projects.md
> [手动选题][talk]: 20221206.2 ⭐️⭐️ 'Don't be Afraid to Contribute' Mirko Brombin Talks about Vanilla OS and Other Future Projects.md

- sources/tech/20221206.0 ⭐️⭐️ Top 5 Live Streaming Applications for Ubuntu and Other Linux [2022 Edition].md
> [手动选题][tech]: 20221206.0 ⭐️⭐️ Top 5 Live Streaming Applications for Ubuntu and Other Linux [2022 Edition].md

- published/20221121.2 ⭐️⭐️ Learn Git 3 commands to level up your skill.md
- translated/tech/20221121.2 ⭐️⭐️ Learn Git 3 commands to level up your skill.md
@chai001125
翻译的很好，很用心！
https://linux.cn/article-15324-1.html
> RP:20221121.2 ⭐️⭐️ learn git 3 commands to level up your skill

- sources/news/20221207.5 ⭐️ Kali Linux's Last Update for the Year Brings a Lot of Early Christmas Gifts.md
> [手动选题][news]: 20221207.5 ⭐️ Kali Linux's Last Update for the Year Brings a Lot of Early Christmas Gifts.md

- sources/tech/20221207.4 ⭐️ Why I use the Enlightenment file manager on Linux.md
> [手动选题][tech]: 20221207.4 ⭐️ Why I use the Enlightenment file manager on Linux.md

- sources/tech/20221207.3 ⭐️⭐️ 16 reasons DDEV will be your new favorite development environment.md
> [手动选题][tech]: 20221207.3 ⭐️⭐️ 16 reasons DDEV will be your new favorite development environment.md

- sources/tech/20221207.2 ⭐️ How to Access UEFI Settings in Linux Systems.md
> [手动选题][tech]: 20221207.2 ⭐️ How to Access UEFI Settings in Linux Systems.md

- published/20221130.1 ⭐️⭐️ Get to know Lua for loops in 4 minutes.md
@geekpi
https://linux.cn/article-15328-1.html
> RP:published/20221130.1 ⭐️⭐️ Get to know Lua for loops in 4 minutes.md

- sources/news/20221208.5 ⭐️⭐️ Apple Silicon GPU Driver is Now Available in Asahi Linux.md
> [手动选题][news]: 20221208.5 ⭐️⭐️ Apple Silicon GPU Driver is Now Available in Asahi Linux.md

- sources/news/20221208.6 ⭐️⭐️ Mastodon's Adoption Gets a Boost With Vivaldi Browser Integration.md
> [手动选题][news]: 20221208.6 ⭐️⭐️ Mastodon's Adoption Gets a Boost With Vivaldi Browser Integration.md

- sources/tech/20221208.4 ⭐️⭐️ Manage your file system from the Linux terminal.md
> [手动选题][tech]: 20221208.4 ⭐️⭐️ Manage your file system from the Linux terminal.md

- sources/tech/20221208.3 ⭐️⭐️ Our favorite markup languages for documentation.md
> [手动选题][tech]: 20221208.3 ⭐️⭐️ Our favorite markup languages for documentation.md

- sources/tech/20221208.2 ⭐️⭐️ 7 pro tips for using the GDB step command.md
> [手动选题][tech]: 20221208.2 ⭐️⭐️ 7 pro tips for using the GDB step command.md

- sources/tech/20221208.1 ⭐️ Convert and Manipulate Images With ‘Converter’ GUI Tool in Linux.md
> [手动选题][tech]: 20221208.1 ⭐️ Convert and Manipulate Images With ‘Converter’ GUI Tool in Linux.md

- sources/news/20221209.2 ⭐️⭐️ Tea Raises $8.9M to Introduce a New Protocol Helping Open-Source Developers Get Paid.md
> [手动选题][news]: 20221209.2 ⭐️⭐️ Tea Raises $8.9M to Introduce a New Protocol Helping Open-Source Developers Get Paid.md

- sources/tech/20221209.1 ⭐️⭐️ A Linux file manager for Emacs fans.md
> [手动选题][tech]: 20221209.1 ⭐️⭐️ A Linux file manager for Emacs fans.md

- sources/tech/20221209.0 ⭐️⭐️ Install open source solar power at home.md
> [手动选题][tech]: 20221209.0 ⭐️⭐️ Install open source solar power at home.md

- sources/tech/20221208.7 ⭐️⭐️ Kumandar Linux Lightweight Debian & Xfce Spin with Windows 7 Look.md
> [手动选题][tech]: 20221208.7 ⭐️⭐️ Kumandar Linux Lightweight Debian & Xfce Spin with Windows 7 Look.md

- published/20200105 Friend of a Friend- The Facebook That Could Have Been.md
- translated/talk/20200105 Friend of a Friend- The Facebook That Could Have Been.md
@aREversez
辛苦了，这么长的文章翻译可不容易！
https://linux.cn/article-15334-1.html
> RP:20200105 friend of a friend  the facebook that could have been

- published/20221127.1 ⭐️ How to Automatically Indent Your Code in Visual Studio Code.md
@geekpi
https://linux.cn/article-15335-1.html
> RP:published/20221127.1 ⭐️ How to Automatically Indent Your Code in Visual Studio Code.md

- sources/tech/20221210.0 ⭐️ How to use the Linux file manager for GNOME 2.md
> [手动选题][tech]: 20221210.0 ⭐️ How to use the Linux file manager for GNOME 2.md

- sources/tech/20221210.2 ⭐️ How to Update Flatpak Packages in Linux.md
> [手动选题][tech]: 20221210.2 ⭐️ How to Update Flatpak Packages in Linux.md

- sources/tech/20221211.0 ⭐️ Simplify your Linux PC with the PCManFM file manager.md
> [手动选题][tech]: 20221211.0 ⭐️ Simplify your Linux PC with the PCManFM file manager.md

- published/20221207.0 ⭐️ How to Find a Process ID and Kill it in Linux [CLI & GUI].md
@yzuowei
https://linux.cn/article-15341-1.html
> RP:published/20221207.0 ⭐️ How to Find a Process ID and Kill it in Linux [CLI & GUI].md

- sources/news/20221212.3 ⭐️⭐️ Unfortunately, Komodo IDE is now Open Source!.md
> [手动选题][news]: 20221212.3 ⭐️⭐️ Unfortunately, Komodo IDE is now Open Source!.md

- sources/tech/20221212.2 ⭐️⭐️ A sysadmin's guide to Carbonio.md
> [手动选题][tech]: 20221212.2 ⭐️⭐️ A sysadmin's guide to Carbonio.md

- sources/tech/20221212.1 ⭐️⭐️ How to Install the Minimalist ArchBang Linux Distro.md
> [手动选题][tech]: 20221212.1 ⭐️⭐️ How to Install the Minimalist ArchBang Linux Distro.md

- sources/news/20221213.8 ⭐️ Kdenlive 22.12 Release Adds Useful New Features.md
> [手动选题][news]: 20221213.8 ⭐️ Kdenlive 22.12 Release Adds Useful New Features.md

- sources/news/20221213.7 ⭐️ Firefox 108 unlocks the power of music on the web with new WebMIDI API support.md
> [手动选题][news]: 20221213.7 ⭐️ Firefox 108 unlocks the power of music on the web with new WebMIDI API support.md

- sources/tech/20221213.6 ⭐️⭐️ Try this Linux web browser as your file manager.md
> [手动选题][tech]: 20221213.6 ⭐️⭐️ Try this Linux web browser as your file manager.md

- sources/tech/20221213.5 ⭐️⭐️ Drupal 10 is worth a fresh look.md
> [手动选题][tech]: 20221213.5 ⭐️⭐️ Drupal 10 is worth a fresh look.md

- sources/tech/20221213.4 ⭐️⭐️ Use Django to send emails with SMTP.md
> [手动选题][tech]: 20221213.4 ⭐️⭐️ Use Django to send emails with SMTP.md

- sources/tech/20221213.3 ⭐️ Linux Mint Upgrade Tool Usage Guide.md
> [手动选题][tech]: 20221213.3 ⭐️ Linux Mint Upgrade Tool Usage Guide.md

- sources/news/20221213.2 ⭐️ Get ready to upgrade your video creation with Kdenlive 22.12.md
> [手动选题][news]: 20221213.2 ⭐️ Get ready to upgrade your video creation with Kdenlive 22.12.md

- sources/tech/20221213.1 ⭐️⭐️⭐️ Battle of the Texts and the Unicode Savior.md
> [手动选题][tech]: 20221213.1 ⭐️⭐️⭐️ Battle of the Texts and the Unicode Savior.md

- sources/news/20221212.5 ⭐️ FreeBSD 12.4 is out with 100+ improvements and fixes.md
> [手动选题][news]: 20221212.5 ⭐️ FreeBSD 12.4 is out with 100+ improvements and fixes.md

- sources/tech/20221212.4 ⭐️⭐️ 5 Best Linux Phones to Watch Out for in 2023.md
> [手动选题][tech]: 20221212.4 ⭐️⭐️ 5 Best Linux Phones to Watch Out for in 2023.md

- sources/tech/20221214.2 ⭐️⭐️ Best Screen Recorders for Wayland in Linux [Compared & Tested].md
> [手动选题][tech]: 20221214.2 ⭐️⭐️ Best Screen Recorders for Wayland in Linux [Compared & Tested].md

- sources/news/20221214.1 ⭐️ Microsoft Soundscape to Go Open Source Marking the End of the Project.md
> [手动选题][news]: 20221214.1 ⭐️ Microsoft Soundscape to Go Open Source Marking the End of the Project.md

- sources/tech/20221214.0 ⭐️⭐️ Experience Linux desktop nostalgia with Rox.md
> [手动选题][tech]: 20221214.0 ⭐️⭐️ Experience Linux desktop nostalgia with Rox.md

- published/20221116.0 ⭐️⭐️ How to Install GNOME Desktop Environment in Linux Mint.md
@robsean
https://linux.cn/article-15350-1.html
> RP:published/20221116.0 ⭐️⭐️ How to Install GNOME Desktop Environment in Linux Mint.md

- sources/tech/20221215.3 ⭐️⭐️ Enjoy two-panel file management on Linux with far2l.md
> [手动选题][tech]: 20221215.3 ⭐️⭐️ Enjoy two-panel file management on Linux with far2l.md

- sources/tech/20221215.1 ⭐️⭐️ Why Drupal is the future of content strategy.md
> [手动选题][tech]: 20221215.1 ⭐️⭐️ Why Drupal is the future of content strategy.md

- sources/tech/20221215.0 ⭐️⭐️ How to Switch from Debian Stable to Testing.md
> [手动选题][tech]: 20221215.0 ⭐️⭐️ How to Switch from Debian Stable to Testing.md

- sources/news/20221216.3 ⭐️ Better Late Than Never! GNOME's File Picker Adds Thumbnail View After 18 Years.md
> [手动选题][news]: 20221216.3 ⭐️ Better Late Than Never! GNOME's File Picker Adds Thumbnail View After 18 Years.md

- sources/tech/20221216.2 ⭐️⭐️ 5 reasons to love Linux GNOME Files.md
> [手动选题][tech]: 20221216.2 ⭐️⭐️ 5 reasons to love Linux GNOME Files.md

- sources/tech/20221216.1 ⭐️ Harmonoid A Beautiful Cross-Platform Music Player With Essential Features.md
> [手动选题][tech]: 20221216.1 ⭐️ Harmonoid A Beautiful Cross-Platform Music Player With Essential Features.md

- sources/news/20221215.5 ⭐️ XFCE 4.18 Release Looks Impressive!.md
> [手动选题][news]: 20221215.5 ⭐️ XFCE 4.18 Release Looks Impressive!.md

- sources/tech/20221218.1 ⭐️ Try this Python-based file manager on Linux.md
> [手动选题][tech]: 20221218.1 ⭐️ Try this Python-based file manager on Linux.md

- sources/tech/20221218.0 ⭐️⭐️ Use my Groovy color wheel calculator.md
> [手动选题][tech]: 20221218.0 ⭐️⭐️ Use my Groovy color wheel calculator.md

- published/20221207.2 ⭐️ How to Access UEFI Settings in Linux Systems.md
- translated/tech/20221207.2 ⭐️ How to Access UEFI Settings in Linux Systems.md
@geekpi
https://linux.cn/article-15361-1.html
> RP:20221207.2 ⭐️ how to access uefi settings in linux systems

- published/20221208.2 ⭐️⭐️ 7 pro tips for using the GDB step command.md
- translated/tech/20221208.2 ⭐️⭐️ 7 pro tips for using the GDB step command.md
@chai001125
https://linux.cn/article-15362-1.html
> RP:20221208.2 ⭐️⭐️ 7 pro tips for using the gdb step command

- sources/tech/20221219.2 ⭐️⭐️ Discover the power of the Linux SpaceFM file manager.md
> [手动选题][tech]: 20221219.2 ⭐️⭐️ Discover the power of the Linux SpaceFM file manager.md

- sources/tech/20221219.1 ⭐️⭐️ How I use my old camera as a webcam with Linux.md
> [手动选题][tech]: 20221219.1 ⭐️⭐️ How I use my old camera as a webcam with Linux.md

- sources/tech/20221219.0 ⭐️⭐️ Use Rexx for scripting in 2023.md
> [手动选题][tech]: 20221219.0 ⭐️⭐️ Use Rexx for scripting in 2023.md

- translated/tech/20221215.2 ⭐️⭐️ Improve your documentation with JavaScript.md
* 12191625
* Update and rename sources/tech/20221215.2 ⭐️⭐️ Improve your documentation with JavaScript.md to translated/tech/20221215.2 ⭐️⭐️ Improve your documentation with JavaScript.md
> Translated 20221215.2 ⭐️⭐️ Improve your documentation with JavaScript.md

- published/20221208.1 ⭐️ Convert and Manipulate Images With ‘Converter’ GUI Tool in Linux.md
@geekpi
https://linux.cn/article-15368-1.html
> RP:published/20221208.1 ⭐️ Convert and Manipulate Images With ‘Converter’ GUI Tool in Linux.md

- published/20221212.4 ⭐️⭐️ 5 Best Linux Phones to Watch Out for in 2023.md
@chai001125
https://linux.cn/article-15371-1.html
> RP:published/20221212.4 ⭐️⭐️ 5 Best Linux Phones to Watch Out for in 2023.md

- published/20221213.3 ⭐️ Linux Mint Upgrade Tool Usage Guide.md
@geekpi
https://linux.cn/article-15372-1.html
> RP:published/20221213.3 ⭐️ Linux Mint Upgrade Tool Usage Guide.md

- sources/tech/20221222.2 ⭐️⭐️ 3 delightful features of the Linux QtFM file manager.md
> [手动选题][tech]: 20221222.2 ⭐️⭐️ 3 delightful features of the Linux QtFM file manager.md

- sources/news/20221222.1 ⭐️ Tails 5.8 Arrives with Official Wayland Support.md
> [手动选题][news]: 20221222.1 ⭐️ Tails 5.8 Arrives with Official Wayland Support.md

- sources/tech/20221222.0 ⭐️⭐️ 11 New Distros to look forward to in 2023.md
> [手动选题][tech]: 20221222.0 ⭐️⭐️ 11 New Distros to look forward to in 2023.md

- sources/tech/20221221.4 ⭐️⭐️ My 4 favorite features of the 4pane file manager on Linux.md
> [手动选题][tech]: 20221221.4 ⭐️⭐️ My 4 favorite features of the 4pane file manager on Linux.md

- sources/tech/20221221.3 ⭐️⭐️ Open source solutions for EV charging.md
> [手动选题][tech]: 20221221.3 ⭐️⭐️ Open source solutions for EV charging.md

- sources/tech/20221221.2 ⭐️⭐️ How to migrate your code from PHP 7.4 to 8.1.md
> [手动选题][tech]: 20221221.2 ⭐️⭐️ How to migrate your code from PHP 7.4 to 8.1.md

- sources/tech/20221221.1 ⭐️ Debugging LibreOffice Basic Macro using Breakpoint and Watch.md
> [手动选题][tech]: 20221221.1 ⭐️ Debugging LibreOffice Basic Macro using Breakpoint and Watch.md

- sources/tech/20221220.6 ⭐️ How to Update Pi-hole Easily.md
> [手动选题][tech]: 20221220.6 ⭐️ How to Update Pi-hole Easily.md

- sources/tech/20221221.0 ⭐️⭐️ EndeavourOS Your Search for Perfect Arch Distro Ends Here.md
> [手动选题][tech]: 20221221.0 ⭐️⭐️ EndeavourOS Your Search for Perfect Arch Distro Ends Here.md

- sources/news/20221220.5 ⭐️⭐️ Linux Mint 21.1 Arrives with a Ton of Visual Changes and Improvements.md
> [手动选题][news]: 20221220.5 ⭐️⭐️ Linux Mint 21.1 Arrives with a Ton of Visual Changes and Improvements.md
