LCTT/TranslateProject

sources/news/20221220.4 ⭐️ EndeavourOS 'Cassini' Releases With New Features and Linux Kernel 6.0.md
=> [手动选题][news]: 20221220.4 ⭐️ EndeavourOS 'Cassini' Releases With New Features and Linux Kernel 6.0.md

sources/tech/20221220.3 ⭐️⭐️ Explore the features of the Linux Double Commander file manager.md
=> [手动选题][tech]: 20221220.3 ⭐️⭐️ Explore the features of the Linux Double Commander file manager.md

sources/tech/20221220.2 ⭐️⭐️ How I use Artipie, a PyPI repo.md
=> [手动选题][tech]: 20221220.2 ⭐️⭐️ How I use Artipie, a PyPI repo.md

sources/tech/20221220.1 ⭐️ How to Downgrade Flatpak Packages in Linux.md
=> [手动选题][tech]: 20221220.1 ⭐️ How to Downgrade Flatpak Packages in Linux.md

sources/tech/20221220.0 ⭐️⭐️ Writing a Macro in LibreOffice Calc Getting Started.md
=> [手动选题][tech]: 20221220.0 ⭐️⭐️ Writing a Macro in LibreOffice Calc Getting Started.md

sources/tech/20221219.3 ⭐️⭐️ Fedora Media Writer World-Class LIVE USB Creator [Tutorial].md
=> [手动选题][tech]: 20221219.3 ⭐️⭐️ Fedora Media Writer World-Class LIVE USB Creator [Tutorial].md

published/20221215.2 ⭐️⭐️ Improve your documentation with JavaScript.md
@duoluoxiaosheng
https://linux.cn/article-15375-1.html
=> RP:published/20221215.2 ⭐️⭐️ Improve your documentation with JavaScript.md

published/20221211.0 ⭐️ Simplify your Linux PC with the PCManFM file manager.md
@geekpi
https://linux.cn/article-15378-1.html
=> RP:published/20221211.0 ⭐️ Simplify your Linux PC with the PCManFM file manager.md

sources/tech/20221221.3 ⭐️⭐️ Open source solutions for EV charging.md
申请 20221221.3 ⭐️⭐️ Open source solutions for EV charging
=> [翻译申请]20221221.3 ⭐️⭐️ Open source solutions for EV charging

published/20221216.1 ⭐️ Harmonoid A Beautiful Cross-Platform Music Player With Essential Features.md
@geekpi
https://linux.cn/article-15386-1.html
=> RP:published/20221216.1 ⭐️ Harmonoid A Beautiful Cross-Platform Music Player With Essential Features.md

sources/news/20221226.1 ⭐️ Manjaro Linux 22.0 Releases Featuring Xfce 4.18 and Linux Kernel 6.1.md
=> [手动选题][news]: 20221226.1 ⭐️ Manjaro Linux 22.0 Releases Featuring Xfce 4.18 and Linux Kernel 6.1.md

sources/tech/20221227.0 ⭐️⭐️ 5 Upcoming Code Editors that May Challenge the Supremacy of Visual Studio Code.md
=> [手动选题][tech]: 20221227.0 ⭐️⭐️ 5 Upcoming Code Editors that May Challenge the Supremacy of Visual Studio Code.md

sources/tech/20221227.1 ⭐️⭐️ oh my zsh and powerlevel10k A Match Made in Heaven.md
=> [手动选题][tech]: 20221227.1 ⭐️⭐️ oh my zsh and powerlevel10k A Match Made in Heaven.md

sources/news/20221229.0 ⭐️ Be Delighted! Unity Teases Version 7.7 as the Sign of Active Development.md
=> [手动选题][news]: 20221229.0 ⭐️ Be Delighted! Unity Teases Version 7.7 as the Sign of Active Development.md

sources/tech/20221228.1 ⭐️⭐️ 11 tips for writing a good Git commit message.md
=> [手动选题][tech]: 20221228.1 ⭐️⭐️ 11 tips for writing a good Git commit message.md

published/20220729 Learn Rust by debugging Rust.md
@yzuowei
https://linux.cn/article-15395-1.html
=> RP:published/20220729 Learn Rust by debugging Rust.md

published/20221218.1 ⭐️ Try this Python-based file manager on Linux.md
@geekpi
https://linux.cn/article-15396-1.html
=> RP:published/20221218.1 ⭐️ Try this Python-based file manager on Linux.md

sources/tech/20221230.0 ⭐️ An Open-Source Alternative to Google, Alexa, and Siri in Works for Home Assistant Platform.md
=> [手动选题][tech]: 20221230.0 ⭐️ An Open-Source Alternative to Google, Alexa, and Siri in Works for Home Assistant Platform.md

published/20221220.1 ⭐️ How to Downgrade Flatpak Packages in Linux.md
@geekpi
https://linux.cn/article-15402-1.html
=> RP:published/20221220.1 ⭐️ How to Downgrade Flatpak Packages in Linux.md

published/20221124.4 ⭐️⭐️⭐️ Write a C++ extension module for Python.md
@MjSeven
https://linux.cn/article-15405-1.html
=> RP:published/20221124.4 ⭐️⭐️⭐️ Write a C++ extension module for Python.md

published/20221210.2 ⭐️ How to Update Flatpak Packages in Linux.md
@geekpi
https://linux.cn/article-15408-1.html
=> RP:published/20221210.2 ⭐️ How to Update Flatpak Packages in Linux.md

sources/tech/20230102.0 ⭐️ How to read and write files in Rust.md
=> [手动选题][tech]: 20230102.0 ⭐️ How to read and write files in Rust.md

sources/news/20230103.0 ⭐️⭐️ Ultramarine Linux 37 Release Adds Pop OS-Style KDE Plasma, Drops Cutefish.md
=> [手动选题][news]: 20230103.0 ⭐️⭐️ Ultramarine Linux 37 Release Adds Pop OS-Style KDE Plasma, Drops Cutefish.md

sources/tech/20230103.1 ⭐️⭐️ Document with BookStack, an open source Confluence alternative.md
=> [手动选题][tech]: 20230103.1 ⭐️⭐️ Document with BookStack, an open source Confluence alternative.md

sources/tech/20230103.3 ⭐️ Whereis Command in Linux and BSD with Examples.md
=> [手动选题][tech]: 20230103.3 ⭐️ Whereis Command in Linux and BSD with Examples.md

sources/tech/20230102.1 ⭐️ who Command in Linux Explanation with Examples.md
=> [手动选题][tech]: 20230102.1 ⭐️ who Command in Linux Explanation with Examples.md

sources/tech/20230102.2 ⭐️ Colorblind Filters GNOME Extension to help Colorblind Users.md
=> [手动选题][tech]: 20230102.2 ⭐️ Colorblind Filters GNOME Extension to help Colorblind Users.md

sources/news/20230104.1 ⭐️ Official Fedora Budgie & Sway Spins to Arrive With Fedora 38 Release.md
=> [手动选题][news]: 20230104.1 ⭐️ Official Fedora Budgie & Sway Spins to Arrive With Fedora 38 Release.md

published/20221126.1 ⭐️ How I Fixed Buzzing Noise Coming from Speakers in Linux.md
@geekpi
https://linux.cn/article-15415-1.html
=> RP:published/20221126.1 ⭐️ How I Fixed Buzzing Noise Coming from Speakers in Linux.md

sources/news/20230105.3 ⭐️ Pinta 2.1 Release Introduces WebP Support. But You Can't Use It Yet Unfortunately.md
=> [手动选题][news]: 20230105.3 ⭐️ Pinta 2.1 Release Introduces WebP Support. But You Can't Use It Yet Unfortunately.md

published/20221201.5 ⭐️⭐️ What is Firefox ESR How to Install it in Ubuntu.md
@geekpi
https://linux.cn/article-15421-1.html
=> RP:published/20221201.5 ⭐️⭐️ What is Firefox ESR How to Install it in Ubuntu.md

sources/news/20230106.2 ⭐️ Budgie's Upcoming 10.7 Release Promises These 3 Key Improvements for Linux Users.md
=> [手动选题][news]: 20230106.2 ⭐️ Budgie's Upcoming 10.7 Release Promises These 3 Key Improvements for Linux Users.md

sources/tech/20230106.0 ⭐️⭐️ Use time-series data to power your edge projects with open source tools.md
=> [手动选题][tech]: 20230106.0 ⭐️⭐️ Use time-series data to power your edge projects with open source tools.md

sources/tech/20230107.0 ⭐️ Learn w Command in Linux & BSD with Examples.md
=> [手动选题][tech]: 20230107.0 ⭐️ Learn w Command in Linux & BSD with Examples.md

published/20221230.0 ⭐️ An Open-Source Alternative to Google, Alexa, and Siri in Works for Home Assistant Platform.md
@geekpi
https://linux.cn/article-15426-1.html
=> RP:published/20221230.0 ⭐️ An Open-Source Alternative to Google, Alexa, and Siri in Works for Home Assistant Platform.md

sources/tech/20230109.0 ⭐️⭐️ Learn the Ada programming language by writing a simple game.md
=> [手动选题][tech]: 20230109.0 ⭐️⭐️ Learn the Ada programming language by writing a simple game.md

sources/tech/20230109.1 ⭐️⭐️ Use this open source API gateway to scale your API.md
=> [手动选题][tech]: 20230109.1 ⭐️⭐️ Use this open source API gateway to scale your API.md

sources/news/20230109.3 ⭐️ OBS Studio 29 Release Has Little in Store For Linux.md
=> [手动选题][news]: 20230109.3 ⭐️ OBS Studio 29 Release Has Little in Store For Linux.md

sources/tech/20230110.0 ⭐️⭐️ A guide to strings in MySQL.md
=> [手动选题][tech]: 20230110.0 ⭐️⭐️ A guide to strings in MySQL.md

sources/news/20230110.2 ⭐️ Wow! CoolerMaster's MasterPlus Software to Go Open Source!.md
=> [手动选题][news]: 20230110.2 ⭐️ Wow! CoolerMaster's MasterPlus Software to Go Open Source!.md

published/20230110.0 ⭐️⭐️ A guide to strings in MySQL.md
@wxy
https://linux.cn/article-15434-1.html
=> P:published/20230110.0 ⭐️⭐️ A guide to strings in MySQL.md

published/20230107.0 ⭐️ Learn w Command in Linux & BSD with Examples.md
@geekpi
https://linux.cn/article-15437-1.html
=> RP:published/20230107.0 ⭐️ Learn w Command in Linux & BSD with Examples.md

sources/news/20230111.0 ⭐️⭐️ Linux is All Set to Disable Microsoft's RNDIS Drivers.md
=> [手动选题][news]: 20230111.0 ⭐️⭐️ Linux is All Set to Disable Microsoft's RNDIS Drivers.md

sources/tech/20230110.3 ⭐️⭐️ How to use methods in Java.md
=> [手动选题][tech]: 20230110.3 ⭐️⭐️ How to use methods in Java.md

published/20230109.0 ⭐️⭐️ Learn the Ada programming language by writing a simple game.md
@geekpi
https://linux.cn/article-15440-1.html
=> RP:published/20230109.0 ⭐️⭐️ Learn the Ada programming language by writing a simple game.md

sources/tech/20230113.2 ⭐️ Share Folder Between Guest and Host in virt-manager (KVMQemulibvirt).md
=> [手动选题][tech]: 20230113.2 ⭐️ Share Folder Between Guest and Host in virt-manager (KVMQemulibvirt).md

sources/news/20230113.1 ⭐️⭐️ Mastodon's Growth Continues, Medium Joins in With its New Community Platform.md
=> [手动选题][news]: 20230113.1 ⭐️⭐️ Mastodon's Growth Continues, Medium Joins in With its New Community Platform.md

sources/tech/20230113.0 ⭐️ How to Install Python on Windows [Beginner’s Guide].md
=> [手动选题][tech]: 20230113.0 ⭐️ How to Install Python on Windows [Beginner’s Guide].md

published/20230102.0 ⭐️ How to read and write files in Rust.md
@geekpi
https://linux.cn/article-15442-1.html
=> RP:published/20230102.0 ⭐️ How to read and write files in Rust.md

sources/news/20230112.2 ⭐️⭐️ Discourse 3.0 is an Amazing Release With Much-Needed Feature Additions.md
=> [手动选题][news]: 20230112.2 ⭐️⭐️ Discourse 3.0 is an Amazing Release With Much-Needed Feature Additions.md

sources/news/20230112.1 ⭐️ Ubuntu 23.04 Lunar Lobster Wallpaper Competition is Now Open.md
=> [手动选题][news]: 20230112.1 ⭐️ Ubuntu 23.04 Lunar Lobster Wallpaper Competition is Now Open.md

sources/tech/20230111.1 ⭐️ Wordbook Offline English Dictionary App for GNOME.md
=> [手动选题][tech]: 20230111.1 ⭐️ Wordbook Offline English Dictionary App for GNOME.md

sources/tech/20230114.0 ⭐️ A 4-minute guide to Java loops.md
=> [手动选题][tech]: 20230114.0 ⭐️ A 4-minute guide to Java loops.md

published/20230103.3 ⭐️ Whereis Command in Linux and BSD with Examples.md
@geekpi
https://linux.cn/article-15446-1.html
=> RP:published/20230103.3 ⭐️ Whereis Command in Linux and BSD with Examples.md

published/20221123.0 ⭐️⭐️ apt remove vs apt purge What’s the Difference.md, translated/tech/20221123.0 ⭐️⭐️ apt remove vs apt purge What’s the Difference.md
@Tingze-G
本文首发地址：https://linux.cn/article-15458-1.html
您的 LCTT 专页：https://linux.cn/lctt/Tingze-G
请注意一下排版，也不能丢失文内链接，可以参照我的校对。
=> RP:20221123.0 ⭐️⭐️ apt remove vs apt purge what’s the difference

published/20230102.2 ⭐️ Colorblind Filters GNOME Extension to help Colorblind Users.md
@geekpi
https://linux.cn/article-15464-1.html
=> RP:published/20230102.2 ⭐️ Colorblind Filters GNOME Extension to help Colorblind Users.md

published/20230111.1 ⭐️ Wordbook Offline English Dictionary App for GNOME.md
@geekpi
https://linux.cn/article-15466-1.html
=> RP:published/20230111.1 ⭐️ Wordbook Offline English Dictionary App for GNOME.md

published/20230113.2 ⭐️ Share Folder Between Guest and Host in virt-manager (KVMQemulibvirt).md
@geekpi
https://linux.cn/article-15470-1.html
=> RP:published/20230113.2 ⭐️ Share Folder Between Guest and Host in virt-manager (KVMQemulibvirt).md

published/20230113.0 ⭐️ How to Install Python on Windows [Beginner’s Guide].md
@geekpi
https://linux.cn/article-15480-1.html
=> RP:published/20230113.0 ⭐️ How to Install Python on Windows [Beginner’s Guide].md

sources/tech/20230118.2 ⭐️⭐️ Beyond Bash 9 Lesser-Known Linux Shells and Their Capabilities.md
=> [手动选题][tech]: 20230118.2 ⭐️⭐️ Beyond Bash 9 Lesser-Known Linux Shells and Their Capabilities.md

sources/tech/20230115.0 ⭐️ Share Folder Between Guest and Host in GNOME Boxes.md
=> [手动选题][tech]: 20230115.0 ⭐️ Share Folder Between Guest and Host in GNOME Boxes.md

sources/tech/20230116.0 ⭐️ Meet ecode An Upcoming Modern, Lightweight Code Editor With a Brand New GUI Framework.md
=> [手动选题][tech]: 20230116.0 ⭐️ Meet ecode An Upcoming Modern, Lightweight Code Editor With a Brand New GUI Framework.md

sources/tech/20230117.0 ⭐️⭐️ Learn zip Command in Linux Using Examples.md
=> [手动选题][tech]: 20230117.0 ⭐️⭐️ Learn zip Command in Linux Using Examples.md

sources/tech/20230117.1 ⭐️⭐️ Top 10 Linux Distributions for Servers in 2023.md
=> [手动选题][tech]: 20230117.1 ⭐️⭐️ Top 10 Linux Distributions for Servers in 2023.md

sources/talk/20230117.2 ⭐️⭐️ Making Content that Resonates An Interview with 'The Linux Cast' Creator, Matthew Weber.md
=> [手动选题][talk]: 20230117.2 ⭐️⭐️ Making Content that Resonates An Interview with 'The Linux Cast' Creator, Matthew Weber.md

sources/news/20230119.0 ⭐️ Over 90% Systems Had Flatpak Installed, Says GNOME's Research Report.md
=> [手动选题][news]: 20230119.0 ⭐️ Over 90% Systems Had Flatpak Installed, Says GNOME's Research Report.md

sources/tech/20230119.1 ⭐️ GNOME Screenshot Tool Old and New Methods.md
=> [手动选题][tech]: 20230119.1 ⭐️ GNOME Screenshot Tool Old and New Methods.md

sources/tech/20230117.1 ⭐️⭐️ Top 10 Linux Distributions for Servers in 2023.md
=> Update 20230117.1 ⭐️⭐️ Top 10 Linux Distributions for Servers in 2023.md

published/20230117.3 ⭐️ A ChatGPT GNOME Extension is in Development for Linux Users.md
@chai001125
https://linux.cn/article-15498-1.html
=> RP:published/20230117.3 ⭐️ A ChatGPT GNOME Extension is in Development for Linux Users.md

published/20230116.1 ⭐️ Kodi 20.0 Nexus Update Includes Support for AV1 Video and Steam Deck Controller.md, translated/news/20230116.1 ⭐️ Kodi 20.0 Nexus Update Includes Support for AV1 Video and Steam Deck Controller.md
@natsumm
本文首发地址：https://linux.cn/article-15501-1.html
您的 LCTT 专页：https://linux.cn/lctt/natsumm
文章也会同步发布的公众号、知乎的同名官方账号下。
=> RP:20230116.1 ⭐️ kodi 20.0 nexus update includes support for av1 video and steam deck controller

sources/news/20230202.0 ⭐️ LibreOffice 7.5 Unveils Stunning New App Icons and Cool Features.md
=> [手动选题][news]: 20230202.0 ⭐️ LibreOffice 7.5 Unveils Stunning New App Icons and Cool Features.md

sources/tech/20230202.1 ⭐️ Learn Basic by coding a game.md
=> [手动选题][tech]: 20230202.1 ⭐️ Learn Basic by coding a game.md

sources/news/20230201.0 ⭐️⭐️ System76's Upcoming COSMIC Desktop is Gearing Up With Big Changes.md
=> [手动选题][news]: 20230201.0 ⭐️⭐️ System76's Upcoming COSMIC Desktop is Gearing Up With Big Changes.md

sources/tech/20230201.1 ⭐️⭐️⭐️ A guide to fuzzy queries with Apache ShardingSphere.md
=> [手动选题][tech]: 20230201.1 ⭐️⭐️⭐️ A guide to fuzzy queries with Apache ShardingSphere.md

sources/news/20230131.0 ⭐️⭐️ elementary OS 7 is a Modest Upgrade With Useful Changes.md
=> [手动选题][news]: 20230131.0 ⭐️⭐️ elementary OS 7 is a Modest Upgrade With Useful Changes.md

published/20220906 How to Analyse Sentiments Using Machine Learning.md
@chai001125
https://linux.cn/article-15504-1.html
恭喜！升级为⭐️⭐️⭐️⭐️贡献者！
=> RP:published/20220906 How to Analyse Sentiments Using Machine Learning.md

published/20220616 9 Best Matrix Clients for Decentralized Messaging.md
@TravinDreek
https://linux.cn/article-15515-1.html
=> RP:published/20220616 9 Best Matrix Clients for Decentralized Messaging.md

sources/tech/20230203.0 ⭐️⭐️ 7 Best Gentoo-Based Linux Distributions.md
=> [手动选题][tech]: 20230203.0 ⭐️⭐️ 7 Best Gentoo-Based Linux Distributions.md

sources/news/20230203.1 ⭐️⭐️ Escuelas Linux 8.0 A Major Upgrade for the 25th Anniversary.md
=> [手动选题][news]: 20230203.1 ⭐️⭐️ Escuelas Linux 8.0 A Major Upgrade for the 25th Anniversary.md

sources/tech/20230204.0 ⭐️ Open source video captioning on Linux.md
=> [手动选题][tech]: 20230204.0 ⭐️ Open source video captioning on Linux.md

sources/tech/20230206.0 ⭐️ Elementary OS 7 Installation Guide with Screenshots.md
=> [手动选题][tech]: 20230206.0 ⭐️ Elementary OS 7 Installation Guide with Screenshots.md

sources/tech/20230206.1 ⭐️⭐️ Wordsmith on the Linux command line with dict.md
=> [手动选题][tech]: 20230206.1 ⭐️⭐️ Wordsmith on the Linux command line with dict.md

sources/news/20230206.3 ⭐️⭐️ Mozilla's Abandoned Servo Web Engine is Making a Comeback in 2023.md
=> [手动选题][news]: 20230206.3 ⭐️⭐️ Mozilla's Abandoned Servo Web Engine is Making a Comeback in 2023.md

sources/tech/20230131.1 ⭐️⭐️ Use Terraform to manage an OpenStack cluster.md
=> [手动选题][tech]: 20230131.1 ⭐️⭐️ Use Terraform to manage an OpenStack cluster.md

sources/tech/20230131.2 ⭐️⭐️ Merge design and code with Penpot.md
=> [手动选题][tech]: 20230131.2 ⭐️⭐️ Merge design and code with Penpot.md

sources/tech/20230131.3 ⭐️⭐️ 5 Linux Distros for Visually Impaired People.md
=> [手动选题][tech]: 20230131.3 ⭐️⭐️ 5 Linux Distros for Visually Impaired People.md

published/20221215.0 ⭐️⭐️ How to Switch from Debian Stable to Testing.md
@geekpi
https://linux.cn/article-15520-1.html
=> RP:published/20221215.0 ⭐️⭐️ How to Switch from Debian Stable to Testing.md

published/20221109.3 ⭐️⭐️ A Guide to systemd journal Maintenance [With Examples].md
@Chao-zhi
https://linux.cn/article-15526-1.html
=> RP:published/20221109.3 ⭐️⭐️ A Guide to systemd journal Maintenance [With Examples].md

sources/tech/20210922 My favorite LibreOffice productivity tips.md, translated/tech/20210922 My favorite LibreOffice productivity tips.md
XiaotingHuang22 translating...
=> Update 20210922 My favorite LibreOffice productivity tips.md

sources/talk/20230210.1 ⭐️⭐️ What an open license means to gamers.md
=> [手动选题][talk]: 20230210.1 ⭐️⭐️ What an open license means to gamers.md

sources/news/20230210.0 ⭐️ Opera Browser Plans to Integrate ChatGPT.md
=> [手动选题][news]: 20230210.0 ⭐️ Opera Browser Plans to Integrate ChatGPT.md

published/20230202.1 ⭐️ Learn Basic by coding a game.md
@geekpi
https://linux.cn/article-15529-1.html
=> RP:published/20230202.1 ⭐️ Learn Basic by coding a game.md

published/20210922 My favorite LibreOffice productivity tips.md, translated/tech/20210922 My favorite LibreOffice productivity tips.md
@XiaotingHuang22
本文首发地址：https://linux.cn/article-15530-1.html
您的 LCTT 专页：https://linux.cn/lctt/XiaotingHuang22
=> RP:20210922 my favorite libre office productivity tips

sources/talk/20230207.3 ⭐️ How the Gherkin language bridges the gap between customers and developers.md
=> [手动选题][talk]: 20230207.3 ⭐️ How the Gherkin language bridges the gap between customers and developers.md

sources/news/20230207.2 ⭐️ Lightweight Distro LegacyOS 2023 Released After Nine Years.md
=> [手动选题][news]: 20230207.2 ⭐️ Lightweight Distro LegacyOS 2023 Released After Nine Years.md

sources/talk/20230207.1 ⭐️⭐️ A brief history of LibreOffice.md
=> [手动选题][talk]: 20230207.1 ⭐️⭐️ A brief history of LibreOffice.md

sources/tech/20230208.1 ⭐️⭐️ Improve your coding skills with temporal values in MySQL.md
=> [手动选题][tech]: 20230208.1 ⭐️⭐️ Improve your coding skills with temporal values in MySQL.md

sources/news/20230208.0 ⭐️ Transmission 4.0 Upgrade is Here After Two Years.md
=> [手动选题][news]: 20230208.0 ⭐️ Transmission 4.0 Upgrade is Here After Two Years.md

sources/tech/20230209.5 ⭐️⭐️ Endless OS 5.0 Review The Best of GNOME with Wayland and Apps.md
=> [手动选题][tech]: 20230209.5 ⭐️⭐️ Endless OS 5.0 Review The Best of GNOME with Wayland and Apps.md

sources/tech/20230209.4 ⭐️ Start developing for WebAssembly with our new guide.md
=> [手动选题][tech]: 20230209.4 ⭐️ Start developing for WebAssembly with our new guide.md

sources/tech/20230209.3 ⭐️⭐️ Learn Tcl by writing a simple game.md
=> [手动选题][tech]: 20230209.3 ⭐️⭐️ Learn Tcl by writing a simple game.md

sources/talk/20230209.2 ⭐️⭐️ 3 types of leadership for open organizations.md
=> [手动选题][talk]: 20230209.2 ⭐️⭐️ 3 types of leadership for open organizations.md

sources/news/20230209.1 ⭐️ GNOME is (kind of) Bringing Back a Feature It Had Removed a Few Years Ago.md
=> [手动选题][news]: 20230209.1 ⭐️ GNOME is (kind of) Bringing Back a Feature It Had Removed a Few Years Ago.md

sources/news/20230209.0 ⭐️ Linux Kernel 6.1 is Now Approved as an LTS Version.md
=> [手动选题][news]: 20230209.0 ⭐️ Linux Kernel 6.1 is Now Approved as an LTS Version.md

sources/tech/20230210.4 ⭐️ How to Install DOSBox in Ubuntu to Play Old Games.md
=> [手动选题][tech]: 20230210.4 ⭐️ How to Install DOSBox in Ubuntu to Play Old Games.md

sources/news/20230210.3 ⭐️ Verified Flatpak Apps are Coming Soon.md
=> [手动选题][news]: 20230210.3 ⭐️ Verified Flatpak Apps are Coming Soon.md

sources/talk/20230210.2 ⭐️⭐️ How open source leaders can foster an inclusive environment.md
=> [手动选题][talk]: 20230210.2 ⭐️⭐️ How open source leaders can foster an inclusive environment.md

sources/tech/20230210.4 ⭐️ How to Install DOSBox in Ubuntu to Play Old Games.md
sources/tech/20230210.4 ⭐️ How to Install DOSBox in Ubuntu to Play Old Games.md
=> gpchn translating

sources/tech/20220922 How to Install and Use GNOME Boxes to Create Virtual Machines.md
tech_How to Install and Use GNOME Boxes to Create Virtual Machines
=> tech_How to Install and Use GNOME Boxes to Create Virtual Machines

sources/talk/20220616 -It-s time to contribute to open source-.md
=> Update 20220616 -It-s time to contribute to open source-.md

published/20230210.4 ⭐️ How to Install DOSBox in Ubuntu to Play Old Games.md
@gpchn
https://linux.cn/article-15538-1.html
=> RP:published/20230210.4 ⭐️ How to Install DOSBox in Ubuntu to Play Old Games.md

published/20230117.0 ⭐️⭐️ Learn zip Command in Linux Using Examples.md
@Chao-zhi
https://linux.cn/article-15539-1.html
=> RP:published/20230117.0 ⭐️⭐️ Learn zip Command in Linux Using Examples.md

sources/tech/20230214.1 ⭐️ Lua loops how to use while and repeat until.md
=> [手动选题][tech]: 20230214.1 ⭐️ Lua loops how to use while and repeat until.md

sources/tech/20230214.0 ⭐️⭐️ Create a modern user interface with the Tkinter Python library.md
=> [手动选题][tech]: 20230214.0 ⭐️⭐️ Create a modern user interface with the Tkinter Python library.md

sources/tech/20230213.0 ⭐️⭐️ Learn Expect by writing and automating a simple game.md
=> [手动选题][tech]: 20230213.0 ⭐️⭐️ Learn Expect by writing and automating a simple game.md

sources/talk/20230213.1 ⭐️⭐️⭐️ A 10-step guide for a successful hackathon.md
=> [手动选题][talk]: 20230213.1 ⭐️⭐️⭐️ A 10-step guide for a successful hackathon.md

published/20221125.2 ⭐️ Rnote An Open-Source Drawing App for Notes and Annotation.md
@geekpi
https://linux.cn/article-15545-1.html
=> RP:published/20221125.2 ⭐️ Rnote An Open-Source Drawing App for Notes and Annotation.md

published/20220914 Why Enterprises Should  Opt for Platform as a Service.md
@onionstalgia
https://linux.cn/article-15548-1.html
=> RP:published/20220914 Why Enterprises Should  Opt for Platform as a Service.md

sources/tech/20230217.1 ⭐️ Downgrading a Package via apt-get.md
=> [手动选题][tech]: 20230217.1 ⭐️ Downgrading a Package via apt-get.md

sources/tech/20230216.1 ⭐️⭐️ Beginner's Guide to R Markdown Syntax [With Cheat Sheet].md
=> [手动选题][tech]: 20230216.1 ⭐️⭐️ Beginner's Guide to R Markdown Syntax [With Cheat Sheet].md

sources/tech/20230216.0 ⭐️ 5 escape sequences for your Linux shell.md
=> [手动选题][tech]: 20230216.0 ⭐️ 5 escape sequences for your Linux shell.md

sources/tech/20230215.0 ⭐️ Login as Root in Ubuntu GUI.md
=> [手动选题][tech]: 20230215.0 ⭐️ Login as Root in Ubuntu GUI.md

published/20230204.0 ⭐️ Open source video captioning on Linux.md
@geekpi
https://linux.cn/article-15554-1.html
=> RP:published/20230204.0 ⭐️ Open source video captioning on Linux.md

published/20230206.0 ⭐️ Elementary OS 7 Installation Guide with Screenshots.md
@geekpi
https://linux.cn/article-15556-1.html
=> RP:published/20230206.0 ⭐️ Elementary OS 7 Installation Guide with Screenshots.md

sources/tech/20230218.0 ⭐️⭐️ 40+ Best Open Source Android Apps.md
=> [手动选题][tech]: 20230218.0 ⭐️⭐️ 40+ Best Open Source Android Apps.md

sources/news/20230220.1 ⭐️ Firefox 110 Released with GPU Sandboxing, WebGL Improvements.md
=> [手动选题][news]: 20230220.1 ⭐️ Firefox 110 Released with GPU Sandboxing, WebGL Improvements.md

sources/tech/20230221.0 ⭐️ Making Directories in Linux Terminal.md
=> [手动选题][tech]: 20230221.0 ⭐️ Making Directories in Linux Terminal.md

sources/tech/20230222.1 ⭐️⭐️ Fedora 38 Overview of Its Features and Enhancements.md
=> [手动选题][tech]: 20230222.1 ⭐️⭐️ Fedora 38 Overview of Its Features and Enhancements.md

sources/tech/20230222.0 ⭐️⭐️ NixOS Series 
=> [手动选题][tech]: 20230222.0 ⭐️⭐️ NixOS Series #1 Why Should You Consider Using NixOS.md

sources/talk/20230223.1 ⭐️ Linux is Just a Kernel What Does it Mean.md
=> [手动选题][talk]: 20230223.1 ⭐️ Linux is Just a Kernel What Does it Mean.md

sources/news/20230223.0 ⭐️ Ubuntu Flavours Decide to Stop Flatpak by Default.md
=> [手动选题][news]: 20230223.0 ⭐️ Ubuntu Flavours Decide to Stop Flatpak by Default.md

published/20230207.2 ⭐️ Lightweight Distro LegacyOS 2023 Released After Nine Years.md
@Cubik65536
https://linux.cn/article-15574-1.html
=> RP:published/20230207.2 ⭐️ Lightweight Distro LegacyOS 2023 Released After Nine Years.md

sources/news/20230224.0 ⭐️⭐️ Flathub Plans to Evolve as the Universal Linux App Store.md
=> [手动选题][news]: 20230224.0 ⭐️⭐️ Flathub Plans to Evolve as the Universal Linux App Store.md

published/20230217.1 ⭐️ Downgrading a Package via apt-get.md
@geekpi
https://linux.cn/article-15580-1.html
=> RP:published/20230217.1 ⭐️ Downgrading a Package via apt-get.md

sources/tech/20210205.0 ⭐️⭐️ Why simplicity is critical to delivering sturdy applications.md
=> [手动选题][tech]: 20210205.0 ⭐️⭐️ Why simplicity is critical to delivering sturdy applications.md

sources/tech/20230228.2 ⭐️ 3 tips to manage large Postgres databases.md
=> [手动选题][tech]: 20230228.2 ⭐️ 3 tips to manage large Postgres databases.md

sources/news/20230228.1 ⭐️ Ubuntu Plans for Mini ISO Images for Minimal Desktop Workloads.md
=> [手动选题][news]: 20230228.1 ⭐️ Ubuntu Plans for Mini ISO Images for Minimal Desktop Workloads.md

sources/tech/20230228.0 ⭐️ How to Install IDLE Python IDE in Ubuntu and Other Linux.md
=> [手动选题][tech]: 20230228.0 ⭐️ How to Install IDLE Python IDE in Ubuntu and Other Linux.md

sources/talk/20230227.1 ⭐️⭐️ Essential tips and tricks for your first tech job.md
=> [手动选题][talk]: 20230227.1 ⭐️⭐️ Essential tips and tricks for your first tech job.md

published/20230131.1 ⭐️⭐️ Use Terraform to manage an OpenStack cluster.md
@geekpi
https://linux.cn/article-15586-1.html
=> RP:published/20230131.1 ⭐️⭐️ Use Terraform to manage an OpenStack cluster.md

sources/tech/20230301.0 ⭐️ How to Install PgAdmin4 on RHEL 9 Step by Step.md
=> [手动选题][tech]: 20230301.0 ⭐️ How to Install PgAdmin4 on RHEL 9 Step by Step.md

sources/tech/20230228.3 ⭐️ Terminal Basics Series 3 Listing the Contents of Directory With ls Command.md
=> [手动选题][tech]: 20230228.3 ⭐️ Terminal Basics Series 3 Listing the Contents of Directory With ls Command.md

published/20210819 Short option parsing using getopt in C.md
@toknow-gh
https://linux.cn/article-15589-1.html
=> RP:published/20210819 Short option parsing using getopt in C.md

published/20221220.2 ⭐️⭐️ How I use Artipie, a PyPI repo.md
@geekpi
https://linux.cn/article-15592-1.html
=> RP:published/20221220.2 ⭐️⭐️ How I use Artipie, a PyPI repo.md

sources/tech/20230302.2 ⭐️⭐️ Create Your First Program Using OpenAI ChatGPT API [Beginner’s Guide].md
=> [手动选题][tech]: 20230302.2 ⭐️⭐️ Create Your First Program Using OpenAI ChatGPT API [Beginner’s Guide].md

sources/tech/20230303.1 ⭐️ How I automate graphics creation with Inkscape.md
=> [手动选题][tech]: 20230303.1 ⭐️ How I automate graphics creation with Inkscape.md

sources/tech/20230303.0 ⭐️ A trivia vending machine made with a Raspberry Pi.md
=> [手动选题][tech]: 20230303.0 ⭐️ A trivia vending machine made with a Raspberry Pi.md

sources/tech/20230302.0 ⭐️⭐️ Parallel and distributed computing with Raspberry Pi clusters.md
=> [手动选题][tech]: 20230302.0 ⭐️⭐️ Parallel and distributed computing with Raspberry Pi clusters.md

sources/tech/20230301.4 ⭐️⭐️ 5 Best PDF editors for Ubuntu and Other Linux.md
=> [手动选题][tech]: 20230301.4 ⭐️⭐️ 5 Best PDF editors for Ubuntu and Other Linux.md

sources/tech/20230301.3 ⭐️⭐️ Use your Raspberry Pi as a streaming server.md
=> [手动选题][tech]: 20230301.3 ⭐️⭐️ Use your Raspberry Pi as a streaming server.md

sources/talk/20230301.2 ⭐️⭐️ 3 myths about open source CMS platforms.md
=> [手动选题][talk]: 20230301.2 ⭐️⭐️ 3 myths about open source CMS platforms.md

sources/news/20230301.1 ⭐️⭐️ FFmpeg 6.0 Released with WBMP and Radiance HDR Image Support.md
=> [手动选题][news]: 20230301.1 ⭐️⭐️ FFmpeg 6.0 Released with WBMP and Radiance HDR Image Support.md

sources/tech/20230304.0 ⭐️⭐️ Top 5 Best Arch Linux Distros For Everyone.md
=> [手动选题][tech]: 20230304.0 ⭐️⭐️ Top 5 Best Arch Linux Distros For Everyone.md

sources/tech/20230304.1 ⭐️ Ubuntu Workspaces Enabling, Creating, and Switching.md
=> [手动选题][tech]: 20230304.1 ⭐️ Ubuntu Workspaces Enabling, Creating, and Switching.md

sources/tech/20230304.2 ⭐️⭐️ Create templates for your video graphics with Inkscape.md
=> [手动选题][tech]: 20230304.2 ⭐️⭐️ Create templates for your video graphics with Inkscape.md

sources/tech/20211014 9 ways to use open source every day.md
=> XiaotingHuang22 is translating

sources/tech/20230305.0 ⭐️ Install DOSBox in Ubuntu to Play Retro Games.md
=> [手动选题][tech]: 20230305.0 ⭐️ Install DOSBox in Ubuntu to Play Retro Games.md

published/20230228.2 ⭐️ 3 tips to manage large Postgres databases.md
@geekpi
https://linux.cn/article-15601-1.html
=> RP:published/20230228.2 ⭐️ 3 tips to manage large Postgres databases.md

sources/talk/20230306.2 ⭐️ How Wikipedia helps keep the internet open.md
=> [手动选题][talk]: 20230306.2 ⭐️ How Wikipedia helps keep the internet open.md

sources/tech/20230306.1 ⭐️⭐️ Build a Raspberry Pi monitoring dashboard in under 30 minutes.md
=> [手动选题][tech]: 20230306.1 ⭐️⭐️ Build a Raspberry Pi monitoring dashboard in under 30 minutes.md

sources/tech/20230306.0 ⭐️ Xubuntu Minimal Opportunity to Build Your Own Distro.md
=> [手动选题][tech]: 20230306.0 ⭐️ Xubuntu Minimal Opportunity to Build Your Own Distro.md

published/20230206.1 ⭐️⭐️ Wordsmith on the Linux command line with dict.md
@geekpi
https://linux.cn/article-15607-1.html
=> RP:published/20230206.1 ⭐️⭐️ Wordsmith on the Linux command line with dict.md

sources/tech/20230227.0 ⭐️⭐️ NixOS Series 2 How to Install NixOS on a Virtual Machine.md
=> [手动选题][tech]: 20230227.0 ⭐️⭐️ NixOS Series 2 How to Install NixOS on a Virtual Machine.md

sources/tech/20230309.2 ⭐️⭐️ Compiler optimization and its effect on debugger line information.md
=> [手动选题][tech]: 20230309.2 ⭐️⭐️ Compiler optimization and its effect on debugger line information.md

sources/talk/20230309.1 ⭐️ Contribute to open source without code.md
=> [手动选题][talk]: 20230309.1 ⭐️ Contribute to open source without code.md

sources/tech/20230309.0 ⭐️ Postgres DevOps database administrator A day in the life.md
=> [手动选题][tech]: 20230309.0 ⭐️ Postgres DevOps database administrator A day in the life.md

sources/tech/20230308.7 ⭐️⭐️ Top 5 Best EPUB Readers for Linux [Compared].md
=> [手动选题][tech]: 20230308.7 ⭐️⭐️ Top 5 Best EPUB Readers for Linux [Compared].md

sources/talk/20230308.6 ⭐️⭐️ The power of sisterhood and allyship in open source.md
=> [手动选题][talk]: 20230308.6 ⭐️⭐️ The power of sisterhood and allyship in open source.md

sources/tech/20230308.5 ⭐️⭐️⭐️ Own your cloud with NextcloudPi on the Raspberry Pi.md
=> [手动选题][tech]: 20230308.5 ⭐️⭐️⭐️ Own your cloud with NextcloudPi on the Raspberry Pi.md

sources/talk/20230308.3 ⭐️ 8 examples of influential women in tech.md
=> [手动选题][talk]: 20230308.3 ⭐️ 8 examples of influential women in tech.md

sources/tech/20230308.2 ⭐️⭐️ How to Install MiniKube on RHEL 8Rocky Linux 8AlmaLinux 8.md
=> [手动选题][tech]: 20230308.2 ⭐️⭐️ How to Install MiniKube on RHEL 8Rocky Linux 8AlmaLinux 8.md

sources/news/20230308.1 ⭐️ Vanilla OS Drops Ubuntu, Welcomes Debian Sid.md
=> [手动选题][news]: 20230308.1 ⭐️ Vanilla OS Drops Ubuntu, Welcomes Debian Sid.md

sources/tech/20230307.1 ⭐️ Switch from iCloud to Nextcloud.md
=> [手动选题][tech]: 20230307.1 ⭐️ Switch from iCloud to Nextcloud.md

sources/tech/20230307.1 ⭐️ Switch from iCloud to Nextcloud.md
Xiaoting Huang is translating. 任务申领。
=> Update 20230307.1 ⭐️ Switch from iCloud to Nextcloud.md

sources/tech/20230310.1 ⭐️⭐️ How the GDB debugger and other tools use call frame information to determine the active function calls.md
=> [手动选题][tech]: 20230310.1 ⭐️⭐️ How the GDB debugger and other tools use call frame information to determine the active function calls.md

sources/tech/20230310.0 ⭐️⭐️ What is an edge-native application.md
=> [手动选题][tech]: 20230310.0 ⭐️⭐️ What is an edge-native application.md

sources/tech/20230309.3 ⭐️⭐️ Arch Linux vs Other Linux Distros Which is Right for You.md
=> [手动选题][tech]: 20230309.3 ⭐️⭐️ Arch Linux vs Other Linux Distros Which is Right for You.md

sources/tech/20230213.2 ⭐️ Terminal Basics Series 1 Changing Directories in Linux Terminal.md
=> [手动选题][tech]: 20230213.2 ⭐️ Terminal Basics Series 1 Changing Directories in Linux Terminal.md

sources/talk/20230308.3 ⭐️ 8 examples of influential women in tech.md
XiaotingHuang22 is translating. 翻译任务认领。
=> Update 20230308.3 ⭐️ 8 examples of influential women in tech.md

sources/talk/20230308.3 ⭐️ 8 examples of influential women in tech.md
Reverts LCTT/TranslateProject#28851
=> Revert "Update 20230308.3 ⭐️ 8 examples of influential women in tech.md"

published/20230228.0 ⭐️ How to Install IDLE Python IDE in Ubuntu and Other Linux.md
@geekpi
https://linux.cn/article-15622-1.html
=> RP:published/20230228.0 ⭐️ How to Install IDLE Python IDE in Ubuntu and Other Linux.md

published/20230227.0 ⭐️⭐️ NixOS Series 2 How to Install NixOS on a Virtual Machine.md
@geekpi
https://linux.cn/article-15624-1.html
=> RP:published/20230227.0 ⭐️⭐️ NixOS Series 2 How to Install NixOS on a Virtual Machine.md

published/20230216.1 ⭐️⭐️ Beginner's Guide to R Markdown Syntax [With Cheat Sheet].md
@lxbwolf
https://linux.cn/article-15627-1.html
=> RP:published/20230216.1 ⭐️⭐️ Beginner's Guide to R Markdown Syntax [With Cheat Sheet].md

sources/talk/20230316.4 ⭐️⭐️ How I returned to open source after facing grief.md
=> [手动选题][talk]: 20230316.4 ⭐️⭐️ How I returned to open source after facing grief.md

sources/news/20230316.2 ⭐️ Firefox 111 Released with New Native Notifications.md
=> [手动选题][news]: 20230316.2 ⭐️ Firefox 111 Released with New Native Notifications.md

sources/tech/20230316.1 ⭐️⭐️ Best GUI Package Managers for Arch Linux.md
=> [手动选题][tech]: 20230316.1 ⭐️⭐️ Best GUI Package Managers for Arch Linux.md

sources/tech/20230316.0 ⭐️ Terminal Basics Series 5 View the File Contents in Linux.md
=> [手动选题][tech]: 20230316.0 ⭐️ Terminal Basics Series 5 View the File Contents in Linux.md

sources/tech/20230315.3 ⭐️⭐️ Synchronize databases more easily with open source tools.md
=> [手动选题][tech]: 20230315.3 ⭐️⭐️ Synchronize databases more easily with open source tools.md

sources/tech/20230315.2 ⭐️ How to set up your own open source DNS server.md
=> [手动选题][tech]: 20230315.2 ⭐️ How to set up your own open source DNS server.md

sources/tech/20230315.1 ⭐️ How to know if You are Behind a Proxy Server.md
=> [手动选题][tech]: 20230315.1 ⭐️ How to know if You are Behind a Proxy Server.md

sources/tech/20230315.0 ⭐️ Input Function in Python Concepts and Examples.md
=> [手动选题][tech]: 20230315.0 ⭐️ Input Function in Python Concepts and Examples.md

sources/news/20230314.4 ⭐️ Kali Linux Introduces “Kali Purple” for Defensive Security Hardening.md
=> [手动选题][news]: 20230314.4 ⭐️ Kali Linux Introduces “Kali Purple” for Defensive Security Hardening.md

sources/tech/20230314.3 ⭐️⭐️ Control your Raspberry Pi with Lua.md
=> [手动选题][tech]: 20230314.3 ⭐️⭐️ Control your Raspberry Pi with Lua.md

sources/tech/20230314.2 ⭐️ How I destroyed my Raspberry Pi.md
=> [手动选题][tech]: 20230314.2 ⭐️ How I destroyed my Raspberry Pi.md

sources/tech/20230314.0 ⭐️⭐️ 5 of the most curious uses of the Raspberry Pi.md
=> [手动选题][tech]: 20230314.0 ⭐️⭐️ 5 of the most curious uses of the Raspberry Pi.md

sources/tech/20230313.4 ⭐️⭐️ Monitor Kubernetes cloud costs with open source tools.md
=> [手动选题][tech]: 20230313.4 ⭐️⭐️ Monitor Kubernetes cloud costs with open source tools.md

sources/tech/20230313.2 ⭐️⭐️ NixOS Series 4 Things To Do After Installing NixOS.md
=> [手动选题][tech]: 20230313.2 ⭐️⭐️ NixOS Series 4 Things To Do After Installing NixOS.md

sources/news/20230313.1 ⭐️ Scrcpy 2.0 Released with Audio Forwarding from Android to PC.md
=> [手动选题][news]: 20230313.1 ⭐️ Scrcpy 2.0 Released with Audio Forwarding from Android to PC.md

sources/tech/20230313.0 ⭐️⭐️ A Guide to Find the Right Debian ISO for Download.md
=> [手动选题][tech]: 20230313.0 ⭐️⭐️ A Guide to Find the Right Debian ISO for Download.md

sources/tech/20230312.0 ⭐️ Fixing Slow Download Speed while Using pacman in Arch Linux.md
=> [手动选题][tech]: 20230312.0 ⭐️ Fixing Slow Download Speed while Using pacman in Arch Linux.md

sources/tech/20221219.1 ⭐️⭐️ How I use my old camera as a webcam with Linux.md
=> Update 20221219.1 ⭐️⭐️ How I use my old camera as a webcam with Linux.md

sources/talk/20230317.2 ⭐️⭐️ How being open at work results in happy customers.md
=> [手动选题][talk]: 20230317.2 ⭐️⭐️ How being open at work results in happy customers.md

sources/tech/20230317.0 ⭐️ Variables in Python Concepts with Examples.md
=> [手动选题][tech]: 20230317.0 ⭐️ Variables in Python Concepts with Examples.md

sources/talk/20230317.1 ⭐️ My first pull request at age 14.md
=> [手动选题][talk]: 20230317.1 ⭐️ My first pull request at age 14.md

published/20230316.2 ⭐️ Firefox 111 Released with New Native Notifications.md
@Cubik65536
https://linux.cn/article-15639-1.html
=> RP:published/20230316.2 ⭐️ Firefox 111 Released with New Native Notifications.md

sources/tech/20230318.0 ⭐️⭐️ How I got my first job in tech and helped others do the same.md
=> [手动选题][tech]: 20230318.0 ⭐️⭐️ How I got my first job in tech and helped others do the same.md

sources/tech/20230319.0 ⭐️⭐️ Linux Jargon Buster What is LUKS Encryption.md
=> [手动选题][tech]: 20230319.0 ⭐️⭐️ Linux Jargon Buster What is LUKS Encryption.md

published/20230307.2 ⭐️ Terminal Basics Series 4 Creating Files in Linux.md
@geekpi
https://linux.cn/article-15643-1.html
=> RP:published/20230307.2 ⭐️ Terminal Basics Series 4 Creating Files in Linux.md

published/20230309.0 ⭐️ Postgres DevOps database administrator A day in the life.md
@geekpi
https://linux.cn/article-15649-1.html
=> RP:published/20230309.0 ⭐️ Postgres DevOps database administrator A day in the life.md

published/20230308.7 ⭐️⭐️ Top 5 Best EPUB Readers for Linux [Compared].md
@robsean
https://linux.cn/article-15651-1.html
=> RP:published/20230308.7 ⭐️⭐️ Top 5 Best EPUB Readers for Linux [Compared].md

published/20230303.0 ⭐️ A trivia vending machine made with a Raspberry Pi.md
@geekpi
https://linux.cn/article-15652-1.html
=> RP:published/20230303.0 ⭐️ A trivia vending machine made with a Raspberry Pi.md

sources/tech/20230323.2 ⭐️ 3 surprising things Linux sysadmins can do with systemd.md
=> [手动选题][tech]: 20230323.2 ⭐️ 3 surprising things Linux sysadmins can do with systemd.md

sources/tech/20230323.1 ⭐️ Terminal Basics 6 Delete Files and Folders in Linux.md
=> [手动选题][tech]: 20230323.1 ⭐️ Terminal Basics 6 Delete Files and Folders in Linux.md

sources/tech/20230323.0 ⭐️⭐️ A Screenshot Tour & Walkthrough of New Ubuntu Installer.md
=> [手动选题][tech]: 20230323.0 ⭐️⭐️ A Screenshot Tour & Walkthrough of New Ubuntu Installer.md

sources/talk/20230322.1 ⭐️⭐️ Why your open source project needs a content strategy.md
=> [手动选题][talk]: 20230322.1 ⭐️⭐️ Why your open source project needs a content strategy.md

sources/tech/20230322.0 ⭐️⭐️ 8 steps to refurbish an old computer with Linux.md
=> [手动选题][tech]: 20230322.0 ⭐️⭐️ 8 steps to refurbish an old computer with Linux.md

sources/tech/20230321.3 ⭐️⭐️ Ubuntu 23.04 “Lunar Lobster” Best New Features.md
=> [手动选题][tech]: 20230321.3 ⭐️⭐️ Ubuntu 23.04 “Lunar Lobster” Best New Features.md

sources/tech/20230321.2 ⭐️⭐️ A 5-minute tour of the Fediverse.md
=> [手动选题][tech]: 20230321.2 ⭐️⭐️ A 5-minute tour of the Fediverse.md

sources/tech/20230321.1 ⭐️⭐️ NixOS Series 5 How to set up home-manager on NixOS.md
=> [手动选题][tech]: 20230321.1 ⭐️⭐️ NixOS Series 5 How to set up home-manager on NixOS.md

sources/tech/20230321.0 ⭐️⭐️ How to Install CRI-O (Container Runtime) on Ubuntu 22.04.md
=> [手动选题][tech]: 20230321.0 ⭐️⭐️ How to Install CRI-O (Container Runtime) on Ubuntu 22.04.md

published/20230315.1 ⭐️ How to know if You are Behind a Proxy Server.md
@geekpi
https://linux.cn/article-15657-1.html
=> RP:published/20230315.1 ⭐️ How to know if You are Behind a Proxy Server.md

sources/news/20230323.3 ⭐️⭐️ GNOME 44 is Here With New Tricks Up its Sleeve.md
=> [手动选题][news]: 20230323.3 ⭐️⭐️ GNOME 44 is Here With New Tricks Up its Sleeve.md

sources/news/20230323.4 ⭐️⭐️ Mozilla Plans to Work On Open-Source AI to Develop Solutions like ChatGPT.md
=> [手动选题][news]: 20230323.4 ⭐️⭐️ Mozilla Plans to Work On Open-Source AI to Develop Solutions like ChatGPT.md

sources/news/20230323.5 ⭐️ Adding a Pop of Color to GNOME Accent Colors Are on the Way.md
=> [手动选题][news]: 20230323.5 ⭐️ Adding a Pop of Color to GNOME Accent Colors Are on the Way.md

sources/tech/20230324.0 ⭐️ Open source tools for mind mapping.md
=> [手动选题][tech]: 20230324.0 ⭐️ Open source tools for mind mapping.md

sources/tech/20230307.3 ⭐️⭐️⭐️ Some possible reasons for 8-bit bytes.md
=> [手动选题][tech]: 20230307.3 ⭐️⭐️⭐️ Some possible reasons for 8-bit bytes.md

sources/tech/20230303.2 ⭐️⭐️⭐️ How do Nix builds work.md
=> [手动选题][tech]: 20230303.2 ⭐️⭐️⭐️ How do Nix builds work.md

sources/tech/20230228.4 ⭐️⭐️ Some notes on using nix.md
=> [手动选题][tech]: 20230228.4 ⭐️⭐️ Some notes on using nix.md

sources/tech/20230216.2 ⭐️⭐️ Writing Javascript without a build system.md
=> [手动选题][tech]: 20230216.2 ⭐️⭐️ Writing Javascript without a build system.md

sources/tech/20230208.3 ⭐️⭐️⭐️ Why does 0.1 + 0.2 = 0.30000000000000004.md
=> [手动选题][tech]: 20230208.3 ⭐️⭐️⭐️ Why does 0.1 + 0.2 = 0.30000000000000004.md

sources/tech/20230118.0 ⭐️⭐️⭐️ Examples of problems with integers.md
=> [手动选题][tech]: 20230118.0 ⭐️⭐️⭐️ Examples of problems with integers.md

sources/tech/20230113.0 ⭐️⭐️⭐️ Examples of floating point problems.md
=> [手动选题][tech]: 20230113.0 ⭐️⭐️⭐️ Examples of floating point problems.md

published/20230315.0 ⭐️ Input Function in Python Concepts and Examples.md
@geekpi
https://linux.cn/article-15660-1.html
=> RP:published/20230315.0 ⭐️ Input Function in Python Concepts and Examples.md

sources/tech/20230325.0 ⭐️ How to Install and Use Neovim on Ubuntu and other Linux Distributions.md
=> [手动选题][tech]: 20230325.0 ⭐️ How to Install and Use Neovim on Ubuntu and other Linux Distributions.md

published/20230317.0 ⭐️ Variables in Python Concepts with Examples.md
@geekpi
https://linux.cn/article-15668-1.html
=> RP:published/20230317.0 ⭐️ Variables in Python Concepts with Examples.md

sources/tech/20230327.0 ⭐️ How to Install Kubernetes (K8s) Metrics Server Step by Step.md
=> [手动选题][tech]: 20230327.0 ⭐️ How to Install Kubernetes (K8s) Metrics Server Step by Step.md

sources/news/20230327.1 ⭐️ blendOS Aims to Replace All Linux Distributions.md
=> [手动选题][news]: 20230327.1 ⭐️ blendOS Aims to Replace All Linux Distributions.md

sources/tech/20230327.2 ⭐️ Use this open source accounting app to run your small business.md
=> [手动选题][tech]: 20230327.2 ⭐️ Use this open source accounting app to run your small business.md

sources/tech/20230327.3 ⭐️ Create a ChatBot in Mattermost with Python.md
=> [手动选题][tech]: 20230327.3 ⭐️ Create a ChatBot in Mattermost with Python.md

sources/news/20230327.4 ⭐️ Open-Source Model 'Dolly' Claims to be a Cheaper Alternative to ChatGPT.md
=> [手动选题][news]: 20230327.4 ⭐️ Open-Source Model 'Dolly' Claims to be a Cheaper Alternative to ChatGPT.md

sources/tech/20230328.0 ⭐️⭐️ Debian 12 Bookworm Best New Features.md
=> [手动选题][tech]: 20230328.0 ⭐️⭐️ Debian 12 Bookworm Best New Features.md

sources/tech/20230328.1 ⭐️⭐️ Rust Basics Series 1 Create and Run Your First Rust Program.md
=> [手动选题][tech]: 20230328.1 ⭐️⭐️ Rust Basics Series 1 Create and Run Your First Rust Program.md

sources/tech/20230328.2 ⭐️⭐️ How to use Podman in GitLab Runners.md
=> [手动选题][tech]: 20230328.2 ⭐️⭐️ How to use Podman in GitLab Runners.md

sources/tech/20230328.3 ⭐️⭐️ Why you should use Python and Rust together.md
=> [手动选题][tech]: 20230328.3 ⭐️⭐️ Why you should use Python and Rust together.md

sources/talk/20230329.0 ⭐️⭐️ The open source way of raising a family.md
=> [手动选题][talk]: 20230329.0 ⭐️⭐️ The open source way of raising a family.md

sources/news/20230329.1 ⭐️ Ubuntu Cinnamon Gets Official Ubuntu Flavor Status.md
=> [手动选题][news]: 20230329.1 ⭐️ Ubuntu Cinnamon Gets Official Ubuntu Flavor Status.md

published/20230313.3 ⭐️⭐️ How to Install Kubernetes Cluster Using Kubespray.md
@geekpi
https://linux.cn/article-15675-1.html
=> RP:published/20230313.3 ⭐️⭐️ How to Install Kubernetes Cluster Using Kubespray.md

sources/tech/20230330.1 ⭐️⭐️ 3 reasons my Linux team uses Penpot.md
=> [手动选题][tech]: 20230330.1 ⭐️⭐️ 3 reasons my Linux team uses Penpot.md

sources/tech/20230330.0 ⭐️⭐️ Edubuntu 23.04 Best New Features.md
=> [手动选题][tech]: 20230330.0 ⭐️⭐️ Edubuntu 23.04 Best New Features.md

sources/tech/20230329.2 ⭐️ Linux Terminal Basics 7 Copy Files and Directories in Linux.md
=> [手动选题][tech]: 20230329.2 ⭐️ Linux Terminal Basics 7 Copy Files and Directories in Linux.md

published/20230327.4 ⭐️ Open-Source Model 'Dolly' Claims to be a Cheaper Alternative to ChatGPT.md
@lxbwolf
https://linux.cn/article-15678-1.html
=> RP:published/20230327.4 ⭐️ Open-Source Model 'Dolly' Claims to be a Cheaper Alternative to ChatGPT.md

sources/tech/20230331.2 ⭐️⭐️ Measure pi with a Raspberry Pi.md
=> [手动选题][tech]: 20230331.2 ⭐️⭐️ Measure pi with a Raspberry Pi.md

sources/tech/20230331.1 ⭐️⭐️ 8 Immutable Linux Distributions for Those Looking to Embrace the Future.md
=> [手动选题][tech]: 20230331.1 ⭐️⭐️ 8 Immutable Linux Distributions for Those Looking to Embrace the Future.md

sources/news/20230331.0 ⭐️ SD Maid v2 Android System Cleaning App Goes Open-Source.md
=> [手动选题][news]: 20230331.0 ⭐️ SD Maid v2 Android System Cleaning App Goes Open-Source.md

published/20230325.0 ⭐️ How to Install and Use Neovim on Ubuntu and other Linux Distributions.md
@geekpi
https://linux.cn/article-15680-1.html
=> RP:published/20230325.0 ⭐️ How to Install and Use Neovim on Ubuntu and other Linux Distributions.md

published/20211108 Write your first CI-CD pipeline in Kubernetes with Tekton.md
@lxbwolf
https://linux.cn/article-15681-1.html
=> RP:published/20211108 Write your first CI-CD pipeline in Kubernetes with Tekton.md

sources/tech/20230401.3 ⭐️⭐️ 10 Tweaks to Supercharge Gedit as Code Editor.md
=> [手动选题][tech]: 20230401.3 ⭐️⭐️ 10 Tweaks to Supercharge Gedit as Code Editor.md

sources/tech/20230401.2 ⭐️ Write a cute program with Emojicode.md
=> [手动选题][tech]: 20230401.2 ⭐️ Write a cute program with Emojicode.md

sources/tech/20230401.1 ⭐️⭐️ Using mocks in Python.md
=> [手动选题][tech]: 20230401.1 ⭐️⭐️ Using mocks in Python.md

sources/news/20230401.0 ⭐️ Enough of it! Ubuntu to Ditch Snap Completely With 24.04 LTS Naughty Nightingale.md
=> [手动选题][news]: 20230401.0 ⭐️ Enough of it! Ubuntu to Ditch Snap Completely With 24.04 LTS Naughty Nightingale.md

sources/tech/20211124 5 open source alternatives to Microsoft Exchange.md
XiaotingHuang22 is translating. 任务申领。
=> Update 20211124 5 open source alternatives to Microsoft Exchange.md

sources/tech/20230403.4 ⭐️⭐️ How to Install KVM on Rocky Linux 9  AlmaLinux 9.md
=> [手动选题][tech]: 20230403.4 ⭐️⭐️ How to Install KVM on Rocky Linux 9  AlmaLinux 9.md

sources/tech/20230403.3 ⭐️⭐️ Open source text editing for your website with CKEditor.md
=> [手动选题][tech]: 20230403.3 ⭐️⭐️ Open source text editing for your website with CKEditor.md

sources/tech/20230403.2 ⭐️⭐️ Handle any type of document with this open source tool.md
=> [手动选题][tech]: 20230403.2 ⭐️⭐️ Handle any type of document with this open source tool.md

sources/news/20230403.0 ⭐️ Linux Lite 6.4 Gets Lighter With More Features like WebP Image Support.md
=> [手动选题][news]: 20230403.0 ⭐️ Linux Lite 6.4 Gets Lighter With More Features like WebP Image Support.md

published/20230327.3 ⭐️ Create a ChatBot in Mattermost with Python.md
@geekpi
https://linux.cn/article-15693-1.html
=> RP:published/20230327.3 ⭐️ Create a ChatBot in Mattermost with Python.md

sources/tech/20230328.1 ⭐️⭐️ Rust Basics Series 1 Create and Run Your First Rust Program.md
Reverts LCTT/TranslateProject#29045
=> Revert "trans"

published/20230401.2 ⭐️ Write a cute program with Emojicode.md
@geekpi
https://linux.cn/article-15699-1.html
=> RP:published/20230401.2 ⭐️ Write a cute program with Emojicode.md

sources/tech/20230407.3 ⭐️⭐️ CachyOS Arch-based Distro for Speed and Ease of Use.md
=> [手动选题][tech]: 20230407.3 ⭐️⭐️ CachyOS Arch-based Distro for Speed and Ease of Use.md

sources/tech/20220813 Level up your HTML document with CSS.md
XiaotingHuang22 is translating.
=> Update 20220813 Level up your HTML document with CSS.md

sources/tech/20220523 -Speek!- - An Open-Source Chat App That Uses Tor.md
XiaotingHuang22 is translating. 任务申领。
=> Update 20220523 -Speek!- - An Open-Source Chat App That Uses Tor.md

sources/news/20230407.2 ⭐️⭐️ Xubuntu 23.04 Best New Features.md
=> [手动选题][news]: 20230407.2 ⭐️⭐️ Xubuntu 23.04 Best New Features.md

sources/tech/20230407.1 ⭐️⭐️ 5 best practices for PatternFly, an open source design system.md
=> [手动选题][tech]: 20230407.1 ⭐️⭐️ 5 best practices for PatternFly, an open source design system.md

sources/tech/20230407.0 ⭐️⭐️ A Quick Guide to Install and Play GOG Games on Linux.md
=> [手动选题][tech]: 20230407.0 ⭐️⭐️ A Quick Guide to Install and Play GOG Games on Linux.md

sources/tech/20230406.0 ⭐️⭐️ Make a web-safe color guide with Bash.md
=> [手动选题][tech]: 20230406.0 ⭐️⭐️ Make a web-safe color guide with Bash.md

sources/news/20230405.6 ⭐️⭐️ TUXEDO Stellaris 16 (Gen5) is The Ultimate Linux Laptop You Can Find Now.md
=> [手动选题][news]: 20230405.6 ⭐️⭐️ TUXEDO Stellaris 16 (Gen5) is The Ultimate Linux Laptop You Can Find Now.md

sources/news/20230405.5 ⭐️⭐️ Color Variants & Styles Are Coming to Linux Mint 21.2.md
=> [手动选题][news]: 20230405.5 ⭐️⭐️ Color Variants & Styles Are Coming to Linux Mint 21.2.md

sources/tech/20230405.4 ⭐️⭐️ Our favorite fonts for the Linux terminal.md
=> [手动选题][tech]: 20230405.4 ⭐️⭐️ Our favorite fonts for the Linux terminal.md

sources/tech/20230405.3 ⭐️⭐️ BASIC vs. FORTRAN 77 Comparing programming blasts from the past.md
=> [手动选题][tech]: 20230405.3 ⭐️⭐️ BASIC vs. FORTRAN 77 Comparing programming blasts from the past.md

sources/talk/20230405.2 ⭐️⭐️ Open source community analysis with actionable insights.md
=> [手动选题][talk]: 20230405.2 ⭐️⭐️ Open source community analysis with actionable insights.md

sources/news/20230405.1 ⭐️ Linux Mint Team Announced “Styles” for Cinnamon Desktop.md
=> [手动选题][news]: 20230405.1 ⭐️ Linux Mint Team Announced “Styles” for Cinnamon Desktop.md

sources/tech/20230404.1 ⭐️ How to resolve Git merge conflicts.md
=> [手动选题][tech]: 20230404.1 ⭐️ How to resolve Git merge conflicts.md

sources/tech/20230404.0 ⭐️⭐️ Linux Terminal Basics 8 Move Files and Directories (Cut-Paste Operation).md
=> [手动选题][tech]: 20230404.0 ⭐️⭐️ Linux Terminal Basics 8 Move Files and Directories (Cut-Paste Operation).md

published/20230324.0 ⭐️ Open source tools for mind mapping.md
@geekpi
https://linux.cn/article-15708-1.html
=> RP:published/20230324.0 ⭐️ Open source tools for mind mapping.md

published/20210111 an even better video wharf.md, translated/tech/20210111 an even better video wharf.md
@Drwhooooo
本文首发地址：https://linux.cn/article-15711-1.html
也会同步发布到公众号、知乎的同名账号
您的 LCTT 专页：https://linux.cn/lctt/Drwhooooo
=> RP:20210111 an even better video wharf

published/20230403.2 ⭐️⭐️ Handle any type of document with this open source tool.md
@geekpi
https://linux.cn/article-15712-1.html
=> RP:published/20230403.2 ⭐️⭐️ Handle any type of document with this open source tool.md

published/20230327.0 ⭐️ How to Install Kubernetes (K8s) Metrics Server Step by Step.md
@geekpi
https://linux.cn/article-15714-1.html
=> RP:published/20230327.0 ⭐️ How to Install Kubernetes (K8s) Metrics Server Step by Step.md

published/20230405.4 ⭐️⭐️ Our favorite fonts for the Linux terminal.md, translated/tech/20230405.4 ⭐️⭐️ Our favorite fonts for the Linux terminal.md
@Taivasjumala
本文首发：https://linux.cn/article-15715-1.html
也会发布在知乎、公众号的同名账户
您的 LCTT 专页： https://linux.cn/lctt/Taivasjumala
=> RP:20230405.4 ⭐️⭐️ our favorite fonts for the linux terminal

sources/tech/20230412.5 ⭐️⭐️ How to Connect GitHub to VS Code [Step by Step].md
=> [手动选题][tech]: 20230412.5 ⭐️⭐️ How to Connect GitHub to VS Code [Step by Step].md

sources/news/20230412.4 ⭐️⭐️ Atlas An Open Windows OS Optimized for Gaming and Privacy.md
=> [手动选题][news]: 20230412.4 ⭐️⭐️ Atlas An Open Windows OS Optimized for Gaming and Privacy.md

sources/tech/20230412.2 ⭐️ 7 open source modules to make your website accessible.md
=> [手动选题][tech]: 20230412.2 ⭐️ 7 open source modules to make your website accessible.md

sources/news/20230412.1 ⭐️⭐️ OpenBSD 7.3 Released with New Features and Updates.md
=> [手动选题][news]: 20230412.1 ⭐️⭐️ OpenBSD 7.3 Released with New Features and Updates.md

sources/news/20230412.0 ⭐️ Firefox 112 Released Right-Click to Reveal Password, Improved Tab Management, and More!.md
=> [手动选题][news]: 20230412.0 ⭐️ Firefox 112 Released Right-Click to Reveal Password, Improved Tab Management, and More!.md

sources/tech/20230411.4 ⭐️⭐️ Linux Terminal Basics 9 Editing Files in Linux Terminal.md
=> [手动选题][tech]: 20230411.4 ⭐️⭐️ Linux Terminal Basics 9 Editing Files in Linux Terminal.md

sources/talk/20230411.3 ⭐️⭐️ 7 tips to make the most of your next tech conference.md
=> [手动选题][talk]: 20230411.3 ⭐️⭐️ 7 tips to make the most of your next tech conference.md

sources/talk/20230411.2 ⭐️⭐️ 5 open source principles that help organizational governance.md
=> [手动选题][talk]: 20230411.2 ⭐️⭐️ 5 open source principles that help organizational governance.md

sources/tech/20230411.1 ⭐️⭐️ Beginner’s Guide to Verify ISO Files in Linux.md
=> [手动选题][tech]: 20230411.1 ⭐️⭐️ Beginner’s Guide to Verify ISO Files in Linux.md

sources/news/20230411.0 ⭐️⭐️ Slint 1.0 Release Gives Us a New Rust-based Open-Source GUI Toolkit.md
=> [手动选题][news]: 20230411.0 ⭐️⭐️ Slint 1.0 Release Gives Us a New Rust-based Open-Source GUI Toolkit.md

sources/tech/20230410.1 ⭐️ Remove the background from an image with this Linux command.md
=> [手动选题][tech]: 20230410.1 ⭐️ Remove the background from an image with this Linux command.md

sources/tech/20230410.0 ⭐️⭐️ Rust Basics Series 3 Data Types in Rust.md
=> [手动选题][tech]: 20230410.0 ⭐️⭐️ Rust Basics Series 3 Data Types in Rust.md

sources/tech/20230408.1 ⭐️⭐️ Is Official Ubuntu Mini ISO Truly Minimal A Test Drive.md
=> [手动选题][tech]: 20230408.1 ⭐️⭐️ Is Official Ubuntu Mini ISO Truly Minimal A Test Drive.md

sources/tech/20230408.0 ⭐️ A search engine for Creative Commons.md
=> [手动选题][tech]: 20230408.0 ⭐️ A search engine for Creative Commons.md

sources/news/20230412.0 ⭐️ Firefox 112 Released Right-Click to Reveal Password, Improved Tab Management, and More!.md
=> XiaotingHuang is translating.

published/20220701 How To Create Multiboot USB Drives With Ventoy In Linux.md
@hanszhao80
https://linux.cn/article-15720-1.html
这篇翻译的很用心 👍
=> RP:published/20220701 How To Create Multiboot USB Drives With Ventoy In Linux.md

sources/tech/20230208.1 ⭐️⭐️ Improve your coding skills with temporal values in MySQL.md
=> 申请翻译 [tech] 20230208.1 Improve your coding skills with temporal value

published/20230317.1 ⭐️ My first pull request at age 14.md
@hanszhao80
https://linux.cn/article-15723-1.html
=> RP:published/20230317.1 ⭐️ My first pull request at age 14.md

published/20230316.1 ⭐️⭐️ Best GUI Package Managers for Arch Linux.md
@geekpi
https://linux.cn/article-15727-1.html
=> RP:published/20230316.1 ⭐️⭐️ Best GUI Package Managers for Arch Linux.md

published/20221124.1 ⭐️ How to Merge PDF Files in Linux.md
@geekpi
https://linux.cn/article-15730-1.html
=> RP:published/20221124.1 ⭐️ How to Merge PDF Files in Linux.md

sources/tech/20230414.0 ⭐️ KDE Team Developing a New e-Book Management App Arianna.md
=> [手动选题][tech]: 20230414.0 ⭐️ KDE Team Developing a New e-Book Management App Arianna.md

sources/news/20230420.5 ⭐️ Kubuntu 23.04 Release is Here!.md
=> [手动选题][news]: 20230420.5 ⭐️ Kubuntu 23.04 Release is Here!.md

sources/news/20230420.4 ⭐️ Xubuntu 23.04 Releases With Xfce 4.18 and Pipewire.md
=> [手动选题][news]: 20230420.4 ⭐️ Xubuntu 23.04 Releases With Xfce 4.18 and Pipewire.md

sources/news/20230420.3 ⭐️ Ubuntu Budgie 23.04 Release Brings in a Refreshed User Experience.md
=> [手动选题][news]: 20230420.3 ⭐️ Ubuntu Budgie 23.04 Release Brings in a Refreshed User Experience.md

sources/news/20230420.1 ⭐️ Ubuntu 23.04 Releases With New Installer, A New Flavour, and GNOME 44.md
=> [手动选题][news]: 20230420.1 ⭐️ Ubuntu 23.04 Releases With New Installer, A New Flavour, and GNOME 44.md

sources/talk/20230420.0 ⭐️⭐️ Real-world examples of the sharing economy.md
=> [手动选题][talk]: 20230420.0 ⭐️⭐️ Real-world examples of the sharing economy.md

sources/talk/20230419.2 ⭐️⭐️ The sharing economy and the open organization.md
=> [手动选题][talk]: 20230419.2 ⭐️⭐️ The sharing economy and the open organization.md

sources/tech/20230419.1 ⭐️⭐️ 10 Things to Do after Installing Fedora 38 Workstation.md
=> [手动选题][tech]: 20230419.1 ⭐️⭐️ 10 Things to Do after Installing Fedora 38 Workstation.md

sources/tech/20230419.0 ⭐️⭐️ How to Upgrade to Fedora 38 from Fedora 37 Workstation (GUI and CLI).md
=> [手动选题][tech]: 20230419.0 ⭐️⭐️ How to Upgrade to Fedora 38 from Fedora 37 Workstation (GUI and CLI).md

sources/news/20230418.1 ⭐️⭐️ Fedora 38 is Officially Released. This is What’s New.md
=> [手动选题][news]: 20230418.1 ⭐️⭐️ Fedora 38 is Officially Released. This is What’s New.md

sources/news/20230418.5 ⭐️ Valve's Proton 8.0 Release is Good News for Linux Gamers and Steam Deck Users.md
=> [手动选题][news]: 20230418.5 ⭐️ Valve's Proton 8.0 Release is Good News for Linux Gamers and Steam Deck Users.md

sources/tech/20230418.4 ⭐️⭐️ Linux Terminal Basics 10 Getting Help in Linux Terminal.md
=> [手动选题][tech]: 20230418.4 ⭐️⭐️ Linux Terminal Basics 10 Getting Help in Linux Terminal.md

sources/news/20230418.3 ⭐️⭐️ Vivaldi 6.0 Introduces Workspaces and Custom Icons.md
=> [手动选题][news]: 20230418.3 ⭐️⭐️ Vivaldi 6.0 Introduces Workspaces and Custom Icons.md

sources/tech/20230418.2 ⭐️⭐️ Talk to your cluster with this open source Python API wrapper.md
=> [手动选题][tech]: 20230418.2 ⭐️⭐️ Talk to your cluster with this open source Python API wrapper.md

sources/tech/20230418.0 ⭐️⭐️ Use autoloading and namespaces in PHP.md
=> [手动选题][tech]: 20230418.0 ⭐️⭐️ Use autoloading and namespaces in PHP.md

sources/tech/20230417.2 ⭐️ LXQt 1.3.0 Explore the Upgrades in Lightweight Desktop.md
=> [手动选题][tech]: 20230417.2 ⭐️ LXQt 1.3.0 Explore the Upgrades in Lightweight Desktop.md

sources/tech/20230417.1 ⭐️⭐️ Rust Basics Series 4 Arrays and Tuples in Rust.md
=> [手动选题][tech]: 20230417.1 ⭐️⭐️ Rust Basics Series 4 Arrays and Tuples in Rust.md

sources/tech/20230416.0 ⭐️⭐️ How to Configure FreeIPA Client on Ubuntu 22.04  20.04.md
=> [手动选题][tech]: 20230416.0 ⭐️⭐️ How to Configure FreeIPA Client on Ubuntu 22.04  20.04.md

sources/tech/20230415.3 ⭐️⭐️ Generate Linux Commands from English Text Using ChatGPT AI.md
=> [手动选题][tech]: 20230415.3 ⭐️⭐️ Generate Linux Commands from English Text Using ChatGPT AI.md

sources/tech/20230415.2 ⭐️⭐️ Edit your photos with open source artificial intelligence.md
=> [手动选题][tech]: 20230415.2 ⭐️⭐️ Edit your photos with open source artificial intelligence.md

sources/tech/20230415.1 ⭐️ Pano Clipboard Manager is An Awesome GNOME Extension You Need.md
=> [手动选题][tech]: 20230415.1 ⭐️ Pano Clipboard Manager is An Awesome GNOME Extension You Need.md

sources/tech/20230415.0 ⭐️⭐️ How to Install FreeIPA Server on RHEL 8  Rocky Linux 8  AlmaLinux 8.md
=> [手动选题][tech]: 20230415.0 ⭐️⭐️ How to Install FreeIPA Server on RHEL 8  Rocky Linux 8  AlmaLinux 8.md

sources/tech/20230414.1 ⭐️⭐️⭐️ A distributed database load-balancing architecture with ShardingSphere.md
=> [手动选题][tech]: 20230414.1 ⭐️⭐️⭐️ A distributed database load-balancing architecture with ShardingSphere.md

sources/tech/20230417.0 ⭐️⭐️ Ubuntu Budgie 23.04 Best New Features.md
Reverts LCTT/TranslateProject#29193
=> Revert "申请翻译"

published/20230412.5 ⭐️⭐️ How to Connect GitHub to VS Code [Step by Step].md
@geekpi
https://linux.cn/article-15750-1.html
=> RP:published/20230412.5 ⭐️⭐️ How to Connect GitHub to VS Code [Step by Step].md

published/20230408.1 ⭐️⭐️ Is Official Ubuntu Mini ISO Truly Minimal A Test Drive.md
@imgradeone
https://linux.cn/article-15761-1.html
=> RP:published/20230408.1 ⭐️⭐️ Is Official Ubuntu Mini ISO Truly Minimal A Test Drive.md

sources/talk/20230421.0 ⭐️⭐️ The future of the sharing business model.md
=> [手动选题][talk]: 20230421.0 ⭐️⭐️ The future of the sharing business model.md

sources/tech/20230422.0 ⭐️ How to Set Proxy Settings for APT Command.md
=> [手动选题][tech]: 20230422.0 ⭐️ How to Set Proxy Settings for APT Command.md

sources/news/20230424.2 ⭐️⭐️ KaOS 2023.04 Released with Experimental Plasma 6 ISO, Mastodon Client.md
=> [手动选题][news]: 20230424.2 ⭐️⭐️ KaOS 2023.04 Released with Experimental Plasma 6 ISO, Mastodon Client.md

published/20230410.1 ⭐️ Remove the background from an image with this Linux command.md
@geekpi
https://linux.cn/article-15762-1.html
=> RP:published/20230410.1 ⭐️ Remove the background from an image with this Linux command.md

sources/tech/20230424.3 ⭐️⭐️ Learn TclTk and Wish with this simple game.md
=> [手动选题][tech]: 20230424.3 ⭐️⭐️ Learn TclTk and Wish with this simple game.md

sources/tech/20230424.4 ⭐️⭐️ C vs. Go Comparing programming languages.md
=> [手动选题][tech]: 20230424.4 ⭐️⭐️ C vs. Go Comparing programming languages.md

sources/tech/20230425.0 ⭐️⭐️ How to Configure DHCP Server on RHEL 9  Rocky Linux 9.md
=> [手动选题][tech]: 20230425.0 ⭐️⭐️ How to Configure DHCP Server on RHEL 9  Rocky Linux 9.md

sources/news/20230427.3 ⭐️⭐️ HuggingChat is the First Open Source ChatGPT Alternative That Anyone Can Use.md
=> [手动选题][news]: 20230427.3 ⭐️⭐️ HuggingChat is the First Open Source ChatGPT Alternative That Anyone Can Use.md

sources/talk/20230427.2 ⭐️⭐️ 3 key open source challenges in developing countries.md
=> [手动选题][talk]: 20230427.2 ⭐️⭐️ 3 key open source challenges in developing countries.md

sources/tech/20230427.1 ⭐️⭐️ Run a virtual conference using only open source tools.md
=> [手动选题][tech]: 20230427.1 ⭐️⭐️ Run a virtual conference using only open source tools.md

sources/news/20230427.0 ⭐️⭐️ Voyager Linux 23.04 Snap-free Ubuntu Experience with A Gorgeous Look.md
=> [手动选题][news]: 20230427.0 ⭐️⭐️ Voyager Linux 23.04 Snap-free Ubuntu Experience with A Gorgeous Look.md

sources/news/20230426.2 ⭐️⭐️ Opera's New Redesigned Web Browser is Also Available on Linux.md
=> [手动选题][news]: 20230426.2 ⭐️⭐️ Opera's New Redesigned Web Browser is Also Available on Linux.md

sources/tech/20230426.1 ⭐️⭐️ Test your Drupal website with Cypress.md
=> [手动选题][tech]: 20230426.1 ⭐️⭐️ Test your Drupal website with Cypress.md

sources/talk/20230426.0 ⭐️⭐️ 5 open ways to help UX designers and developers collaborate better.md
=> [手动选题][talk]: 20230426.0 ⭐️⭐️ 5 open ways to help UX designers and developers collaborate better.md

sources/tech/20230425.3 ⭐️⭐️ Retry your Python code until it fails.md
=> [手动选题][tech]: 20230425.3 ⭐️⭐️ Retry your Python code until it fails.md

sources/news/20230425.2 ⭐️⭐️ What's new in GNOME 44.md
=> [手动选题][news]: 20230425.2 ⭐️⭐️ What's new in GNOME 44.md

sources/tech/20230425.1 ⭐️⭐️⭐️ The Ultimate Guide to i3 Customization in Linux.md
=> [手动选题][tech]: 20230425.1 ⭐️⭐️⭐️ The Ultimate Guide to i3 Customization in Linux.md

sources/tech/20230428.0 ⭐️⭐️ 7 Super Lightweight Linux Distros.md
=> [手动选题][tech]: 20230428.0 ⭐️⭐️ 7 Super Lightweight Linux Distros.md

sources/talk/20230428.1 ⭐️⭐️ How I used guilt as a motivator for good.md
=> [手动选题][talk]: 20230428.1 ⭐️⭐️ How I used guilt as a motivator for good.md

sources/talk/20230428.2 ⭐️⭐️ 3 reasons to host a docathon for your open source project.md
=> [手动选题][talk]: 20230428.2 ⭐️⭐️ 3 reasons to host a docathon for your open source project.md

sources/tech/20230430.1 ⭐️⭐️ 11 Ways to Improve Your Privacy.md
=> [手动选题][tech]: 20230430.1 ⭐️⭐️ 11 Ways to Improve Your Privacy.md

sources/talk/20230430.0 ⭐️⭐️ Meet the Techs of Tomorrow Where They Are Today A Conversation With Stu Keroff.md
=> [手动选题][talk]: 20230430.0 ⭐️⭐️ Meet the Techs of Tomorrow Where They Are Today A Conversation With Stu Keroff.md

sources/tech/20230429.1 ⭐️⭐️ Install and Use Qemu on Ubuntu.md
=> [手动选题][tech]: 20230429.1 ⭐️⭐️ Install and Use Qemu on Ubuntu.md

sources/news/20230429.0 ⭐️ Debian 12 'Bookworm' New Features and Release Date.md
=> [手动选题][news]: 20230429.0 ⭐️ Debian 12 'Bookworm' New Features and Release Date.md

published/20230403.1 ⭐️⭐️ Rust Basics Series 2 Using Variables and Constants in Rust Programs.md
@Cubik65536
https://linux.cn/article-15771-1.html
=> RP:published/20230403.1 ⭐️⭐️ Rust Basics Series 2 Using Variables and Constants in Rust Programs.md

sources/tech/20230501.1 ⭐️⭐️ Rust Basics Series 6 Conditional Statements.md
=> [手动选题][tech]: 20230501.1 ⭐️⭐️ Rust Basics Series 6 Conditional Statements.md

published/20230414.0 ⭐️ KDE Team Developing a New e-Book Management App Arianna.md
@geekpi
https://linux.cn/article-15773-1.html
=> RP:published/20230414.0 ⭐️ KDE Team Developing a New e-Book Management App Arianna.md

published/20230208.1 ⭐️⭐️ Improve your coding skills with temporal values in MySQL.md
@hanszhao80
https://linux.cn/article-15774-1.html
=> RP:published/20230208.1 ⭐️⭐️ Improve your coding skills with temporal values in MySQL.md

published/20230429.0 ⭐️ Debian 12 'Bookworm' New Features and Release Date.md
@chris000132
https://linux.cn/article-15776-1.html
还应该进一步润色和检查一下。
=> RP:published/20230429.0 ⭐️ Debian 12 'Bookworm' New Features and Release Date.md

sources/news/20230503.2 ⭐️ Ubuntu 18.04 is Reaching End of Life Here's What You Can Do.md
=> [手动选题][news]: 20230503.2 ⭐️ Ubuntu 18.04 is Reaching End of Life Here's What You Can Do.md

sources/tech/20230503.1 ⭐️⭐️ 8 Best Remote Desktop Tools for Linux.md
=> [手动选题][tech]: 20230503.1 ⭐️⭐️ 8 Best Remote Desktop Tools for Linux.md

sources/news/20230503.0 ⭐️ Linux Mint 21.2 Introducing Tooltips Based on Accent Colour.md
=> [手动选题][news]: 20230503.0 ⭐️ Linux Mint 21.2 Introducing Tooltips Based on Accent Colour.md

sources/tech/20230502.2 ⭐️⭐️ Generate web pages from Markdown with Docsify-This.md
=> [手动选题][tech]: 20230502.2 ⭐️⭐️ Generate web pages from Markdown with Docsify-This.md

sources/tech/20230502.1 ⭐️ How to Install FreeIPA Client on RHEL  Rocky Linux  AlmaLinux.md
=> [手动选题][tech]: 20230502.1 ⭐️ How to Install FreeIPA Client on RHEL  Rocky Linux  AlmaLinux.md

sources/news/20230502.0 ⭐️ Ubuntu 23.10 Reveals Codename “Mantic Minotaur”.md
=> [手动选题][news]: 20230502.0 ⭐️ Ubuntu 23.10 Reveals Codename “Mantic Minotaur”.md

sources/news/20230501.2 ⭐️ Say Cheese to the Future Snapshot is GNOME's Next-Gen Camera App.md
=> [手动选题][news]: 20230501.2 ⭐️ Say Cheese to the Future Snapshot is GNOME's Next-Gen Camera App.md

published/20220915 Monitoring and Debugging Kubernetes with Lens Desktop.md
@lxbwolf
https://linux.cn/article-15780-1.html
=> RP:20220915 monitoring and debugging kubernetes with lens desktop

sources/tech/20230504.0 ⭐️ Ubuntu MATE 23.04 Best Features and Updates.md
=> [手动选题][tech]: 20230504.0 ⭐️ Ubuntu MATE 23.04 Best Features and Updates.md

published/20230415.0 ⭐️⭐️ How to Install FreeIPA Server on RHEL 8  Rocky Linux 8  AlmaLinux 8.md
@geekpi
https://linux.cn/article-15783-1.html
=> RP:published/20230415.0 ⭐️⭐️ How to Install FreeIPA Server on RHEL 8  Rocky Linux 8  AlmaLinux 8.md

published/20230418.2 ⭐️⭐️ Talk to your cluster with this open source Python API wrapper.md
@geekpi
https://linux.cn/article-15793-1.html
=> RP:published/20230418.2 ⭐️⭐️ Talk to your cluster with this open source Python API wrapper.md

sources/news/20230509.0 ⭐️ Zinc A New Ubuntu-Based Distro With Nemo File Manager and XFCE Desktop.md
=> [手动选题][news]: 20230509.0 ⭐️ Zinc A New Ubuntu-Based Distro With Nemo File Manager and XFCE Desktop.md

sources/news/20230509.1 ⭐️⭐️ Firefox 113 Introduces Enhanced Picture-in-Picture and Improved Security Features.md
=> [手动选题][news]: 20230509.1 ⭐️⭐️ Firefox 113 Introduces Enhanced Picture-in-Picture and Improved Security Features.md

sources/news/20230508.0 ⭐️ GNOME Files to Drop Old-School Column Chooser, Now Lets You Easily Configure It.md
=> [手动选题][news]: 20230508.0 ⭐️ GNOME Files to Drop Old-School Column Chooser, Now Lets You Easily Configure It.md

sources/tech/20230507.0 ⭐️⭐️ Rust Basics Series 7 Using Loops in Rust.md
=> [手动选题][tech]: 20230507.0 ⭐️⭐️ Rust Basics Series 7 Using Loops in Rust.md

sources/tech/20230506.0 ⭐️⭐️ Introduction to Kali Linux Everything You Need to Know.md
=> [手动选题][tech]: 20230506.0 ⭐️⭐️ Introduction to Kali Linux Everything You Need to Know.md

sources/news/20230511.3 ⭐️ Ubuntu Now Available on the World's First High-Performance RISC-V SBC with GPU.md
=> [手动选题][news]: 20230511.3 ⭐️ Ubuntu Now Available on the World's First High-Performance RISC-V SBC with GPU.md

sources/news/20230511.2 ⭐️ GNOME is Considering to Bring Back Terminal App to Replace the New Console.md
=> [手动选题][news]: 20230511.2 ⭐️ GNOME is Considering to Bring Back Terminal App to Replace the New Console.md

sources/news/20230511.1 ⭐️ AlmaLinux 9.2 Released, with Enhanced Security and Performance.md
=> [手动选题][news]: 20230511.1 ⭐️ AlmaLinux 9.2 Released, with Enhanced Security and Performance.md

sources/news/20230511.0 ⭐️⭐️ Alpine Linux 3.18 Released with Kernel 6.1, GNOME 44.md
=> [手动选题][news]: 20230511.0 ⭐️⭐️ Alpine Linux 3.18 Released with Kernel 6.1, GNOME 44.md

published/20230502.1 ⭐️ How to Install FreeIPA Client on RHEL  Rocky Linux  AlmaLinux.md
@geekpi
https://linux.cn/article-15806-1.html
=> RP:published/20230502.1 ⭐️ How to Install FreeIPA Client on RHEL  Rocky Linux  AlmaLinux.md

published/20210201 My handy guide to software development and testing.md
@toknow-gh
https://linux.cn/article-15808-1.html
=> RP:published/20210201 My handy guide to software development and testing.md

sources/tech/20230514.0 ⭐️⭐️ 10 Things to do After Installing Arch Linux.md
=> [手动选题][tech]: 20230514.0 ⭐️⭐️ 10 Things to do After Installing Arch Linux.md

sources/tech/20230513.0 ⭐️⭐️ risiOS An Easy-to-Use Fedora-based Linux Distribution.md
=> [手动选题][tech]: 20230513.0 ⭐️⭐️ risiOS An Easy-to-Use Fedora-based Linux Distribution.md

sources/news/20230512.1 ⭐️ Loupe is the New Image Viewer App for GNOME.md
=> [手动选题][news]: 20230512.1 ⭐️ Loupe is the New Image Viewer App for GNOME.md

sources/news/20230511.4 ⭐️ KDE Plasma 6 Plans Revealed Includes 5 New Exciting Default Settings.md
=> [手动选题][news]: 20230511.4 ⭐️ KDE Plasma 6 Plans Revealed Includes 5 New Exciting Default Settings.md

published/20210202 How I build and expand application development and testing.md
@toknow-gh
https://linux.cn/article-15817-1.html
=> RP:published/20210202 How I build and expand application development and testing.md

sources/news/20230517.1 ⭐️ Ubuntu 23.10 To Bring Security Enhanced PPAs.md
=> [手动选题][news]: 20230517.1 ⭐️ Ubuntu 23.10 To Bring Security Enhanced PPAs.md

sources/news/20230517.0 ⭐️ Fedora 36 Reaches End Of Life (EOL), Upgrade to Fedora 37.md
=> [手动选题][news]: 20230517.0 ⭐️ Fedora 36 Reaches End Of Life (EOL), Upgrade to Fedora 37.md

sources/tech/20230516.3 ⭐️⭐️ Beginner's Guide to System Updates in Linux Mint.md
=> [手动选题][tech]: 20230516.3 ⭐️⭐️ Beginner's Guide to System Updates in Linux Mint.md

sources/tech/20230516.2 ⭐️ Reminders A Nifty Open-Source Linux App To Help You Get Things Done.md
=> [手动选题][tech]: 20230516.2 ⭐️ Reminders A Nifty Open-Source Linux App To Help You Get Things Done.md

sources/tech/20230515.0 ⭐️⭐️ Rust Basics Series 8 Write the Milestone Rust Program.md
=> [手动选题][tech]: 20230515.0 ⭐️⭐️ Rust Basics Series 8 Write the Milestone Rust Program.md

published/20230514.0 ⭐️⭐️ 10 Things to do After Installing Arch Linux.md
@chris000132
https://linux.cn/article-15824-1.html
=> RP:published/20230514.0 ⭐️⭐️ 10 Things to do After Installing Arch Linux.md

published/20230419.0 ⭐️⭐️ How to Upgrade to Fedora 38 from Fedora 37 Workstation (GUI and CLI).md
@geekpi
https://linux.cn/article-15829-1.html
=> RP:published/20230419.0 ⭐️⭐️ How to Upgrade to Fedora 38 from Fedora 37 Workstation (GUI and CLI).md

published/20221015.1 ⭐️⭐️ How to Get Started with Shell Scripting in Linux.md, translated/tech/20221015.1 ⭐️⭐️ How to Get Started with Shell Scripting in Linux.md
@cyberwaddle
本文首发地址：https://linux.cn/article-15830-1.html
也会同步发布到公众号、知乎。
您的 LCTT 专页：https://linux.cn/lctt/cyberwaddle
=> RP:20221015.1 ⭐️⭐️ how to get started with shell scripting in linux

sources/tech/20230520.0 ⭐️ Fix “invalid or corrupted package (PGP signature)” Error In Arch Linux.md
=> [手动选题][tech]: 20230520.0 ⭐️ Fix “invalid or corrupted package (PGP signature)” Error In Arch Linux.md

published/20230403.4 ⭐️⭐️ How to Install KVM on Rocky Linux 9  AlmaLinux 9.md
@geekpi
https://linux.cn/article-15843-1.html
=> RP:published/20230403.4 ⭐️⭐️ How to Install KVM on Rocky Linux 9  AlmaLinux 9.md

published/20230416.0 ⭐️⭐️ How to Configure FreeIPA Client on Ubuntu 22.04  20.04.md
@geekpi
https://linux.cn/article-15849-1.html
=> RP:published/20230416.0 ⭐️⭐️ How to Configure FreeIPA Client on Ubuntu 22.04  20.04.md

published/20230516.2 ⭐️ Reminders A Nifty Open-Source Linux App To Help You Get Things Done.md
@geekpi
https://linux.cn/article-15852-1.html
=> RP:published/20230516.2 ⭐️ Reminders A Nifty Open-Source Linux App To Help You Get Things Done.md

published/20230507.1 ⭐️⭐️ How to Setup High Availability Apache HTTP Cluster on RHEL 98.md
@geekpi
https://linux.cn/article-15856-1.html
=> RP:published/20230507.1 ⭐️⭐️ How to Setup High Availability Apache HTTP Cluster on RHEL 98.md

published/20210204 How to implement business requirements in software development.md
@toknow-gh
https://linux.cn/article-15860-1.html
=> RP:published/20210204 How to implement business requirements in software development.md

published/20230517.0 ⭐️ Fedora 36 Reaches End Of Life (EOL), Upgrade to Fedora 37.md
@geekpi
https://linux.cn/article-15869-1.html
=> RP:published/20230517.0 ⭐️ Fedora 36 Reaches End Of Life (EOL), Upgrade to Fedora 37.md

published/20230520.0 ⭐️ Fix “invalid or corrupted package (PGP signature)” Error In Arch Linux.md
@geekpi
https://linux.cn/article-15875-1.html
=> RP:published/20230520.0 ⭐️ Fix “invalid or corrupted package (PGP signature)” Error In Arch Linux.md

published/20210205.0 ⭐️⭐️ Why simplicity is critical to delivering sturdy applications.md
@toknow-gh
https://linux.cn/article-15877-1.html
恭喜！大功告成！
=> RP:published/20210205.0 ⭐️⭐️ Why simplicity is critical to delivering sturdy applications.md

sources/tech/20230523.0 ⭐️⭐️ Top 5 Beautiful Arch Linux Distributions.md
=> [手动选题][tech]: 20230523.0 ⭐️⭐️ Top 5 Beautiful Arch Linux Distributions.md

sources/tech/20230524.1 ⭐️⭐️ How to Install Ansible AWX on Kubernetes Cluster.md
=> [手动选题][tech]: 20230524.1 ⭐️⭐️ How to Install Ansible AWX on Kubernetes Cluster.md

sources/tech/20230524.0 ⭐️⭐️ How to Stress Test CPU in Linux.md
=> [手动选题][tech]: 20230524.0 ⭐️⭐️ How to Stress Test CPU in Linux.md

sources/tech/20230529.1 ⭐️ Sniffnet An Interesting Open-Source Network Monitoring Tool Anyone Can Use.md
=> [手动选题][tech]: 20230529.1 ⭐️ Sniffnet An Interesting Open-Source Network Monitoring Tool Anyone Can Use.md

sources/tech/20230529.0 ⭐️⭐️ Enable Fractional Scaling in Fedora with GNOME.md
=> [手动选题][tech]: 20230529.0 ⭐️⭐️ Enable Fractional Scaling in Fedora with GNOME.md

sources/tech/20230530.0 ⭐️⭐️ Install and Use pipx in Linux.md
=> [手动选题][tech]: 20230530.0 ⭐️⭐️ Install and Use pipx in Linux.md

sources/news/20230601.0 ⭐️ Kali Linux 2023.2 Release Adds a New Hyper-V Image and PipeWire to XFCE Variant.md
=> [手动选题][news]: 20230601.0 ⭐️ Kali Linux 2023.2 Release Adds a New Hyper-V Image and PipeWire to XFCE Variant.md

sources/tech/20230602.2 ⭐️⭐️ Install Windows 11 as Guest in Ubuntu using virt-manager.md
=> [手动选题][tech]: 20230602.2 ⭐️⭐️ Install Windows 11 as Guest in Ubuntu using virt-manager.md

sources/tech/20230602.1 ⭐️⭐️ Share Folder Between Windows Guest and Linux Host in KVM using virtiofs.md
=> [手动选题][tech]: 20230602.1 ⭐️⭐️ Share Folder Between Windows Guest and Linux Host in KVM using virtiofs.md

sources/news/20230602.0 ⭐️⭐️ GNOME 45 to Redesign Display Options and Fractional Scaling Tweaks.md
=> [手动选题][news]: 20230602.0 ⭐️⭐️ GNOME 45 to Redesign Display Options and Fractional Scaling Tweaks.md

sources/tech/20230605.1 ⭐️⭐️ How to Setup Dynamic NFS Provisioning in Kubernetes Cluster.md
=> [手动选题][tech]: 20230605.1 ⭐️⭐️ How to Setup Dynamic NFS Provisioning in Kubernetes Cluster.md

sources/news/20230605.0 ⭐️ GNOME Plans to Add a New System Panel Setting With a Remote Desktop Option.md
=> [手动选题][news]: 20230605.0 ⭐️ GNOME Plans to Add a New System Panel Setting With a Remote Desktop Option.md

published/20230502.2 ⭐️⭐️ Generate web pages from Markdown with Docsify-This.md
@chai001125
https://linux.cn/article-15884-1.html
=> RP:published/20230502.2 ⭐️⭐️ Generate web pages from Markdown with Docsify-This.md

published/20230512.1 ⭐️ Loupe is the New Image Viewer App for GNOME.md
@geekpi
https://linux.cn/article-15887-1.html
=> RP:published/20230512.1 ⭐️ Loupe is the New Image Viewer App for GNOME.md

sources/news/20230607.2 ⭐️ Firefox 114 Introduces Streamlined Bookmark Searching and Improved DNS Management.md
=> [手动选题][news]: 20230607.2 ⭐️ Firefox 114 Introduces Streamlined Bookmark Searching and Improved DNS Management.md

sources/news/20230607.1 ⭐️ OpenGL 3.1 is Now Available in Asahi Linux, Boosting Graphics Performance.md
=> [手动选题][news]: 20230607.1 ⭐️ OpenGL 3.1 is Now Available in Asahi Linux, Boosting Graphics Performance.md

sources/news/20230607.0 ⭐️ openSUSE Leap 15.5 Release Arrives With KDE Plasma 5.27 and Vim 9.0.md
=> [手动选题][news]: 20230607.0 ⭐️ openSUSE Leap 15.5 Release Arrives With KDE Plasma 5.27 and Vim 9.0.md

sources/tech/20230609.2 ⭐️⭐️ 10 Best Virtualization Software for Linux.md
=> [手动选题][tech]: 20230609.2 ⭐️⭐️ 10 Best Virtualization Software for Linux.md

sources/news/20230609.1 ⭐️⭐️ I am one of those “woke communists” Linus Torvalds.md
=> [手动选题][news]: 20230609.1 ⭐️⭐️ I am one of those “woke communists” Linus Torvalds.md

sources/tech/20230609.0 ⭐️⭐️ Get Organized and Stylish 7 Best Docks for Ubuntu Linux.md
=> [手动选题][tech]: 20230609.0 ⭐️⭐️ Get Organized and Stylish 7 Best Docks for Ubuntu Linux.md

sources/news/20230610.0 ⭐️⭐️ Debian 12 Bookworm Has Landed.md
=> [手动选题][news]: 20230610.0 ⭐️⭐️ Debian 12 Bookworm Has Landed.md

sources/tech/20230610.1 ⭐️⭐️ How to Upgrade to Debian 12 from Debian 11.md
=> [手动选题][tech]: 20230610.1 ⭐️⭐️ How to Upgrade to Debian 12 from Debian 11.md

sources/tech/20230611.0 ⭐️⭐️ Fuzzy File Search in Linux.md
=> [手动选题][tech]: 20230611.0 ⭐️⭐️ Fuzzy File Search in Linux.md

sources/tech/20230612.0 ⭐️ Tube Downloader An Open Source Tool to Download YouTube Videos.md
=> [手动选题][tech]: 20230612.0 ⭐️ Tube Downloader An Open Source Tool to Download YouTube Videos.md

sources/tech/20230612.1 ⭐️⭐️ Bash Basics Series 1 Create and Run Your First Bash Shell Script.md
=> [手动选题][tech]: 20230612.1 ⭐️⭐️ Bash Basics Series 1 Create and Run Your First Bash Shell Script.md

sources/tech/20230515.0 ⭐️⭐️ Rust Basics Series 8 Write the Milestone Rust Program.md
=> [翻译申请][tech]: 20230515.0 ⭐️⭐️ Rust Basics Series 8 Write the Milestone Rust Program

published/20230529.1 ⭐️ Sniffnet An Interesting Open-Source Network Monitoring Tool Anyone Can Use.md
@geekpi
https://linux.cn/article-15904-1.html
=> RP:published/20230529.1 ⭐️ Sniffnet An Interesting Open-Source Network Monitoring Tool Anyone Can Use.md

sources/tech/20220818 The Functions in the R Stats Package.md
申领原文 20220818 The Functions in the R Stats Package.md
=> 申领原文 20220818 The Functions in the R Stats Package.md

published/20221031.2 ⭐️ How to View AVIF Images in Ubuntu and Other Linux Distributions.md
@geekpi
https://linux.cn/article-15912-1.html
=> RP:published/20221031.2 ⭐️ How to View AVIF Images in Ubuntu and Other Linux Distributions.md

published/20230530.0 ⭐️⭐️ Install and Use pipx in Linux.md
@geekpi
https://linux.cn/article-15915-1.html
=> RP:published/20230530.0 ⭐️⭐️ Install and Use pipx in Linux.md

published/20220705 GitHub Copilot Is Only Effective Because It Steals Open Source Code.md
@TravinDreek
https://linux.cn/article-15916-1.html
=> RP:published/20220705 GitHub Copilot Is Only Effective Because It Steals Open Source Code.md

published/20230612.0 ⭐️ Tube Downloader An Open Source Tool to Download YouTube Videos.md
@geekpi
https://linux.cn/article-15918-1.html
=> RP:published/20230612.0 ⭐️ Tube Downloader An Open Source Tool to Download YouTube Videos.md

published/20210727 Zathura- A Minimalist Document Viewer for Keyboard Shortcut Pros.md
@tanloong
https://linux.cn/article-15924-1.html
=> RP:published/20210727 Zathura- A Minimalist Document Viewer for Keyboard Shortcut Pros.md

published/20230406.0 ⭐️⭐️ Make a web-safe color guide with Bash.md
@geekpi
https://linux.cn/article-15928-1.html
=> RP:published/20230406.0 ⭐️⭐️ Make a web-safe color guide with Bash.md

published/20220818 The Functions in the R Stats Package.md
@tanloong
https://linux.cn/article-15932-1.html
=> RP:published/20220818 The Functions in the R Stats Package.md

sources/news/20230622.0 ⭐️⭐️ Red Hat's Source Code Lockout Spells Disaster for CentOS Alternatives Rocky Linux and AlmaLinux in Trouble.md
=> [手动选题][news]: 20230622.0 ⭐️⭐️ Red Hat's Source Code Lockout Spells Disaster for CentOS Alternatives Rocky Linux and AlmaLinux in Trouble.md

sources/tech/20230621.1 ⭐️ Install and Use Flatpak on Ubuntu.md
=> [手动选题][tech]: 20230621.1 ⭐️ Install and Use Flatpak on Ubuntu.md

sources/tech/20230620.0 ⭐️ Using cd Command in Linux.md
=> [手动选题][tech]: 20230620.0 ⭐️ Using cd Command in Linux.md

sources/news/20230620.1 ⭐️ SoftMaker Office 2024 Releases With Integrated ChatGPT and DeepL.md
=> [手动选题][news]: 20230620.1 ⭐️ SoftMaker Office 2024 Releases With Integrated ChatGPT and DeepL.md

sources/tech/20230620.2 ⭐️⭐️ SparkyLinux 7 “Orion Belt” Review Blending Stability and Freshness.md
=> [手动选题][tech]: 20230620.2 ⭐️⭐️ SparkyLinux 7 “Orion Belt” Review Blending Stability and Freshness.md

sources/tech/20230613.0 ⭐️⭐️ Using head Command in Linux.md
=> [手动选题][tech]: 20230613.0 ⭐️⭐️ Using head Command in Linux.md

sources/tech/20230619.0 ⭐️ Meet 'Clipboard' An Open-Source App That Aims to Turn Up Your Productivity.md
=> [手动选题][tech]: 20230619.0 ⭐️ Meet 'Clipboard' An Open-Source App That Aims to Turn Up Your Productivity.md

sources/tech/20230619.1 ⭐️⭐️ Bash Basics Series 2 Using Variables in Bash.md
=> [手动选题][tech]: 20230619.1 ⭐️⭐️ Bash Basics Series 2 Using Variables in Bash.md

sources/tech/20230618.0 ⭐️⭐️ Best Open Source Email Servers.md
=> [手动选题][tech]: 20230618.0 ⭐️⭐️ Best Open Source Email Servers.md

sources/tech/20230615.0 ⭐️⭐️ 10 Best Linux Distributions for Xfce Desktop.md
=> [手动选题][tech]: 20230615.0 ⭐️⭐️ 10 Best Linux Distributions for Xfce Desktop.md

sources/tech/20230615.1 ⭐️ WhatsApp for Linux A Flatpak Desktop App for Distributions.md
=> [手动选题][tech]: 20230615.1 ⭐️ WhatsApp for Linux A Flatpak Desktop App for Distributions.md

sources/tech/20230624.0 ⭐️⭐️ How to Install and Use Wireshark in Ubuntu 22.04.md
=> [手动选题][tech]: 20230624.0 ⭐️⭐️ How to Install and Use Wireshark in Ubuntu 22.04.md

sources/tech/20230623.0 ⭐️ 2 Ways to Add Users to SUDOERS Group in Debian.md
=> [手动选题][tech]: 20230623.0 ⭐️ 2 Ways to Add Users to SUDOERS Group in Debian.md

published/20230524.1 ⭐️⭐️ How to Install Ansible AWX on Kubernetes Cluster.md
@geekpi
https://linux.cn/article-15941-1.html
=> RP:published/20230524.1 ⭐️⭐️ How to Install Ansible AWX on Kubernetes Cluster.md

published/20230529.0 ⭐️⭐️ Enable Fractional Scaling in Fedora with GNOME.md
@geekpi
https://linux.cn/article-15947-1.html
=> RP:published/20230529.0 ⭐️⭐️ Enable Fractional Scaling in Fedora with GNOME.md

published/20220922 How to Install and Use GNOME Boxes to Create Virtual Machines.md
@geekpi
https://linux.cn/article-15950-1.html
=> RP:published/20220922 How to Install and Use GNOME Boxes to Create Virtual Machines.md

published/20230623.0 ⭐️ 2 Ways to Add Users to SUDOERS Group in Debian.md
@geekpi
https://linux.cn/article-15958-1.html
=> RP:published/20230623.0 ⭐️ 2 Ways to Add Users to SUDOERS Group in Debian.md

sources/tech/20230630.0 ⭐️ How to Install Wine in Ubuntu.md
=> [手动选题][tech]: 20230630.0 ⭐️ How to Install Wine in Ubuntu.md

sources/news/20230628.0 ⭐️ Zorin OS Upgrader is Now Available to Give You Hassle-Free Update Experience.md
=> [手动选题][news]: 20230628.0 ⭐️ Zorin OS Upgrader is Now Available to Give You Hassle-Free Update Experience.md

sources/tech/20230628.1 ⭐️⭐️ Why is Kali Linux Preferred by Hackers.md
=> [手动选题][tech]: 20230628.1 ⭐️⭐️ Why is Kali Linux Preferred by Hackers.md

sources/tech/20230627.0 ⭐️⭐️ Using cat Command in Linux.md
=> [手动选题][tech]: 20230627.0 ⭐️⭐️ Using cat Command in Linux.md

sources/news/20230627.1 ⭐️ Fedora Workstation 39 May Feature Anaconda Web UI Installer by Default.md
=> [手动选题][news]: 20230627.1 ⭐️ Fedora Workstation 39 May Feature Anaconda Web UI Installer by Default.md

sources/tech/20230626.0 ⭐️⭐️ Bash Basics Series 3 Passing Arguments and Accepting User Inputs.md
=> [手动选题][tech]: 20230626.0 ⭐️⭐️ Bash Basics Series 3 Passing Arguments and Accepting User Inputs.md

sources/tech/20230626.1 ⭐️⭐️ Nobara 38 Released, Offering Enhanced Gaming and Content Creation Experience.md
=> [手动选题][tech]: 20230626.1 ⭐️⭐️ Nobara 38 Released, Offering Enhanced Gaming and Content Creation Experience.md

sources/tech/20230626.2 ⭐️⭐️ 15 Best GTK Themes for Ubuntu and Other Distros.md
=> [手动选题][tech]: 20230626.2 ⭐️⭐️ 15 Best GTK Themes for Ubuntu and Other Distros.md

sources/tech/20221108.2 ⭐️⭐️ How to Install LXQt Desktop in Arch Linux [Complete Guide].md
=> 申请翻译，翻译速度可能较慢

published/20230624.0 ⭐️⭐️ How to Install and Use Wireshark in Ubuntu 22.04.md
@geekpi
https://linux.cn/article-15969-1.html
=> RP:published/20230624.0 ⭐️⭐️ How to Install and Use Wireshark in Ubuntu 22.04.md

published/20220105 Create bookmarks for your PDF with pdftk.md
@toknow-gh
https://linux.cn/article-15973-1.html
=> RP:published/20220105 Create bookmarks for your PDF with pdftk.md

published/20230620.2 ⭐️⭐️ SparkyLinux 7 “Orion Belt” Review Blending Stability and Freshness.md
@geekpi
https://linux.cn/article-15976-1.html
=> RP:published/20230620.2 ⭐️⭐️ SparkyLinux 7 “Orion Belt” Review Blending Stability and Freshness.md

published/20230701.1 ⭐️ How to Remove Software Repositories from Ubuntu.md
@geekpi
https://linux.cn/article-15985-1.html
备注一下，这篇图片不需要另外保存。（/content/images/2023/06/）
=> RP:published/20230701.1 ⭐️ How to Remove Software Repositories from Ubuntu.md

published/20220105 What is CloudReady- Is it a Viable Open Source Alternative to Chrome OS.md
@toknow-gh
https://linux.cn/article-15987-1.html
=> RP:published/20220105 What is CloudReady- Is it a Viable Open Source Alternative to Chrome OS.md

sources/tech/20230704.0 ⭐️⭐️ Using ls Command in Linux.md
=> [手动选题][tech]: 20230704.0 ⭐️⭐️ Using ls Command in Linux.md

sources/tech/20230703.0 ⭐️⭐️ Bash Basics Series 4 Arithmetic Operations.md
=> [手动选题][tech]: 20230703.0 ⭐️⭐️ Bash Basics Series 4 Arithmetic Operations.md

sources/tech/20230705.0 ⭐️⭐️ Display Animated ASCII Birthday Wish in Linux Terminal 🎂.md
=> [手动选题][tech]: 20230705.0 ⭐️⭐️ Display Animated ASCII Birthday Wish in Linux Terminal 🎂.md

sources/news/20230708.1 ⭐️ Solus 4.4 The Long-Awaited Return with Refreshed Desktop Experience.md
=> [手动选题][news]: 20230708.1 ⭐️ Solus 4.4 The Long-Awaited Return with Refreshed Desktop Experience.md

sources/news/20230707.0 ⭐️⭐️ Fedora Workstation 40 Considering Inclusion of Privacy-Preserving Telemetry.md
=> [手动选题][news]: 20230707.0 ⭐️⭐️ Fedora Workstation 40 Considering Inclusion of Privacy-Preserving Telemetry.md

sources/news/20230708.0 ⭐️ blendOS v3 The Latest Version of the Immutable Distro is Here!.md
=> [手动选题][news]: 20230708.0 ⭐️ blendOS v3 The Latest Version of the Immutable Distro is Here!.md

sources/tech/20230710.3 ⭐️⭐️ 10 Best Cursor Themes for Linux Desktops.md
=> [手动选题][tech]: 20230710.3 ⭐️⭐️ 10 Best Cursor Themes for Linux Desktops.md

sources/news/20230710.0 ⭐️ Geary 44 Email App for Linux Adds Two Nifty Enhancements.md
=> [手动选题][news]: 20230710.0 ⭐️ Geary 44 Email App for Linux Adds Two Nifty Enhancements.md

sources/news/20230711.0 ⭐️ EndeavourOS Artemis Released with Better ARM Support and Updates.md
=> [手动选题][news]: 20230711.0 ⭐️ EndeavourOS Artemis Released with Better ARM Support and Updates.md

published/20230626.0 ⭐️⭐️ Bash Basics Series 3 Passing Arguments and Accepting User Inputs.md
@geekpi
https://linux.cn/article-16001-1.html
=> RP:published/20230626.0 ⭐️⭐️ Bash Basics Series 3 Passing Arguments and Accepting User Inputs.md

published/20230703.0 ⭐️⭐️ Bash Basics Series 4 Arithmetic Operations.md
@geekpi
https://linux.cn/article-16006-1.html
=> RP:published/20230703.0 ⭐️⭐️ Bash Basics Series 4 Arithmetic Operations.md

published/20220115 Some ways DNS can break.md
@toknow-gh
https://linux.cn/article-16020-1.html
=> RP:published/20220115 Some ways DNS can break.md

published/20230602.1 ⭐️⭐️ Share Folder Between Windows Guest and Linux Host in KVM using virtiofs.md
@geekpi
https://linux.cn/article-16023-1.html
=> RP:published/20230602.1 ⭐️⭐️ Share Folder Between Windows Guest and Linux Host in KVM using virtiofs.md

sources/news/20230721.0 ⭐️ Gyroflow An Open-Source App to Stabilize Video Footage.md
=> [手动选题][news]: 20230721.0 ⭐️ Gyroflow An Open-Source App to Stabilize Video Footage.md

sources/tech/20230721.1 ⭐️ Install and Use Additional Gedit Color Themes.md
=> [手动选题][tech]: 20230721.1 ⭐️ Install and Use Additional Gedit Color Themes.md

sources/tech/20230721.2 ⭐️⭐️ LLaMA 2 vs GPT-4 What are the Differences.md
=> [手动选题][tech]: 20230721.2 ⭐️⭐️ LLaMA 2 vs GPT-4 What are the Differences.md

sources/tech/20230721.3 ⭐️⭐️ 10 Lightweight Linux Distributions for your Old Hardware in 2023.md
=> [手动选题][tech]: 20230721.3 ⭐️⭐️ 10 Lightweight Linux Distributions for your Old Hardware in 2023.md

sources/tech/20230721.4 ⭐️ Install KDE Plasma Desktop in Linux Mint An Experiment.md
=> [手动选题][tech]: 20230721.4 ⭐️ Install KDE Plasma Desktop in Linux Mint An Experiment.md

sources/tech/20230721.5 ⭐️⭐️ Top 5 Privacy Focused Linux Distributions [Compared].md
=> [手动选题][tech]: 20230721.5 ⭐️⭐️ Top 5 Privacy Focused Linux Distributions [Compared].md

sources/tech/20230720.0 ⭐️⭐️ Mix and Match Terminal With Nautilus File Manager in Linux.md
=> [手动选题][tech]: 20230720.0 ⭐️⭐️ Mix and Match Terminal With Nautilus File Manager in Linux.md

sources/tech/20230719.0 ⭐️ Anytype An All-in-One Secure Open-Source App for Work and Productivity.md
=> [手动选题][tech]: 20230719.0 ⭐️ Anytype An All-in-One Secure Open-Source App for Work and Productivity.md

sources/tech/20230719.1 ⭐️⭐️ The systemd Controversy A Beginner's Guide to Understanding the Debate.md
=> [手动选题][tech]: 20230719.1 ⭐️⭐️ The systemd Controversy A Beginner's Guide to Understanding the Debate.md

sources/tech/20230719.2 ⭐️⭐️ Linux Shells Bash, Zsh, and Fish Explained.md
=> [手动选题][tech]: 20230719.2 ⭐️⭐️ Linux Shells Bash, Zsh, and Fish Explained.md

sources/tech/20230717.0 ⭐️⭐️ Bash Basics Series 6 Handling String Operations.md
=> [手动选题][tech]: 20230717.0 ⭐️⭐️ Bash Basics Series 6 Handling String Operations.md

sources/news/20230717.2 ⭐️⭐️ Linux Mint 21.2 Release Improves The Visual Redesign Further.md
=> [手动选题][news]: 20230717.2 ⭐️⭐️ Linux Mint 21.2 Release Improves The Visual Redesign Further.md

sources/tech/20230717.3 ⭐️⭐️ How to Install and Access Kubernetes Dashboard Step-by-Step.md
=> [手动选题][tech]: 20230717.3 ⭐️⭐️ How to Install and Access Kubernetes Dashboard Step-by-Step.md

sources/talk/20230716.0 ⭐️⭐️ Every Year is Someone's Year of Linux Desktop.md
=> [手动选题][talk]: 20230716.0 ⭐️⭐️ Every Year is Someone's Year of Linux Desktop.md

sources/tech/20230716.1 ⭐️⭐️ How to Install Jupyter Notebook in Debian or Ubuntu Linux.md
=> [手动选题][tech]: 20230716.1 ⭐️⭐️ How to Install Jupyter Notebook in Debian or Ubuntu Linux.md

sources/tech/20230714.0 ⭐️⭐️ How to Access the GRUB Menu in Virtual Machine.md
=> [手动选题][tech]: 20230714.0 ⭐️⭐️ How to Access the GRUB Menu in Virtual Machine.md

sources/tech/20230711.1 ⭐️⭐️ Using cp Command in Linux.md
=> [手动选题][tech]: 20230711.1 ⭐️⭐️ Using cp Command in Linux.md

published/20230627.0 ⭐️⭐️ Using cat Command in Linux.md
@geekpi
https://linux.cn/article-16025-1.html
=> RP:published/20230627.0 ⭐️⭐️ Using cat Command in Linux.md

published/20230630.0 ⭐️ How to Install Wine in Ubuntu.md
@robsean
https://linux.cn/article-16028-1.html
=> RP:published/20230630.0 ⭐️ How to Install Wine in Ubuntu.md

published/20230621.1 ⭐️ Install and Use Flatpak on Ubuntu.md
**@geekpi
https://linux.cn/article-16031-1.html**
=> RP:20230621.1 ⭐️ install and use flatpak on ubuntu

published/20230716.1 ⭐️⭐️ How to Install Jupyter Notebook in Debian or Ubuntu Linux.md
@geekpi
https://linux.cn/article-16040-1.html
=> RP:published/20230716.1 ⭐️⭐️ How to Install Jupyter Notebook in Debian or Ubuntu Linux.md

published/20230717.0 ⭐️⭐️ Bash Basics Series 6 Handling String Operations.md
@geekpi
https://linux.cn/article-16047-1.html
=> RP:published/20230717.0 ⭐️⭐️ Bash Basics Series 6 Handling String Operations.md

sources/tech/20230729.0 ⭐️⭐️ Best Video Editors for Linux in 2023.md
=> [手动选题][tech]: 20230729.0 ⭐️⭐️ Best Video Editors for Linux in 2023.md

sources/tech/20230728.0 ⭐️⭐️ Colors in ls Command Output What do They Mean.md
=> [手动选题][tech]: 20230728.0 ⭐️⭐️ Colors in ls Command Output What do They Mean.md

sources/tech/20230728.1 ⭐️⭐️ GNOME’s Ambitious Window Management Overhaul.md
=> [手动选题][tech]: 20230728.1 ⭐️⭐️ GNOME’s Ambitious Window Management Overhaul.md

sources/tech/20230727.0 ⭐️⭐️ What is Compiz in Linux.md
=> [手动选题][tech]: 20230727.0 ⭐️⭐️ What is Compiz in Linux.md

sources/tech/20230727.1 ⭐️ How to Install GitLab on Ubuntu 22.04  20.04.md
=> [手动选题][tech]: 20230727.1 ⭐️ How to Install GitLab on Ubuntu 22.04  20.04.md

sources/tech/20230724.0 ⭐️⭐️ Bash Basics Series 7 If Else Statement.md
=> [手动选题][tech]: 20230724.0 ⭐️⭐️ Bash Basics Series 7 If Else Statement.md

published/20230329.2 ⭐️ Linux Terminal Basics 7 Copy Files and Directories in Linux.md
@geekpi
https://linux.cn/article-16053-1.html
=> RP:published/20230329.2 ⭐️ Linux Terminal Basics 7 Copy Files and Directories in Linux.md

sources/tech/20230308.8 ⭐️⭐️ Fedora Linux editions part 3 Labs.md
=> [手动选题][tech]: 20230308.8 ⭐️⭐️ Fedora Linux editions part 3 Labs.md

sources/tech/20230714.1 ⭐️⭐️ Fedora Linux editions part 4 Alt Downloads.md
=> [手动选题][tech]: 20230714.1 ⭐️⭐️ Fedora Linux editions part 4 Alt Downloads.md

published/20220118 Perform unit tests using GoogleTest and CTest.md, translated/tech/20220118 Perform unit tests using GoogleTest and CTest.md
@toknow-gh
https://linux.cn/article-16055-1.html
=> RP:20220118 perform unit tests using google test and c test

published/20230717.3 ⭐️⭐️ How to Install and Access Kubernetes Dashboard Step-by-Step.md
@geekpi
https://linux.cn/article-16064-1.html
=> RP:published/20230717.3 ⭐️⭐️ How to Install and Access Kubernetes Dashboard Step-by-Step.md

published/20230727.1 ⭐️ How to Install GitLab on Ubuntu 22.04  20.04.md
@geekpi
https://linux.cn/article-16074-1.html
=> RP:published/20230727.1 ⭐️ How to Install GitLab on Ubuntu 22.04  20.04.md

published/20230721.4 ⭐️ Install KDE Plasma Desktop in Linux Mint An Experiment.md
@robsean
https://linux.cn/article-16080-1.html
=> RP:published/20230721.4 ⭐️ Install KDE Plasma Desktop in Linux Mint An Experiment.md

sources/tech/20230809 Fedora Linux Flatpak cool apps to try for August.md
sources/tech/20230809 Fedora Linux Flatpak cool apps to try for August.md
=> 选题[tech]: 20230809 Fedora Linux Flatpak cool apps to try for August

sources/tech/20230804 Behind -Hello World- on Linux.md
sources/tech/20230804 Behind -Hello World- on Linux.md
=> 选题[tech]: 20230804 Behind "Hello World" on Linux

sources/tech/20230616 Using Postfix DNS SRV record resolution feature.md
sources/tech/20230616 Using Postfix DNS SRV record resolution feature.md
=> 选题[tech]: 20230616 Using Postfix DNS SRV record resolution feature

sources/tech/20230510 Use FIDO U2F security keys with Fedora Linux.md
sources/tech/20230510 Use FIDO U2F security keys with Fedora Linux.md
=> 选题[tech]: 20230510 Use FIDO U2F security keys with Fedora Linux

published/20230330.1 ⭐️⭐️ 3 reasons my Linux team uses Penpot.md
@geekpi
https://linux.cn/article-16092-1.html
=> RP:published/20230330.1 ⭐️⭐️ 3 reasons my Linux team uses Penpot.md

published/20220131 How to set up a CI pipeline on GitLab.md
@toknow-gh
https://linux.cn/article-16105-1.html
这个系列辛苦了！
=> RP:published/20220131 How to set up a CI pipeline on GitLab.md

published/20230728.0 ⭐️⭐️ Colors in ls Command Output What do They Mean.md
@geekpi
https://linux.cn/article-16108-1.html
=> RP:published/20230728.0 ⭐️⭐️ Colors in ls Command Output What do They Mean.md

published/20230313.4 ⭐️⭐️ Monitor Kubernetes cloud costs with open source tools.md
@geekpi
https://linux.cn/article-16111-1.html
=> RP:published/20230313.4 ⭐️⭐️ Monitor Kubernetes cloud costs with open source tools.md

published/20230809 Fedora Linux Flatpak cool apps to try for August.md
@geekpi
https://linux.cn/article-16113-1.html
=> RP:published/20230809 Fedora Linux Flatpak cool apps to try for August.md

published/20230328.2 ⭐️⭐️ How to use Podman in GitLab Runners.md
@geekpi
https://linux.cn/article-16122-1.html
=> RP:published/20230328.2 ⭐️⭐️ How to use Podman in GitLab Runners.md

published/20230819 How to Rotate a Video With VLC Media Player.md
@geekpi
https://linux.cn/article-16129-1.html
=> RP:published/20230819 How to Rotate a Video With VLC Media Player.md

published/20230808 Easily Take Full Webpage Screenshots in Firefox and Chrome.md
@geekpi
https://linux.cn/article-16141-1.html
=> RP:published/20230808 Easily Take Full Webpage Screenshots in Firefox and Chrome.md

published/20230822 Remove Home Folder Icon from Ubuntu Desktop.md
@geekpi
https://linux.cn/article-16151-1.html
=> RP:published/20230822 Remove Home Folder Icon from Ubuntu Desktop.md

published/20230901 Fedora Linux Flatpak cool apps to try for September.md
@geekpi
https://linux.cn/article-16167-1.html
=> ATRP:published/20230901 Fedora Linux Flatpak cool apps to try for September.md

published/20230901 How to Check VLC Log Files.md
@geekpi
https://linux.cn/article-16180-1.html
=> RP:published/20230901 How to Check VLC Log Files.md

published/20230902 Making your Windows System Ready for Virtual Machines.md
@geekpi
https://linux.cn/article-16186-1.html
=> RP:20230902 making your windows system ready for virtual machines

published/20230908 Ubuntu 23.10 to Feature Experimental TPM-backed Full Disk Encryption.md
@geekpi
https://linux.cn/article-16187-1.html
=> RP:published/20230908 Ubuntu 23.10 to Feature Experimental TPM-backed Full Disk Encryption.md

sources/tech/20230213.2 ⭐️ Terminal Basics Series 1 Changing Directories in Linux Terminal.md
回归来做做翻译啦 🤣
这个系列好像只有第 4 篇已经被翻译了？我应该会像 Rust 系列似的持续把这个翻译完
=> [翻译申请][tech]: 20230213.2 ⭐️ Terminal Basics Series 1 Changing Directories in Linux Terminal

published/20221004 Using R for Building an Interactive Web App.md, translated/tech/20221004 Using R for Building an Interactive Web App.md
@Charonxin
感谢您完成了第一篇翻译贡献！
本文首发地址：https://linux.cn/article-16193-1.html
也会同步到公众号和知乎
您的 LCTT 专页：https://linux.cn/lctt/Charonxin
=> RP:20221004 using r for building an interactive web app

sources/tech/20220526 Document your source code with Doxygen on Linux.md
tech/20220526 Document your source code with Doxygen on Linux.md
=> Transalting

published/20220222 4 levels of DevOps documentation maturity.md
@toknow-gh
https://linux.cn/article-16196-1.html
=> RP:published/20220222 4 levels of DevOps documentation maturity.md

sources/tech/20220706 10 Tools to Generate and Have Fun With ASCII Art in Linux Terminal.md
Reverts LCTT/TranslateProject#30121
=> Revert "[完成翻译] 20220706 10 Tools to Generate and Have Fun With ASCII Art in L…"

sources/tech/20221202 Working with Btrfs - Subvolumes.md
sources/tech/20221202 Working with Btrfs - Subvolumes.md
=> 选题[tech]: 20221202 Working with Btrfs – Subvolumes

sources/tech/20221230 Working with Btrfs - Snapshots.md
sources/tech/20221230 Working with Btrfs - Snapshots.md
=> 选题[tech]: 20221230 Working with Btrfs – Snapshots

sources/tech/20230217 Working with Btrfs - Compression.md
sources/tech/20230217 Working with Btrfs - Compression.md
=> 选题[tech]: 20230217 Working with Btrfs – Compression

published/20230918 Tagger-s New Update Lets You Organize and Tag Your Music Better.md
@geekpi
https://linux.cn/article-16217-1.html
=> RP:published/20230918 Tagger-s New Update Lets You Organize and Tag Your Music Better.md

published/20220526 Document your source code with Doxygen on Linux.md
@toknow-gh
https://linux.cn/article-16227-1.html
=> RP:published/20220526 Document your source code with Doxygen on Linux.md

published/20230922 Element X- Making a Decentralized WhatsApp Killer With Matrix 2.0.md
@geekpi
https://linux.cn/article-16235-1.html
=> RP:published/20230922 Element X- Making a Decentralized WhatsApp Killer With Matrix 2.0.md

published/20230922 Terraria Devs Support Open-Source Game Engines Over Unity.md
@GenshinMinecraft
https://linux.cn/article-16236-1.html （延后发布）
=> RP:published/20230922 Terraria Devs Support Open-Source Game Engines Over Unity.md

published/20230919 Fixing Cannot add PPA- --This PPA does not support jammy-- Error.md
@geekpi
https://linux.cn/article-16246-1.html
=> ATRP:published/20230919 Fixing Cannot add PPA- --This PPA does not support jammy-- Error.md

published/20231004 Fixing -Bash- man command not found- error in Arch Linux.md
@geekpi
https://linux.cn/article-16270-1.html
=> RP:published/20231004 Fixing -Bash- man command not found- error in Arch Linux.md

published/20220629 ABCs of FreeDOS- 26 commands I use all the time.md
@robsean
https://linux.cn/article-16276-1.html
=> RP:published/20220629 ABCs of FreeDOS- 26 commands I use all the time.md

published/20231004 Install and Use Yay on Arch Linux.md
@geekpi
https://linux.cn/article-16284-1.html
=> RP:published/20231004 Install and Use Yay on Arch Linux.md

sources/tech/20230928 4 Incredibly Simple Ways to Customize Budgie Desktop in Linux.md
20230928 4 Incredibly Simple Ways to Customize Budgie Desktop in Linux.md
翻译认领
=>  2023年10月18日申请认领该翻译

published/20231009 Add Minimize and Maximize Buttons in GNOME.md
@geekpi
https://linux.cn/article-16295-1.html
=> RP:published/20231009 Add Minimize and Maximize Buttons in GNOME.md

published/20221013 How To Monitor User Activity In Linux.md
@wxy
https://linux.cn/article-16297-1.html
=> ATRP:published/20221013 How To Monitor User Activity In Linux.md

published/20231011 How to Record Your Screen with VLC -For Fun.md
@geekpi
https://linux.cn/article-16310-1.html
=> RP:published/20231011 How to Record Your Screen with VLC -For Fun.md

translated/tech/20231020 Some miscellaneous git facts.md
=> Update 20231020 Some miscellaneous git facts.md

published/20231020 Some miscellaneous git facts.md, translated/tech/20231020 Some miscellaneous git facts.md
@KaguyaQiang
本文首发地址：https://linux.cn/article-16316-1.html
也会同步发布到知乎、公众号等平台
您的 LCTT 专页：https://linux.cn/lctt/KaguyaQiang
=> RP:20231020 some miscellaneous git facts

published/20231016 Warehouse- A Powerhouse Tool to Manage Flatpak Apps.md
@geekpi
https://linux.cn/article-16321-1.html
=> RP:published/20231016 Warehouse- A Powerhouse Tool to Manage Flatpak Apps.md

published/20220809 Artificial Intelligence- Explaining the Basics.md
=> R:published/20220809 Artificial Intelligence- Explaining the Basics.md

published/20231026 KDE Plasma 6 Will Not Support Older Desktop Widgets.md
@geekpi
https://linux.cn/article-16333-1.html
=> RP:published/20231026 KDE Plasma 6 Will Not Support Older Desktop Widgets.md

published/20220815 How ODT files are structured.md
@toknow-gh
https://linux.cn/article-16340-1.html
=> ATRP:published/20220815 How ODT files are structured.md

published/20231018 Fedora Linux Flatpak cool apps to try for October.md
@geekpi
https://linux.cn/article-16343-1.html
=> PR:published/20231018 Fedora Linux Flatpak cool apps to try for October.md

published/20231031 Skiff Mail Adds a Convenient -Quick Aliases- Feature.md
@geekpi
https://linux.cn/article-16346-1.html
=> RP:published/20231031 Skiff Mail Adds a Convenient -Quick Aliases- Feature.md

published/20231023 How to Install the Latest LibreOffice on Ubuntu.md
@geekpi
https://linux.cn/article-16349-1.html
=> RP:published/20231023 How to Install the Latest LibreOffice on Ubuntu.md

published/20220809 A guide to JVM interpretation and compilation.md
@toknow-gh
https://linux.cn/article-16353-1.html
=> RP:published/20220809 A guide to JVM interpretation and compilation.md

sources/tech/20221107.2 ⭐️⭐️⭐️ Build your own SaaS on Linux with Vely.md
=> Update 20221107.2 ⭐️⭐️⭐️ Build your own SaaS on Linux with Vely.md

published/20220901 Are You Familiar with These Popular  Open Source Databases-.md
@toknow-gh
https://linux.cn/article-16374-1.html
=> RP:published/20220901 Are You Familiar with These Popular  Open Source Databases-.md

sources/tech/20230727 AI- A Few More Useful Python Libraries.md
sources/tech/20230727 AI- A Few More Useful Python Libraries.md
=> 选题[tech]: 20230727 AI: A Few More Useful Python Libraries

sources/tech/20230417 AI- An Introduction to Natural Language Processing.md
sources/tech/20230417 AI- An Introduction to Natural Language Processing.md
=> 选题[tech]: 20230417 AI: An Introduction to Natural Language Processing

sources/tech/20230515 AI- Introduction to Computer Vision.md
sources/tech/20230515 AI- Introduction to Computer Vision.md
=> 选题[tech]: 20230515 AI: Introduction to Computer Vision

sources/tech/20230626 AI- Classical Techniques and Hidden Python Gems.md
sources/tech/20230626 AI- Classical Techniques and Hidden Python Gems.md
=> 选题[tech]: 20230626 AI: Classical Techniques and Hidden Python Gems

sources/tech/20230710 AI- Beyond Python.md
sources/tech/20230710 AI- Beyond Python.md
=> 选题[tech]: 20230710 AI: Beyond Python

sources/tech/20231009 Coq and Lean- Powerful Interactive Theorem Provers.md
sources/tech/20231009 Coq and Lean- Powerful Interactive Theorem Provers.md
=> 选题[tech]: 20231009 Coq and Lean: Powerful Interactive Theorem Provers

published/20231101 Fedora Linux Flatpak cool apps to try for November.md
@geekpi
https://linux.cn/article-16401-1.html
=> RP:published/20231101 Fedora Linux Flatpak cool apps to try for November.md

published/20231118 Enabling Bluetooth on Arch Linux.md
@geekpi
https://linux.cn/article-16403-1.html
=> RP:published/20231118 Enabling Bluetooth on Arch Linux.md

published/20231113 FIDO2 for centrally managed users.md
@wxy
https://linux.cn/article-16406-1.html
=> RP:published/20231113 FIDO2 for centrally managed users.md

published/20231031 Install VSCodium on Fedora.md
@geekpi
https://linux.cn/article-16414-1.html
=> RP:published/20231031 Install VSCodium on Fedora.md

published/20231201 Godot 4.2 Released- Taking The Open-Source Game Engine Up a Notch.md
@geekpi
https://linux.cn/article-16447-1.html
=> RP:published/20231201 Godot 4.2 Released- Taking The Open-Source Game Engine Up a Notch.md

sources/tech/20221017.4 ⭐️⭐️⭐️ Why you should consider Rexx for scripting.md
=> Update 20221017.4 ⭐️⭐️⭐️ Why you should consider Rexx for scripting.md

published/20231201 Fedora Linux Flatpak cool apps to try for December.md
@geekpi
https://linux.cn/article-16457-1.html
=> RP:published/20231201 Fedora Linux Flatpak cool apps to try for December.md

published/20221107.2 ⭐️⭐️⭐️ Build your own SaaS on Linux with Vely.md
@Drwhooooo
https://linux.cn/article-16462-1.html
=> RP:published/20221107.2 ⭐️⭐️⭐️ Build your own SaaS on Linux with Vely.md

sources/talk/20221018.2 ⭐️⭐️⭐️ Exploring innovative Open Organization charts.md
=> 15th translation request

published/20231212 Celeste- A Multi-Cloud Open-Source GUI File Sync Client in Rust.md
@geekpi
https://linux.cn/article-16492-1.html
=> RP:published/20231212 Celeste- A Multi-Cloud Open-Source GUI File Sync Client in Rust.md

sources/tech/20231204 Mounting git commits as folders with NFS.md
=> Update 20231204 Mounting git commits as folders with NFS.md

published/20221228 AI- Anaconda and More on Probability.md
@toknow-gh
https://linux.cn/article-16526-1.html
=> RP:published/20221228 AI- Anaconda and More on Probability.md

published/20231230 Big News- Gentoo Linux is Now Providing Binary Packages for Quick Software Installation.md
@geekpi
https://linux.cn/article-16528-1.html
=> RP:published/20231230 Big News- Gentoo Linux is Now Providing Binary Packages for Quick Software Installation.md

published/20240104 Deepin becomes the first Linux distro to integrate AI features for Photos and IDE.md
@geekpi
https://linux.cn/article-16546-1.html
=> RP:published/20240104 Deepin becomes the first Linux distro to integrate AI features for Photos and IDE.md

published/20240108 AI Tools Are Here for Open-Source Audio Editor -Audacity.md
@geekpi
https://linux.cn/article-16560-1.html
=> RP:published/20240108 AI Tools Are Here for Open-Source Audio Editor -Audacity.md

sources/tech/20240122 OKD on Fedora Workstation with CRC.md
sources/tech/20240122 OKD on Fedora Workstation with CRC.md
=> 选题[tech]: 20240122 OKD on Fedora Workstation with CRC

sources/tech/20240123 scp Command Examples.md
sources/tech/20240123 scp Command Examples.md
=> 选题[tech]: 20240123 scp Command Examples

sources/news/20240123 MX Linux 23.2 -Libretto- is Here.md
sources/news/20240123 MX Linux 23.2 -Libretto- is Here.md
=> 选题[news]: 20240123 MX Linux 23.2 'Libretto' is Here!

sources/tech/20240124 Shut Down WSL Running Linux Distributions.md
sources/tech/20240124 Shut Down WSL Running Linux Distributions.md
=> 选题[tech]: 20240124 Shut Down WSL Running Linux Distributions

sources/tech/20240116 mv Command Examples.md
sources/tech/20240116 mv Command Examples.md
=> 选题[tech]: 20240116 mv Command Examples

sources/news/20240116 Linux Mint 21.3 Lands With Cinnamon 6.0 Desktop.md
sources/news/20240116 Linux Mint 21.3 Lands With Cinnamon 6.0 Desktop.md
=> 选题[news]: 20240116 Linux Mint 21.3 Lands With Cinnamon 6.0 Desktop

sources/news/20240117 Wine 9.0 Release Adds Experimental Wayland Driver.md
sources/news/20240117 Wine 9.0 Release Adds Experimental Wayland Driver.md
=> 选题[news]: 20240117 Wine 9.0 Release Adds Experimental Wayland Driver

sources/tech/20240126 Inside .git.md
sources/tech/20240126 Inside .git.md
=> 选题[tech]: 20240126 Inside .git

published/20230821 How to Use Subtitles with VLC.md
@geekpi
https://linux.cn/article-16594-1.html
=> RP:published/20230821 How to Use Subtitles with VLC.md
